# Czechs - initial VP = 50
province = { id = 471 points = 1 }
province = { id = 470 points = 1 }
province = { id = 466 points = 1 }
province = { id = 472 points = 1 }
province = { id = 469 points = 20 } # Praha
province = { id = 468 points = 1 }
province = { id = 467 points = 1 }
province = { id = 474 points = 1 }
province = { id = 475 points = 5 } # Brno
province = { id = 476 points = 5 } # Bratislava
province = { id = 478 points = 1 }
province = { id = 477 points = 1 }
province = { id = 490 points = 1 }
province = { id = 499 points = 5 } #Presov

# Germans - initial VP = 20 (to motivate them to attack!)
province = { id = 308 points = 1 }
province = { id = 482 points = 1 }
province = { id = 473 points = 1 } # Breslau
province = { id = 300 points = 4 } # Berlin
province = { id = 309 points = 1 }
province = { id = 311 points = 1 }
province = { id = 310 points = 1 }
province = { id = 83 points = 1 }
province = { id = 312 points = 1 } # Nurnberg
province = { id = 375 points = 1 }
province = { id = 376 points = 1 } # Munich
province = { id = 462 points = 1 }
province = { id = 465 points = 1 }
province = { id = 461 points = 1 }
province = { id = 460 points = 1 }
province = { id = 463 points = 1 } # Vienna
province = { id = 464 points = 1 }