#
# First eshelon air bases
###############################

# Riga
province = {
	id = 197
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

# Western Front Airfields
province = {
	id = 503
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Southwestern Front Airfields
province = {
	id = 229
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}
	}
# Southern Front Airfields (Odessa)
province = {
	id = 233
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}


#
# Second defense line airfields
################################

#Leningrad
province = {
	id = 187
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

# Sevastopol
province = {
	id = 253
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

# Moscow
province = {
	id = 175
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Murmansk
province = {
	id = 133
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

# Kiev
province = {
	id = 238
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Kharkov
province = {
	id = 248
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Smolensk
province = {
	id = 219
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Rostov
province = {
	id = 258
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Voronez
province = {
	id = 263
	air_base = {
		size = 10
		current_size = 10
		}
	}


province = {	id = 187	landfort = 5 coastalfort = 5 anti_air = 4 }#eningrad
province = {	id = 175	landfort = 5 coastalfort = 0 anti_air = 4 }#Moscow
province = {	id = 163	landfort = 5 coastalfort = 0 anti_air = 3 }#talingrad
province = {	id = 253	landfort = 3 coastalfort = 5 }#Sevestapol
province = {	id = 504	landfort = 3 anti_air = 3 } #Brest-Litovsk

#Anti Aircraft Batteries 
province = { id = 191   anti_air = 1 } #Novgorod
province = { id = 133   anti_air = 2 } #Murmansk
province = { id = 154   anti_air = 2 } #Archangelsk
province = { id = 217   anti_air = 2 } #Vitebsk
province = { id = 219   anti_air = 3 } #Smolensk
province = { id = 212   anti_air = 3 } #Minsk
province = { id = 277   anti_air = 2 } #Bryansk
province = { id = 181   anti_air = 1 } #Kaluga
province = { id = 238   anti_air = 3 } #Kiev
province = { id = 246   anti_air = 2 } #Dnepropetrovsk
province = { id = 253   anti_air = 3 } #Sevastopol
province = { id = 248   anti_air = 1 } #Kharkov
province = { id = 258   anti_air = 2 } #Rostov
province = { id = 263  anti_air = 1 } #Voronezh




country = {
    tag = SOV

ai = "fallbarbarossa_SOV_I.ai"

	capital = 175



	headofstate = { type = 9 id = 4001 }
	headofgovernment = { type = 9 id = 4002 }
  	foreignminister = { type = 9 id = 4034 }
  	armamentminister = { type = 9 id = 4004 }
  	ministerofsecurity = { type = 9 id = 4041 }
  	ministerofintelligence = { type = 9 id = 4048 }
  	chiefofstaff = { type = 9 id = 4053 }
  	chiefofarmy = { type = 9 id = 4059 }
  	chiefofnavy = { type = 9 id = 4062 } 
  	chiefofair = { type = 9 id = 4064 }

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 1
        political_left = 10
        freedom = 1
        free_market = 1
        professional_army = 3
        defense_lobby = 6
        interventionism = 4
    }

steal_leader = 9803
steal_leader = 9807
steal_leader = 9827
steal_leader = 9856
steal_leader = 9858
steal_leader = 9862
steal_leader = 9880
steal_leader = 9883
steal_leader = 9889
steal_leader = 9897
steal_leader = 9899
steal_leader = 9906
steal_leader = 9919
steal_leader = 9935
steal_leader = 9971
steal_leader = 9985
steal_leader = 9989
steal_leader = 9990
steal_leader = 9997
steal_leader = 9998
steal_leader = 10013
steal_leader = 10014
steal_leader = 10025
steal_leader = 10037
steal_leader = 10041
steal_leader = 10057
steal_leader = 10074
steal_leader = 10076
steal_leader = 10095
steal_leader = 10101
steal_leader = 10125
steal_leader = 10144
steal_leader = 10152
steal_leader = 10173
steal_leader = 10180
steal_leader = 10190
steal_leader = 10198
steal_leader = 10200
steal_leader = 10210
steal_leader = 10218
steal_leader = 10241
steal_leader = 10246
steal_leader = 10290
steal_leader = 10293
steal_leader = 10298
steal_leader = 10308
steal_leader = 10311
steal_leader = 10320
steal_leader = 10347
steal_leader = 10351
steal_leader = 10375
steal_leader = 10413
steal_leader = 10457
steal_leader = 10459
steal_leader = 10480
steal_leader = 9802
steal_leader = 9816
steal_leader = 9818
steal_leader = 9850
steal_leader = 9851
steal_leader = 9872
steal_leader = 9885
steal_leader = 9895
steal_leader = 9898
steal_leader = 9901
steal_leader = 9949
steal_leader = 9959
steal_leader = 9982
steal_leader = 10017
steal_leader = 10034
steal_leader = 10040
steal_leader = 10063
steal_leader = 10064
steal_leader = 10065
steal_leader = 10092
steal_leader = 10109
steal_leader = 10113
steal_leader = 10135
steal_leader = 10155
steal_leader = 10182
steal_leader = 10186
steal_leader = 10201
steal_leader = 10205
steal_leader = 10209
steal_leader = 10262
steal_leader = 10301
steal_leader = 10360
steal_leader = 10394
steal_leader = 10402
steal_leader = 10406
steal_leader = 10409
steal_leader = 10448
steal_leader = 9814
steal_leader = 9831
steal_leader = 9854
steal_leader = 9857
steal_leader = 9887
steal_leader = 9888
steal_leader = 9918
steal_leader = 9934
steal_leader = 9943
steal_leader = 9970
steal_leader = 9983
steal_leader = 10029
steal_leader = 10038
steal_leader = 10072
steal_leader = 10082
steal_leader = 10164
steal_leader = 10174
steal_leader = 10187
steal_leader = 10280
steal_leader = 10287
steal_leader = 10309
steal_leader = 10325
steal_leader = 10345
steal_leader = 10346
steal_leader = 10348
steal_leader = 10363
steal_leader = 10398
steal_leader = 10403
steal_leader = 10404
steal_leader = 10410
steal_leader = 10432
steal_leader = 10437
steal_leader = 10455
steal_leader = 10471
steal_leader = 10476
steal_leader = 10499
steal_leader = 9806
steal_leader = 9811
steal_leader = 9824
steal_leader = 9913
steal_leader = 9921
steal_leader = 9922
steal_leader = 9992
steal_leader = 10081
steal_leader = 10105
steal_leader = 10111
steal_leader = 10133
steal_leader = 10146
steal_leader = 10159
steal_leader = 10171
steal_leader = 10175
steal_leader = 10189
steal_leader = 10212
steal_leader = 10299
steal_leader = 10318
steal_leader = 10326
steal_leader = 10354
steal_leader = 10458
steal_leader = 10486
steal_leader = 9805
steal_leader = 9808
steal_leader = 9844
steal_leader = 9873
steal_leader = 9874
steal_leader = 9875
steal_leader = 9892
steal_leader = 9904
steal_leader = 9927
steal_leader = 9932
steal_leader = 9967
steal_leader = 9968
steal_leader = 9978
steal_leader = 10075
steal_leader = 10083
steal_leader = 10129
steal_leader = 10151
steal_leader = 10216
steal_leader = 10223
steal_leader = 10281
steal_leader = 10337
steal_leader = 10385
steal_leader = 10430
steal_leader = 10439
steal_leader = 10466
steal_leader = 10489
steal_leader = 10490
steal_leader = 9801
steal_leader = 9819
steal_leader = 9837
steal_leader = 9923
steal_leader = 9941
steal_leader = 9952
steal_leader = 9961
steal_leader = 9975
steal_leader = 9979
steal_leader = 9980
steal_leader = 10012
steal_leader = 10043
steal_leader = 10086
steal_leader = 10090
steal_leader = 10091
steal_leader = 10128
steal_leader = 10167
steal_leader = 10192
steal_leader = 10256
steal_leader = 10266
steal_leader = 10359
steal_leader = 10364
steal_leader = 10389
steal_leader = 10446
steal_leader = 10450
steal_leader = 10491
steal_leader = 10494
steal_leader = 9847
steal_leader = 9909
steal_leader = 9911
steal_leader = 9954
steal_leader = 9956
steal_leader = 9960
steal_leader = 9963
steal_leader = 10009
steal_leader = 10055
steal_leader = 10093
steal_leader = 10116
steal_leader = 10130
steal_leader = 10194
steal_leader = 10239
steal_leader = 10252
steal_leader = 10275
steal_leader = 10285
steal_leader = 10350
steal_leader = 10352
steal_leader = 10424
steal_leader = 10498
steal_leader = 9800
steal_leader = 9804
steal_leader = 9809
steal_leader = 9810
steal_leader = 9812
steal_leader = 9813
steal_leader = 9815
steal_leader = 9817
steal_leader = 9820
steal_leader = 9821
steal_leader = 9822
steal_leader = 9823
steal_leader = 9825
steal_leader = 9826
steal_leader = 9828
steal_leader = 9829
steal_leader = 9830
steal_leader = 9832
steal_leader = 9833
steal_leader = 9834
steal_leader = 9835
steal_leader = 9836
steal_leader = 9838
steal_leader = 9840
steal_leader = 9842
steal_leader = 9845
steal_leader = 9846
steal_leader = 9848
steal_leader = 9852
steal_leader = 9853
steal_leader = 9855
steal_leader = 9859
steal_leader = 9860
steal_leader = 9861
steal_leader = 9863
steal_leader = 9864
steal_leader = 9865
steal_leader = 9866
steal_leader = 9867
steal_leader = 9868
steal_leader = 9869
steal_leader = 9870
steal_leader = 9871
steal_leader = 9876
steal_leader = 9877
steal_leader = 9878
steal_leader = 9879
steal_leader = 9881
steal_leader = 9882
steal_leader = 9886
steal_leader = 9890
steal_leader = 9891
steal_leader = 9893
steal_leader = 9902
steal_leader = 9903
steal_leader = 9905
steal_leader = 9908
steal_leader = 9912
steal_leader = 9914
steal_leader = 9915
steal_leader = 9916
steal_leader = 9917
steal_leader = 9920
steal_leader = 9924
steal_leader = 9925
steal_leader = 9928
steal_leader = 9929
steal_leader = 9931
steal_leader = 9933
steal_leader = 9936
steal_leader = 9937
steal_leader = 9938
steal_leader = 9939
steal_leader = 9940
steal_leader = 9942
steal_leader = 9944
steal_leader = 9945
steal_leader = 9946
steal_leader = 9947
steal_leader = 9948
steal_leader = 9950
steal_leader = 9953
steal_leader = 9957
steal_leader = 9958
steal_leader = 9962
steal_leader = 9964
steal_leader = 9965
steal_leader = 9966
steal_leader = 9972
steal_leader = 9976
steal_leader = 9977
steal_leader = 9981
steal_leader = 9984
steal_leader = 9986
steal_leader = 9987
steal_leader = 9988
steal_leader = 9994
steal_leader = 9995
steal_leader = 9996
steal_leader = 9999
steal_leader = 10000
steal_leader = 10001
steal_leader = 10002
steal_leader = 10003
steal_leader = 10004
steal_leader = 10005
steal_leader = 10007
steal_leader = 10008
steal_leader = 10010
steal_leader = 10011
steal_leader = 10015
steal_leader = 10018
steal_leader = 10020
steal_leader = 10021
steal_leader = 10022
steal_leader = 10023
steal_leader = 10024
steal_leader = 10026
steal_leader = 10027
steal_leader = 10030
steal_leader = 10032
steal_leader = 10033
steal_leader = 10035
steal_leader = 10036
steal_leader = 10039
steal_leader = 10044
steal_leader = 10045
steal_leader = 10046
steal_leader = 10047
steal_leader = 10048
steal_leader = 10049
steal_leader = 10050
steal_leader = 10051
steal_leader = 10052
steal_leader = 10053
steal_leader = 10056
steal_leader = 10058
steal_leader = 10059
steal_leader = 10060
steal_leader = 10061
steal_leader = 10067
steal_leader = 10069
steal_leader = 10070
steal_leader = 10073
steal_leader = 10077
steal_leader = 10078
steal_leader = 10079
steal_leader = 10080
steal_leader = 10084
steal_leader = 10085
steal_leader = 10087
steal_leader = 10088
steal_leader = 10089
steal_leader = 10094
steal_leader = 10096
steal_leader = 10097
steal_leader = 10098
steal_leader = 10099
steal_leader = 10100
steal_leader = 10102
steal_leader = 10103
steal_leader = 10104
steal_leader = 10106
steal_leader = 10107
steal_leader = 10108
steal_leader = 10110
steal_leader = 10112
steal_leader = 10117
steal_leader = 10118
steal_leader = 10119
steal_leader = 10120
steal_leader = 10121
steal_leader = 10122
steal_leader = 10124
steal_leader = 10126
steal_leader = 10127
steal_leader = 10131
steal_leader = 10132
steal_leader = 10134
steal_leader = 10136
steal_leader = 10139
steal_leader = 10140
steal_leader = 10141
steal_leader = 10142
steal_leader = 10143
steal_leader = 10145
steal_leader = 10147
steal_leader = 10148
steal_leader = 10149
steal_leader = 10150
steal_leader = 10153
steal_leader = 10154
steal_leader = 10156
steal_leader = 10157
steal_leader = 10158
steal_leader = 10160
steal_leader = 10161
steal_leader = 10162
steal_leader = 10163
steal_leader = 10165
steal_leader = 10166
steal_leader = 10168
steal_leader = 10169
steal_leader = 10170
steal_leader = 10172
steal_leader = 10176
steal_leader = 10177
steal_leader = 10178
steal_leader = 10179
steal_leader = 10181
steal_leader = 10183
steal_leader = 10184
steal_leader = 10185
steal_leader = 10188
steal_leader = 10191
steal_leader = 10193
steal_leader = 10195
steal_leader = 10196
steal_leader = 10197
steal_leader = 10199
steal_leader = 10203
steal_leader = 10204
steal_leader = 10206
steal_leader = 10207
steal_leader = 10211
steal_leader = 10213
steal_leader = 10214
steal_leader = 10217
steal_leader = 10219
steal_leader = 10220
steal_leader = 10221
steal_leader = 10222
steal_leader = 10224
steal_leader = 10225
steal_leader = 10226
steal_leader = 10227
steal_leader = 10228
steal_leader = 10229
steal_leader = 10230
steal_leader = 10231
steal_leader = 10232
steal_leader = 10233
steal_leader = 10234
steal_leader = 10235
steal_leader = 10236
steal_leader = 10237
steal_leader = 10238
steal_leader = 10240
steal_leader = 10242
steal_leader = 10243
steal_leader = 10245
steal_leader = 10247
steal_leader = 10248
steal_leader = 10249
steal_leader = 10250
steal_leader = 10251
steal_leader = 10254
steal_leader = 10255
steal_leader = 10257
steal_leader = 10258
steal_leader = 10259
steal_leader = 10260
steal_leader = 10261
steal_leader = 10263
steal_leader = 10264
steal_leader = 10265
steal_leader = 10267
steal_leader = 10268
steal_leader = 10269
steal_leader = 10270
steal_leader = 10272
steal_leader = 10273
steal_leader = 10274
steal_leader = 10277
steal_leader = 10278
steal_leader = 10279
steal_leader = 10282
steal_leader = 10284
steal_leader = 10288
steal_leader = 10289
steal_leader = 10291
steal_leader = 10292
steal_leader = 10294
steal_leader = 10295
steal_leader = 10296
steal_leader = 10300
steal_leader = 10302
steal_leader = 10303
steal_leader = 10304
steal_leader = 10305
steal_leader = 10306
steal_leader = 10307
steal_leader = 10310
steal_leader = 10312
steal_leader = 10313
steal_leader = 10314
steal_leader = 10315
steal_leader = 10316
steal_leader = 10317
steal_leader = 10319
steal_leader = 10321
steal_leader = 10323
steal_leader = 10324
steal_leader = 10327
steal_leader = 10328
steal_leader = 10329
steal_leader = 10330
steal_leader = 10331
steal_leader = 10332
steal_leader = 10333
steal_leader = 10334
steal_leader = 10335
steal_leader = 10336
steal_leader = 10338
steal_leader = 10339
steal_leader = 10340
steal_leader = 10341
steal_leader = 10343
steal_leader = 10344
steal_leader = 10353
steal_leader = 10355
steal_leader = 10356
steal_leader = 10357
steal_leader = 10358
steal_leader = 10361
steal_leader = 10362
steal_leader = 10365
steal_leader = 10366
steal_leader = 10367
steal_leader = 10368
steal_leader = 10372
steal_leader = 10373
steal_leader = 10374
steal_leader = 10376
steal_leader = 10377
steal_leader = 10378
steal_leader = 10379
steal_leader = 10380
steal_leader = 10381
steal_leader = 10382
steal_leader = 10383
steal_leader = 10384
steal_leader = 10386
steal_leader = 10387
steal_leader = 10388
steal_leader = 10390
steal_leader = 10391
steal_leader = 10392
steal_leader = 10393
steal_leader = 10395
steal_leader = 10396
steal_leader = 10397
steal_leader = 10399
steal_leader = 10400
steal_leader = 10405
steal_leader = 10407
steal_leader = 10408
steal_leader = 10411
steal_leader = 10412
steal_leader = 10414
steal_leader = 10415
steal_leader = 10416
steal_leader = 10418
steal_leader = 10419
steal_leader = 10420
steal_leader = 10421
steal_leader = 10422
steal_leader = 10423
steal_leader = 10425
steal_leader = 10426
steal_leader = 10427
steal_leader = 10428
steal_leader = 10429
steal_leader = 10431
steal_leader = 10433
steal_leader = 10434
steal_leader = 10435
steal_leader = 10436
steal_leader = 10438
steal_leader = 10440
steal_leader = 10441
steal_leader = 10442
steal_leader = 10443
steal_leader = 10444
steal_leader = 10445
steal_leader = 10447
steal_leader = 10449
steal_leader = 10451
steal_leader = 10452
steal_leader = 10454
steal_leader = 10456
steal_leader = 10460
steal_leader = 10461
steal_leader = 10462
steal_leader = 10464
steal_leader = 10465
steal_leader = 10467
steal_leader = 10468
steal_leader = 10469
steal_leader = 10470
steal_leader = 10473
steal_leader = 10474
steal_leader = 10475
steal_leader = 10478
steal_leader = 10479
steal_leader = 10481
steal_leader = 10482
steal_leader = 10483
steal_leader = 10484
steal_leader = 10485
steal_leader = 10487
steal_leader = 10488
steal_leader = 10492
steal_leader = 10493
steal_leader = 10495
steal_leader = 10496
steal_leader = 10497
steal_leader = 10501
steal_leader = 10502
steal_leader = 10503
steal_leader = 10504
steal_leader = 10505
steal_leader = 10506
steal_leader = 10507
steal_leader = 10508
steal_leader = 10509
steal_leader = 10510
steal_leader = 10511
steal_leader = 10512
steal_leader = 10513



	extra_tc = 330 # Maybe later I'll balance it more...

	# Resource Reserves
	
	
	oil 		= 15000	
	supplies  	= 2000

	free = 		{
		oil 	=	150
		supplies =	300
		ic = 550
	}

	manpower = 1600
	dissent = 15


	ownedprovinces =      {
 

133
134
135
145
146
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
1776
1777
1778
178
179
180
181
182
183
1830
1831
1832
1833
1834
1835
1836
1837
1838
184
1841
1842
1843
1844
1845
1846
1847
1848
1849
185
1850
1856
1857
1858
186
187
1874
188
189
190
1907
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
433
434
435
500
501
502
503
504
505
506
507
508
511
562
577
94


		
		
	}
	controlledprovinces = {

133
134
135
145
146
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
1776
1777
1778
178
179
180
181
182
183
1830
1831
1832
1833
1834
1835
1836
1837
1838
184
1841
1842
1843
1844
1845
1846
1847
1848
1849
185
1850
1856
1857
1858
186
187
1874
188
189
190
1907
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
433
434
435
500
501
502
503
504
505
506
507
508
511
562
577
94




	}
	nationalprovinces =   {


133
134
135
145
146
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
1776
1777
1778
178
179
180
181
182
183
1830
1831
1832
1833
1834
1835
1836
1837
1838
184
1841
1842
1843
1844
1845
1846
1847
1848
1849
185
1850
1856
1857
1858
186
187
1874
188
189
190
1907
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
433
434
435
500
501
502
503
504
505
506
507
508
511
562
577
94



	} 

	techapps               = { 5550  1120  9010  9020  9030  9040  9090  9050  9060  9100  9110  9120  9140  4010  4020  4120  4130  4170  4250  4030 
                             4040  4140  4180  4220  4260  4280  2010  2020  2030  2040  2150  2290  2300  2310  2320  2450  2070  2330  2100  2400 
                             2460  2510  2050  2080  2170  2260  2340  2370  2380  2410  2470  2520  5010  5050  5080  5090  5100  5190  5020  5110 
                             5120  5200  5060  5070  5130  5140  5160  5180  5210  5470  5480  5490  1010  1020  1110  1190  1070  1200  1030  1210 
                             1220  1230  1310  6300  6310  6320  6330  6210  8010  8020  8030  8040  8050  8070  3010  3020  3030  3070  3080  3090 
                             3130  3140  3190  3200  3210  3250  3260  3270  3280  3400  3410  3420  3430  14000 14010
                           }

#################################
# USSR Barbarossa OOB 22nd June,1941
#
# NOTE: None of units got initial str higher then 50, to represent initial chaos and
# unfinished mobilization.
#
#####################################


# Northern Front, Leningrad Area
####################################

	# 7th Army
	landunit = {
        id = { type = 13000 id = 1 } 
		location = 150 
		name = "7ya Armiya"

		division = {
	        id = { type = 13000 id = 2 } 
			name = "54. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

		division = {
	        id = { type = 13000 id = 3 } 
			name = "71. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 4 } 
			name = "168. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 5 } 
			name = "237. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = anti_air
			brigade_model = 1
		}

	}

	# 14th Army
	landunit = {
        id = { type = 13000 id = 6 } 
		location = 133 
		name = "14ya Armiya"

		division = {
	        id = { type = 13000 id = 7 } 
			name = "14. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 8 } 
			name = "52. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 9 } 
			name = "1. Tankovaya Diviziya"
			type = armor
			model = 1
		}

	}

	# 42nd Corps
	landunit = {
        id = { type = 13000 id = 10 } 
		location = 135 
		name = "42oy Korps"

		division = {
	        id = { type = 13000 id = 11 } 
			name = "104. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 12 } 
			name = "122. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

	}


	# 23rd Army
	landunit = {
        id = { type = 13000 id = 13 } 
		location = 146 
		name = "23ya Armiya"

		division = {
	        id = { type = 13000 id = 14 } 
			name = "177. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 15 } 
			name = "191. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = anti_air
		}

		division = {
	        id = { type = 13000 id = 16 } 
			name = "8. Strelkovaya Brigada"
			type = infantry
			model = 2
			strength = 40
			max_strength = 40
			extra = artillery
		}

	}

	# 43rd Corps
	landunit = {
        id = { type = 13000 id = 17 } 
		location = 145 
		name = "43iy Korps"

		division = {
	        id = { type = 13000 id = 18 } 
			name = "115. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 19 } 
			name = "142. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = anti_air
		}


	}

	# 50th Corps
	landunit = {
        id = { type = 13000 id = 20 } 
		location = 152 
		name = "50iy Korps"

		division = {
	        id = { type = 13000 id = 21 } 
			name = "43. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 22 } 
			name = "70. Strelkovaya Diviziya"
			type = infantry
			model = 2

		}

		division = {
	        id = { type = 13000 id = 23 } 
			name = "123. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

	}

	# 10th Mech. Corps
	landunit = {
        id = { type = 13000 id = 24 } 
		location = 187 
		name = "10yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 25 } 
			name = "21. Tankovaya Diviziya"
			type = armor
			model = 1
			strength = 55
		}

		division = {
	        id = { type = 13000 id = 26 } 
			name = "24. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 55

		}

		division = {
	        id = { type = 13000 id = 27 } 
			name = "198. Motoriz. Div."
			type = motorized
			model = 0
			strength = 55
			extra = armored_car
			brigade_model = 1

		}

	}

	# 1st Mech. Corps
	landunit = {
        id = { type = 13000 id = 28 } 
		location = 200 
		name = "1yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 29 } 
			name = "3. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 30 } 
			name = "163. Motoriz. Div."
			type = motorized
			model = 0
			strength = 60
			extra = armored_car
		}

	}

# Northern-Western Front
##########################

	# 8th Army
	landunit = {
        id = { type = 13000 id = 31 } 
		location = 204 
		name = "8ya Armiya"

		division = {
	        id = { type = 13000 id = 32 } 
			name = "10. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 33 } 
			name = "48. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 34 } 
			name = "90. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 3 # Light modern art.

		}
	
	}
	
	# 11th Corps
	landunit = {
        id = { type = 13000 id = 35 } 
		location = 205 
		name = "11yj Korps"

		division = {
	        id = { type = 13000 id = 36 } 
			name = "11. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank
		}

		division = {
	        id = { type = 13000 id = 37 } 
			name = "125. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}

	# 12nd Mech. Corps
	landunit = {
        id = { type = 13000 id = 38 } 
		location = 577 
		name = "12yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 39 } 
			name = "23. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 60
		}


		division = {
	        id = { type = 13000 id = 40 } 
			name = "28. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 41 } 
			name = "202. Motoriz. Div."
			type = motorized
			model = 0
			strength = 60
			extra = armored_car
			brigade_model = 1

		}

	}

	# 16yj Korps
	landunit = {
        id = { type = 13000 id = 42 } 
		location = 207 
		name = "16yj Korps"

		division = {
	        id = { type = 13000 id = 43 } 
			name = "5. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 44 } 
			name = "33. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 45 } 
			name = "188. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}

	# 29yj Korps
	landunit = {
        id = { type = 13000 id = 46 } 
		location = 208 
		name = "29yj Korps"

		division = {
	        id = { type = 13000 id = 47 } 
			name = "179. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 48 } 
			name = "184. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}

	# 3rd Mech. Corps
	landunit = {
        id = { type = 13000 id = 49 } 
		location = 511 
		name = "3yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 50 } 
			name = "2. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40
			extra = heavy_armor
			brigade_model = 0

		}


		division = {
	        id = { type = 13000 id = 51 } 
			name = "5. Tankovaya Diviziya"
			type = armor
			model = 3
			strength = 40
		}

		division = {
	        id = { type = 13000 id = 52 } 
			name = "84. Motoriz. Div."
			type = motorized
			model = 0
			strength = 60
			extra = armored_car
		}

	}


	# 11ya Armiya
	landunit = {
        id = { type = 13000 id = 53 } 
		location = 207 
		name = "11ya Armiya"

		division = {
	        id = { type = 13000 id = 54 } 
			name = "23. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 55 } 
			name = "126. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank

		}

		division = {
	        id = { type = 13000 id = 56 } 
			name = "128. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air
		}

	}


	# 27ya Armiya
	landunit = {
        id = { type = 13000 id = 57 } 
		location = 203 
		name = "27ya Armiya"

		division = {
	        id = { type = 13000 id = 58 } 
			name = "16. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 59 } 
			name = "67. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air

		}

	}

	# 22oy Korps
	landunit = {
        id = { type = 13000 id = 60 } 
		location = 194 
		name = "22oy Korps"

		division = {
	        id = { type = 13000 id = 61 } 
			name = "180. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 62 } 
			name = "182. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}


	# 24oy Korps
	landunit = {
        id = { type = 13000 id = 63 } 
		location = 203 
		name = "22oy Korps"

		division = {
	        id = { type = 13000 id = 64 } 
			name = "181. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 65 } 
			name = "183. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60


		}

	}

	# 5th Paratrooper Corps
	landunit = {
        id = { type = 13000 id = 66 } 
		location = 202 
		name = "5yj Korps Voz.Des."

		division = {
	        id = { type = 13000 id = 67 } 
			name = "5yj Korps Voz.Des."
			type = paratrooper
			model = 0
			strength = 80

		}
	}



#Western Front
##################

	# 3ya Armiya
	landunit = {
        id = { type = 13000 id = 68 } 
		location = 209 
		name = "3ya Armiya"

		division = {
	        id = { type = 13000 id = 69 } 
			name = "27. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 3 # Light modern art.
		}

		division = {
	        id = { type = 13000 id = 70 } 
			name = "56. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank

		}

		division = {
	        id = { type = 13000 id = 71 } 
			name = "85. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60


		}

	}


	# 11th Mech. Corps
	landunit = {
        id = { type = 13000 id = 72 } 
		location = 505 
		name = "11yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 73 } 
			name = "33. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40
		}


		division = {
	        id = { type = 13000 id = 74 } 
			name = "29. Tankovaya Diviziya"
			type = armor
			model = 3
			strength = 40
		}

		division = {
	        id = { type = 13000 id = 75 } 
			name = "204. Motoriz. Div."
			type = motorized
			model = 0
			strength = 45
			extra = armored_car
		}

	}


	# 4ya Armiya
	landunit = {
        id = { type = 13000 id = 76 } 
		location = 506 
		name = "4ya Armiya"

		division = {
	        id = { type = 13000 id = 77 } 
			name = "6. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 78 } 
			name = "42. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air
		}

		division = {
	        id = { type = 13000 id = 79 } 
			name = "49. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60


		}

		division = {
	        id = { type = 13000 id = 80 } 
			name = "75. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60


		}

	}


	# 14th Mech. Corps
	landunit = {
        id = { type = 13000 id = 81 } 
		location = 508 
		name = "14yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 82 } 
			name = "22. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 45
		}


		division = {
	        id = { type = 13000 id = 83 } 
			name = "30. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 45
		}

		division = {
	        id = { type = 13000 id = 84 } 
			name = "205. Motoriz. Div."
			type = motorized
			model = 0
			strength = 45
			extra = armored_car
			brigade_model = 1
		}

	}


	# 10ya Armiya
	landunit = {
        id = { type = 13000 id = 85 } 
		location = 508 
		name = "10ya Armiya"

		division = {
	        id = { type = 13000 id = 86 } 
			name = "2. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 87 } 
			name = "8. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}


	# 5th Corps
	landunit = {
        id = { type = 13000 id = 88 } 
		location = 504 
		name = "5yj Korps"

		division = {
	        id = { type = 13000 id = 89 } 
			name = "13. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air

		}

		division = {
	        id = { type = 13000 id = 90 } 
			name = "86. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 91 } 
			name = "113. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}


	# 6th Cavalry Corps
	landunit = {
        id = { type = 13000 id = 92 } 
		location = 506 
		name = "6oj Kav. Korps"

		division = {
	        id = { type = 13000 id = 93 } 
			name = "6. Chongarskaya Kav. Div."
			type = cavalry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 94 } 
			name = "36. Kavaleriyskaya Diviziya"
			type = cavalry
			model = 2
			strength = 60

		}

	}


	# 6th Mech. Corps
	landunit = {
        id = { type = 13000 id = 95 } 
		location = 506 
		name = "6oj Mech. Korps"

		division = {
	        id = { type = 13000 id = 96 } 
			name = "4. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40
			extra = heavy_armor
			brigade_model = 0
		}


		division = {
	        id = { type = 13000 id = 97 } 
			name = "7. Tankovaya Diviziya"
			type = armor
			model = 3
			strength = 40
			extra = heavy_armor
			brigade_model = 0

		}

		division = {
	        id = { type = 13000 id = 98 } 
			name = "29. Motoriz. Div."
			type = motorized
			model = 0
			strength = 45
			extra = armored_car
		}

	}


	# 13th Mech. Corps
	landunit = {
        id = { type = 13000 id = 99 } 
		location = 506 
		name = "13yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 100 } 
			name = "25. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}


		division = {
	        id = { type = 13000 id = 101 } 
			name = "31. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

		division = {
	        id = { type = 13000 id = 102 } 
			name = "208. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}


	# 10th Army Reserve
	landunit = {
        id = { type = 13000 id = 103 } 
		location = 505 
		name = "10ya Armiya (Riezerv)"

		division = {
	        id = { type = 13000 id = 104 } 
			name = "155. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

	}

	# 2nd Corps
	landunit = {
        id = { type = 13000 id = 105 } 
		location = 221 
		name = "2oy Korps"

		division = {
	        id = { type = 13000 id = 106 } 
			name = "100. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 107 } 
			name = "161. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

	}

	# 21st Corps
	landunit = {
        id = { type = 13000 id = 108 } 
		location = 211 
		name = "21yj Korps"

		division = {
	        id = { type = 13000 id = 109 } 
			name = "17. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 110 } 
			name = "24. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 111 } 
			name = "37. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air
		}

	}


	# 44th Corps
	landunit = {
        id = { type = 13000 id = 112 } 
		location =211 
		name = "44oj Korps"

		division = {
	        id = { type = 13000 id = 113 } 
			name = "64. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank
			brigade_model = 1

		}

		division = {
	        id = { type = 13000 id = 114 } 
			name = "108. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}


	}

	# 47th Corps
	landunit = {
        id = { type = 13000 id = 115 } 
		location = 506 
		name = "47yj Korps"

		division = {
	        id = { type = 13000 id = 116 } 
			name = "55. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air

		}

		division = {
	        id = { type = 13000 id = 117 } 
			name = "121. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 118 } 
			name = "143. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}


	}


	# 4th Paratrooper Corps
	landunit = {
        id = { type = 13000 id = 119 } 
		location = 220 
		name = "4yj Korps Voz.Des."

		division = {
	        id = { type = 13000 id = 120 } 
			name = "4yj Korps Voz.Des."
			type = paratrooper
			model = 0
			strength = 80

		}
	}


	# 17th Mech. Corps
	landunit = {
        id = { type = 13000 id = 121 } 
		location = 506 
		name = "17yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 122 } 
			name = "27. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 15

		}


		division = {
	        id = { type = 13000 id = 123 } 
			name = "36. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 15

		}

		division = {
	        id = { type = 13000 id = 124 } 
			name = "209. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}


	# 20th Mech. Corps
	landunit = {
        id = { type = 13000 id = 125 } 
		location = 506 
		name = "20yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 126 } 
			name = "26. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 20

		}


		division = {
	        id = { type = 13000 id = 127 } 
			name = "38. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 20

		}

		division = {
	        id = { type = 13000 id = 128 } 
			name = "210. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

	# Western Front Reserve
	landunit = {
        id = { type = 13000 id = 129 } 
		location = 221 
		name = "Rezerv Zapadnovo Fronta"

		division = {
	        id = { type = 13000 id = 130 } 
			name = "50. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank

		}

	}



#Southern-Western Front
###############################


	# 5th Army
	landunit = {
        id = { type = 13000 id = 131 } 
		location = 503 
		name = "5ya Armiya"

		division = {
	        id = { type = 13000 id = 132 } 
			name = "45. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 1 # Medium GW art.

		}

		division = {
	        id = { type = 13000 id = 133 } 
			name = "62. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

	}

	# 27th Corps
	landunit = {
        id = { type = 13000 id = 134 } 
		location = 226 
		name = "27yj Korps"

		division = {
	        id = { type = 13000 id = 135 } 
			name = "87. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 136 } 
			name = "124. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 137 } 
			name = "135. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

	}

	# 9th Mech. Corps
	landunit = {
        id = { type = 13000 id = 138 } 
		location = 226 
		name = "9yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 139 } 
			name = "20. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}


		division = {
	        id = { type = 13000 id = 140 } 
			name = "35. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

		division = {
	        id = { type = 13000 id = 141 } 
			name = "131. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
			brigade_model = 1
		}

	}


	# 22th Mech. Corps
	landunit = {
        id = { type = 13000 id = 142 } 
		location = 226 
		name = "22oj Mech. Korps"

		division = {
	        id = { type = 13000 id = 143 } 
			name = "19. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}


		division = {
	        id = { type = 13000 id = 144 } 
			name = "41. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40
			extra = heavy_armor
			brigade_model = 0

		}

		division = {
	        id = { type = 13000 id = 145 } 
			name = "215. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}


	# 6th Army
	landunit = {
        id = { type = 13000 id = 146 } 
		location = 502 
		name = "6ya Armiya"

		division = {
	        id = { type = 13000 id = 147 } 
			name = "41. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 148 } 
			name = "97. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 149 } 
			name = "159. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

	}


	# 37th Corps
	landunit = {
        id = { type = 13000 id = 150 } 
		location = 501 
		name = "37yj Korps"

		division = {
	        id = { type = 13000 id = 151 } 
			name = "80. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank
			brigade_model = 1

		}

		division = {
	        id = { type = 13000 id = 152 } 
			name = "139. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 153 } 
			name = "141. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

	}


	# 5th Cavalry Corps
	landunit = {
        id = { type = 13000 id = 154 } 
		location = 501 
		name = "5yj Kav. Korps"

		division = {
	        id = { type = 13000 id = 155 } 
			name = "3. Bessarabskaya Kav. Div."
			type = cavalry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 156 } 
			name = "14. Kavaleriyskaya Diviziya"
			type = cavalry
			model = 2
			strength = 60

		}

	}


	# 4th Mech. Corps
	landunit = {
        id = { type = 13000 id = 157 } 
		location = 228 
		name = "4yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 158 } 
			name = "8. Tankovaya Diviziya"
			type = armor
			model = 3
			strength = 40
			extra = heavy_armor
			brigade_model = 0

		}


		division = {
	        id = { type = 13000 id = 159 } 
			name = "32. Tankovaya Diviziya"
			type = armor
			model = 3
			strength = 40
			extra = heavy_armor
			brigade_model = 0

		}

		division = {
	        id = { type = 13000 id = 160 } 
			name = "81. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

	# 15th Mech. Corps
	landunit = {
        id = { type = 13000 id = 161 } 
		location = 238 
		name = "15yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 162 } 
			name = "10. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40
			extra = heavy_armor
			brigade_model = 0
		}


		division = {
	        id = { type = 13000 id = 163 } 
			name = "37. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

		division = {
	        id = { type = 13000 id = 164 } 
			name = "212. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

	# 12th Army
	landunit = {
        id = { type = 13000 id = 165 } 
		location = 500 
		name = "12ya Armiya"

		division = {
	        id = { type = 13000 id = 166 } 
			name = "44. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 167 } 
			name = "58. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 168 } 
			name = "192. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60
		}

	}

	# 17th Corps
	landunit = {
        id = { type = 13000 id = 169 } 
		location = 230 
		name = "17yj Korps"

		division = {
	        id = { type = 13000 id = 170 } 
			name = "60. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 171 } 
			name = "96. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 172 } 
			name = "164. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

	}


	# 16th Mech. Corps
	landunit = {
        id = { type = 13000 id = 173 } 
		location = 230 
		name = "16yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 174 } 
			name = "15. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}


		division = {
	        id = { type = 13000 id = 175 } 
			name = "39. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}

		division = {
	        id = { type = 13000 id = 176 } 
			name = "240. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}


	# 26th Army
	landunit = {
        id = { type = 13000 id = 177 } 
		location = 433 
		name = "26ya Armiya"

		division = {
	        id = { type = 13000 id = 178 } 
			name = "72. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 179 } 
			name = "173. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 180 } 
			name = "199. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

	}


	# 8th Mech. Corps
	landunit = {
        id = { type = 13000 id = 181 } 
		location = 231 
		name = "8oj Mech. Korps"

		division = {
	        id = { type = 13000 id = 182 } 
			name = "12. Tankovaya Diviziya"
			type = armor
			model = 3
			strength = 20
			extra = heavy_armor
			brigade_model = 0

		}


		division = {
	        id = { type = 13000 id = 183 } 
			name = "34. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

		division = {
	        id = { type = 13000 id = 184 } 
			name = "7. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

	# 31st Corps
	landunit = {
        id = { type = 13000 id = 185 } 
		location = 231 
		name = "31yj Korps"

		division = {
	        id = { type = 13000 id = 186 } 
			name = "193. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 187 } 
			name = "195. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 188 } 
			name = "200. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 2
		}

	}

	# 36st Corps
	landunit = {
        id = { type = 13000 id = 189 } 
		location = 229 
		name = "36oj Korps"

		division = {
	        id = { type = 13000 id = 190 } 
			name = "140. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 191 } 
			name = "146. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 192 } 
			name = "228. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_tank
		}

	}

	# 49st Corps
	landunit = {
        id = { type = 13000 id = 193 } 
		location = 229 
		name = "49yj Korps"

		division = {
	        id = { type = 13000 id = 194 } 
			name = "190. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 195 } 
			name = "197. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 196 } 
			name = "199. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = anti_air
		}

	}

	# 55st Corps
	landunit = {
        id = { type = 13000 id = 197 } 
		location = 229 
		name = "55yj Korps"

		division = {
	        id = { type = 13000 id = 198 } 
			name = "130. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 199 } 
			name = "169. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 200 } 
			name = "189. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

	}


	# 1st Paratrooper Corps
	landunit = {
        id = { type = 13000 id = 201 } 
		location = 239 
		name = "1yj Korps Voz.Des."

		division = {
	        id = { type = 13000 id = 202 } 
			name = "1yj Korps Voz.Des."
			type = paratrooper
			model = 0
			strength = 80

		}
	}

	# 19th Mech. Corps
	landunit = {
        id = { type = 13000 id = 203 } 
		location = 237 
		name = "19yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 204 } 
			name = "40. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}


		division = {
	        id = { type = 13000 id = 205 } 
			name = "43. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}

		division = {
	        id = { type = 13000 id = 206 } 
			name = "213. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}


	# 24th Mech. Corps
	landunit = {
        id = { type = 13000 id = 207 } 
		location = 237 
		name = "24yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 208 } 
			name = "45. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 15

		}


		division = {
	        id = { type = 13000 id = 209 } 
			name = "49. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 15

		}

		division = {
	        id = { type = 13000 id = 210 } 
			name = "216. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

#9th Separate Army - Odessa MD
####################################

	# 14st Corps
	landunit = {
        id = { type = 13000 id = 211 } 
		location = 232 
		name = "14yj Korps"

		division = {
	        id = { type = 13000 id = 212 } 
			name = "190. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = engineer

		}

		division = {
	        id = { type = 13000 id = 213 } 
			name = "197. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}



	}


	# 35st Corps
	landunit = {
        id = { type = 13000 id = 214 } 
		location = 435 
		name = "35yj Korps"

		division = {
	        id = { type = 13000 id = 215 } 
			name = "95. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 216 } 
			name = "176. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}



	}

	# 48th Corps
	landunit = {
        id = { type = 13000 id = 217 } 
		location = 434 
		name = "48yj Korps"

		division = {
	        id = { type = 13000 id = 218 } 
			name = "30. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 219 } 
			name = "74. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 220 } 
			name = "150. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

	}

	# 2th Cavalry Corps
	landunit = {
        id = { type = 13000 id = 221 } 
		location = 233 
		name = "2oj Kav. Korps"

		division = {
	        id = { type = 13000 id = 222 } 
			name = "9. Krymskaya Kav. Div."
			type = cavalry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 223 } 
			name = "5. Kavaleriyskaya Diviziya"
			type = cavalry
			model = 2
			strength = 60

		}

	}

	# 2nd Mech. Corps
	landunit = {
        id = { type = 13000 id = 224 } 
		location = 232 
		name = "2oj Mech. Korps"

		division = {
	        id = { type = 13000 id = 225 } 
			name = "11. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}


		division = {
	        id = { type = 13000 id = 226 } 
			name = "16. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}

		division = {
	        id = { type = 13000 id = 227 } 
			name = "15. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
			brigade_model = 1

		}

	}


	# 18nd Mech. Corps
	landunit = {
        id = { type = 13000 id = 228 } 
		location = 232 
		name = "18yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 229 } 
			name = "44. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}


		division = {
	        id = { type = 13000 id = 230 } 
			name = "47. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

		division = {
	        id = { type = 13000 id = 231 } 
			name = "218. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}


#
# Other units deployed at the start (id's 328-348)
#
###################################################

	# 2nf Paratrooper Corps
	landunit = {
        id = { type = 13000 id = 328 } 
		location = 248 # Charkov 
		name = "2oj Korps Voz.Des."

		division = {
	        id = { type = 13000 id = 329 } 
			name = "2oj Korps Voz.Des."
			type = paratrooper
			model = 0
			strength = 80

		}
	}

	# 3rd Paratrooper Corps
	landunit = {
        id = { type = 13000 id = 330 } 
		location = 252 # Crimea 
		name = "3yj Korps Voz.Des."

		division = {
	        id = { type = 13000 id = 331 } 
			name = "3yj Korps Voz.Des."
			type = paratrooper
			model = 0
			strength = 80

		}
	}

	# 9th Corps
	landunit = {
        id = { type = 13000 id = 332 } 
		location = 253 # Sevastopol 
		name = "9yj Korps"

		division = {
	        id = { type = 13000 id = 333 } 
			name = "47. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60

		}

		division = {
	        id = { type = 13000 id = 334 } 
			name = "106. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 335 } 
			name = "156. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
		}

		division = {
	        id = { type = 13000 id = 336 } 
			name = "32. Kavaleriyskaya Diviziya"
			type = cavalry
			model = 2
			strength = 60

		}

	}


	# 21nd Mech. Corps
	landunit = {
        id = { type = 13000 id = 337 } 
		location = 278 # Tula 
		name = "21yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 338 } 
			name = "42. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 20

		}


		division = {
	        id = { type = 13000 id = 339 } 
			name = "46. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 20

		}

		division = {
	        id = { type = 13000 id = 340 } 
			name = "185. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

	# 23rd Mech. Corps
	landunit = {
        id = { type = 13000 id = 341 } 
		location = 256  
		name = "23yj Mech. Korps"

		division = {
	        id = { type = 13000 id = 342 } 
			name = "48. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 20

		}


		division = {
	        id = { type = 13000 id = 343 } 
			name = "51. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 20

		}

		division = {
	        id = { type = 13000 id = 344 } 
			name = "220. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}

	}

	# 28th Mech. Corps
	landunit = {
        id = { type = 13000 id = 345 } 
		location = 258 # Rostov 
		name = "28oj Mech. Korps"

		division = {
	        id = { type = 13000 id = 346 } 
			name = "6. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}


		division = {
	        id = { type = 13000 id = 347 } 
			name = "54. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

		division = {
	        id = { type = 13000 id = 348 } 
			name = "236. Motoriz. Div."
			type = motorized
			model = 0
			strength = 60
			extra = armored_car
		}

	}

#
# HQ Units - First Eshelon
#######################################

	landunit = {
        id = { type = 13000 id = 232 } 
		location = 187 # Piter
		leader = 10193 # Popov
		name = "Leningrad Front HQ"

		division = {
	        id = { type = 13000 id = 233 } 
			name = "Leningrad Front HQ"
			type = hq
		}
	}

	landunit = {
        id = { type = 13000 id = 234 } 
		location = 197 # Riga
		leader = 10068 # Kuznietsov
		name = "North-Western Front HQ"

		division = {
	        id = { type = 13000 id = 235 } 
			name = "North-Western Front HQ"
			type = hq
		}
	}

	landunit = {
        id = { type = 13000 id = 236 } 
		location = 212 # Minsk
		leader = 10173 # Pavlov
		name = "Western Front HQ"

		division = {
	        id = { type = 13000 id = 237 } 
			name = "Western Front HQ"
			type = hq
		}
	}

	landunit = {
        id = { type = 13000 id = 238 } 
		location = 238 # Kiev
		leader = 10014 # Kirponos
		name = "South-Western Front HQ"

		division = {
	        id = { type = 13000 id = 239 } 
			name = "South-Western Front HQ"
			type = hq
		}

	}

	landunit = {
        id = { type = 13000 id = 240 } 
		location = 233 # Odessa
		name = "Southern Front HQ"
		leader = 10334 # Tiuleniev

		division = {
	        id = { type = 13000 id = 241 } 
			name = "Southern Front HQ"
			type = hq
		}

	}

	landunit = {
        id = { type = 13000 id = 242 } 
		location = 175 # Moscow
		leader = 10393 # Zhukov
		name = "STAVKA"

		division = {
	        id = { type = 13000 id = 243 } 
			name = "STAVKA HQ"
			type = hq
		}

	}


#
#
# Reserves - 2nd eshelon
####################################

# location 238 
# Kiev - from Transbaikal MD
# 16ya Armiya

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 244 } 
			name = "46. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 245 } 
			name = "152. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

	

# 5th Mech. Corps
# location = 248 
# Kharkov 
# 5yj Mech. Korps

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 246 } 
			name = "13. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 247 } 
			name = "17. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 248 } 
			name = "109. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}


# location = 237 
# near Kiev
# 19ya Armiya

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 249 } 
			name = "127. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 250 } 
			name = "134. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 251 } 
			name = "162. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 252 } 
			name = "38. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}



#location = 237 
# near Kiev 
# 26oj Mech. Korps

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 253 } 
			name = "52. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40
			extra = engineer

		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 254 } 
			name = "56. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 40

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 255 } 
			name = "103. Motoriz. Div."
			type = motorized
			model = 0
			strength = 40
			extra = armored_car
		}



# location = 237 
# near Kiev
# 34yj Korps

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 256 } 
			name = "129. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = engineer
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 257 } 
			name = "158. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 258 } 
			name = "171. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}



# 20th Army
# Orel Area

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 259 } 
			name = "110. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 260 } 
			name = "144. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 261 } 
			name = "172. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 262 } 
			name = "73. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 263 } 
			name = "229. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 264 } 
			name = "233. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}


# 7th Corps
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 265 } 
			name = "14. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 45
			extra = engineer

		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 266 } 
			name = "18. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 45

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 267 } 
			name = "1. Motoriz. Div."
			type = motorized
			model = 0
			strength = 60
			extra = armored_car
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 268 } 
			name = "18. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4 # Medium modern			
		}

# 21nd Army
# Moving from Urals to Western District
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 269 } 
			name = "53. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 270 } 
			name = "148. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 271 } 
			name = "167. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 272 } 
			name = "61. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 273 } 
			name = "117. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 274 } 
			name = "154. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 4 # Medium modern	
		}

# 25h Corps
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 275 } 
			name = "50. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50
			extra = engineer

		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 276 } 
			name = "55. Tankovaya Diviziya"
			type = light_armor
			model = 1
			strength = 50

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 277 } 
			name = "219. Motoriz. Div."
			type = motorized
			model = 0
			strength = 60
			extra = armored_car
		}


# 22nd Army
# Moving from Urals to Western District
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 278 } 
			name = "98. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 279 } 
			name = "112. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 280 } 
			name = "153. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 281 } 
			name = "170. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 282 } 
			name = "174. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4			
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 283 } 
			name = "186. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 60			
		}


# 24th Army 
# Siberia -  West
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 284 } 
			name = "91. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 2 # Heavy	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 285 } 
			name = "119. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 4	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 286 } 
			name = "166. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 287 } 
			name = "107. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 288 } 
			name = "133. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 289 } 
			name = "178. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}



landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 349 } 
			name = "Reserve Front HQ"
			type = hq
		}


#
# STAVKA Reserves (II reinforcements)
#
# id's 298 -
#
#########################################

#
# North
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 290 } 
			name = "88. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 291 } 
			name = "111. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 292 } 
			name = "9. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 2 # Heavy GW		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 293 } 
			name = "31. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 2 # Heavy GW		
		}

#
# South
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 294 } 
			name = "136. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 295 } 
			name = "138. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 296 } 
			name = "20. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 297 } 
			name = "47. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 298 } 
			name = "63. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 299 } 
			name = "76. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 300 } 
			name = "77. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 301 } 
			name = "17. Gornokav. Diviziya"
			type = cavalry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 302 } 
			name = "24. Kavaleriyskaya Diviziya"
			type = cavalry
			model = 2		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 303 } 
			name = "4. Strelkovaya Diviziya"
			type = infantry
			model = 2		
		}

#
# Crimea
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 304 } 
			name = "116. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 2 # heavy GW		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 305 } 
			name = "196. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 2 # heavy GW		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 306 } 
			name = "206. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 2 # heavy GW		
		}

#
# Caucasus
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 307 } 
			name = "28. Gornostrelk. Diviziya"
			type = bergsjaeger
			model = 0		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 308 } 
			name = "165. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 4		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 309 } 
			name = "175. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 4		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 310 } 
			name = "157. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 4		
		}

#
# Kharkov
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 311 } 
			name = "187. Strelkovaya Diviziya"
			type = infantry
			model = 2		
			extra = artillery
			brigade_model = 4		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 312 } 
			name = "227. Strelkovaya Diviziya"
			type = infantry
			model = 2			
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 313 } 
			name = "232. Strelkovaya Diviziya"
			type = infantry
			model = 2			
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 314 } 
			name = "102. Strelkovaya Diviziya"
			type = infantry
			model = 2			
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 315 } 
			name = "132. Strelkovaya Diviziya"
			type = infantry
			model = 2			
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 316 } 
			name = "151. Strelkovaya Diviziya"
			type = infantry
			model = 2			
		}


#
# Moscow
#

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 317 } 
			name = "137. Strelkovaya Diviziya"
			type = infantry
			model = 2	
			extra = rocket_artillery		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 318 } 
			name = "160. Strelkovaya Diviziya"
			type = infantry
			model = 2	
			extra = rocket_artillery		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 319 } 
			name = "118. Strelkovaya Diviziya"
			type = infantry
			model = 2	
			extra = artillery
			brigade_model = 4		
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 320 } 
			name = "235. Strelkovaya Diviziya"
			type = infantry
			model = 2	
			extra = artillery	
			brigade_model = 4	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 321 } 
			name = "19. Strelkovaya Diviziya"
			type = infantry
			model = 2	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 322 } 
			name = "149. Strelkovaya Diviziya"
			type = infantry
			model = 2	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 323 } 
			name = "217. Strelkovaya Diviziya"
			type = infantry
			model = 2	
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 324 } 
			name = "89. Strelkovaya Diviziya"
			type = infantry
			model = 2	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 325 } 
			name = "120. Strelkovaya Diviziya"
			type = infantry
			model = 2	
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 326 } 
			name = "145. Strelkovaya Diviziya"
			type = infantry
			model = 2	
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 327 } 
			name = "222. Strelkovaya Diviziya"
			type = infantry
			model = 2	
	
		}
		
		
#
# General mobilization (Moscow Battle)
# 47 divisions, last hope
# id's 350-397
#
####################################

landdivision = {

dormant = yes

id = { type = 13000 id = 350 } 
name = "303. Strelkovaya Diviziya"
type = infantry
model = 2 
}


landdivision = {

dormant = yes

id = { type = 13000 id = 351 } 
name = "29. Strelkovaya Diviziya"
type = militia
model = 0 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 352 } 
name = "248. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 353 } 
name = "194. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 354 } 
name = "220. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 355 } 
name = "247. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 356 } 
name = "8. Strelkovaya Diviziya"
type = militia
model = 0 
}


landdivision = {

dormant = yes

id = { type = 13000 id = 357 } 
name = "2. Strelkovaya Diviziya"
type = militia
model = 0 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 358 } 
name = "140. Strelkovaya Diviziya"
type = militia
model = 0 
}


landdivision = {

dormant = yes

id = { type = 13000 id = 359 } 
name = "226. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 360 } 
name = "283. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 361 } 
name = "298. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 362 } 
name = "307. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 363 } 
name = "52. Kavaleriyskaya Diviziya"
type = cavalry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 364 } 
name = "55. Kavaleriyskaya Diviziya"
type = cavalry
model = 2 
}


landdivision = {

dormant = yes

id = { type = 13000 id = 365 } 
name = "282. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 366 } 
name = "260. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 367 } 
name = "287. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 368 } 
name = "280. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 369 } 
name = "108. Tankovaya Diviziya"
type = light_armor
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 370 } 
name = "290. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 371 } 
name = "260. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 372 } 
name = "258. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 373 } 
name = "299. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 374 } 
name = "278. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 375 } 
name = "279. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 376 } 
name = "217. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 377 } 
name = "211. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 378 } 
name = "103. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 379 } 
name = "309. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 380 } 
name = "229. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 381 } 
name = "101. Mot. Diviziya"
type = motorized
model = 0 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 382 } 
name = "45. Kavaleriyskaya Diviziya"
type = cavalry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 383 } 
name = "214. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 384 } 
name = "36. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 385 } 
name = "244. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 386 } 
name = "107. Mot. Diviziya"
type = motorized
model = 0 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 387 } 
name = "251. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 388 } 
name = "242. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 389 } 
name = "250. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 390 } 
name = "50. Kavaleriyskaya Diviziya"
type = cavalry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 391 } 
name = "53. Kavaleriyskaya Diviziya"
type = cavalry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 392 } 
name = "246. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 393 } 
name = "243. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 394 } 
name = "256. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 395 } 
name = "249. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 396 } 
name = "252. Strelkovaya Diviziya"
type = infantry
model = 2 
}

landdivision = {

dormant = yes

id = { type = 13000 id = 397 } 
name = "4. Strelkovaya Diviziya"
type = militia
model = 0 
} 		


#
# VVS (Voyenno-Vozdushnyje Sily)
####################################


		airunit = {
		id = { type = 13000 id = 700 }
		name = "Leningrad PVO"
		location = 187
		base = 187
			
			division = {
			id = { type = 13000 id = 701 }
			name = "1. AD"
			strength = 40
			type = interceptor
                        model = 2 #Yak 1
			}

			division = {
			id = { type = 13000 id = 702 }
			name = "2. AD"
			strength = 40
			type = interceptor
                      	model = 1 # I 16
			}	

			division = {
			id = { type = 13000 id = 703 }
			name = "4. AD"
			strength = 40
			type = interceptor
                       	model = 0 #I-15
                        }

			division = {
			id = { type = 13000 id = 704 }
			name = "5. AD"
			strength = 40
			type = interceptor
		        model = 0 #I 15
                       	}

			division = {
			id = { type = 13000 id = 705 }
			name = "23. BAD"
			strength = 40
			type = tactical_bomber
                     	model = 1 #SB2
                       	}

			division = {
			id = { type = 13000 id = 706 }
			name = "24. BAD"
			strength = 40
			type = tactical_bomber
                      	model = 1 #SB2
			}                        

			division = {
			id = { type = 13000 id = 707 }
			name = "26. AD"
			strength = 40
			type = tactical_bomber
                        model = 1 #SB2
			}
		
			division = {
			id = { type = 13000 id = 708 }
			name = "40. BAD"
			strength = 40
			type = tactical_bomber
                     	model = 2 #PE2
                       	}

			division = {
			id = { type = 13000 id = 709 }
			name = "41. AD"
			strength = 40
			type = tactical_bomber
                      	model = 1 #SB2
			}                        

			division = {
			id = { type = 13000 id = 710 }
			name = "3. BAD"
			strength = 40
			type = strategic_bomber
                        model = 0 #IL4
			}
			}

		airunit = {
		id = { type = 13000 id = 711 }
		name = "Baltiiskii PVO"
		location = 197
		base = 197
			
			division = {
			id = { type = 13000 id = 712 }
			name = "6. AD"
			strength = 40
			type = interceptor
                        model = 1 #I-16
			}

			division = {
			id = { type = 13000 id = 713 }
			name = "7. AD"
			strength = 40
			type = interceptor
                      	model = 1 # I 16
			}	

			division = {
			id = { type = 13000 id = 714 }
			name = "8. AD"
			strength = 40
			type = interceptor
                       	model = 0 #I-15
                        }

			division = {
			id = { type = 13000 id = 715 }
			name = "39. IAD"
			strength = 40
			type = interceptor
		        model = 2 #LaGG 3
                       	}

			division = {
			id = { type = 13000 id = 716 }
			name = "12. BAD"
			strength = 40
			type = tactical_bomber
                     	model = 1 #SB2
                       	}

			division = {
			id = { type = 13000 id = 717 }
			name = "13. BAD"
			strength = 40
			type = tactical_bomber
                      	model = 1 #SB2
			}                        

			division = {
			id = { type = 13000 id = 718 }
			name = "57. AD"
			strength = 40
			type = tactical_bomber
                        model = 1 #SB2
			}
		
			division = {
			id = { type = 13000 id = 719 }
			name = "62. BAD"
			strength = 40
			type = tactical_bomber
                     	model = 2 #PE2
                       	}
			}

		airunit = {
		id = { type = 13000 id = 720 }
		name = "Zapadnaya Vozdushnaya Armiya"
		location = 503
		base = 503
			
			division = {
			id = { type = 13000 id = 721 }
			name = "9. AD"
			strength = 40
			type = interceptor
                        model = 1 #I16
			}

			division = {
			id = { type = 13000 id = 722 }
			name = "10. AD"
			strength = 40
			type = interceptor
                      	model = 1 # I 16
			}	

			division = {
			id = { type = 13000 id = 723 }
			name = "11. AD"
			strength = 40
			type = interceptor
                       	model = 0 #I-15
                        }

			division = {
			id = { type = 13000 id = 724 }
			name = "25. AD"
			strength = 40
			type = tactical_bomber
		        model = 1 #SB2
                       	}

			division = {
			id = { type = 13000 id = 725 }
			name = "28. AD"
			strength = 40
			type = tactical_bomber
                     	model = 1 #SU2
                       	}

			division = {
			id = { type = 13000 id = 726 }
			name = "31. BAD"
			strength = 40
			type = tactical_bomber
                      	model = 2 #PE2
			}                        

			division = {
			id = { type = 13000 id = 727 }
			name = "29. BAD"
			strength = 40
			type = strategic_bomber
                        model = 0 #IL4
			}
		
			division = {
			id = { type = 13000 id = 728 }
			name = "30. BAD"
			strength = 40
			type = strategic_bomber
                     	model = 0 #IL4
                       	}

			division = {
			id = { type = 13000 id = 729 }
			name = "42. BAD"
			strength = 40
			type = strategic_bomber
                      	model = 0 #IL4
			}                        
			}



		airunit = {
		id = { type = 13000 id = 740 }
		name = "Yugo-Zapadnaya Vozdushnaya Armiya"
		location = 229
		base = 229
			
			division = {
			id = { type = 13000 id = 741 }
			name = "14. AD"
			strength = 40
			type = interceptor
                        model = 1 #I16
			}

			division = {
			id = { type = 13000 id = 742 }
			name = "15. AD"
			strength = 40
			type = interceptor
                      	model = 1 # I 16
			}	

			division = {
			id = { type = 13000 id = 743 }
			name = "16. AD"
			strength = 40
			type = interceptor
                       	model = 0 #I-15
                        }

			division = {
			id = { type = 13000 id = 744 }
			name = "17. AD"
			strength = 40
			type = interceptor
		        model = 0 #I-15
                       	}

			division = {
			id = { type = 13000 id = 745 }
			name = "19. AD"
			strength = 40
			type = tactical_bomber
                     	model = 1 #SB2
                       	}

			division = {
			id = { type = 13000 id = 746 }
			name = "32. BAD"
			strength = 40
			type = tactical_bomber
                      	model = 2 #PE2
			}                        

			division = {
			id = { type = 13000 id = 747 }
			name = "33. BAD"
			strength = 40
			type = tactical_bomber
                        model = 2 #PE2
			}
		
			division = {
			id = { type = 13000 id = 748 }
			name = "37. AD"
			strength = 40
			type = tactical_bomber
                     	model = 1 #SU2
                       	}

			division = {
			id = { type = 13000 id = 749 }
			name = "34. BAD"
			strength = 40
			type = strategic_bomber
                      	model = 0 #IL4
			}                        
			}


		airunit = {
		id = { type = 13000 id = 750 }
		name = "Odessa PVO"
		location = 233
		base = 233
			
			division = {
			id = { type = 13000 id = 751 }
			name = "20. AD"
			strength = 40
			type = interceptor
                        model = 1 #I16
			}

			division = {
			id = { type = 13000 id = 752 }
			name = "21. AD"
			strength = 40
			type = interceptor
                      	model = 1 # I 16
			}	

			division = {
			id = { type = 13000 id = 753 }
			name = "22. AD"
			strength = 40
			type = interceptor
                       	model = 0 #I-15
                        }

			division = {
			id = { type = 13000 id = 754 }
			name = "27. IAD"
			strength = 40
			type = interceptor
		        model = 2 #MiG3
                       	}

			division = {
			id = { type = 13000 id = 755 }
			name = "18. BAD"
			strength = 40
			type = tactical_bomber
                     	model = 1 #SB2
                       	}

			division = {
			id = { type = 13000 id = 756 }
			name = "45. BAD"
			strength = 40
			type = tactical_bomber
                      	model = 1 #SB2
			}                        

			division = {
			id = { type = 13000 id = 757 }
			name = "35. BAD"
			strength = 40
			type = strategic_bomber
                        model = 0 #IL4
			}
		

			division = {
			id = { type = 13000 id = 759 }
			name = "38. BAD"
			strength = 40
			type = strategic_bomber
                      	model = 0 #IL4
			}                        
			}



		airunit = {
		id = { type = 13000 id = 760 }
		name = "Moskva PVO"
		location = 175
		base = 175
			
			division = {
			id = { type = 13000 id = 761 }
			name = "36. IAD"
			strength = 100
			type = interceptor
                        model = 2 #Mig3
			}

			division = {
			id = { type = 13000 id = 762 }
			name = "43. IAD"
			strength = 100
			type = interceptor
                      	model = 2 # Yak1
			}	

			division = {
			id = { type = 13000 id = 763 }
			name = "46/48. Transport Division"
			strength = 100
			type = transport_plane
                       	model = 0 #TB3
                        }

			division = {
			id = { type = 13000 id = 764 }
			name = "49/50. Transport Division"
			strength = 100
			type = transport_plane
		        model = 0 #TB3
                       	}

			division = {
			id = { type = 13000 id = 765 }
			name = "44. IAD"
			strength = 100
			type = interceptor
                     	model = 2 #Mig3
                       	}

			division = {
			id = { type = 13000 id = 766 }
			name = "47. SzAD"
			strength = 100
			type = cas
                      	model = 0 #IL2
			}                        

			division = {
			id = { type = 13000 id = 767 }
			name = "55. AD"
			strength = 40
			type = tactical_bomber
                        model = 1 #SB2
			}
		
			division = {
			id = { type = 13000 id = 768 }
			name = "52. BAD"
			strength = 40
			type = tactical_bomber
                     	model = 2 #PE2
                       	}
			}

#
# Krasnyj Flot
####################################

	navalunit = {
	id = { type = 10848 id = 400 }
	name = "Arctic Fleet"
	location = 133
	base = 133
		division = {   id = { type = 13000 id = 401 }   name = "1. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 402 }   name = "2. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 403 }   name = "1. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 404 }   name = "2. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 405 }   name = "3. Flotiliya Podlodok"  type = submarine model = 1 }
	}
	
	navalunit = {
	id = { type = 10848 id = 406 }
	name = "Red Banner Baltic Fleet"
	location = 187
	base = 187
		division = {   id = { type = 13000 id = 407 }   name = "Gangut"  type = battleship model = 1 seaattack = 16 }
		division = {   id = { type = 13000 id = 408 }   name = "Marat"  type = battleship model = 1 seaattack = 16 }
		division = {   id = { type = 13000 id = 409 }   name = "Kirov"  type = heavy_cruiser model = 2 }
		division = {   id = { type = 13000 id = 410 }   name = "Maksim Gorki"  type = heavy_cruiser model = 2 }
		division = {   id = { type = 13000 id = 411 }   name = "3. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 412 }   name = "4. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 413 }   name = "5. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 414 }   name = "4. Flotiliya Podlodok"  type = submarine model = 2 }
		division = {   id = { type = 13000 id = 415 }   name = "5. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 416 }   name = "6. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 417 }   name = "7. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 418 }   name = "8. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 419 }   name = "9. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 420 }   name = "10. Flotiliya Podlodok"  type = submarine model = 1 }
		}

		navalunit = {
		id = { type = 10848 id = 421 }
		name = "Black Sea Fleet"
		location = 253
		base = 253
            
		division = {   id = { type = 13000 id = 422 } name = "Parishkaya Kommuna" type = battleship model = 1 }
		division = {   id = { type = 13000 id = 423 }   name = "Krasni Krim"  type = heavy_cruiser model = 1 }
		division = {   id = { type = 13000 id = 424 }   name = "Komintern"  type = heavy_cruiser model = 0 }
		division = {   id = { type = 13000 id = 425 }   name = "Molotov"  type = heavy_cruiser model = 2 }
		division = {   id = { type = 13000 id = 426 }   name = "Krasni Kavkaz"  type = heavy_cruiser model = 1 }
		division = {   id = { type = 13000 id = 427 }   name = "Voroshilov"  type = heavy_cruiser model = 2 }
		division = {   id = { type = 13000 id = 428 }   name = "6. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 429 }   name = "7. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 430 }   name = "11. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 431 }   name = "12. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 432 }   name = "13. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 433 }   name = "14. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 434 }   name = "15. Flotiliya Podlodok"  type = submarine model = 1 }
		}

transports = 60
escorts = 30

##################################################


}


