province = { id = 303 points = 2 } #Danzig
province = { id = 306 points = 1 }
province = { id = 307 points = 5 } #Poznan
province = { id = 482 points = 1 }
province = { id = 479 points = 5 } #Krakow
province = { id = 480 points = 1 }
province = { id = 481 points = 1 }
province = { id = 483 points = 5 } #Lodz
province = { id = 484 points = 1 }
province = { id = 305 points = 1 }
province = { id = 485 points = 10 } #Warszawa
province = { id = 486 points = 1 }
province = { id = 487 points = 1 }
province = { id = 488 points = 5 } #Lwow
province = { id = 489 points = 1 }
province = { id = 500 points = 1 }
province = { id = 501 points = 1 }
province = { id = 502 points = 1 }
province = { id = 503 points = 1 }
province = { id = 504 points = 8 } #Brest-Litovsk
province = { id = 505 points = 1 }
province = { id = 506 points = 1 }
province = { id = 507 points = 1 }
province = { id = 508 points = 1 }
province = { id = 509 points = 1 }
province = { id = 208 points = 5 } #Vilna
province = { id = 209 points = 1 }
province = { id = 210 points = 1 }
province = { id = 211 points = 1 }
province = { id = 213 points = 1 }
province = { id = 214 points = 1 }
province = { id = 222 points = 1 }
province = { id = 229 points = 1 }
province = { id = 562 points = 1 }