#	ARGENTINA VPs (20)
province = { id = 667 points = 10 } # Buenos Aires
province = { id = 852 points = 2 } # Mar del Plata
province = { id = 725 points = 4 } # Santa Fé
province = { id = 845 points = 4 } # Córdoba

#	BRAZIL VPs (20)
province = { id = 883 points = 8 } # Belo Horizonte
province = { id = 885 points = 2 } # Rio de Janeiro
province = { id = 881 points = 4 } # Recife
province = { id = 882 points = 1 } # Salvador
province = { id = 879 points = 1 } # Belém
province = { id = 884 points = 2 } # Vitória
province = { id = 886 points = 2 } # São Paulo

#	NEUTRAL (16)
#Uruguay
province = { id = 849 points = 1 } # Montevideo
#Paraguay
province = { id = 837 points = 1 } # Asunción
#Peru
province = { id = 830 points = 2 } # Lima
province = { id = 831 points = 2 } # Arequipa
#Chile
province = { id = 893 points = 4 } # Santiago
province = { id = 839 points = 2 } # Antofagasta
#Bolivia
province = { id = 832 points = 2 } # La Paz
#Ecuador
province = { id = 815 points = 2 } # Quito

