#
# Naval bases
###############################

# Sevastopol
province = {
	id = 253
	anti_air = 3
	air_base = {
		size = 10
		current_size = 3
		}

	naval_base = {
		size = 10
		current_size = 3
		}
	}


# Novorossiysk
province = {
	id = 255
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
		}
	naval_base = {
		size = 5
		current_size = 5
		}
	}

# Tuapse
province = {
	id = 1848
	air_base = {
		size = 5
		current_size = 5
		}
	naval_base = {
		size = 5
		current_size = 5
		}
	}

#
#
# Air bases
###############################

# Rostov
province = {
	id = 258
	air_base = {
		size = 10
		current_size = 10
		}
	}

# Voronez
province = {
	id = 283
	air_base = {
		size = 10
		current_size = 10
		}
	}


# Tula
province = {
	id = 278
	anti_air = 3
	air_base = {
		size = 10
		current_size = 10
		}
	}



# Orel
province = {
	id = 282
	air_base = {
		size = 5
		current_size = 5
		}
	}


province = {
	id = 281
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 279
	air_base = {
		size = 5
		current_size = 5
		}
	}

# Kuybyshev
province = {
	id = 1828
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 1835
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 268
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 163
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 1847
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 1850
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 1907
	air_base = {
		size = 5
		current_size = 5
		}
	}


province = {	id = 163	landfort = 4 coastalfort = 0 anti_air = 3 }#Stalingrad
province = {	id = 253	landfort = 6 coastalfort = 5 } #Sevastapol
province = {	id = 283	landfort = 1 coastalfort = 0 anti_air = 1 }#Voronez UR
province = {	id = 258	landfort = 1 coastalfort = 0 anti_air = 2 }#Rostov UR

province = {  id = 253  oilpool = 50 supplypool = 300 } # Sevastopol


country = {
    tag = SOV

	ai = "fallblau_SOV_I.ai"


	capital = 1828 # Kujbyshev


	headofstate = { type = 9 id = 4001 }
	headofgovernment = { type = 9 id = 4002 }
  	foreignminister = { type = 9 id = 4034 }
  	armamentminister = { type = 9 id = 4037 } # Ustinov
  	ministerofsecurity = { type = 9 id = 4041 }
  	ministerofintelligence = { type = 9 id = 4048 }
  	chiefofstaff = { type = 9 id = 4054 } # Vassilevsky
  	chiefofarmy = { type = 9 id = 4059 }
  	chiefofnavy = { type = 9 id = 4062 } 
  	chiefofair = { type = 9 id = 4068 } # Novikov

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 1
        political_left = 10
        freedom = 1
        free_market = 1
        professional_army = 3
        defense_lobby = 6
        interventionism = 4
    }

steal_leader = 9803
steal_leader = 9807
steal_leader = 9827
steal_leader = 9856
steal_leader = 9858
steal_leader = 9862
steal_leader = 9880
steal_leader = 9883
steal_leader = 9889
steal_leader = 9897
steal_leader = 9899
steal_leader = 9906
steal_leader = 9919
steal_leader = 9935
steal_leader = 9971
steal_leader = 9985
steal_leader = 9989
steal_leader = 9990
steal_leader = 9997
steal_leader = 9998
steal_leader = 10013
steal_leader = 10025
steal_leader = 10037
steal_leader = 10041
steal_leader = 10057
steal_leader = 10074
steal_leader = 10076
steal_leader = 10095
steal_leader = 10101
steal_leader = 10125
steal_leader = 10144
steal_leader = 10152
steal_leader = 10180
steal_leader = 10190
steal_leader = 10198
steal_leader = 10200
steal_leader = 10210
steal_leader = 10218
steal_leader = 10241
steal_leader = 10246
steal_leader = 10290
steal_leader = 10293
steal_leader = 10308
steal_leader = 10311
steal_leader = 10320
steal_leader = 10347
steal_leader = 10351
steal_leader = 10375
steal_leader = 10413
steal_leader = 10457
steal_leader = 10459
steal_leader = 10480
steal_leader = 9802
steal_leader = 9816
steal_leader = 9818
steal_leader = 9850
steal_leader = 9851
steal_leader = 9872
steal_leader = 9885
steal_leader = 9895
steal_leader = 9898
steal_leader = 9901
steal_leader = 9949
steal_leader = 9959
steal_leader = 9982
steal_leader = 10017
steal_leader = 10034
steal_leader = 10040
steal_leader = 10063
steal_leader = 10064
steal_leader = 10065
steal_leader = 10092
steal_leader = 10109
steal_leader = 10113
steal_leader = 10135
steal_leader = 10155
steal_leader = 10182
steal_leader = 10186
steal_leader = 10201
steal_leader = 10205
steal_leader = 10209
steal_leader = 10262
steal_leader = 10301
steal_leader = 10360
steal_leader = 10394
steal_leader = 10402
steal_leader = 10406
steal_leader = 10409
steal_leader = 10448
steal_leader = 9831
steal_leader = 9854
steal_leader = 9857
steal_leader = 9887
steal_leader = 9888
steal_leader = 9918
steal_leader = 9943
steal_leader = 9970
steal_leader = 9983
steal_leader = 10029
steal_leader = 10038
steal_leader = 10072
steal_leader = 10082
steal_leader = 10164
steal_leader = 10174
steal_leader = 10187
steal_leader = 10280
steal_leader = 10287
steal_leader = 10309
steal_leader = 10325
steal_leader = 10345
steal_leader = 10348
steal_leader = 10398
steal_leader = 10403
steal_leader = 10404
steal_leader = 10410
steal_leader = 10432
steal_leader = 10437
steal_leader = 10455
steal_leader = 10471
steal_leader = 10476
steal_leader = 9806
steal_leader = 9811
steal_leader = 9824
steal_leader = 9913
steal_leader = 9921
steal_leader = 9922
steal_leader = 9992
steal_leader = 10081
steal_leader = 10105
steal_leader = 10111
steal_leader = 10133
steal_leader = 10146
steal_leader = 10159
steal_leader = 10171
steal_leader = 10175
steal_leader = 10189
steal_leader = 10212
steal_leader = 10299
steal_leader = 10318
steal_leader = 10326
steal_leader = 10354
steal_leader = 10458
steal_leader = 10486
steal_leader = 9805
steal_leader = 9808
steal_leader = 9844
steal_leader = 9873
steal_leader = 9874
steal_leader = 9875
steal_leader = 9892
steal_leader = 9904
steal_leader = 9927
steal_leader = 9932
steal_leader = 9967
steal_leader = 9968
steal_leader = 9978
steal_leader = 10075
steal_leader = 10083
steal_leader = 10129
steal_leader = 10151
steal_leader = 10216
steal_leader = 10223
steal_leader = 10337
steal_leader = 10385
steal_leader = 10430
steal_leader = 10439
steal_leader = 10466
steal_leader = 10489
steal_leader = 10490
steal_leader = 9801
steal_leader = 9819
steal_leader = 9837
steal_leader = 9923
steal_leader = 9941
steal_leader = 9952
steal_leader = 9961
steal_leader = 9975
steal_leader = 9979
steal_leader = 9980
steal_leader = 10012
steal_leader = 10043
steal_leader = 10086
steal_leader = 10090
steal_leader = 10091
steal_leader = 10128
steal_leader = 10167
steal_leader = 10192
steal_leader = 10256
steal_leader = 10266
steal_leader = 10359
steal_leader = 10364
steal_leader = 10389
steal_leader = 10446
steal_leader = 10450
steal_leader = 10491
steal_leader = 10494
steal_leader = 9847
steal_leader = 9909
steal_leader = 9911
steal_leader = 9954
steal_leader = 9956
steal_leader = 9960
steal_leader = 9963
steal_leader = 10009
steal_leader = 10055
steal_leader = 10093
steal_leader = 10116
steal_leader = 10130
steal_leader = 10194
steal_leader = 10239
steal_leader = 10252
steal_leader = 10275
steal_leader = 10285
steal_leader = 10350
steal_leader = 10352
steal_leader = 10424
steal_leader = 10498
steal_leader = 9800
steal_leader = 9804
steal_leader = 9809
steal_leader = 9810
steal_leader = 9812
steal_leader = 9813
steal_leader = 9815
steal_leader = 9817
steal_leader = 9820
steal_leader = 9821
steal_leader = 9822
steal_leader = 9823
steal_leader = 9825
steal_leader = 9826
steal_leader = 9828
steal_leader = 9829
steal_leader = 9830
steal_leader = 9832
steal_leader = 9833
steal_leader = 9834
steal_leader = 9835
steal_leader = 9836
steal_leader = 9838
steal_leader = 9840
steal_leader = 9842
steal_leader = 9845
steal_leader = 9846
steal_leader = 9848
steal_leader = 9852
steal_leader = 9853
steal_leader = 9855
steal_leader = 9859
steal_leader = 9860
steal_leader = 9861
steal_leader = 9863
steal_leader = 9864
steal_leader = 9865
steal_leader = 9866
steal_leader = 9867
steal_leader = 9868
steal_leader = 9869
steal_leader = 9870
steal_leader = 9871
steal_leader = 9876
steal_leader = 9877
steal_leader = 9878
steal_leader = 9879
steal_leader = 9881
steal_leader = 9882
steal_leader = 9886
steal_leader = 9890
steal_leader = 9891
steal_leader = 9893
steal_leader = 9902
steal_leader = 9903
steal_leader = 9905
steal_leader = 9908
steal_leader = 9912
steal_leader = 9914
steal_leader = 9915
steal_leader = 9916
steal_leader = 9917
steal_leader = 9920
steal_leader = 9924
steal_leader = 9925
steal_leader = 9928
steal_leader = 9929
steal_leader = 9931
steal_leader = 9933
steal_leader = 9936
steal_leader = 9937
steal_leader = 9938
steal_leader = 9939
steal_leader = 9940
steal_leader = 9942
steal_leader = 9944
steal_leader = 9945
steal_leader = 9946
steal_leader = 9947
steal_leader = 9948
steal_leader = 9950
steal_leader = 9953
steal_leader = 9957
steal_leader = 9958
steal_leader = 9962
steal_leader = 9964
steal_leader = 9965
steal_leader = 9966
steal_leader = 9972
steal_leader = 9976
steal_leader = 9977
steal_leader = 9981
steal_leader = 9984
steal_leader = 9986
steal_leader = 9987
steal_leader = 9988
steal_leader = 9994
steal_leader = 9995
steal_leader = 9996
steal_leader = 9999
steal_leader = 10000
steal_leader = 10001
steal_leader = 10002
steal_leader = 10003
steal_leader = 10004
steal_leader = 10005
steal_leader = 10007
steal_leader = 10008
steal_leader = 10010
steal_leader = 10011
steal_leader = 10015
steal_leader = 10018
steal_leader = 10020
steal_leader = 10021
steal_leader = 10022
steal_leader = 10023
steal_leader = 10024
steal_leader = 10027
steal_leader = 10030
steal_leader = 10032
steal_leader = 10033
steal_leader = 10035
steal_leader = 10036
steal_leader = 10039
steal_leader = 10044
steal_leader = 10045
steal_leader = 10046
steal_leader = 10047
steal_leader = 10048
steal_leader = 10049
steal_leader = 10050
steal_leader = 10051
steal_leader = 10052
steal_leader = 10053
steal_leader = 10056
steal_leader = 10058
steal_leader = 10059
steal_leader = 10060
steal_leader = 10061
steal_leader = 10067
steal_leader = 10069
steal_leader = 10070
steal_leader = 10073
steal_leader = 10077
steal_leader = 10078
steal_leader = 10079
steal_leader = 10080
steal_leader = 10084
steal_leader = 10085
steal_leader = 10087
steal_leader = 10088
steal_leader = 10089
steal_leader = 10094
steal_leader = 10096
steal_leader = 10097
steal_leader = 10098
steal_leader = 10099
steal_leader = 10100
steal_leader = 10102
steal_leader = 10103
steal_leader = 10104
steal_leader = 10106
steal_leader = 10107
steal_leader = 10108
steal_leader = 10110
steal_leader = 10112
steal_leader = 10117
steal_leader = 10118
steal_leader = 10119
steal_leader = 10120
steal_leader = 10121
steal_leader = 10122
steal_leader = 10124
steal_leader = 10126
steal_leader = 10127
steal_leader = 10131
steal_leader = 10132
steal_leader = 10134
steal_leader = 10136
steal_leader = 10139
steal_leader = 10140
steal_leader = 10141
steal_leader = 10142
steal_leader = 10143
steal_leader = 10145
steal_leader = 10147
steal_leader = 10148
steal_leader = 10149
steal_leader = 10150
steal_leader = 10153
steal_leader = 10154
steal_leader = 10156
steal_leader = 10157
steal_leader = 10158
steal_leader = 10160
steal_leader = 10161
steal_leader = 10162
steal_leader = 10163
steal_leader = 10165
steal_leader = 10166
steal_leader = 10168
steal_leader = 10169
steal_leader = 10170
steal_leader = 10172
steal_leader = 10176
steal_leader = 10177
steal_leader = 10178
steal_leader = 10179
steal_leader = 10181
steal_leader = 10183
steal_leader = 10184
steal_leader = 10185
steal_leader = 10188
steal_leader = 10191
steal_leader = 10193
steal_leader = 10195
steal_leader = 10196
steal_leader = 10197
steal_leader = 10199
steal_leader = 10203
steal_leader = 10204
steal_leader = 10206
steal_leader = 10207
steal_leader = 10211
steal_leader = 10213
steal_leader = 10214
steal_leader = 10217
steal_leader = 10219
steal_leader = 10220
steal_leader = 10221
steal_leader = 10222
steal_leader = 10224
steal_leader = 10225
steal_leader = 10226
steal_leader = 10227
steal_leader = 10228
steal_leader = 10229
steal_leader = 10230
steal_leader = 10231
steal_leader = 10232
steal_leader = 10233
steal_leader = 10234
steal_leader = 10235
steal_leader = 10236
steal_leader = 10237
steal_leader = 10238
steal_leader = 10240
steal_leader = 10242
steal_leader = 10243
steal_leader = 10245
steal_leader = 10247
steal_leader = 10248
steal_leader = 10249
steal_leader = 10250
steal_leader = 10251
steal_leader = 10254
steal_leader = 10255
steal_leader = 10257
steal_leader = 10258
steal_leader = 10259
steal_leader = 10260
steal_leader = 10261
steal_leader = 10263
steal_leader = 10264
steal_leader = 10265
steal_leader = 10267
steal_leader = 10268
steal_leader = 10269
steal_leader = 10270
steal_leader = 10272
steal_leader = 10273
steal_leader = 10274
steal_leader = 10277
steal_leader = 10278
steal_leader = 10279
steal_leader = 10282
steal_leader = 10284
steal_leader = 10288
steal_leader = 10289
steal_leader = 10291
steal_leader = 10292
steal_leader = 10294
steal_leader = 10295
steal_leader = 10296
steal_leader = 10300
steal_leader = 10302
steal_leader = 10303
steal_leader = 10304
steal_leader = 10305
steal_leader = 10306
steal_leader = 10307
steal_leader = 10310
steal_leader = 10312
steal_leader = 10313
steal_leader = 10314
steal_leader = 10315
steal_leader = 10316
steal_leader = 10317
steal_leader = 10319
steal_leader = 10321
steal_leader = 10323
steal_leader = 10324
steal_leader = 10327
steal_leader = 10328
steal_leader = 10329
steal_leader = 10330
steal_leader = 10331
steal_leader = 10332
steal_leader = 10333
steal_leader = 10334
steal_leader = 10335
steal_leader = 10336
steal_leader = 10338
steal_leader = 10339
steal_leader = 10340
steal_leader = 10341
steal_leader = 10343
steal_leader = 10344
steal_leader = 10353
steal_leader = 10355
steal_leader = 10356
steal_leader = 10357
steal_leader = 10358
steal_leader = 10361
steal_leader = 10362
steal_leader = 10365
steal_leader = 10366
steal_leader = 10367
steal_leader = 10368
steal_leader = 10372
steal_leader = 10373
steal_leader = 10374
steal_leader = 10376
steal_leader = 10377
steal_leader = 10378
steal_leader = 10379
steal_leader = 10380
steal_leader = 10381
steal_leader = 10382
steal_leader = 10383
steal_leader = 10384
steal_leader = 10386
steal_leader = 10387
steal_leader = 10388
steal_leader = 10390
steal_leader = 10391
steal_leader = 10392
steal_leader = 10393
steal_leader = 10395
steal_leader = 10396
steal_leader = 10397
steal_leader = 10399
steal_leader = 10400
steal_leader = 10405
steal_leader = 10407
steal_leader = 10408
steal_leader = 10411
steal_leader = 10412
steal_leader = 10414
steal_leader = 10415
steal_leader = 10416
steal_leader = 10418
steal_leader = 10419
steal_leader = 10420
steal_leader = 10421
steal_leader = 10422
steal_leader = 10423
steal_leader = 10425
steal_leader = 10426
steal_leader = 10427
steal_leader = 10428
steal_leader = 10429
steal_leader = 10431
steal_leader = 10433
steal_leader = 10434
steal_leader = 10435
steal_leader = 10436
steal_leader = 10438
steal_leader = 10440
steal_leader = 10441
steal_leader = 10442
steal_leader = 10443
steal_leader = 10444
steal_leader = 10445
steal_leader = 10447
steal_leader = 10449
steal_leader = 10451
steal_leader = 10452
steal_leader = 10454
steal_leader = 10456
steal_leader = 10460
steal_leader = 10461
steal_leader = 10462
steal_leader = 10464
steal_leader = 10465
steal_leader = 10467
steal_leader = 10468
steal_leader = 10469
steal_leader = 10470
steal_leader = 10473
steal_leader = 10474
steal_leader = 10475
steal_leader = 10478
steal_leader = 10479
steal_leader = 10481
steal_leader = 10482
steal_leader = 10483
steal_leader = 10484
steal_leader = 10485
steal_leader = 10487
steal_leader = 10488
steal_leader = 10492
steal_leader = 10493
steal_leader = 10495
steal_leader = 10496
steal_leader = 10497
steal_leader = 10501
steal_leader = 10502
steal_leader = 10503
steal_leader = 10504
steal_leader = 10505
steal_leader = 10506
steal_leader = 10507
steal_leader = 10508
steal_leader = 10509
steal_leader = 10510
steal_leader = 10511
steal_leader = 10512
steal_leader = 10513

# Dead/POW leaders, other fronts
#steal_leader = 10173 # Pavlov - shot
#steal_leader = 9814 # Apanasienko - Far East
#steal_leader = 10014 # Kirponos - retired
#steal_leader = 10281 # Shaposhnikov - retired
#steal_leader = 10363 # Vlasov - POW
#steal_leader = 10499 # Smukshchevitch - shot
#steal_leader = 9934 # Gamarnik - bites the dust
#steal_leader = 10298 # Shtern - dead and gone


	extra_tc = 300 # Maybe later I'll balance it more...

	# Resource Reserves
	# NOTE - balance!!!	
	
	oil 		= 3000	
	supplies  	= 5000

	free = 		{
		oil 	=	150
		supplies =	300
		ic = 550
	}

	manpower = 1600
	dissent = 10


	ownedprovinces =      {
 
266
278
282
262
261
260
258
253
255
256
257
269
259
265
263
283
281
279
280
155
158
1778
1830
1831
1832
156
284
264
157
159
160
1777
169
168
1780
1781
1827
1570
1577
1578
1569
1838
1568
1828
1839
1829
1835
1836
1834
267
268
161
162
163
164
271
270
1842
1833
1837
1847
1846
1843
1844
1845
1848
1850
1849
1857
1907
1858
1856

#German occupied
231
232
233
240
237
236
234
251
235
250
252
254
246
245
239
241
273
272
225
276
277
243
247
244
242
248
249
		
		
	}
	controlledprovinces = {

266
278
282
262
261
260
258
253
255
256
257
269
259
265
263
283
281
279
280
155
158
1778
1830
1831
1832
156
284
264
157
159
160
1777
169
168
1780
1781
1827
1570
1577
1578
1569
1838
1568
1828
1839
1829
1835
1836
1834
267
268
161
162
163
164
271
270
1842
1833
1837
1847
1846
1843
1844
1845
1848
1850
1849
1857
1907
1858
1856




	}
	nationalprovinces =   {

266
278
282
262
261
260
258
253
255
256
257
269
259
265
263
283
281
279
280
155
158
1778
1830
1831
1832
156
284
264
157
159
160
1777
169
168
1780
1781
1827
1570
1577
1578
1569
1838
1568
1828
1839
1829
1835
1836
1834
267
268
161
162
163
164
271
270
1842
1833
1837
1847
1846
1843
1844
1845
1848
1850
1849
1857
1907
1858
1856

#German occupied territories

562
502
229
226
227
238
228
231
232
233
240
237
236
234
251
235
250
252
254
246
245
239
241
273
272
225
276
277
243
247
244
242
248
249

	} 

	techapps               = { 5550  1120  9010  9020  9030  9040  9090  9050  9060  9100  9110  9120  9140  4010  4020  4120  4130  4170  4250  4030 
                             4040  4140  4180  4220  4260  4280  2010  2020  2030  2040  2150  2290  2300  2310  2320  2450  2070  2330  2100  2400 
                             2460  2510  2050  2080  2170  2260  2340  2370  2380  2410  2470  2520  5010  5050  5080  5090  5100  5190  5020  5110 
                             5120  5200  5060  5070  5130  5140  5160  5180  5210  5470  5480  5490  1010  1020  1110  1190  1070  1200  1030  1210 
                             1220  1230  1310  6300  6310  6320  6330  6210  8010  8020  8030  8040  8050  8070  3010  3020  3030  3070  3080  3090 
                             3130  3140  3190  3200  3210  3250  3260  3270  3280  3400  3410  3420  3430  14000 14010
                           }

#################################
# USSR Fall Blau OOB 27nd July,1942
#
# Briansk Front
# South-Western Front
# Southern Front
# Sevastopol UR
# Reserves
# 
#####################################

# Briansk Front
####################################

	# 13th Army
	landunit = {
        id = { type = 13000 id = 1 } 
		location = 278
		#leader =  
		name = "13ya Armiya"

		division = {
	        id = { type = 13000 id = 2 } 
			name = "132. Strelkovaya Diviziya"
			type = infantry
			model = 2	
			strength = 70	
		}

		division = {
	        id = { type = 13000 id = 3 } 
			name = "148. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
		}

		division = {
	        id = { type = 13000 id = 4 } 
			name = "143. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 5 } 
			name = "15. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = artillery
			brigade_model = 4
		}

	}

	# 13th Army - mobile
	landunit = {
        id = { type = 13000 id = 6 } 
		location = 278
		name = "Front reserves"

		division = {
	        id = { type = 13000 id = 7 } 
			name = "109/129. Tankovaya Brigada"
			type = armor
			model = 3
			strength = 60	
		}

	}

	# 40th Army
	landunit = {
        id = { type = 13000 id = 8 } 
		location = 278
		name = "40ya Armiya"

		division = {
	        id = { type = 13000 id = 9 } 
			name = "121. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 10 } 
			name = "160. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 11 } 
			name = "212. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
		division = {
	        id = { type = 13000 id = 12 } 
			name = "45. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
		division = {
	        id = { type = 13000 id = 13 } 
			name = "62. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
		division = {
	        id = { type = 13000 id = 14 } 
			name = "60. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
		division = {
	        id = { type = 13000 id = 15 } 
			name = "284. Strelkovaya Diviziya"
			type = infantry
			model = 2			
			strength = 70	

		}

	}


	# 16th Tank Corps
	landunit = {
        id = { type = 13000 id = 16 } 
		location = 278
		leader = 10171 # Pavelkin
		name = "16yj Tankovyj Korps"

		division = {
	        id = { type = 13000 id = 17 } 
			name = "16yj Tankovyj Korps"
			type = armor
			model = 3
			strength = 70	
		}

	}

	# 40th Army Reserves
	landunit = {
        id = { type = 13000 id = 18 } 
		location = 278

		name = "Army Reserves"

		division = {
	        id = { type = 13000 id = 19 } 
			name = "111/119/284. Strelkovaya Brigada"
			type = motorized
			model = 0
			strength = 70	
		}

		division = {
	        id = { type = 13000 id = 20 } 
			name = "14/115/116. Tankovaya Brigada"
			type = armor
			model = 3
			strength = 60	
		}


	}

	# 75th Fortified Region
	landunit = {
        id = { type = 13000 id = 21 } 
		location = 283 # Voronez

		name = "75yj UR"

		division = {
	        id = { type = 13000 id = 22 } 
			name = "75yj Ukreplennyj Rayon"
			type = garrison
			model = 1
		}

	}


	# 21st Army
	landunit = {
        id = { type = 13000 id = 23 } 
		location = 282
		name = "21ya Armiya"

		division = {
	        id = { type = 13000 id = 24 } 
			name = "226. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = artillery
			brigade_model = 4 # Medium modern art.
		}

		division = {
	        id = { type = 13000 id = 25 } 
			name = "297. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 26 } 
			name = "227. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 27 } 
			name = "301. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 28 } 
			name = "293. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 29 } 
			name = "76. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 30 } 
			name = "124. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 31 } 
			name = "343. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 32 } 
			name = "8. Diviziya Opolcheniya"
			type = militia
			model = 0

		}

	}

	# 24th Tank Corps
	landunit = {
        id = { type = 13000 id = 33 } 
		location = 282
		leader = 9822 # Badanov
		name = "24yj Tankovyj Korps"

		division = {
	        id = { type = 13000 id = 34 } 
			name = "24yj Tankovyj Korps"
			type = armor
			model = 3
			strength = 70	

		}

	}


	# 4th Tank Corps
	landunit = {
        id = { type = 13000 id = 35 } 
		location = 282
		leader = 10126 # Mishulin
		name = "4yj Tankovyj Korps"

		division = {
	        id = { type = 13000 id = 36 } 
			name = "4yj Tankovyj Korps"
			type = armor
			model = 3
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 37 } 
			name = "10ya Tankovaya Brigada"
			type = armor
			model = 3
			strength = 30
			max_strength = 40
		}


	}


	# 53rd Fortified Region
	landunit = {
        id = { type = 13000 id = 38 } 
		location = 263

		name = "53ij UR"

		division = {
	        id = { type = 13000 id = 39 } 
			name = "53ij Ukreplennyj Rayon"
			type = garrison
			model = 1
		}

	}

	# 117th Fortified Region
	landunit = {
        id = { type = 13000 id = 40 } 
		location = 265

		name = "117oj UR"

		division = {
	        id = { type = 13000 id = 41 } 
			name = "117oj Ukreplennyj Rayon"
			type = garrison
			model = 1
		}

	}


# South-Western Front
##########################

	# 28th Army
	landunit = {
        id = { type = 13000 id = 42 } 
		location = 262 
		name = "28ya Armiya"

		division = {
	        id = { type = 13000 id = 43 } 
			name = "13. Gvardieyska Strelk. Div."
			type = infantry
			model = 3
			experience = 20
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 44 } 
			name = "15. Gvardieyska Strelk. Div."
			type = infantry
			model = 3
			experience = 20
		}

		division = {
	        id = { type = 13000 id = 45 } 
			name = "169. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 46 } 
			name = "175. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 47 } 
			name = "38. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}		

		division = {
	        id = { type = 13000 id = 48 } 
			name = "244. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
	
	}
	
	# Army Reserve
	landunit = {
        id = { type = 13000 id = 49 } 
		location = 262
		name = "Army Reserve"

		division = {
	        id = { type = 13000 id = 50 } 
			name = "90/65 Tankovaya Brigada"
			type = armor
			model = 3
			strength = 60	

		}


	}

# 38th Army
############################

	# 3rd Cavalry Corps (Guards)
	landunit = {
        id = { type = 13000 id = 51 } 
		location = 261
		name = "3ij Gvardieyskiy Kav. Korps"

		division = {
	        id = { type = 13000 id = 52 } 
			name = "5. Gvardieyskaya Kav. Div."
			type = cavalry
			model = 3
			experience = 20
		}

		division = {
	        id = { type = 13000 id = 53 } 
			name = "6. Gvardieyskaya Kav. Div."
			type = cavalry
			model = 3
			experience = 20

		}

		division = {
	        id = { type = 13000 id = 54 } 
			name = "32. Kav. Div."
			type = cavalry
			model = 2
			strength = 70	

		}

	}


	# 38th Army
	landunit = {
        id = { type = 13000 id = 55 } 
		location = 261
		name = "38ya Armiya"

		division = {
	        id = { type = 13000 id = 56 } 
			name = "300. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 57 } 
			name = "162. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 58 } 
			name = "277. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 59 } 
			name = "278. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
		division = {
	        id = { type = 13000 id = 60 } 
			name = "242. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
		division = {
	        id = { type = 13000 id = 61 } 
			name = "189. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

	}

	# Army Reserve
	landunit = {
        id = { type = 13000 id = 62 } 
		location = 261
		name = "Army Reserve"

		division = {
	        id = { type = 13000 id = 63 } 
			name = "9. Gvardieyska Strelk. Div."
			type = infantry
			model = 3
			experience = 20			
		}

		division = {
	        id = { type = 13000 id = 64 } 
			name = "3/133. Tankovaya Brigada"
			type = armor
			model = 3
			strength = 60
			max_strength = 80
		}
	}


	# 118th Fortified Region
	landunit = {
        id = { type = 13000 id = 65 } 
		location = 266

		name = "118yj UR"

		division = {
	        id = { type = 13000 id = 66 } 
			name = "118yj Ukreplennyj Rayon"
			type = garrison
			model = 1
		}

	}


	# 9th Army
	landunit = {
        id = { type = 13000 id = 67 } 
		location = 260
		name = "9ya Armiya"

		division = {
	        id = { type = 13000 id = 68 } 
			name = "255. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 69 } 
			name = "140. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = anti_tank
		}

		division = {
	        id = { type = 13000 id = 70 } 
			name = "51. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = anti_air
		}

		division = {
	        id = { type = 13000 id = 71 } 
			name = "296. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 72 } 
			name = "318. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}


		division = {
	        id = { type = 13000 id = 73 } 
			name = "333. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 74 } 
			name = "106. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 75 } 
			name = "81. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

	}


	# 5th Cav. Corps
	landunit = {
        id = { type = 13000 id = 76 } 
		location = 260
		name = "5yj Kav. Korps"

		division = {
	        id = { type = 13000 id = 77 } 
			name = "30. Kav. Diviziya"
			type = cavalry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 78 } 
			name = "60. Kav. Diviziya"
			type = cavalry
			model = 2
			strength = 70	


		}

		division = {
	        id = { type = 13000 id = 79 } 
			name = "34. Kav. Diviziya"
			type = cavalry
			model = 2
			strength = 70	

		}

	}

	# 14th Tank Korps
	landunit = {
        id = { type = 13000 id = 80 } 
		location = 260 
		leader = 9852 # Bogdanov
		name = "14yj Tankovyj Korps"

		division = {
	        id = { type = 13000 id = 81 } 
			name = "14yj Tankovyj Korps"
			type = armor
			model = 3
			strength = 20 # In the middle of reorganization

		}

	}


	# 37th Army
	landunit = {
        id = { type = 13000 id = 82 } 
		location = 260

		name = "37ya Armiya"

		division = {
	        id = { type = 13000 id = 83 } 
			name = "275. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = artillery
			brigade_model = 4 # Medium art
		}

		division = {
	        id = { type = 13000 id = 84 } 
			name = "295. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 85 } 
			name = "230. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 86 } 
			name = "102. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 87 } 
			name = "218. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 88 } 
			name = "349. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}
	}

	# 12th Army
	landunit = {
        id = { type = 13000 id = 89 } 
		location = 260

		name = "12ya Armiya"

		division = {
	        id = { type = 13000 id = 90 } 
			name = "261. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = artillery
			brigade_model = 4 # Medium art
		}

		division = {
	        id = { type = 13000 id = 91 } 
			name = "4. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 92 } 
			name = "74. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 93 } 
			name = "176. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 94 } 
			name = "73. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

	}


	# 12th Army Reserve
	landunit = {
        id = { type = 13000 id = 95 } 
		location = 260
		name = "Army Reserve"

		division = {
	        id = { type = 13000 id = 96 } 
			name = "75/140 Tankovaya Brigada"
			type = armor
			model = 3
			strength = 60 
			max_strength = 70 

		}

	}


# Southern Front
##################

	# 18th Army
	landunit = {
        id = { type = 13000 id = 97 } 
		location = 258
		name = "18ya Armiya"

		division = {
	        id = { type = 13000 id = 98 } 
			name = "353. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 99 } 
			name = "383. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = anti_tank
		}

		division = {
	        id = { type = 13000 id = 100 } 
			name = "395. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 101 } 
			name = "216. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 102 } 
			name = "347. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 103 } 
			name = "228. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}


	}


	# Army Reserve
	landunit = {
        id = { type = 13000 id = 104 } 
		location = 258
		name = "Army Reserve"

		division = {
	        id = { type = 13000 id = 105 } 
			name = "64. Tankovaya Brigada"
			type = armor
			model = 3
			strength = 20
			max_strength = 30

		}

	}


	# 56th Army
	landunit = {
        id = { type = 13000 id = 106 } 
		location = 258
		name = "56ya Armiya"

		division = {
	        id = { type = 13000 id = 107 } 
			name = "31. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	
			extra = artillery
			brigade_model = 4 # Medium modern art.

		}

		division = {
	        id = { type = 13000 id = 108 } 
			name = "339. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 109 } 
			name = "30. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 110 } 
			name = "16/68. Strelkovaya Brigada"
			type = infantry
			model = 2
			strength = 70
		}

		division = {
	        id = { type = 13000 id = 111 } 
			name = "81/76. Strelkovaya Brigada"
			type = infantry
			model = 2
			strength = 70
		}


		division = {
	        id = { type = 13000 id = 112 } 
			name = "2. Gvardeyska Strelk. Div."
			type = infantry
			model = 3
			experience = 20	
		}

	}


	# Army Reserve
	landunit = {
        id = { type = 13000 id = 113 } 
		location = 258
		name = "Army Reserve"

		division = {
	        id = { type = 13000 id = 114 } 
			name = "63. Tankovaya Brigada"
			type = armor
			model = 3
			strength = 70	

		}

	}


#
# Coastal Army (Sevastopol)
#######################################

	landunit = {
        id = { type = 13000 id = 115 } 
		location = 253 #Sevastopol
		name = "Primorskaya Armiya"
		dig_in = 20

		division = {
	        id = { type = 13000 id = 116 } 
			name = "109. Strelkovaya Diviziya"
			type = infantry
			model = 2
			experience = 20
		}

		division = {
	        id = { type = 13000 id = 117 } 
			name = "25. Strelkovaya Diviziya"
			type = infantry
			model = 2
			experience = 20
		}

		division = {
	        id = { type = 13000 id = 118 } 
			name = "95. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
			brigade_model = 4
			experience = 20
		}

		division = {
	        id = { type = 13000 id = 119 } 
			name = "Morskaya Piekhota"
			type = marine
			model = 0
			experience = 20
		}

		division = {
	        id = { type = 13000 id = 120 } 
			name = "172. Strelkovaya Diviziya"
			type = infantry
			model = 2
			experience = 20
		}


		division = {
	        id = { type = 13000 id = 121 } 
			name = "345. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

	}


#
# North Caucasus Front
#######################################

	# 47th Army
	landunit = {
        id = { type = 13000 id = 122 } 
		location = 255 #Novorossiysk
		name = "47ya Armiya"

		division = {
	        id = { type = 13000 id = 123 } 
			name = "16. Cav. Diviziya"
			type = cavalry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 124 } 
			name = "156. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 125 } 
			name = "236. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

		division = {
	        id = { type = 13000 id = 126 } 
			name = "318. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

	}

	# 51th Army
	landunit = {
        id = { type = 13000 id = 127 } 
		location = 256
		name = "51ya Armiya"

		division = {
	        id = { type = 13000 id = 128 } 
			name = "12. Cav. Diviziya"
			type = cavalry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 129 } 
			name = "13. Cav. Diviziya"
			type = cavalry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 130 } 
			name = "15. Cav. Diviziya"
			type = cavalry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 131 } 
			name = "15. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 132 } 
			name = "91. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 133 } 
			name = "138. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

		division = {
	        id = { type = 13000 id = 134 } 
			name = "157. Strelkovaya Diviziya"
			type = infantry
			model = 2
			strength = 70	

		}

	}



#
# HQ Units
#######################################

	landunit = {
        id = { type = 13000 id = 135 } 
		location = 278 #Tula
		leader = 10236 # Rokossovsky
		name = "Briansk Front HQ"

		division = {
	        id = { type = 13000 id = 136 } 
			name = "Briansk Front HQ"
			type = hq
		}
	}

	landunit = {
        id = { type = 13000 id = 137 } 
		location = 263 # Svoboda
		leader = 10333 #Timoshenko
		name = "South-Western Front HQ"

		division = {
	        id = { type = 13000 id = 138 } 
			name = "South-Western Front HQ"
			type = hq
		}
	}

	landunit = {
        id = { type = 13000 id = 139 } 
		location = 258 #Rostov
		#leader = 10102 #Malinovsky - NOTE, he is not general?
		name = "Southern Front HQ"

		division = {
	        id = { type = 13000 id = 140 } 
			name = "Southern Front HQ"
			type = hq
		}

	}

	landunit = {
        id = { type = 13000 id = 141 } 
		location = 256 #Rostov
		#leader = 9861 #Budionny
		name = "Northern Caucasus Front HQ"

		division = {
	        id = { type = 13000 id = 142 } 
			name = "Southern Front HQ"
			type = hq
		}

	}


#
# Reserves
##############

# 
# 1st Tank Army
#################### 

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 143 } 
			name = "13. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 144 } 
			name = "28. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 145 } 
			name = "131. Strelkovaya Diviziya"
			type = infantry
			model = 2

		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 146 } 
			name = "399. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

	

#
# 4th Tank Army
################

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 147 } 
			name = "22. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 148 } 
			name = "23. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 149 } 
			name = "18. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


# 
# 5th Tank Army
#####################

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 150 } 
			name = "2. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 151 } 
			name = "11. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 152 } 
			name = "7. Tankovyj Korps"
			type = armor
			model = 3

		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 153 } 
			name = "340. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


#
# Trans Kavk. Front
###################

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 154 } 
			name = "Trans Kavk. Front HQ"
			type = hq
		}

#
# 46th Army (Maykop)
###################

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 155 } 
			name = "394. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 156 } 
			name = "63. Kav. Diviziya"
			type = cavalry
			model = 2
		}


#
# 58th Army (Baku)
###################

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 157 } 
			name = "406. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 158 } 
			name = "407. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 159 } 
			name = "408. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 160 } 
			name = "409. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 161 } 
			name = "1. Kav. Diviziya"
			type = cavalry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 162 } 
			name = "23. Kav. Diviziya"
			type = cavalry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 163 } 
			name = "39. Kav. Diviziya"
			type = cavalry
			model = 2
		}


# 44th Army (Georgia)
##############

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 164 } 
			name = "20. Gornostrelkovaya Diviziya"
			type = bergsjaeger
			model = 0
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 165 } 
			name = "89. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 166 } 
			name = "223. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 167 } 
			name = "414. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 168 } 
			name = "416. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

# 45th Army (Astrakhan)
############

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 169 } 
			name = "140. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 170 } 
			name = "151. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 171 } 
			name = "328. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 172 } 
			name = "389. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 173 } 
			name = "392. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

# STAVKA Reserve (North)
#########################

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 174 } 
			name = "87. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 175 } 
			name = "187. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 176 } 
			name = "199. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 177 } 
			name = "49. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 178 } 
			name = "231. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 179 } 
			name = "296. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 180 } 
			name = "147. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}
landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 181 } 
			name = "181. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 182 } 
			name = "184. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 183 } 
			name = "192. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = light_armor_brigade
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 184 } 
			name = "196. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 185 } 
			name = "301. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 186 } 
			name = "308. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = light_armor_brigade
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 187 } 
			name = "126. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 188 } 
			name = "127. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 189 } 
			name = "153. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 190 } 
			name = "197. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 191 } 
			name = "203. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 192 } 
			name = "139. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 193 } 
			name = "145. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 194 } 
			name = "146. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = artillery
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 195 } 
			name = "258. Strelkovaya Diviziya"
			type = infantry
			model = 2
		}


landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 196 } 
			name = "306. Strelkovaya Diviziya"
			type = infantry
			model = 2
			extra = anti_tank
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 197 } 
			name = "33. Gvardeyska Strelk. Diviziya"
			type = infantry
			model = 3
			experience = 20
			extra = sp_rct_artillery
		}

landdivision = {
		
		dormant = yes

	        id = { type = 13000 id = 198 } 
			name = "14. Gvardeyska Strelk. Diviziya"
			type = infantry
			model = 3
			experience = 20
			extra = sp_rct_artillery
		}

#
# Air Reserve (North - Stavka)
#######################

airdivision = {
		
		dormant = yes

			id = { type = 13000 id = 743 }
			name = "44. IAD"
			type = multi_role
                        model = 0 #Mig3
			}

airdivision = {
		
		dormant = yes

			id = { type = 13000 id = 744 }
			name = "51. AD"
			type = interceptor
                        model = 2 #Hurricane
			strength = 70
			}

airdivision = {
		
		dormant = yes

			id = { type = 13000 id = 745 }
			name = "44. BAD"
			type = cas
                        model = 1 #Il2
			strength = 80
			}

airdivision = {
		
		dormant = yes

			id = { type = 13000 id = 746 }
			name = "47. BAD"
			type = cas
                        model = 1 #il2
			strength = 80
			}

airdivision = {
		
		dormant = yes

			id = { type = 13000 id = 747 }
			name = "52. DBAD"
			type = tactical_bomber
                        model = 3 #Pe2
			strength = 50
			}

airdivision = {
		
		dormant = yes

			id = { type = 13000 id = 748 }
			name = "53. AD"
			type = cas
                        model = 1 #il2
			strength = 70
			}

#
# VVS (Voyenno-Vozdushnyje Sily)
#
# Southern Direction
####################################



		airunit = {
		id = { type = 13000 id = 720 }
		name = "Aviatsiya Brianskovo Fronta"
		location = 278 # Tula
		base = 278
			
			division = {
			id = { type = 13000 id = 721 }
			name = "9. AD"
			strength = 80
			type = multi_role
                        model = 0 #Yak-1
			}

			division = {
			id = { type = 13000 id = 722 }
			name = "10. AD"
			strength = 80
			type = interceptor
                      	model = 1 # I 16
			}	

			division = {
			id = { type = 13000 id = 723 }
			name = "18. BAD"
			strength = 90
			type = cas
                       	model = 1 #Il-2
                        }

			division = {
			id = { type = 13000 id = 724 }
			name = "31. DBAD"
			strength = 80
			type = tactical_bomber
		        model = 3 #Pe2
                       	}
		}



		airunit = {
		id = { type = 13000 id = 725 }
		name = "Aviatsiya Yugo-Zapadnovo Fronta"
		location = 283 # Voronez
		base = 283
			
			division = {
			id = { type = 13000 id = 726 }
			name = "14. AD"
			strength = 45
			type = interceptor
                        model = 1 #I16
			}

			division = {
			id = { type = 13000 id = 727 }
			name = "15. AD"
			strength = 100
			type = interceptor
                      	model = 2 #Yak1
			}	

			division = {
			id = { type = 13000 id = 728 }
			name = "11. AD"
			strength = 70
			type = interceptor
                       	model = 2 #Lagg3
                        }

			division = {
			id = { type = 13000 id = 729 }
			name = "23. BAD"
			strength = 60
			type = tactical_bomber
		        model = 3 #Pe2
                       	}

			division = {
			id = { type = 13000 id = 730 }
			name = "33. DBAD"
			strength = 85
			type = tactical_bomber
                     	model = 3 #Pe2
                       	}

		}
		


		airunit = {
		id = { type = 13000 id = 731 }
		name = "Aviatsiya Yuzhnovo Fronta"
		location = 258 # Rostov
		base = 258
			
			division = {
			id = { type = 13000 id = 732 }
			name = "36. IAD"
			strength = 80
			type = multi_role
                        model = 0 #Mig3
			}

			division = {
			id = { type = 13000 id = 733 }
			name = "34. DBAD"
			strength = 80
			type = naval_bomber
                      	model = 1 #Il-4
			}	

			division = {
			id = { type = 13000 id = 734 }
			name = "35. DBAD"
			strength = 90
			type = naval_bomber
                       	model = 1 #Il-4
                        }

			division = {
			id = { type = 13000 id = 735 }
			name = "38. DBAD"
			strength = 80
			type = naval_bomber
		        model = 1 #Il-4
                       	}

		}



		airunit = {
		id = { type = 13000 id = 736 }
		name = "Aviatsiya Siev. Cav. Fronta"
		location = 255 # Novorossyjsk
		base = 255
			
			division = {
			id = { type = 13000 id = 737 }
			name = "39. IAD"
			strength = 100
			type = interceptor
                        model = 2 #Lagg3
			}

			division = {
			id = { type = 13000 id = 738 }
			name = "37. AD"
			strength = 70
			type = cas
                      	model = 1 #Il-2
			}	
		}


		airunit = {
		id = { type = 13000 id = 739 }
		name = "Aviatsiya Trans. Cav. Fronta"
		location = 1907 #Baku
		base = 1907
			
			division = {
			id = { type = 13000 id = 740 }
			name = "43. IAD"
			strength = 100
			type = interceptor
                        model = 2 #Lagg3
			}

			division = {
			id = { type = 13000 id = 741 }
			name = "40. DBAD"
			strength = 80
			type = tactical_bomber
                      	model = 3 #Pe-2
			}	

			division = {
			id = { type = 13000 id = 742 }
			name = "41. AD"
			strength = 100
			type = cas
                      	model = 0 #Su-2
			}	

		}


#
# Krasnyj Flot
####################################

		navalunit = {
		id = { type = 10848 id = 421 }
		name = "Black Sea Fleet"
		location = 255 # Novorossiysk
		base = 255
            
		division = {   id = { type = 13000 id = 422 } name = "Parishkaya Kommuna" type = battleship model = 1 }
		division = {   id = { type = 13000 id = 423 }   name = "Krasni Krim"  type = heavy_cruiser model = 1 }
		division = {   id = { type = 13000 id = 424 }   name = "Molotov"  type = heavy_cruiser model = 2 }
		division = {   id = { type = 13000 id = 425 }   name = "Krasni Kavkaz"  type = heavy_cruiser model = 1 }
		division = {   id = { type = 13000 id = 426 }   name = "Voroshilov"  type = heavy_cruiser model = 2 }
		division = {   id = { type = 13000 id = 427 }   name = "6. Flotiliya Esmintsev"  type = destroyer model = 1 }
		division = {   id = { type = 13000 id = 428 }   name = "11. Flotiliya Podlodok"  type = submarine model = 1 }
		division = {   id = { type = 13000 id = 429 }   name = "12. Flotiliya Podlodok"  type = submarine model = 1 }
		}



transports = 80
escorts = 30

##################################################


}


