# Commintern - 114 VP

# Main targets - 60 VP
province = { id = 1907 points = 30 } # Baku
province = { id = 163 points = 20 } # Stalingrad
province = { id = 253 points = 5 } # Sevastopol
province = { id = 283 points = 5 } #Voronez

# Secondary targets - 54 VP
province = { id = 1828 points = 20 } # Kujbyshev
province = { id = 258 points = 2 } # Rostov-Don
province = { id = 278 points = 10 } #Tula
province = { id = 255 points = 2 } #Novorossyjsk
province = { id = 1848 points = 2 } #Tuapse
province = { id = 282 points = 2 }
province = { id = 281 points = 2 }
province = { id = 279 points = 2 }
province = { id = 282 points = 2 }
province = { id = 1835 points = 2 }
province = { id = 1838 points = 2 }
province = { id = 268 points = 2 }
province = { id = 1847 points = 2 }
province = { id = 1850 points = 2 }


# Axis - 30 VP
province = { id = 233 points = 4 } # Odessa
province = { id = 248 points = 5 } # Kharkov
province = { id = 238 points = 10 } # Kiev
province = { id = 431 points = 3 } # Ploesti
province = { id = 424 points = 3 } # Bucaresti