
# list of spanish bases 

province = {
	id = 357 #tarragona
	anti_air = 2
	naval_base = {
		size = 6
		current_size = 6
	}
	air_base = {
		size = 6
		current_size = 6
	}
}

province = {
	id = 354 #valencia
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 334 # coruña
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 7
		current_size = 7
	}
}

province = {
	id = 535 #mallorca
	anti_air = 2
	naval_base = {
		size = 2
		current_size = 2
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 347 #sevilla
	anti_air = 2
	naval_base = {
		size = 4
		current_size = 4
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 972 #villa cisneros
	anti_air = 2
}

province = {
	id = 963 #gran canaria
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 341 #madrid
	anti_air = 3
	air_base = {
		size = 2
		current_size = 2
	}
}

province = { id = 332 #oviedo  
	     anti_air = 2 
	     air_base = { #a couple of small airfields were made during SCW, and later "scrapped"
		size = 1
		current_size = 1
		}
	} 
	
province = { id = 350 #almería
	     air_base = {
		size = 2
		current_size = 2
		}
	}	

province = { id = 356   #tarragona
	     anti_air = 2 
	      air_base = {
		size = 2
		current_size = 2
		}
		naval_base = {
		size = 4
		current_size = 4
		}
	     
	    } 
	    
	    
province = { id = 352 #murcia (cartagena)
	     anti_air = 2
	     naval_base = {
		size = 8
		current_size = 8
		}
	}

province = { id =	957 #ceuta
	     anti_air = 1	
	     naval_base = { size =	2	current_size = 	2	} 
	     air_base = { size =	2	current_size = 	2       }
	}


province = { id =	346	naval_base = { size =	4	current_size = 	4	}  #huelva
				air_base = { size =	4	current_size = 	4	} }

province = { id =	355	naval_base = { size =	3	current_size = 	3	} #castellón
				air_base = { size =	3	current_size = 	3	} } 
				
province = { id =	536	naval_base = { size =	2	current_size = 	2	} 
				air_base = { size =	2	current_size = 	2	} } #menorca

province = { id =	537	naval_base = { size =	3	current_size = 	3	} 
				air_base = { size =	1	current_size = 	1	} } #ibiza



