# USSR - initial VP = 200
province = { id = 233 points = 5 } # Odessa
province = { id = 238 points = 10 } # Kiev
province = { id = 212 points = 5 } # Minsk
province = { id = 197 points = 5 } # Riga
province = { id = 194 points = 5 } # Tallin
province = { id = 208 points = 5 } # Vilnius
province = { id = 253 points = 10 } # Sevastopol
province = { id = 219 points = 5 } # Smolensk
province = { id = 187 points = 30 } # Leningrad
province = { id = 133 points = 10 } # Murmansk
province = { id = 248 points = 5 } # Kharkov
province = { id = 1907 points = 20 } # Baku
province = { id = 258 points = 5 } # Rostov-Don
province = { id = 278 points = 5 } #Tula
province = { id = 175 points = 40 } # Moscow
province = { id = 154 points = 10 } # Archangielsk
province = { id = 163 points = 10 } # Stalingrad
province = { id = 1830 points = 15 } # Kujbyshev


# Axis - initial VP = 50 (to motivate them to attack!)
province = { id = 510 points = 2 } # Koeningsberg
province = { id = 473 points = 5 } # Breslau
province = { id = 300 points = 20 } # Berlin
province = { id = 485 points = 2 } # Warsaw
province = { id = 303 points = 2 } # Danzig
province = { id = 479 points = 2 } # Cracow
province = { id = 457 points = 5 } # Budapest
province = { id = 431 points = 5 } # Ploesti
province = { id = 424 points = 5 } # Bucaresti
province = { id = 477 points = 2 } # Bratislava