#################################
# Designed by Greven and Tracid #
#################################

province = {
	id = 16
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 17
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 19
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 20
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
	naval_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 21
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
	naval_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 22
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 23
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
}

province = { id = 13 radar_station = { size = 6 current_size = 6 } } #Sheffield
province = { id = 14 radar_station = { size = 2 current_size = 2 } } #Liverpool
province = { id = 15 radar_station = { size = 4 current_size = 4 } } #Cardiff
province = { id = 16 radar_station = { size = 2 current_size = 2 } } #Birmingham
province = { id = 17 radar_station = { size = 7 current_size = 7 } } #Norwich
province = { id = 19 radar_station = { size = 4 current_size = 4 } } #London
province = { id = 20 radar_station = { size = 8 current_size = 8 } } #Dover
province = { id = 21 radar_station = { size = 8 current_size = 8 } } #Portsmouth
province = { id = 22 radar_station = { size = 5 current_size = 5 } } #Bristol
province = { id = 23 radar_station = { size = 7 current_size = 7 } } #Plymouth

province = {
	id = 367	#Corsica
	supplypool = 1500
	oilpool = 1500
	anti_air = 6
	air_base = {
		size = 10
		current_size = 10
	}
	naval_base = {
		size = 10
		current_size = 10
	}
}

country = {
    tag = ALS

	ai = "dday_als.ai"

	# Resource Reserves	(No Production or Trade in this scenario)
	oil =	4000
	supplies =	6000
	extra_TC = 300

		free = 		{
		oil 	=	60
		supplies =	150
		ic = 160
	}


	diplomacy = {

			}

	manpower = 1000


	transports = 20

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 10
        political_left = 7
        freedom = 10
        free_market = 10
        professional_army = 1
        defense_lobby = 5
        interventionism = 1
    }

	headofstate = { type = 9 id = 6001 }
	headofgovernment = { type = 9 id = 6046 }
	foreignminister = { type = 9 id = 6060 }
	armamentminister = { type = 9 id = 6082 }
	ministerofsecurity = { type = 9 id = 6005 }
	ministerofintelligence = { type = 9 id = 6128 }
	chiefofstaff = { type = 9 id = 6136 }
	chiefofarmy = { type = 9 id = 6144 }
	chiefofnavy = { type = 9 id = 6163 }
	chiefofair = { type = 9 id = 6167 }


	steal_leader = 1224 #Montgomery
	steal_leader = 60427 # Kirk
	steal_leader = 60057 #Bradley
	steal_leader = 60104 #Collins
	steal_leader = 60172 #Gerow
	steal_leader = 1399 # Vian
	steal_leader = 1099 #Dempsey
	steal_leader = 1055 #Bucknall
	steal_leader = 1085 #Crocker
	steal_leader = 60371
	steal_leader = 1417
	steal_leader = 60128 #Devers
	steal_leader = 60291 #Patch
	steal_leader = 60352 #Truscott
	steal_leader = 24114 #de Lattre
	steal_leader = 60458
	steal_leader = 60566
	steal_leader = 1437
	steal_leader = 1422
	steal_leader = 1482
	steal_leader = 1479
	steal_leader = 60548
	steal_leader = 24218
	steal_leader = 60554
	steal_leader = 1492 # Steele
	steal_leader = 1426 # Cannon
	steal_leader = 52052
	steal_leader = 1237
	steal_leader = 1170
	steal_leader = 60109
	steal_leader = 60105
	steal_leader = 1131
	steal_leader = 60311
	steal_leader = 60438
 	steal_leader = 60220 #Huebner
 	steal_leader = 60170 #Gerhardt
 	steal_leader = 60142 #Eddy
 	steal_leader = 60027 # Barton
 	steal_leader = 60377 #Wyche
 	steal_leader = 60271 #Middleton
 	steal_leader = 60375 #Wood
 	steal_leader = 60184 #Grow
 	steal_leader = 60342 #Stroh
	steal_leader = 1262  #Rennie
 	steal_leader = 1115  #Erskine
	steal_leader = 52031 #Keller
 	steal_leader = 52032 #Kitching
	steal_leader = 60394 # Cooke (correct theater?)
	steal_leader = 1335 # Crutchley (correct theater?)
	steal_leader = 60571 # Young (correct theater?)
	steal_leader = 60568 # Whitehead (correct theater?)
	steal_leader = 1418 # Boyd (correct theater?)
	steal_leader = 1430 # Collishaw (correct theater?)
	steal_leader = 60351 # Roosevelt jr.
	steal_leader = 60027 # Barton
	steal_leader = 60170 # Gerhardt
	steal_leader = 60267 # McLain
	steal_leader = 60365 # Weaver
	steal_leader = 60325 # Sebree
	steal_leader = 60018 # Baade
	steal_leader = 52031 # Keller
	steal_leader = 52067 # Spry
	steal_leader = 1056 # Bullen-Smith
	steal_leader = 1262 # Rennie
	steal_leader = 1266 # Roberts
	steal_leader = 1155 # Harvey
	steal_leader = 60335 # Smith
	steal_leader = 1456 # Leigh-Malory
	steal_leader = 60548 # Quesada
	steal_leader = 1513 # Coningham
	steal_leader = 1447 # Harris
	steal_leader = 60557 # Spaatz
	steal_leader = 1384 #Ramsey
	steal_leader = 60469 # Spruance
	steal_leader = 1384 # Ramsey
	steal_leader = 60419 # Hewitt
	steal_leader = 60122 # Davidson
	steal_leader = 60460 # Rodgers
	steal_leader = 60505 # Doolittle
	steal_leader = 60506 # Eaker
	steal_leader = 60545 # Partridge
	steal_leader = 60558 # Timberlake
	steal_leader = 60554 # Sanders
	steal_leader = 1479 # Sholto-Douglas
	steal_leader = 1470 # Portal

	capital = 19 #London

    ownedprovinces =      {
		20 21 22 23 19 17 16 15 14 13 367
	 }
    controlledprovinces = {
		20 21 22 23 19 17 16 15 14 13 367
	  }
    nationalprovinces =   {
		20 21 22 23 19 17 16 15 14 13 367
	  }

	techapps               = { 4010  4020  4030  4040  4050  4060  4070  4080  4090  4100  4110  4120  4130  4140  4150  4160  7030  4170  4280  4180 
                             4190  4200  4210  4220  4230  4240  4250  4260  2150  2160  2010  2020  2030  2040  2050  2060  2030  2070  2080  2090 
                             2100  2110  2170  2180  2190  2220  2230  2240  2260  2270  2290  2300  2310  2320  2330  2340  2350  2360  2370  2380 
                             2400  2410  2420  2430  2450  2460  2470  2480  2490  2510  2520  2530  1010  1020  1030  1040  1050  1190  1200  1210 
                             1220  1110  1120  1130  1040  1070  1080  1090  1230  1240  1250  1260  1270  1280  1310  1320  1330  1340  1350  1360 
                             5010  5020  5030  5050  5060  5070  5080  5090  5100  5110  5120  5130  5140  5150  5160  5180  5190  5200  5210  5220 
                             5230  5310  5320  5330  5340  5350  5360  5370  5380  5390  5400  5410  5420  5430  5440  5450  5470  5480  5490  5500 
                             5510  5520  5530  7140  5550  5560  5570  9010  9020  9030  9040  9050  9060  9070  9080  9090  9100  9110  9120  9130 
                             9140  9150  9160  9170  9180  9190  9200  9210  9220  9230  9240  9250  9260  9270  9280  9290  9300  9310  9320  9330 
                             9340  9350  9360  9370  9380  9390  9400  9410  9420  9430  9440  9450  9460  6010  6020  6040  6050  6060  6070  6080 
                             6090  1150  1160  1170  1180  8010  8020  8030  8040  8050  8060  8090  8100  8110  8130  8160  8170  8180  8230  8240 
                             8310  8320  8140  8250  8270  8350  3010  3020  3030  3040  3050  3070  3080  3090  3100  3110  3130  3140  3150  3160 
                             3170  3190  3200  3210  3220  3250  3260  3270  3280  3320  3330  3340  3350  3360  3400  3410  3420  3430  3370  3230 
                             2200  2540  3290  7280  7150  7160  5540  14000 14010 14020 14030
                           }
############################
#  ALLIED OOB    	   	   #
############################

landunit = {
id = { type = 10178 id = 1 }
name = "21st Army Group"
leader = 1224 #Montgomery
location = 21

division = {
id = { type = 10178 id = 2 }
name = "21st Army Group HQ"
type = hq
model = 2
strength = 50
   max_strength = 50
extra = artillery
}
}
########################
#  1st WAVE  	   	   #
########################

navalunit = {
	id = { type = 10178 id = 3 }
	name = "Western Task Force"
	leader = 60427 # Kirk
	location = 2412
	base = 20

	mission = {
            type = shore_bombardment
            target = 39
            percentage = 0.200
            night = yes
            day = yes
            task = 1
            location = 2412
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
    }

	division = { id = { type = 10178 id = 4 } name = "USS Nevada" type = battleship  model = 3 }
	division = { id = { type = 10178 id = 5 } name = "USS Texas" type = battleship  model = 3 }
	division = { id = { type = 10178 id = 6 } name = "USS Arkansas" type = battleship  model = 3 }
	division = { id = { type = 10178 id = 7 } name = "USS Quincy" type = light_cruiser  model = 2 }
	division = { id = { type = 10178 id = 8 } name = "USS Tuscaloosa" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 9 } name = "FR Montcalm" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 10 } name = "FR George Leygues" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 11 } name = "UK Enterprise" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 12 } name = "UK Black Prince" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 13 } name = "UK Hawkins" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 14 } name = "UK Glasgow" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 15 } name = "1st US Destroyer Division" type = destroyer model = 2 }
	division = { id = { type = 10178 id = 16 } name = "2nd US Destroyer Division" type = destroyer model = 2 }
	division = { id = { type = 10178 id = 17 } name = "1st UK Destroyer Division" type = destroyer model = 2 }
}

navalunit = {
	id = { type = 10178 id = 271 }
	name = "Western Landing Force"
	leader = 60469 # Spruance
	location = 2412
	base = 20

	division = { id = { type = 10178 id = 18 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 19 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 20 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 21 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 22 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 23 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 24 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 25 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 26 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 27 } name = "US Transport Division" type = transport }

	landunit = {
		id = { type = 10178 id = 28 }
		name = "1st US Army"
		leader = 60057 #Bradley
		location = 0

		target = 39
		invasion = yes

		division = {
		id = { type = 10178 id = 29 }
		name = "1st US Army HQ"
		type = hq
		model = 2
		strength = 50
		   max_strength = 50
		extra = rocket_artillery
		}
	}

	landunit = {
		id = { type = 10178 id = 30 }
		name = "VII US Corps"
		leader = 60105 #Collins
		location = 0

		target = 39
		invasion = yes

		division = {
			id = { type = 10178 id = 32 }
			name = "4th US Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = artillery
		}

		division = {
			id = { type = 10178 id = 99 }
			name = "90th US Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = engineer
		}

		division = {
			id = { type = 10178 id = 101 }
			name = "9th US Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = light_armor_brigade
		}
	}

	landunit = {
		id = { type = 10178 id = 33 }
		name = "V US Corps"
		leader = 60172 #Gerow
		location = 0

		target = 39
		invasion = yes

		division = {
			id = { type = 10178 id = 35 }
			name = "1st US Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = engineer
		}

		division = {
			id = { type = 10178 id = 97 }
			name = "2nd US Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = artillery
		}

		division = {
			id = { type = 10178 id = 103 }
			name = "29th US Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = light_armor_brigade
		}
	}
} # navalunit
###

navalunit = {
	id = { type = 10178 id = 36 }
	name = "Eastern Task Force"
	leader = 1399 # Vian
	location = 2412
    base = 21

	mission = {
            type = shore_bombardment
            target = 39
            percentage = 0.200
            night = yes
            day = yes
            task = 1
            location = 2412
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
	}

	division = { id = { type = 10178 id = 37 } name = "RN Erebus" type = battleship  model = 3 }
	division = { id = { type = 10178 id = 38 } name = "RN Warspite" type = battleship  model = 3 }
	division = { id = { type = 10178 id = 39 } name = "RN Ramillies" type = battleship  model = 3 }
	division = { id = { type = 10178 id = 40 } name = "RN Argonaut" type = light_cruiser  model = 2 }
	division = { id = { type = 10178 id = 41 } name = "RN Orion" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 42 } name = "RN Emerald" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 43 } name = "RN Ajax" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 44 } name = "RN Diadem" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 45 } name = "RN Belfast" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 46 } name = "RN Arethusa" type = light_cruiser  model = 2 }
	division = { id = { type = 10178 id = 47 } name = "RN Roberts" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 48 } name = "RN Frobisher" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 49 } name = "RN Mauritius" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 50 } name = "RN Danae" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 51 } name = "RN Dragon" type = light_cruiser model = 2 }
	division = { id = { type = 10178 id = 52 } name = "2nd UK Destroyer Division" type = destroyer model = 2 }
	division = { id = { type = 10178 id = 53 } name = "3rd UK Destroyer Division" type = destroyer model = 2 }
	division = { id = { type = 10178 id = 54 } name = "4th UK Destroyer Division" type = destroyer model = 2 }
}


navalunit = {
	id = { type = 10178 id = 272 }
	name = "Eastern Landing Force"
	leader = 1335 # Crutchley
	location = 2412
    base = 21

	division = { id = { type = 10178 id = 55 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 56 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 57 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 58 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 59 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 60 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 61 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 62 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 63 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 64 } name = "UK Transport Division" type = transport }

	landunit = {
		id = { type = 10178 id = 65 }
		name = "2nd UK Army"
		leader = 1099 #Dempsey
		location = 0

		target = 39
		invasion = yes

		division = {
			id = { type = 10178 id = 66 }
			name = "2nd UK Army HQ"
			type = hq
			model = 2
			strength = 50
		   	max_strength = 50
			extra = rocket_artillery
		}
	}
	landunit = {
		id = { type = 10178 id = 67 }
		name = "XXX UK Corps"
		leader = 1055 #Bucknall
		location = 0

		target = 39
		invasion = yes

		division = {
			id = { type = 10178 id = 69 }
			name = "50th UK Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = engineer
		}

		division = {
			id = { type = 10178 id = 70 }
			name = "8th UK Tank Brigade"
			type = armor
			strength = 50
			max_strength = 50
			model = 3
		}

		division = {
			id = { type = 10178 id = 95 }
			name = "51st UK Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = artillery
		}

		division = {
			id = { type = 10178 id = 91 }
			name = "7th UK Tank Division"
			type = armor
			strength = 100
			model = 3
		}
	}
	landunit = {
		id = { type = 10178 id = 71 }
		name = "I UK Corps"
		leader = 1085 #Crocker
		location = 0

		target = 39
		invasion = yes

		division = {
			id = { type = 10178 id = 73 }
			name = "3rd Can Infantry Division"
			type = infantry
			strength = 100
			model = 4
		}

		division = {
			id = { type = 10178 id = 74 }
			name = "2nd Can Tank Brigade"
			type = armor
			strength = 50
			max_strength = 50
			model = 3
		}

		division = {
			id = { type = 10178 id = 75 }
			name = "3rd UK Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = engineer
		}

		division = {
			id = { type = 10178 id = 76 }
			name = "27th UK Tank Brigade"
			type = armor
			strength = 50
			max_strength = 50
			model = 3
		}

		division = {
			id = { type = 10178 id = 93 }
			name = "49th UK Infantry Division"
			type = infantry
			strength = 100
			model = 4
			extra = artillery
		}
	}
} # navalunit
########################
#  AIRBORNE WAVE  	   #
########################

airunit = {
location = 16
base = 16
id = { type = 10178 id = 77 }
name = "IX Troop Carrier Command"
#leader = 60371

mission = {
            type = airborne_assault
            target = 39
            percentage = 0.200
            night = yes
            day = yes
            task = 1
            location = 16
            startdate = { year = 1944 month = june day = 2  }
            enddate = { year = 1980  }

            }


division = {
id = { type = 10178 id = 78 }
name = "50th Troop Carrier Wing"
strength = 100
type = transport_plane
model = 1 #C-47
}

division = {
id = { type = 10178 id = 79 }
name = "52th Troop Carrier Wing"
strength = 100
type = transport_plane
model = 1 #C-47
}

division = {
id = { type = 10178 id = 80 }
name = "53th Troop Carrier Wing"
strength = 100
type = transport_plane
model = 2 #C-53
}

landunit = {
id = { type = 10178 id = 81 }
name = "82nd US Airborne Div"
location = 16
leader = 60348

division = {
id = { type = 10178 id = 82 }
name = "82nd US Airborne Div"
type = paratrooper
strength = 100
model = 3
}
}

landunit = {
id = { type = 10178 id = 83 }
name = "101st US Airborne Div"
location = 16
leader = 60311

division = {
id = { type = 10178 id = 84 }
name = "101st US Airborne Div"
type = paratrooper
strength = 100
model = 3
}
}

}
###
airunit = {
location = 19
base = 19
id = { type = 10178 id = 85 }
name = "RAF Transport Command"
leader = 1417

mission = {
            type = airborne_assault
            target = 39
            percentage = 0.200
            night = yes
            day = yes
            task = 1
            location = 19
            startdate = { year = 1944 month = june day = 2  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 86 }
name = "No 38 Transport Group"
strength = 100
type = transport_plane
model = 1 #Horsa
}

division = {
id = { type = 10178 id = 87 }
name = "No 46 Transport Group"
strength = 100
type = transport_plane
model = 2 #Dakota/Horsa
}

landunit = {
id = { type = 10178 id = 88 }
name = "6th UK Airborne Div"
location = 19
leader = 1131

division = {
id = { type = 10178 id = 89 }
name = "6th UK Airborne Div"
type = paratrooper
strength = 100
model = 4
}
}

}

########################
#  2nd WAVE  	   	   #
########################


landunit = {
id = { type = 10178 id = 106 }
name = "VIII. US Corps"
location = 20

target = 39

leader = 60352

division = {
id = { type = 10178 id = 107 }
name = "8th US Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 109 }
name = "35th US Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 115 }
name = "4th US Tank Division"
type = armor
strength = 100
model = 3
}

division = {
id = { type = 10178 id = 117 }
name = "2nd US Tank Division"
type = armor
strength = 100
model = 3
}

division = {
id = { type = 10178 id = 105 }
name = "79th US Infantry Division"
type = infantry
strength = 100
model = 4
}

}
###
landunit = {
id = { type = 10178 id = 110 }
name = "XIX. US Corps"
location = 20
leader = 60109

target = 39

division = {
id = { type = 10178 id = 111 }
name = "5th US Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 113 }
name = "30th US Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 119 }
name = "3rd US Tank Division"
type = armor
strength = 100
model = 3
}

division = {
id = { type = 10178 id = 121 }
name = "83rd US Tank Division"
type = armor
strength = 100
model = 3
}
}
###
landunit = {
id = { type = 10178 id = 122 }
name = "XII. UK Corps"
location = 21
leader = 1170

target = 39

division = {
id = { type = 10178 id = 123 }
name = "15th UK Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 125 }
name = "59th UK Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 127 }
name = "53rd UK Infantry Division"
type = infantry
strength = 100
model = 4
}
}
###
landunit = {
id = { type = 10178 id = 128 }
name = "VIII. UK Corps"
location = 21
leader = 1237

target = 39

division = {
id = { type = 10178 id = 129 }
name = "43rd UK Infantry Division"
type = infantry
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 131 }
name = "UK Guards Tank Division"
type = armor
strength = 100
model = 4
}

division = {
id = { type = 10178 id = 133 }
name = "11th UK Tank Division"
type = armor
strength = 100
model = 3
}
}

###
landunit = {
	id = { type = 10178 id = 134 }
	name = "II. Canadian Corps"
	location = 21
	leader =  52052
	target = 39

	division = {
		id = { type = 10178 id = 135 }
		name = "3rd UK Infantry Division"
		type = infantry
		strength = 100
		model = 4
	}

	division = {
		id = { type = 10178 id = 137 }
		name = "2nd Can Infantry Division"
		type = infantry
		strength = 100
		model = 4
	}
}

navalunit = {
	id = { type = 10178 id = 280 }
	name = "UK Landing Force"
	leader = 1384 # Ramsey
	location = 21
        base = 21

	division = { id = { type = 10178 id = 281 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 282 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 283 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 284 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 285 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 286 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 287 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 288 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 289 } name = "UK Transport Division" type = transport }
	division = { id = { type = 10178 id = 290 } name = "UK Transport Division" type = transport }
}
navalunit = {
	id = { type = 10178 id = 291 }
	name = "US Landing Force"
	leader = 60460 # Rodgers
	location = 20
        base = 20

	division = { id = { type = 10178 id = 292 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 293 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 294 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 295 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 296 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 297 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 298 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 299 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 300 } name = "US Transport Division" type = transport }
	division = { id = { type = 10178 id = 301 } name = "US Transport Division" type = transport }
}

########################
#  ALLIED AIRFORCE     #
########################

########US NINTH AIR FORCE########

#landunit = {
#id = { type = 10178 id = 153 }
#name = "US 9th Air Force"
#location = 22
#
#division = {
#	locked = yes
#id = { type = 10178 id = 154 }
#name = "US 9th Air Force Base"
#type = hq
#model = 2
#strength = 50
#max_strength = 50
#extra = anti_air
#}
#}

###IX Fighter Command###

#landunit = {
#id = { type = 10178 id = 155 }
#name = "IX Fighter Command"
#location = 21
#
#division = {
#	locked = yes
#id = { type = 10178 id = 156 }
#name = "IX Fighter Command Base"
#type = hq
#model = 2
#strength = 50
#max_strength = 50
#extra = anti_air
#}
#}

###
airunit = {
location = 21
base = 21
id = { type = 10178 id = 157 }
name = "IX Tactical Air Command"
leader = 60528 # Kepner

mission = {
            type = air_superiority
            target = 2412
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 21
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 159 }
name = "71st Fighter Wing"
strength = 100
type = multi_role
model = 1 #P-47 Thunderbolt
}

division = {
id = { type = 10178 id = 160 }
name = "84th Fighter Wing"
strength = 100
type = multi_role
model = 1 #P-47 Thunderbolt
}
}
###
airunit = {
location = 23
base = 23
id = { type = 10178 id = 161 }
name = "XIX Tactical Air Command"
leader = 60566

mission = {
            type = air_superiority
            target = 2412
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 23
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 162 }
name = "100th Fighter Wing"
strength = 100
type = multi_role
model = 2 #P-51 Mustang
}

division = {
id = { type = 10178 id = 163 }
name = "303rd Fighter Wing"
strength = 100
type = multi_role
model = 1 #P-47 Thunderbolt
}
}
###
airunit = {
location = 22
base = 22
id = { type = 10178 id = 164 }
name = "IX Bomber Command"
leader = 60554 #?

mission = {
            type = ground_attack
            target = 39
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 22
            startdate = { year = 1944 month = june day = 1  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 165 }
name = "97th Combat Bombardment Wing"
strength = 100
type = tactical_bomber
model = 4 #A-20 Havoc
}

division = {
id = { type = 10178 id = 166 }
name = "98th Combat Bombardment Wing"
strength = 100
type = tactical_bomber
model = 4 #B-26 Marauder
}

division = {
id = { type = 10178 id = 167 }
name = "99th Combat Bombardment Wing"
strength = 100
type = tactical_bomber
model = 4 #B-26 Marauder
}
division = {
id = { type = 10178 id = 158 }
name = "70th Fighter Wing/IX Tac AC"
strength = 100
type = multi_role
model = 1 #P-38 Lightning
}
}
###


###UK 2nd Tactical Air Force###

#landunit = {
#id = { type = 10178 id = 168 }
#name = "UK 2nd Tactical Air Force"
#location = 19
#
#division = {
#	locked = yes
#id = { type = 10178 id = 169 }
#name = "UK 2nd Tactical Air Force Base"
#type = hq
#model = 2
#strength = 50
#max_strength = 50
#extra = anti_air
#}
#}

###
airunit = {
location = 19
base = 19
id = { type = 10178 id = 170 }
name = "RAF Group No.2"
leader = 1437

mission = {
            type = interdiction
            target = 39
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 19
            startdate = { year = 1944 month = june day = 1  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 171 }
name = "137th Bomber Wing"
strength = 100
type = tactical_bomber
model = 4 #Boston IIIA
}

division = {
id = { type = 10178 id = 172 }
name = "138th Bomber Wing"
strength = 100
type = cas
model = 1 #Mosquito VI
}

division = {
id = { type = 10178 id = 173 }
name = "139th Bomber Wing"
strength = 100
type = tactical_bomber
model = 4 #Mitchell II
}

division = {
id = { type = 10178 id = 174 }
name = "140th Bomber Wing"
strength = 100
type = cas
model = 1 #Mosquito VI
}
}
###
airunit = {
location = 21
base = 21
id = { type = 10178 id = 175 }
name = "RAF Group No.83/AirSupG"
leader = 1422

mission = {
            type = air_superiority
            target = 39
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 21
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 176 }
name = "39th Recon Wing"
strength = 100
type = multi_role
model = 1 #Spitfire XI
}

division = {
id = { type = 10178 id = 178 }
name = "122nd Fighter Wing"
strength = 100
type = multi_role
model = 1 #Mustang III
}

division = {
id = { type = 10178 id = 180 }
name = "125th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 181 }
name = "126th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 182 }
name = "127th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 184 }
name = "143rd Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}
}
###
airunit = {
location = 21
base = 21
id = { type = 10178 id = 276 }
name = "RAF Group No.83/AirDefG"
leader = 60568 # Whitehead

division = {
id = { type = 10178 id = 177 }
name = "121st Fighter Wing"
strength = 100
type = interceptor
model = 3 #Typhoon IB
}

division = {
id = { type = 10178 id = 179 }
name = "124th Fighter Wing"
strength = 100
type = interceptor
model = 3 #Typhoon IB
}

division = {
id = { type = 10178 id = 183 }
name = "129th Fighter Wing"
strength = 100
type = interceptor
model = 3 #Typhoon IB
}
}
###
airunit = {
location = 20
base = 20
id = { type = 10178 id = 185 }
name = "RAF Group No.84/AirSupG"
leader = 1426 # Cannon

mission = {
            type = air_superiority
            target = 2412
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 20
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 186 }
name = "35th Recon Wing"
strength = 100
type = multi_role
model = 1 #Mustang IA
}

division = {
id = { type = 10178 id = 188 }
name = "131st Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 189 }
name = "132nd Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 190 }
name = "133rd Fighter Wing"
strength = 100
type = multi_role
model = 1 #Mustang III
}

division = {
id = { type = 10178 id = 191 }
name = "134th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 192 }
name = "135th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 194 }
name = "145th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}
}
###
airunit = {
location = 20
base = 20
id = { type = 10178 id = 275 }
name = "RAF Group No.84/AirDefG"
leader = 1418 # Boyd

mission = {
            type = air_superiority
            target = 2413
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 20
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 187 }
name = "123rd Fighter Wing"
strength = 100
type = interceptor
model = 3 #Typhoon IB
}

division = {
id = { type = 10178 id = 193 }
name = "136th Fighter Wing"
strength = 100
type = interceptor
model = 3 #Typhoon IB
}

division = {
id = { type = 10178 id = 195 }
name = "146th Fighter Wing"
strength = 100
type = interceptor
model = 3 #Typhoon IB
}
division = {
id = { type = 10178 id = 202 }
name = "150th Fighter Wing/Gr.No.85"
strength = 100
type = interceptor
model = 4 #Tempest V
}
}
###
airunit = {
location = 17
base = 17
id = { type = 10178 id = 196 }
name = "RAF Group No.85/AirSupG"
leader = 1492 # Steele

mission = {
            type = air_superiority
            target = 2412
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 17
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 197 }
name = "141st Fighter Wing"
strength = 100
type = multi_role
model = 2 #Spitfire XIV
}

division = {
id = { type = 10178 id = 198 }
name = "142nd Fighter Wing"
strength = 100
type = multi_role #?
model = 2 #Spitfire XIV
}

division = {
id = { type = 10178 id = 203 }
name = "34th Recon Wing"
strength = 100
type = multi_role
model = 1 #Spitfire XI
}
}
###
airunit = {
location = 17
base = 17
id = { type = 10178 id = 274 }
name = "RAF Group No.85/EscG"
leader = 1430 # Collishaw


division = {
id = { type = 10178 id = 199 }
name = "147th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Mosquito XIII
}

division = {
id = { type = 10178 id = 200 }
name = "148th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Mosquito XIII
}

division = {
id = { type = 10178 id = 201 }
name = "149th Fighter Wing"
strength = 100
type = multi_role
model = 1 #Mosquito XIII
}
}


###RAF Air Defense Command###
airunit = {
location = 19
base = 19
id = { type = 10178 id = 204 }
name = "RAF Air Defense Command"
leader = 1482

mission = {
            type = air_superiority
            target = 2412
            percentage = 0.020
            night = yes
            day = yes
            task = 1
            location = 19
            startdate = { year = 1944 month = june day = 0  }
            enddate = { year = 1980  }
            }

division = {
id = { type = 10178 id = 205 }
name = "No 10A Group"
strength = 100
type = multi_role
model = 2 #Spitfire IX
}

division = {
id = { type = 10178 id = 206 }
name = "No 10B Group"
strength = 100
type = multi_role
model = 2 #Beaufighter VIF
}

division = {
id = { type = 10178 id = 207 }
name = "No 11A Group"
strength = 100
type = multi_role
model = 1 #Spitfire IX
}

division = {
id = { type = 10178 id = 208 }
name = "No 11B Group"
strength = 100
type = multi_role
model = 1 #Typhoon IB
}

division = {
id = { type = 10178 id = 209 }
name = "No 12A Group"
strength = 100
type = multi_role
model = 2 #Spitfire VB
}

division = {
id = { type = 10178 id = 210 }
name = "No 12B Group"
strength = 100
type = multi_role
model = 2 #Spitfire VB
}

division = {
id = { type = 10178 id = 211 }
name = "Fighter Interception Unit"
strength = 50
max_strength = 50
type = interceptor
model = 4 #Tempest Mosquito/Mustang
}

division = {
id = { type = 10178 id = 212 }
name = "No 13A Group"
strength = 100
type = multi_role
model = 2 #Spitfire VB
}
}

###RAF Coastal Command###
airunit = {
location = 17
base = 17
id = { type = 10178 id = 213 }
name = "RAF Coastal Command"
leader = 1479

division = {
id = { type = 10178 id = 214 }
name = "No 15 Group"
strength = 100
type = naval_bomber
model = 2 #Swordfish/Liberator V
}

division = {
id = { type = 10178 id = 215 }
name = "No 16 Group"
strength = 100
type = naval_bomber
model = 2 #Beaufighter X
}

division = {
id = { type = 10178 id = 216 }
name = "No 18 Group"
strength = 100
type = naval_bomber
model = 2 #Catalina IV
}

division = {
id = { type = 10178 id = 217 }
name = "No 19A Group"
strength = 100
type = naval_bomber
model = 2 #Sunderland III
}

division = {
id = { type = 10178 id = 218 }
name = "No 19B Group"
strength = 100
type = naval_bomber
model = 2 #Sunderland III
}
}

########US TWELWTH AIR FORCE########


#landunit = {
#id = { type = 10178 id = 219 }
#name = "US 12th Air Force"
#location = 367
#
#division = {
#	locked = yes
#id = { type = 10178 id = 220 }
#name = "US 12th Air Force Base"
#type = hq
#model = 2
#strength = 50
#max_strength = 50
#extra = anti_air
#}
#}

###
airunit = {
id = { type = 10178 id = 221 }
name = "Air Superiority TF/12th US AF"
leader = 24218 #Gerardot
location = 367

division = {
id = { type = 10178 id = 222 }
name = "1. FFR Fighter Sqn/1. FFR AC"
strength = 100
type = multi_role
model = 3 #?
}

division = {
id = { type = 10178 id = 223 }
name = "2. FFR Fighter Sqn/1. FFR AC"
strength = 100
type = multi_role
model = 3 #?
}

}
###
airunit = {
id = { type = 10178 id = 225 }
name = "Bomber TF/12th US AF"
leader = 60548 #Barcus
location = 367

division = {
id = { type = 10178 id = 228 }
name = "27th Fighter-Bomber Group/XII Tac AC"
strength = 100
type = multi_role
model = 2 #?
}

division = {
id = { type = 10178 id = 229 }
name = "86th Fighter-Bomber Group/XII Tac AC"
strength = 100
type = multi_role
model = 2 #?
}

division = {
id = { type = 10178 id = 230 }
name = "323rd Bomber Wing/XII Tac AC"
strength = 100
type = tactical_bomber
model = 3 #?
}

division = {
id = { type = 10178 id = 231 }
name = "326th Bomber Wing/XII Tac AC"
strength = 100
type = tactical_bomber
model = 3 #?
}

division = {
id = { type = 10178 id = 224 }
name = "1. FFR Bomber Sqn/1. FFR AC"
strength = 100
type = tactical_bomber
model = 2 #?
}
}

###
airunit = {
id = { type = 10178 id = 273 }
name = "Air Defense TF/12th US AF"
leader = 60571 # Young
location = 367

division = {
id = { type = 10178 id = 226 }
name = "57th Fighter Group/XII Tac AC"
strength = 100
type = interceptor
model = 2 #?
}

division = {
id = { type = 10178 id = 227 }
name = "79th Fighter Group/XII Tac AC"
strength = 100
type = interceptor
model = 2 #?
}
}

############################
# Mediterranean Task Force #
############################


	navaldivision = { id = { type = 10178 id = 233 } dormant = yes name = "HMS Rodney" type = battleship  model = 3 }
	navaldivision = { id = { type = 10178 id = 234 } dormant = yes name = "USS Oklahoma" type = battleship  model = 3 }
	navaldivision = { id = { type = 10178 id = 235 } dormant = yes name = "USS Wyoming" type = battleship  model = 3 }
	navaldivision = { id = { type = 10178 id = 236 } dormant = yes name = "USS New York" type = battleship  model = 3 }
	navaldivision = { id = { type = 10178 id = 237 } dormant = yes name = "FR Richelieu" type = battleship  model = 3 }
	navaldivision = { id = { type = 10178 id = 238 } dormant = yes name = "HMS Albercrombie" type = light_cruiser  model = 2 }
	navaldivision = { id = { type = 10178 id = 239 } dormant = yes name = "HMS Boise" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 240 } dormant = yes name = "HMS Glennon" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 241 } dormant = yes name = "HMS Ulster" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 242 } dormant = yes name = "HMS Birmingham" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 243 } dormant = yes name = "HMS Uganda" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 244 } dormant = yes name = "HMS Spartan" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 245 } dormant = yes name = "FR Foch" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 246 } dormant = yes name = "FR Guepard" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 247 } dormant = yes name = "FR Fougueux" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 248 } dormant = yes name = "FR Simoun" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 249 } dormant = yes name = "FR La Flore" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 250 } dormant = yes name = "USS Brooklyn" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 251 } dormant = yes name = "USS Savannah" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 252 } dormant = yes name = "USS Philadelphia" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 253 } dormant = yes name = "USS Shubrick" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 254 } dormant = yes name = "USS Jeffers" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 255 } dormant = yes name = "USS Wichita" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 256 } dormant = yes name = "USS Augusta" type = light_cruiser model = 2 }
	navaldivision = { id = { type = 10178 id = 257 } dormant = yes name = "5th UK Destroyer Division" type = destroyer model = 2 }
	navaldivision = { id = { type = 10178 id = 258 } dormant = yes name = "1st FR Destroyer Division" type = destroyer model = 2 }
	navaldivision = { id = { type = 10178 id = 259 } dormant = yes name = "3rd US Destroyer Division" type = destroyer model = 2 }
	navaldivision = { id = { type = 10178 id = 260 } dormant = yes name = "4th US Destroyer Division" type = destroyer model = 2 }
	navaldivision = { id = { type = 10178 id = 261 } dormant = yes name = "US Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 262 } dormant = yes name = "US Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 263 } dormant = yes name = "US Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 264 } dormant = yes name = "US Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 265 } dormant = yes name = "UK Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 266 } dormant = yes name = "UK Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 267 } dormant = yes name = "UK Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 268 } dormant = yes name = "UK Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 269 } dormant = yes name = "FR Transport Division" type = transport }
	navaldivision = { id = { type = 10178 id = 270 } dormant = yes name = "FR Transport Division" type = transport }

}