#################################
# Designed by Greven and Tracid #
#################################
# Allied VP locations

province = { id = 24 points = 5 }  # Plymouth 
province = { id = 21 points = 5 }  # Portsmouth 
province = { id = 22 points = 3 }  # Bristol 
province = { id = 20 points = 10 } # Dover 
province = { id = 19 points = 50 } # London 


# German VP locations

province = { id = 31 points = 5 }  # Brest 
province = { id = 38 points = 5 }  # Cherbourg 
province = { id = 41 points = 5 }  # Le Havre 
province = { id = 18 points = 5 }  # Calais 
province = { id = 43 points = 5 }  # Dunquerque 
province = { id = 56 points = 25 } # Paris 
province = { id = 51 points = 15 } # Brussels 
province = { id = 66 points = 10 } # Aachen 
province = { id = 67 points = 25 } # Essen 
province = { id = 75 points = 15 } # Cologne 
province = { id = 76 points = 10 } # Dortmund 