  country = {
    tag = ETH

    policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 3
        political_left = 4
        free_market = 7
        freedom = 3
        professional_army = 5
        defense_lobby = 8
        interventionism = 2
    }

	headofstate = { type = 9 id = 65001 }
	headofgovernment = { type = 9 id = 65002 }
	foreignminister = { type = 9 id = 65003 }
	armamentminister = { type = 9 id = 65004 }
	ministerofsecurity = { type = 9 id = 65005 }
	ministerofintelligence = { type = 9 id = 65006 }
	chiefofstaff = { type = 9 id = 65007 }
	chiefofarmy = { type = 9 id = 65008 }
	chiefofnavy = { type = 9 id = 65009 } 
	chiefofair = { type = 9 id = 65010 }

	# Resource Reserves
	energy	=	1000   
	metal	= 1000		
	rare_materials =	500	
	oil =	500	
	supplies =	500
	money = 100

	capital = 1046
	manpower = 80


	ownedprovinces =      {
		1044 1048 1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054
	}
	controlledprovinces = {
		1044 1048 1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054
	}
	nationalprovinces =   {
		1044 1048 1049 1042 1043 1050 1045 1046 1047 1053 1052 1051 1054
	}

	# ROTW Minor Tech '36
	techapps = {
# Group E 1939 techs
#######################

4010 # GW fighter

2150 # Basic Armoured Car

2290 # GW light artillery

1010 # GW infantry

1190 # GW Cavalry


# Optional doctrines

6300 # Human Wave


	}
}