province = { id = 1670 points = 5 }
province = { id = 1671 points = 1 }
province = { id = 1672 points = 3 }
province = { id = 1679 points = 5 }
province = { id = 1669 points = 1 }
province = { id = 1613 points = 5 }
province = { id = 1683 points = 2 }
province = { id = 1682 points = 1 } 
province = { id = 1685 points = 5 }
province = { id = 1692 points = 5 }
province = { id = 1756 points = 5 }
province = { id = 1722 points = 10 }
province = { id = 1669 points = 1 }
province = { id = 1693 points = 1 }
province = { id = 1696 points = 1 }
province = { id = 1698 points = 1 } 

