# Warms the GDScript class_name cache by loading scripts in dependency order.
# Must be the FIRST autoload in project.godot.
extends Node

# === Layer 1: Core resources with NO class_name dependencies ===
const _Leader = preload("res://scripts/leaders/Leader.gd")
const _Agent = preload("res://scripts/agents/Agent.gd")
const _Province = preload("res://scripts/data/Province.gd")
const _Factory = preload("res://scripts/map/Factory.gd")
const _Country = preload("res://scripts/data/Country.gd")
const _EquipmentModule = preload("res://scripts/data/EquipmentModule.gd")
const _UnitTemplate = preload("res://scripts/data/UnitTemplate.gd")
const _SupplyRules = preload("res://scripts/supply/SupplyRules.gd")
const _ProductionModifier = preload("res://scripts/production/ProductionModifier.gd")
const _ProductionNavalRules = preload("res://scripts/production/ProductionNavalRules.gd")

# === Layer 2: Depend on Layer 1 class_names ===
const _LeaderGenerator = preload("res://scripts/leaders/LeaderGenerator.gd")
const _LeaderScreenData = preload("res://scripts/ui_data/LeaderScreenData.gd")
const _AgentGenerator = preload("res://scripts/agents/AgentGenerator.gd")
const _AgentMissionImpact = preload("res://scripts/agents/AgentMissionImpact.gd")
const _AgentNetwork = preload("res://scripts/agents/AgentNetwork.gd")
const _AgentScreenData = preload("res://scripts/ui_data/AgentScreenData.gd")
const _Formation = preload("res://scripts/formations/Formation.gd")
const _FormationSpawner = preload("res://scripts/formations/FormationSpawner.gd")
const _DivisionTemplate = preload("res://scripts/supply/DivisionTemplate.gd")
const _DivisionTemplateLoader = preload("res://scripts/supply/DivisionTemplateLoader.gd")
const _UnitSupplyRequirements = preload("res://scripts/supply/UnitSupplyRequirements.gd")
const _ProductionModifiers = preload("res://scripts/production/ProductionModifiers.gd")
const _AdjacencySystem = preload("res://scripts/data/AdjacencySystem.gd")
const _MapScenarioData = preload("res://scripts/data/MapScenarioData.gd")
const _ProvinceEffects = preload("res://scripts/map/ProvinceEffects.gd")
const _ProvinceFactoryComponent = preload("res://scripts/map/ProvinceFactoryComponent.gd")
const _ProvinceDepotState = preload("res://scripts/supply/ProvinceDepotState.gd")
const _ProvinceForceReport = preload("res://scripts/supply/ProvinceForceReport.gd")
const _ProvinceSupplyHub = preload("res://scripts/supply/ProvinceSupplyHub.gd")
const _SupplyCargoProfile = preload("res://scripts/supply/SupplyCargoProfile.gd")
const _SupplyRoutePlan = preload("res://scripts/supply/SupplyRoutePlan.gd")
const _CombatPresenceRegistry = preload("res://scripts/supply/CombatPresenceRegistry.gd")
const _CombatWidthCalculator = preload("res://scripts/combat/CombatWidthCalculator.gd")

# === Layer 3: Depend on Layer 2 ===
const _DesignLineState = preload("res://scripts/production/DesignLineState.gd")
const _RefinementProject = preload("res://scripts/production/RefinementProject.gd")
const _ReliabilityProfile = preload("res://scripts/production/ReliabilityProfile.gd")
const _ReliabilityCalculator = preload("res://scripts/production/ReliabilityCalculator.gd")
const _LogisticsCalculator = preload("res://scripts/production/LogisticsCalculator.gd")
const _ProductionCostCalculator = preload("res://scripts/production/ProductionCostCalculator.gd")
const _RetoolingCalculator = preload("res://scripts/production/RetoolingCalculator.gd")
const _RetoolingSimilarityTable = preload("res://scripts/production/RetoolingSimilarityTable.gd")
const _EquipmentShortageTracker = preload("res://scripts/production/EquipmentShortageTracker.gd")
const _DesignDataLoader = preload("res://scripts/core/DesignDataLoader.gd")
const _ProductionLine = preload("res://scripts/production/ProductionLine.gd")
const _AgentNetworkLayer = preload("res://scripts/map/AgentNetworkLayer.gd")
const _ProvinceHoverTooltip = preload("res://scripts/map/ProvinceHoverTooltip.gd")
const _ProvinceMapVisuals = preload("res://scripts/map/ProvinceMapVisuals.gd")
const _MapViewInput = preload("res://scripts/map/MapViewInput.gd")
const _MapPickGrid = preload("res://scripts/map/MapPickGrid.gd")
const _SupplyPathfinder = preload("res://scripts/supply/SupplyPathfinder.gd")
const _SupplyMultimodalRouter = preload("res://scripts/supply/SupplyMultimodalRouter.gd")
const _SupplyNetworkBuilder = preload("res://scripts/supply/SupplyNetworkBuilder.gd")
const _SupplyInterdictionEstimator = preload("res://scripts/supply/SupplyInterdictionEstimator.gd")
const _SupplyIntelBridge = preload("res://scripts/supply/SupplyIntelBridge.gd")
const _SupplyMapLayer = preload("res://scripts/supply/SupplyMapLayer.gd")
const _SupplyMenuPanel = preload("res://scripts/map/SupplyMenuPanel.gd")
const _SupplyOverlayPanel = preload("res://scripts/map/SupplyOverlayPanel.gd")
const _MapTechnologyContext = preload("res://scripts/map/MapTechnologyContext.gd")
const _TechnologyUnlockRegistry = preload("res://scripts/technology/TechnologyUnlockRegistry.gd")
const _AttritionReplenishmentLedger = preload("res://scripts/supply/AttritionReplenishmentLedger.gd")
const _NationalModifierDisplay = preload("res://scripts/national/NationalModifierDisplay.gd")

# === Layer 4: Depend on Layer 3 (heaviests) ===
const _ScenarioLoader = preload("res://scripts/core/ScenarioLoader.gd")
const _ScenarioCountryRuntime = preload("res://scripts/core/ScenarioCountryRuntime.gd")
const _ScenarioDataResolver = preload("res://scripts/core/ScenarioDataResolver.gd")
const _ScenarioProvinceApplier = preload("res://scripts/core/ScenarioProvinceApplier.gd")
const _ScenarioFactoryBootstrap = preload("res://scripts/core/ScenarioFactoryBootstrap.gd")
const _ScenarioFactorySpawner = preload("res://scripts/scenarios/ScenarioFactorySpawner.gd")
const _ProvinceInsight = preload("res://scripts/map/ProvinceInsight.gd")
const _CameraController = preload("res://scripts/map/CameraController.gd")
const _ConflictOverlayLayer = preload("res://scripts/map/ConflictOverlayLayer.gd")
const _MapRenderer = preload("res://scripts/map/MapRenderer.gd")
const _CombatResolver = preload("res://scripts/combat/CombatResolver.gd")

# === Layer 5: UI screens (depend on everything above) ===
const _TechnologyScreenData = preload("res://scripts/ui_data/TechnologyScreenData.gd")
const _ProductionScreenData = preload("res://scripts/ui_data/ProductionScreenData.gd")
const _NationalSpiritsScreenData = preload("res://scripts/ui_data/NationalSpiritsScreenData.gd")
const _DraggablePanel = preload("res://scripts/ui/DraggablePanel.gd")
const _RetrowaveTheme = preload("res://scripts/ui/RetrowaveTheme.gd")
const _GameDateDisplay = preload("res://scripts/ui/GameDateDisplay.gd")
const _LanguageSelector = preload("res://scripts/ui/LanguageSelector.gd")
const _SettingsPopup = preload("res://scripts/ui/SettingsPopup.gd")
const _StartMenu = preload("res://scripts/ui/StartMenu.gd")
const _NationSelectScreen = preload("res://scripts/ui/NationSelectScreen.gd")
const _LeaderPickerPopup = preload("res://scripts/ui/LeaderPickerPopup.gd")
const _LeaderDetailScreen = preload("res://scripts/ui/LeaderDetailScreen.gd")
const _LeaderReplacementPickerPopup = preload("res://scripts/ui/LeaderReplacementPickerPopup.gd")
const _LeaderAssignmentScreen = preload("res://scripts/ui/LeaderAssignmentScreen.gd")
const _RetirementOfferPopup = preload("res://scripts/ui/RetirementOfferPopup.gd")
const _RetoolingWarningPopup = preload("res://scripts/ui/RetoolingWarningPopup.gd")
const _TrainingPathScreen = preload("res://scripts/ui/TrainingPathScreen.gd")
const _BattleResultPopup = preload("res://scripts/ui/BattleResultPopup.gd")
const _EventPopup = preload("res://scripts/ui/EventPopup.gd")
const _TutorialPopup = preload("res://scripts/ui/TutorialPopup.gd")
const _DesignPickerPopup = preload("res://scripts/ui/DesignPickerPopup.gd")
const _FormationPickerPopup = preload("res://scripts/ui/FormationPickerPopup.gd")
const _MissionPickerPopup = preload("res://scripts/ui/MissionPickerPopup.gd")
const _TechnologyMissionTargetPopup = preload("res://scripts/ui/TechnologyMissionTargetPopup.gd")
const _TechnologyGraphView = preload("res://scripts/ui/TechnologyGraphView.gd")
const _TechnologyScreen = preload("res://scripts/ui/TechnologyScreen.gd")
const _AgentAssignmentScreen = preload("res://scripts/ui/AgentAssignmentScreen.gd")
const _ProductionAssignmentScreen = preload("res://scripts/ui/ProductionAssignmentScreen.gd")
const _NationalSpiritsScreen = preload("res://scripts/ui/NationalSpiritsScreen.gd")
const _MainMenu = preload("res://scripts/ui/MainMenu.gd")
const _TopInfoBar = preload("res://scripts/ui/TopInfoBar.gd")
const _VictoryScreen = preload("res://scripts/ui/VictoryScreen.gd")