###home bases
province = { id = 1457 points = 1 }
province = { id = 1187 points = 1 }
province = { id = 1722 points = 1 }
province = { id = 1756 points = 1 }


##w/o event
province = { id = 1315 points = 3 }
province = { id = 1624 points = 2 }


###phi
province = { id = 1737 points = 1 }
province = { id = 1738 points = 1 }
province = { id = 1739 points = 1 }
province = { id = 1740 points = 1 }
province = { id = 1749 points = 1 }
province = { id = 1750 points = 1 }

##borneo
province = { id = 1648 points = 1 }
province = { id = 1656 points = 1 }
province = { id = 1650 points = 1 }
province = { id = 1653 points = 1 }

##sumatra
province = { id = 1358 points = 1 }
province = { id = 1355 points = 1 }

####malaya
province = { id = 1348 points = 1 }
province = { id = 1351 points = 1 }
province = { id = 1352 points = 1 }
province = { id = 1353 points = 1 }


##java
province = { id = 1632 points = 1 }
province = { id = 1657 points = 1 }
province = { id = 1628 points = 1 }
province = { id = 1629 points = 1 }


#various
province = { id = 1296 points = 1 }
province = { id = 1299 points = 1 }
province = { id = 1337 points = 1 }
province = { id = 1672 points = 1 }
province = { id = 1670 points = 1 }
province = { id = 1679 points = 1 }
province = { id = 1689 points = 1 }
province = { id = 1692 points = 1 }
province = { id = 1646 points = 1 }
province = { id = 1659 points = 1 }
province = { id = 1665 points = 1 }