 province = {
	id = 1345
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

 country = {
    tag = SIA


	# Resource Reserves
	
energy		= 5000   
metal		= 5000	
rare_materials 		= 5000	
oil 		= 2000	
supplies 	= 2000
money 		= 1000

	capital = 1343 #Bangkok

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 2
        political_left = 3
        freedom = 3
        free_market = 3
        professional_army = 2
        defense_lobby = 5
        interventionism = 5
    }
		headofstate = { type = 9 id = 62112 }
		headofgovernment = { type = 9 id = 62035 }
  		foreignminister = { type = 9 id = 62043 }
  		armamentminister = { type = 9 id = 62059 }
  		ministerofsecurity = { type = 9 id = 62073 }
  		ministerofintelligence = { type = 9 id = 62085 }
  		chiefofstaff = { type = 9 id = 62091 }
  		chiefofarmy = { type = 9 id = 62097 }
  		chiefofnavy = { type = 9 id = 62102 } 
  		chiefofair = { type = 9 id = 62107 }

	manpower = 145


    ownedprovinces =      {
	1347 1345 1343 1342 1331 1330 1344 1348

	 }
    controlledprovinces = {
	1347 1345 1343 1342 1331 1330 1344 1348

	  }
    nationalprovinces =   {
	1348 1347 1345 1343 1342 1331 1330 1344 1348

	  }

	techapps = {
# Group D 1941 techs
#######################

4010 4020 4030 # Basic Fighter

4120 4130 # Early bomber

2010 2020 2030 2040 2050 # Improved light tank

2150 # Basic Armoured Car

2290 2300 2310 2320 # up to the WW II light artillery

1010 1020 1030 # Basic infantry

1190 1200 1210 # Basic Cavalry

1110 # Early Mountain

2330 # Basic motorized

2400 # Early AT artillery

2450 2460 2470 # Basic Static AA

2510 # Basic AA

9010 # Air superiority

5010 # Modern Agriculture

5050 # Basic Machine Tools

5080 5090 5100 # Construction (up to the forts)

5190 # Basic oil conversion

6010 6020 # Superior Firepower

3010
3070
3400

8050

# No Nuclear Research (Tier 5)
#hospital
14000

	}


}
