
##############################
# Country definition for JAP #
##############################

province = { id = 1174 oilpool = 100 supplypool = 500 } # Shumushushima
province = { id = 1176 oilpool = 100 supplypool = 500 } # Toyohara
province = { id = 1179 anti_air = 1 } # Sapporo
province = { id = 1180 ic = 3 } # Sendai
province =
{ id         = 1181
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
  anti_air   = 1
}              # Akita
province = { id = 1182 anti_air = 1 } # Fukushima
province = { id = 1183 anti_air = 1 } # Niigata
province =
{ id         = 1184
  ic         = 8
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 2
}              # Tokyo
province =
{ id         = 1185
  ic         = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 1
}              # Nagoya
province =
{ id         = 1186
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
}              # Kanazawa
province =
{ id         = 1187
  ic         = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 1
}              # Osaka
province =
{ id         = 1188
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
}              # Hiroshima
province =
{ id         = 1189
  ic         = 4
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  anti_air   = 1
}              # Shikoku
province =
{ id         = 1190
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 1
}              # Fukuoka
province = { id = 1192 oilpool = 100 supplypool = 500 } # Amami
province =
{ id         = 1193
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
  anti_air   = 1
  oilpool    = 100
  supplypool = 500
}              # Okinawa
province =
{ id         = 1196
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
  anti_air   = 1
}              # Busan
province =
{ id                  = 1202
  province_revoltrisk = 10
  air_base            = { size = 4 current_size = 4 }
  naval_base          = { size = 6 current_size = 6 }
  anti_air            = 1
}                       # Dalian
province = { id = 1203 province_revoltrisk = 10 } # Tangshan
province = { id = 1219 province_revoltrisk = 10 } # Nantong
province =
{ id                  = 1322
  province_revoltrisk = 10
  air_base            = { size = 4 current_size = 4 }
  naval_base          = { size = 6 current_size = 6 }
  anti_air            = 1
  oilpool             = 100
  supplypool          = 500
}                       # Kaohsiung
province = { id = 1323 province_revoltrisk = 10 oilpool = 100 supplypool = 500 } # Taipei
province = { id = 1324 province_revoltrisk = 10 oilpool = 100 supplypool = 500 } # Hualien
province =
{ id       = 1391
  air_base = { size = 4 current_size = 4 }
  anti_air = 1
}            # Hyesan
province = { id = 1600 oilpool = 100 supplypool = 500 } # Bikini
province =
{ id         = 1601
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  anti_air   = 1
  oilpool    = 100
  supplypool = 500
}              # Eniwetok
province = { id = 1602 oilpool = 100 supplypool = 500 } # Wotje
province = { id = 1603 oilpool = 100 supplypool = 500 } # Maloelap
province = { id = 1604 oilpool = 100 supplypool = 500 } # Wolelai
province = { id = 1605 anti_air = 1 oilpool = 100 supplypool = 500 } # Majuro
province = { id = 1606 oilpool = 100 supplypool = 500 } # Mili
province = { id = 1607 oilpool = 100 supplypool = 500 } # Jaluit
province =
{ id         = 1608
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  anti_air   = 1
  oilpool    = 100
  supplypool = 500
}              # Kwajalein
province = { id = 1609 oilpool = 100 supplypool = 500 } # Kosrae
province = { id = 1610 oilpool = 100 supplypool = 500 } # Ponape
province = { id = 1612 oilpool = 100 supplypool = 500 } # Satawan
province =
{ id         = 1613
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
  anti_air   = 2
  oilpool    = 100
  supplypool = 500
}              # Truk
province = { id = 1615 oilpool = 100 supplypool = 500 } # Ulul
province = { id = 1616 oilpool = 100 supplypool = 500 } # Pulusuk
province = { id = 1617 oilpool = 100 supplypool = 500 } # Woleai
province = { id = 1618 oilpool = 100 supplypool = 500 } # Ulithi
province = { id = 1619 anti_air = 1 oilpool = 100 supplypool = 500 } # Yap
province = { id = 1620 oilpool = 100 supplypool = 500 } # Ngulu
province = { id = 1621 oilpool = 100 supplypool = 500 } # Palau
province = { id = 1625 oilpool = 100 supplypool = 500 } # Rota
province = { id = 1626 oilpool = 100 supplypool = 500 } # Tinian
province = { id = 1627 anti_air = 1 oilpool = 100 supplypool = 500 } # Saipan
province = { id = 1784 anti_air = 1 } # Bonin Islands
province = { id = 1785 oilpool = 100 supplypool = 500 } # Marcus Island

#####################
# Country main data #
#####################

country =
{ tag                    = JAP
  capital                = 1184
  belligerence           = 15
  manpower               = 735
  energy                 = 2000
  metal                  = 2000
  rare_materials         = 1000
  oil                    = 1500
  supplies               = 500
  money                  = 100
  transports             = 400 # had 6 million tons = one third of UK
  escorts                = 11
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 2
    freedom           = 2
    free_market       = 3
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 2 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  SpyInfo                = { country = "USA" NumberOfSpies = 3 }
  SpyInfo                = { country = "SIK" NumberOfSpies = 1 }
  SpyInfo                = { country = "TAN" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 2 }
  SpyInfo                = { country = "CXB" NumberOfSpies = 2 }
  SpyInfo                = { country = "CYN" NumberOfSpies = 2 }
  SpyInfo                = { country = "LUX" NumberOfSpies = 1 }
  SpyInfo                = { country = "POR" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 2 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 4 }
  SpyInfo                = { country = "CGX" NumberOfSpies = 1 }
  SpyInfo                = { country = "PHI" NumberOfSpies = 2 }
  SpyInfo                = { country = "NZL" NumberOfSpies = 1 }
  SpyInfo                = { country = "AST" NumberOfSpies = 2 }
  # Part of Guangdong
  nationalprovinces      = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1174 1176 1175 1194
                             1195 1196 1197 1198 1199 1393 1391 1376 1392 1200 1201 1624
                           }
  ownedprovinces         = { 1203 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1219 1627 1626
                             1625 1619 1621 1604 1620 1618 1617 1616 1615 1613 1612 1610 1609 1600 1601 1602 1603 1605 1606 1607 1608 1323 1322 1324
                             1376 1391 1392 1200 1201 1199 1198 1197 1196 1195 1194 1393 1202 1176 1174
                           }
  controlledprovinces    = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1219 1627 1626 1625
                             1619 1621 1604 1620 1618 1617 1616 1615 1613 1612 1610 1609 1600 1601 1602 1603 1605 1606 1607 1608 1323 1322 1324 1376
                             1391 1392 1200 1201 1199 1198 1197 1196 1195 1194 1393 1202 1176 1174 1203 1204 1205 1210 1211 1212 1225 1226 1213 1214
                             1215 1216 1217 1220 1235 1236 1237 1221 1218 1223 1234 1233 1224 1238 1239 1252 1247 1248
                           }
  # Great War Infantry
  techapps               = { 1010  1020  1110  1150  1160  1190  1200  1210  1310  1340  2010  2020  2030  2040  2150  2290  2300  2310  2320  2330 
                             2450  2460  2510  3010  3020  3030  3070  3080  3090  3100  3130  3140  3150  3190  3200  3210  3250  3260  3270  3280 
                             3310  3320  3330  3340  3350  3400  3410  3420  3430  4010  4020  4050  4120  4130  4190  4250  5010  5050  5080  5090 
                             5190  5200  5310  5320  5350  5470  6010  6030  6110  6120  6160  8010  8020  8030  8040  8060  8090  8100  8110  8180 
                             9010  9020  9030  9040  9050  9060  9090  9100  9110  9190  9200  14000 12100
                           }
  diplomacy =
  { relation = { tag = AST value = -25 }
    relation = { tag = BEL value = -25 }
    relation = { tag = CGX value = -200 }
    relation = { tag = CHC value = -200 }
    relation = { tag = CHI value = -200 }
    relation = { tag = CHL value = 20 }
    relation = { tag = CSX value = -200 }
    relation = { tag = CXB value = -200 }
    relation = { tag = CYN value = -100 }
    relation = { tag = ENG value = -50 }
    relation = { tag = ETH value = 35 }
    relation = { tag = FIN value = 20 }
    relation = { tag = FRA value = -40 }
    relation = { tag = GER value = 75 }
    relation = { tag = HOL value = -50 }
    relation = { tag = MAN value = 200 access = yes }
    relation = { tag = MEN value = 200 access = yes }
    relation = { tag = SIA value = 75 }
    relation = { tag = USA value = 15 }
  }
  headofstate            = { type = 9 id = 5001 }
  headofgovernment       = { type = 9 id = 5035 }
  foreignminister        = { type = 9 id = 5056 }
  armamentminister       = { type = 9 id = 5082 }
  ministerofsecurity     = { type = 9 id = 5108 }
  ministerofintelligence = { type = 9 id = 5137 }
  chiefofstaff           = { type = 9 id = 5007 }
  chiefofarmy            = { type = 9 id = 5008 }
  chiefofnavy            = { type = 9 id = 5200 }
  chiefofair             = { type = 9 id = 5185 }
  dormant_ministers      = { 5002 5040 5033 5034 5041 5003 5057 5063 5053 5055 5004 5005 5105 5106 5107 5115 5006 5134 5189 }
  landunit =
  { id       = { type = 30036 id = 4500 }
    name     = "China Exp Army"
    location = 1224
    division =
    { experience = 20
      id         = { type = 30036 id = 2501 }
      name       = "China Exp Army HQ"
      type       = hq
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 2503 }
      name       = "3. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
  }
  landunit =
  { id       = { type = 30036 id = 1511 }
    name     = "23. Hendan"
    location = 1226
    division =
    { experience = 20
      id         = { type = 30036 id = 505 }
      name       = "13. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 506 }
      name       = "34. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
  }
  landunit =
  { id       = { type = 30036 id = 1521 }
    name     = "39. Hoheishidan"
    location = 1225
    division =
    { experience = 20
      id         = { type = 30036 id = 507 }
      name       = "39. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1529 }
    name     = "13. Hendan"
    location = 1239 # Shanghai, China 
    division =
    { experience = 20
      id         = { type = 30036 id = 512 }
      name       = "15. Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 513 }
      name       = "17. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1513 }
    name     = "7. Hendan"
    location = 1238
    division =
    { experience = 20
      id         = { type = 30036 id = 514 }
      name       = "22. Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 519 }
      name       = "17. Independent Mixed Brigade"
      strength   = 50
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1514 }
    name     = "6. Hendan"
    location = 1234 # Shanghai
    division =
    { experience = 20
      id         = { type = 30036 id = 520 }
      name       = "20. Independent Mixed Brigade"
      strength   = 50
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 521 }
      name       = "2. Independent Mixed Brigade"
      strength   = 50
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1562 }
    name     = "23. Hendan"
    location = 1252 # Jiujiang
    division =
    { experience = 20
      id         = { type = 30036 id = 523 }
      name       = "38. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 524 }
      name       = "51. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
  }
  landunit =
  { id       = { type = 30036 id = 1572 }
    name     = "23. Hendan"
    location = 1233 # Anqing
    division =
    { experience = 20
      id         = { type = 30036 id = 525 }
      name       = "104. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 526 }
      name       = "19. Independent Mixed Brigade"
      type       = infantry
      model      = 1
      extra      = armored_car
    }
  }
  landunit =
  { id       = { type = 30036 id = 1577 }
    name     = "2. Hendan"
    location = 1208 # Hohhot
    division =
    { experience = 20
      id         = { type = 30036 id = 529 }
      name       = "27. Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 530 }
      name       = "35. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1536 }
    name     = "1. Hendan"
    location = 1235 # Nanjing
    division =
    { experience = 20
      id         = { type = 30036 id = 537 }
      name       = "36. Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 538 }
      name       = "37. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 540 }
      name       = "3. Independent Mixed Brigade"
      strength   = 50
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 543 }
      name       = "16. Independent Mixed Brigade"
      strength   = 50
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1544 }
    name     = "12. Hendan"
    location = 1221 # Hefei
    division =
    { experience = 20
      id         = { type = 30036 id = 545 }
      name       = "32. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1549 }
    name     = "Mongol Army"
    location = 1209 # Datong
    division =
    { experience = 20
      id         = { type = 30036 id = 550 }
      name       = "26. Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { id       = { type = 30036 id = 551 }
      name     = "2. Independent Mixed Brigade"
      strength = 50
      type     = infantry
      model    = 1
    }
    division =
    { id    = { type = 30036 id = 552 }
      name  = "1 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 553 }
      name  = "2 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 554 }
      name  = "3 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 555 }
      name  = "4 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
    division =
    { id    = { type = 30036 id = 556 }
      name  = "5 Moukogo Kiheishidan"
      type  = cavalry
      model = 0
    }
  }
  landunit =
  { id       = { type = 30036 id = 1561 }
    name     = "10. Hoheishidan"
    location = 1223
    division =
    { id    = { type = 30036 id = 563 }
      name  = "10. Hoheishidan"
      type  = infantry
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1564 }
    name     = "29. Hoheishidan"
    location = 1218
    division =
    { experience = 20
      id         = { type = 30036 id = 565 }
      name       = "29.  Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1369 }
    name     = "3. Hendan"
    location = 1530 # Heihe
    division =
    { id    = { type = 30036 id = 568 }
      name  = "9. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 570 }
      name  = "57. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 572 }
      name  = "1. Border Guards"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1273 }
    name     = "4. Hendan"
    location = 1381 # Mohe
    division =
    { id    = { type = 30036 id = 574 }
      name  = "1. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 575 }
      name  = "2. Border Guards"
      type  = garrison
      model = 1
    }
    division =
    { id    = { type = 30036 id = 576 }
      name  = "3. Border Guards"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 577 }
    name     = "5. Hendan"
    location = 1374 # Jiamusi
    division =
    { id    = { type = 30036 id = 578 }
      name  = "11. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 579 }
      name  = "24. Hoheishidan"
      type  = infantry
      model = 1
    }
    division =
    { id    = { type = 30036 id = 582 }
      name  = "5. Border Guards"
      type  = garrison
      model = 1
    }
    division =
    { id       = { type = 30036 id = 583 }
      name     = "3 Manchuko Kiheishidan"
      strength = 50
      type     = cavalry
      model    = 0
    }
  }
  landunit =
  { id       = { type = 30036 id = 584 }
    name     = "6. Hendan"
    location = 1382 # Hailar, Manchuko 
    division =
    { id    = { type = 30036 id = 585 }
      name  = "14. Hoheishidan"
      type  = infantry
      model = 1
      extra = armored_car
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 586 }
      name       = "23. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = police
    }
  }
  landunit =
  { id       = { type = 30036 id = 587 }
    name     = "20. Hendan"
    location = 1375 # Mudanjiang
    division =
    { id    = { type = 30036 id = 588 }
      name  = "8. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 589 }
      name  = "25. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 590 }
      name  = "6. Border Guards"
      type  = garrison
      model = 1
      extra = armored_car
    }
  }
  landunit =
  { id       = { type = 30036 id = 597 }
    name     = "14. Hendan"
    location = 1248
    division =
    { experience = 20
      id         = { type = 30036 id = 598 }
      name       = "16. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 599 }
      name       = "48. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = artillery
    }
  }
  landunit =
  { id       = { type = 30036 id = 2602 }
    name     = "15. Hendan"
    location = 1322
    division =
    { experience = 20
      id         = { type = 30036 id = 2603 }
      name       = "33. Hoheishidan"
      type       = infantry
      model      = 1
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 2604 }
      name       = "55. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 2605 }
    name     = "15. Hendan"
    location = 1235
    division =
    { experience = 20
      id         = { type = 30036 id = 2606 }
      name       = "2. Hoheishidan"
      type       = infantry
      model      = 1
      extra      = engineer
    }
  }
  landunit =
  { id       = { type = 30036 id = 614 }
    name     = "Imperial General HQ"
    location = 1184 # Tokyo 
    division =
    { id    = { type = 30036 id = 615 }
      name  = "Imperial General HQ"
      type  = hq
      model = 1
    }
    division =
    { experience = 40
      id         = { type = 30036 id = 3612 }
      name       = "Imperial Guards"
      type       = infantry
      model      = 1
      extra      = artillery
    }
    division =
    { id    = { type = 30036 id = 616 }
      name  = "4. Hoheishidan"
      type  = infantry
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 618 }
    name     = "North Japan Army"
    location = 1181
    division =
    { id    = { type = 30036 id = 622 }
      name  = "1. Home Guards"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 626 }
    name     = "Central Japan Army"
    location = 1185
    division =
    { id    = { type = 30036 id = 630 }
      name  = "5. Home Guards"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 632 }
    name     = "West Japan Army"
    location = 1187
    division =
    { id    = { type = 30036 id = 633 }
      name  = "5. Depot"
      type  = infantry
      model = 0
    }
  }
  landunit =
  { id       = { type = 30036 id = 642 }
    name     = "East Japan Army"
    location = 1190
    division =
    { id    = { type = 30036 id = 645 }
      name  = "16. Home Guards"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 647 }
    name     = "Korean Army"
    location = 1376
    division =
    { id    = { type = 30036 id = 648 }
      name  = "19. Hoheishidan"
      type  = infantry
      model = 1
    }
    division =
    { id    = { type = 30036 id = 649 }
      name  = "20. Hoheishidan"
      type  = infantry
      model = 1
      extra = artillery
    }
    division =
    { id    = { type = 30036 id = 650 }
      name  = "1. Korean Garrison"
      type  = garrison
      model = 1
    }
    division =
    { id    = { type = 30036 id = 651 }
      name  = "2. Korean Garrison"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 654 }
    name     = "Taiwan Army"
    location = 1322
    division =
    { id    = { type = 30036 id = 655 }
      name  = "1. Taiwan Garrison"
      type  = garrison
      model = 1
    }
    division =
    { id    = { type = 30036 id = 656 }
      name  = "2. Taiwan Garrison"
      type  = garrison
      model = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 1654 }
    name     = "Special Taskforce"
    location = 1322
    division =
    { experience = 40
      id         = { type = 10300 id = 1616 }
      name       = "14. Hoheishidan"
      type       = infantry
      model      = 1
    }
  }
  landunit =
  { id       = { type = 30036 id = 681 }
    name     = "Shumushushima Hendan"
    location = 1174
    division =
    { id   = { type = 30036 id = 682 }
      name = "Shumushushima Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 667 }
    name     = "Shana Hendan"
    location = 1177
    division =
    { id   = { type = 30036 id = 668 }
      name = "Shana Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 664 }
    name     = "Tomari Hendan"
    location = 1179
    division =
    { id   = { type = 30036 id = 665 }
      name = "Tomari Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 662 }
    name     = "Toyohara Hendan"
    location = 1184
    division =
    { id   = { type = 30036 id = 663 }
      name = "Toyohara Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 660 }
    name     = "Naha Hendan"
    location = 1193
    division =
    { id   = { type = 30036 id = 661 }
      name = "Naha Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 658 }
    name     = "Saishu Hendan"
    location = 1194
    division =
    { id   = { type = 30036 id = 659 }
      name = "Saishu Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 683 }
    name     = "Bonin Hendan"
    location = 1599
    division =
    { id   = { type = 30036 id = 684 }
      name = "Bonin Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 675 }
    name     = "Bikini Hendan"
    location = 1600
    division =
    { id   = { type = 30036 id = 676 }
      name = "Bikini Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 673 }
    name     = "Eniwetok Hendan"
    location = 1601
    division =
    { id   = { type = 30036 id = 674 }
      name = "Eniwetok Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 693 }
    name     = "Marshall Hendan"
    location = 1605
    division =
    { id   = { type = 30036 id = 694 }
      name = "Marshall Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 677 }
    name     = "Kwajalein Hendan"
    location = 1608
    division =
    { id   = { type = 30036 id = 678 }
      name = "Kwajalein Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 691 }
    name     = "Ponape Hendan"
    location = 1610
    division =
    { id   = { type = 30036 id = 692 }
      name = "Ponape Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 689 }
    name     = "Truk Hendan"
    location = 1613
    division =
    { id   = { type = 30036 id = 690 }
      name = "Truk Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 687 }
    name     = "Ulithi Hendan"
    location = 1618
    division =
    { id   = { type = 30036 id = 688 }
      name = "Ulithi Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 695 }
    name     = "Yap Hendan"
    location = 1619
    division =
    { id   = { type = 30036 id = 696 }
      name = "Yap Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 671 }
    name     = "Palau Hendan"
    location = 1621
    division =
    { id   = { type = 30036 id = 672 }
      name = "Palau Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 679 }
    name     = "Saipan Hendan"
    location = 1627
    division =
    { id   = { type = 30036 id = 680 }
      name = "Saipan Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 669 }
    name     = "Omura Hendan"
    location = 1784
    division =
    { id   = { type = 30036 id = 670 }
      name = "Omura Hendan"
      type = garrison
    }
  }
  landunit =
  { id       = { type = 30036 id = 685 }
    name     = "Marcus Hendan"
    location = 1785
    division =
    { id   = { type = 30036 id = 686 }
      name = "Marcus Hendan"
      type = garrison
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1000 }
    name     = "1. (Battle) Fleet"
    location = 1188
    base     = 1188 # Hiroshima 
    division =
    { id    = { type = 10300 id = 403 }
      name  = "IJN Ryuju"
      type  = escort_carrier
      model = 1
    }
    division =
    { id    = { type = 10300 id = 21403 }
      name  = "IJN Chitose"
      type  = escort_carrier
      model = 1
    }
    division =
    { id    = { type = 10300 id = 10 }
      name  = "IJN Fuso"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10300 id = 12 }
      name  = "IJN Yamashiro"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10300 id = 14 }
      name  = "IJN Ise"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10300 id = 16 }
      name  = "IJN Hyuga"
      type  = battleship
      model = 1
    }
    division =
    { id    = { type = 10300 id = 2 }
      name  = "IJN Kongo"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 4 }
      name  = "IJN Hiei"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 23 }
      name  = "IJN Kako"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 24 }
      name  = "IJN Aoba"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 25 }
      name  = "IJN Kinugasa"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 22 }
      name  = "IJN Furutaka"
      type  = heavy_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 52 }
      name  = "IJN Kitakami"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 53 }
      name  = "IJN Oi"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 64 }
      name  = "IJN Sendai"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 1001 }
      name  = "IJN Yubari"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 149 }
      name  = "40 Kuchikukantai"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10300 id = 150 }
      name  = "41 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 154 }
      name  = "45 Kuchikukantai"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1010 }
    name     = "2. (Scouting) Fleet"
    location = 1184
    base     = 1184 # Tokyo
    division =
    { id    = { type = 10300 id = 410 }
      name  = "IJN Chitose"
      type  = carrier
      model = 1
    }         # seaplane tender
    division =
    { id    = { type = 10300 id = 35 }
      name  = "IJN Atago"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 36 }
      name  = "IJN Maya"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 37 }
      name  = "IJN Chokai"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 27 }
      name  = "IJN Myoko"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 41 }
      name  = "IJN Suzuya"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10300 id = 42 }
      name  = "IJN Kumano"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10300 id = 63 }
      name  = "IJN Naka"
      type  = light_cruiser
      model = 1
    }
    division =
    { id       = { type = 10300 id = 59 }
      name     = "IJN Natori"
      type     = light_cruiser
      model    = 1
      maxspeed = 36
    }
    division =
    { id    = { type = 10300 id = 90 }
      name  = "2 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 93 }
      name  = "5 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 96 }
      name  = "7 Kuchikukantai"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1011 }
    name     = "3. (Blockade) Fleet"
    location = 1322
    base     = 1322 # Taiwan
    division =
    { id    = { type = 10300 id = 6 }
      name  = "IJN Haruna"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 28 }
      name  = "IJN Nachi"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 29 }
      name  = "IJN Haguro"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 30 }
      name  = "IJN Ashigara"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 44 }
      name  = "IJN Tone"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 65 }
      name  = "IJN Jintsu"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 50 }
      name  = "IJN Kuma"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 103 }
      name  = "13 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10300 id = 107 }
      name  = "17 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 10300 id = 362 }
      name = "10 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 363 }
      name = "11 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 364 }
      name = "12 Yuso Sentai"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1015 }
    name     = "4. (Mandates) Fleet"
    location = 1613
    base     = 1613 # Truk
    division =
    { id    = { type = 10300 id = 47 }
      name  = "IJN Tenryu"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10300 id = 48 }
      name  = "IJN Tatsuta"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10300 id = 98 }
      name  = "9 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10300 id = 99 }
      name  = "10 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 30036 id = 613 }
      name  = "13 Sensuikantai"
      type  = submarine
      model = 3
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1016 }
    name     = "5. (Northern) Fleet"
    location = 1181
    base     = 1181 # Akita
    division =
    { id    = { type = 10300 id = 51 }
      name  = "IJN Tama"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 54 }
      name  = "IJN Kiso"
      type  = light_cruiser
      model = 1
    }
  }
  navalunit =
  { id       = { type = 30036 id = 900 }
    name     = "6. (Submarine) Fleet"
    location = 1186
    base     = 1186 # Kanazawa (Maizuru)
    division =
    { id    = { type = 30036 id = 601 }
      name  = "1 Sensuikantai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 602 }
      name  = "2 Sensuikantai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 603 }
      name  = "3 Sensuikantai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 604 }
      name  = "4 Sensuikantai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 605 }
      name  = "5 Sensuikantai"
      type  = submarine
      model = 0
    }
    division =
    { id    = { type = 30036 id = 606 }
      name  = "6 Sensuikantai"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 30036 id = 607 }
      name  = "7 Sensuikantai"
      type  = submarine
      model = 1
    }
    division =
    { id    = { type = 30036 id = 608 }
      name  = "8 Sensuikantai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 609 }
      name  = "9 Sensuikantai"
      type  = submarine
      model = 3
    }
    division =
    { id    = { type = 30036 id = 610 }
      name  = "10 Sensuikantai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 611 }
      name  = "11 Sensuikantai"
      type  = submarine
      model = 2
    }
    division =
    { id    = { type = 30036 id = 612 }
      name  = "12 Sensuikantai"
      type  = submarine
      model = 3
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1018 }
    name     = "Striking Force"
    location = 1184
    base     = 1184 # Tokyo
    division =
    { id            = { type = 10300 id = 401 }
      name          = "IJN Kaga"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 3
      experience    = 20
    }
    division =
    { id            = { type = 10300 id = 402 }
      name          = "IJN Agaki"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 3
      experience    = 20
    }
    division =
    { id            = { type = 10300 id = 404 }
      name          = "IJN Soryu"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 3
      experience    = 20
    }
    division =
    { id    = { type = 10300 id = 18 }
      name  = "IJN Nagato"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 10300 id = 20 }
      name  = "IJN Mutsu"
      type  = battleship
      model = 2
    }
    division =
    { id    = { type = 10300 id = 8 }
      name  = "IJN Kirishima"
      type  = battlecruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 34 }
      name  = "IJN Takao"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 39 }
      name  = "IJN Mogami"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10300 id = 40 }
      name  = "IJN Mikuma"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 10300 id = 151 }
      name  = "42 Kuchikukantai"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 10300 id = 152 }
      name  = "43 Kuchikukantai"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1019 }
    name     = "IJN Reserve Fleet"
    location = 1190
    base     = 1190
    division =
    { id            = { type = 10300 id = 1007 }
      name          = "IJN Hosho"
      type          = carrier
      model         = 0
      extra         = cag
      brigade_model = 0
    }
    division =
    { id    = { type = 10300 id = 997 }
      name  = "IJN Izumo"
      type  = heavy_cruiser
      model = 0
    }
    division =
    { id    = { type = 10300 id = 999 }
      name  = "IJN Hirado"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10300 id = 998 }
      name  = "IJN Yahagi"
      type  = light_cruiser
      model = 0
    }
    division =
    { id    = { type = 10300 id = 89 }
      name  = "1 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10300 id = 91 }
      name  = "3 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10300 id = 92 }
      name  = "4 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10300 id = 94 }
      name  = "6 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id    = { type = 10300 id = 97 }
      name  = "8 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 10300 id = 354 }
      name = "4 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 360 }
      name = "8 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 361 }
      name = "9 Yuso Sentai"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1020 }
    name     = "China Fleet"
    location = 1237
    base     = 1237
    division =
    { id    = { type = 10300 id = 57 }
      name  = "IJN Isuzu"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 58 }
      name  = "IJN Yura"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 60 }
      name  = "IJN Kinu"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 61 }
      name  = "IJN Abukuma"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 101 }
      name  = "12 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 104 }
      name  = "14 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 105 }
      name  = "15 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 106 }
      name  = "16 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 10300 id = 108 }
      name  = "18 Kuchikukantai"
      type  = destroyer
      model = 1
    }
    division =
    { id   = { type = 10300 id = 355 }
      name = "1 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 356 }
      name = "2 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 353 }
      name = "3 Yuso Sentai"
      type = transport
    }
  }
  navalunit =
  { id       = { type = 10300 id = 1021 }
    name     = "Korea Fleet"
    location = 1196
    base     = 1196
    division =
    { id    = { type = 10300 id = 45 }
      name  = "IJN Chikuma"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 10300 id = 56 }
      name  = "IJN Nagara"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 10300 id = 100 }
      name  = "11 Kuchikukantai"
      type  = destroyer
      model = 0
    }
    division =
    { id   = { type = 10300 id = 357 }
      name = "5 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 358 }
      name = "6 Yuso Sentai"
      type = transport
    }
    division =
    { id   = { type = 10300 id = 359 }
      name = "7 Yuso Sentai"
      type = transport
    }
  }
  airunit =
  { id       = { type = 30036 id = 213 }
    name     = "1. Hikoshidan"
    location = 1184
    base     = 1184 # Tokyo
    division =
    { experience = 20
      id         = { type = 30036 id = 214 }
      name       = "1 Zerosen no Hikodan"
      type       = interceptor
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 215 }
      name       = "12 Hikodan"
      type       = transport_plane
      model      = 0
    }
  }
  airunit =
  { id       = { type = 30036 id = 217 }
    name     = "2. Hikoshidan"
    location = 1202
    base     = 1202 # Dalian 
    division =
    { experience = 20
      id         = { type = 30036 id = 218 }
      name       = "2 Keibakugekiki no Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 220 }
      name       = "9 Keibakugekiki no Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 219 }
      name       = "8 Zerosen no Hikodan"
      type       = interceptor
      model      = 1
    }
  }
  airunit =
  { id       = { type = 30036 id = 222 }
    name     = "3. Hikoshidan"
    location = 1322
    base     = 1322 # Taiwan 
    division =
    { experience = 20
      id         = { type = 30036 id = 223 }
      name       = "3 Keibakugekiki no Hikodan"
      strength   = 100
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 224 }
      name       = "7 Keibakugekiki no Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 225 }
      name       = "10 Keibakugekiki no Hikodan"
      type       = tactical_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 226 }
      name       = "12 Zerosen no Hikodan"
      type       = interceptor
      model      = 1
    }
  }
  airunit =
  { id       = { type = 30036 id = 227 }
    name     = "1. Koku Kantai"
    location = 1322
    base     = 1322 # Taiwan 
    division =
    { experience = 20
      id         = { type = 30036 id = 228 }
      name       = "1. Koku Sentai"
      type       = naval_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 229 }
      name       = "2. Koku Sentai"
      type       = naval_bomber
      model      = 0
    }
    division =
    { experience = 20
      id         = { type = 30036 id = 230 }
      name       = "3. Koku Sentai"
      type       = multi_role
      model      = 0
    }
  }

  # Completion dates for CVs and BBs based upon historical start date plus HoI 2 build times
  # These build times are quicker than history but player may delay completion by lowering them in build queue priority
  division_development =
  { name  = "IJN Chiyoda" # seaplane carrier
    type  = escort_carrier
    model = 2
    cost  = 4
    id    = { type = 10300 id = 517 }
    date  = { year = 1938 month = december day = 14 } #86% ready
  }
  division_development =
    { id            = { type = 10300 id = 405 }
      name          = "IJN Hiryu"
      type          = carrier
      model         = 2
      cost          = 6
      date  = { year = 1939 month = march day = 25 } # 72% ready
  }
  brigade_development =
  { name  = "Hiryu CAG"
    type  = cag
    model = 2
    cost  = 2.7
    id    = { type = 10300 id = 406 }
    date  = { year = 1939 month = march day = 10 }
    }
  division_development =
  { name  = "IJN Zuiho" # conversion from submarine tender
    type  = carrier
    model = 2
    cost  = 6
    id    = { type = 10300 id = 510 }
    date  = { year = 1939 month = july day = 4 } #58% ready
  }
  brigade_development =
  { name  = "Zuiho CAG"
    type  = cag
    model = 2
    cost  = 2.7
    id    = { type = 10300 id = 511 }
    date  = { year = 1939 month = march day = 10 }
  }
  division_development =
  { name  = "IJN Shoho" # conversion from submarine tender, 1 year earlier than history per general HoI speed up
    type  = carrier
    model = 2
    cost  = 6
    id    = { type = 10300 id = 515 }
    date  = { year = 1939 month = august day = 5 } # 54% ready
  }
  brigade_development =
  { name  = "Shoho CAG"
    type  = cag
    model = 2
    cost  = 2.7
    id    = { type = 10300 id = 516 }
    date  = { year = 1939 month = march day = 10 }
  }
  division_development =
  { name  = "IJN Shokaku"
    type  = carrier
    model = 3
    cost  = 7
    id    = { type = 10300 id = 504 }
    date  = { year = 1940 month = april day = 9 } #20% ready
  }
  brigade_development =
  { name  = "Shokaku CAG"
    type  = cag
    model = 3
    cost  = 3.2
    id    = { type = 10300 id = 505 }
    date  = { year = 1939 month = march day = 10 }
  }
  division_development =
  { name  = "33 Sensuikantai"
    type  = submarine
    model = 3
    cost  = 2.3
    id    = { type = 10300 id = 503 }
    date  = { year = 1939 month = may day = 1 }
  }
  division_development =
  { name  = "IJN Zuikaku"
    type  = carrier
    model = 3
    cost  = 7
    id    = { type = 10300 id = 506 }
    date  = { year = 1940 month = july day = 2 } #8% ready
  }
  brigade_development =
  { name  = "Zuikaku CAG"
    type  = cag
    model = 3
    cost  = 3.2
    id    = { type = 10300 id = 507 }
    date  = { year = 1939 month = march day = 10 }
  }
  division_development =
  { name  = "IJN Yamato"
    type  = battleship
    model = 6
    cost  = 16
    id    = { type = 10300 id = 508 }
    date  = { year = 1940 month = april day = 30 } #20% ready
  }
  division_development =
  { name  = "IJN Musashi"
    type  = battleship
    model = 6
    cost  = 16
    id    = { type = 10300 id = 509 }
    date  = { year = 1940 month = july day = 17 } #10% ready
  }
}



