province = { id = 939 points = 1 } #Tunis
province = { id = 515 points = 20 } #Rome
province = { id = 534 points = 1 } #Sardinia
province = { id = 31 points = 3 } #Malta
province = { id = 525 points = 5 } #Palermo
province = { id = 521 points = 5 } #Napoli
province = { id = 378 points = 5 } # Venezia
province = { id = 370 points = 5 } # Milano
province = { id = 376 points = 5 } # München
province = { id = 377 points = 5 } # Innsbruck
province = { id = 378 points = 5 } # Genoa
