#################################
# Designed by Greven and Tracid #
#################################
#	Allied VP locations

province = { id = 56 points = 25 } # Paris 
province = { id = 50 points = 10 } # Antwerp 
province = { id = 51 points = 15 } # Brussels 
province = { id = 46 points = 5 }  # Rotterdam 
province = { id = 18 points = 5 }  # Calais 
province = { id = 69 points = 3 }  # Bastogne 
province = { id = 73 points = 2 }  # Strassbourg 
province = { id = 72 points = 3 }  # Metz 
province = { id = 71 points = 3 }  # Luxembourg 


#	German VP locations

province = { id = 47 points = 3 }  # Amsterdam 
province = { id = 67 points = 15 } # Essen 
province = { id = 75 points = 10 } # Cologne 
province = { id = 76 points = 5 }  # Dortmund 
province = { id = 77 points = 3 }  # Saarbrücken 
province = { id = 313 points = 3 } # Frankfurt am Main 
province = { id = 314 points = 5 } # Stuttgart 
province = { id = 315 points = 2 } # Freiburg 