#!/usr/bin/env python3
"""ASW, radar, night vision, aircraft ordnance, engines, and carrier systems."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══ ASW · DEPTH CHARGES & THROWERS ═══════════════════════════════════════
    {"id": "depth_charge_mk6", "name": "Mk 6 Depth Charge", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 10, "hard_attack": 48, "piercing": 12, "anti_ship": 32,
     "cost": {"steel": 3, "explosives": 12}, "production_time": 22,
     "special_flags": ["naval", "asw", "usa", "depth_charge"],
     "description": "Standard U.S. 600 lb depth charge. Rolled from stern racks; backbone of early-war ASW."},
    {"id": "depth_charge_mk9", "name": "Mk 9 Depth Charge", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 12, "hard_attack": 58, "piercing": 14, "anti_ship": 42,
     "cost": {"steel": 4, "explosives": 18}, "production_time": 28,
     "special_flags": ["naval", "asw", "usa", "depth_charge", "deep_setting"],
     "description": "U.S. deep-depth charge for convoy escorts. Effective against diving U-boats."},
    {"id": "k_gun_launcher", "name": "K-gun Depth Charge Projector", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 8, "hard_attack": 44, "piercing": 10, "anti_ship": 30,
     "cost": {"steel": 6, "explosives": 10}, "production_time": 26,
     "special_flags": ["naval", "asw", "usa", "depth_charge"],
     "description": "Side-thrown depth charge launcher. Widens attack pattern around escorts."},
    {"id": "hedgehog_sprengbombe", "name": "Hedgehog Spigot Mortar", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 18, "hard_attack": 55, "piercing": 8, "anti_ship": 48,
     "cost": {"steel": 10, "explosives": 14}, "production_time": 35,
     "special_flags": ["naval", "asw", "uk", "ahead_thrown"],
     "description": "24-spigot ahead-throwing mortar. Contact-fused; only damages submarines."},
    {"id": "mousetrap_asw", "name": "Mousetrap ASW Rocket", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 14, "hard_attack": 46, "piercing": 10, "anti_ship": 38,
     "cost": {"steel": 5, "explosives": 8}, "production_time": 28,
     "special_flags": ["naval", "asw", "usa", "rocket"],
     "description": "Small rocket launcher for coastal escorts. Simpler than Hedgehog."},
    {"id": "squid_asw_mortar", "name": "Squid ASW Mortar", "category": "SecondaryWeapon", "tier": 4,
     "soft_attack": 22, "hard_attack": 62, "piercing": 10, "anti_ship": 55,
     "cost": {"steel": 14, "explosives": 18, "electronics": 6}, "production_time": 48,
     "special_flags": ["naval", "asw", "uk", "ahead_thrown", "cold_war"],
     "description": "Post-war British ahead-throwing mortar with improved pattern and fusing."},
    {"id": "limbo_asw_mortar", "name": "Limbo ASW Mortar", "category": "SecondaryWeapon", "tier": 4,
     "soft_attack": 24, "hard_attack": 65, "piercing": 12, "anti_ship": 58,
     "cost": {"steel": 16, "explosives": 20, "electronics": 8}, "production_time": 52,
     "special_flags": ["naval", "asw", "uk", "cold_war"],
     "description": "Three-barrel British ASW mortar of the 1950s. Standard on frigates."},
    {"id": "german_wasserbombe", "name": "Wasserbombe W44", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 9, "hard_attack": 46, "piercing": 11, "anti_ship": 30,
     "cost": {"steel": 3, "explosives": 11}, "production_time": 24,
     "special_flags": ["naval", "asw", "germany", "depth_charge"],
     "description": "Kriegsmarine depth charge. Used on U-boat hunters and destroyers."},
    {"id": "ijn_type2_depth_charge", "name": "Type 2 Depth Charge", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 9, "hard_attack": 44, "piercing": 10, "anti_ship": 28,
     "cost": {"steel": 3, "explosives": 10}, "production_time": 23,
     "special_flags": ["naval", "asw", "japan", "depth_charge"],
     "description": "Imperial Japanese Navy standard depth charge. Less sophisticated than Allied patterns."},

    # ═══ ASW · SONAR & HOMING TORPEDOES ═══════════════════════════════════════
    {"id": "sonar_qcba", "name": "QCB Sonar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 4, "electronics": 14, "copper": 4}, "production_time": 40,
     "special_flags": ["naval", "asw", "sonar", "usa"],
     "description": "Early U.S. active sonar for destroyer escorts. Enables underwater detection and attack runs."},
    {"id": "sonar_type144", "name": "Type 144 Sonar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 3,
     "cost": {"steel": 4, "electronics": 12}, "production_time": 38,
     "special_flags": ["naval", "asw", "sonar", "uk"],
     "description": "British destroyer sonar set. Improved bearing accuracy for Hedgehog attacks."},
    {"id": "sonar_gdcs", "name": "GDCS Sonar Suite", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 5, "electronics": 18, "copper": 5}, "production_time": 48,
     "special_flags": ["naval", "asw", "sonar", "usa", "late_war"],
     "description": "Late-war U.S. sonar with improved range and discrimination against snorkel U-boats."},
    {"id": "mk24_fido_torpedo", "name": "Mk 24 FIDO Torpedo", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 16, "hard_attack": 52, "piercing": 20, "anti_ship": 62,
     "cost": {"steel": 8, "explosives": 14, "electronics": 10}, "production_time": 45,
     "special_flags": ["naval", "asw", "acoustic_homing", "usa", "air_launched"],
     "description": "Air-dropped acoustic homing torpedo. Devastating when U-boats were surfaced or snorkeling."},
    {"id": "mark44_lightweight_torpedo", "name": "Mark 44 Lightweight Torpedo", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 18, "hard_attack": 50, "piercing": 22, "anti_ship": 58,
     "cost": {"steel": 9, "explosives": 12, "electronics": 12}, "production_time": 50,
     "special_flags": ["naval", "asw", "homing", "usa", "helicopter"],
     "description": "Early lightweight ASW torpedo for helicopters and ASW aircraft (1950s)."},
    {"id": "weapon_alpha_asw", "name": "Weapon Alpha ASW Rocket", "category": "SecondaryWeapon", "tier": 4,
     "soft_attack": 20, "hard_attack": 60, "piercing": 12, "anti_ship": 52,
     "cost": {"steel": 12, "explosives": 16, "electronics": 8}, "production_time": 55,
     "special_flags": ["naval", "asw", "usa", "cold_war", "nuclear_depth_charge_capable"],
     "description": "U.S. ahead-throwing ASW weapon of the 1950s. Bridge between Hedgehog and modern ASROC."},

    # ═══ RADAR · AIR / NAVAL / GROUND ═════════════════════════════════════════
    {"id": "scr_520_airborne_radar", "name": "SCR-520 Airborne Radar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 3,
     "cost": {"steel": 5, "electronics": 16, "aluminum": 4}, "production_time": 45,
     "special_flags": ["radar", "airborne", "usa"],
     "description": "Early U.S. air-search radar on B-17 and patrol aircraft. Enables night and bad-weather detection."},
    {"id": "ai_mk4_radar", "name": "AI Mk IV Airborne Intercept", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 4, "electronics": 20, "aluminum": 6}, "production_time": 55,
     "special_flags": ["radar", "airborne", "night_fighter", "usa"],
     "description": "Centimetric radar for Mosquito and P-61 night fighters. Game-changer vs Luftwaffe night raids."},
    {"id": "fu_g_202_lichtenstein", "name": "FuG 202 Lichtenstein", "category": "Sensors", "tier": 3,
     "reliability_bonus": 2,
     "cost": {"steel": 5, "electronics": 18, "aluminum": 5}, "production_time": 52,
     "special_flags": ["radar", "airborne", "night_fighter", "germany"],
     "description": "German night-fighter airborne radar. Gave Bf 110 and Ju 88 crews night interception capability."},
    {"id": "fu_g_220_lichtenstein_sn2", "name": "FuG 220 Lichtenstein SN-2", "category": "Sensors", "tier": 4,
     "reliability_bonus": 4,
     "cost": {"steel": 6, "electronics": 22, "aluminum": 6}, "production_time": 60,
     "special_flags": ["radar", "airborne", "night_fighter", "germany", "late_war"],
     "description": "Improved German night-fighter radar with reduced vulnerability to Window jamming."},
    {"id": "type281_surface_radar", "name": "Type 281 Surface Radar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 3,
     "cost": {"steel": 6, "electronics": 14}, "production_time": 48,
     "special_flags": ["radar", "naval", "uk", "search"],
     "description": "Early RN long-range surface search radar on capital ships and cruisers."},
    {"id": "type273_surface_radar", "name": "Type 273 Target-Indication", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 5, "electronics": 16}, "production_time": 50,
     "special_flags": ["radar", "naval", "uk", "fire_control"],
     "description": "British destroyer/cruiser radar for surface gunnery in poor visibility."},
    {"id": "sg_surface_radar", "name": "SG Surface Search Radar", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 5, "electronics": 18}, "production_time": 52,
     "special_flags": ["radar", "naval", "usa"],
     "description": "U.S. microwave surface search radar. Standard on late-war destroyers and cruisers."},
    {"id": "sk_surface_radar", "name": "SK Air Search Radar", "category": "Sensors", "tier": 3,
     "reliability_bonus": 3,
     "cost": {"steel": 8, "electronics": 20}, "production_time": 58,
     "special_flags": ["radar", "naval", "usa", "carrier", "air_search"],
     "description": "U.S. fleet carrier air-search radar. Critical for CAP direction and raid warning."},
    {"id": "an_sps6_air_search", "name": "AN/SPS-6 Air Search", "category": "Sensors", "tier": 4,
     "reliability_bonus": 5,
     "cost": {"steel": 10, "electronics": 24}, "production_time": 65,
     "special_flags": ["radar", "naval", "usa", "carrier", "cold_war"],
     "description": "1950s carrier air-search radar. Replaces SK on Essex and Midway classes."},
    {"id": "wurzburg_ground_radar", "name": "Würzburg Ground Radar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 6, "electronics": 12}, "production_time": 42,
     "special_flags": ["radar", "ground", "germany", "flak"],
     "description": "German fire-control radar for flak batteries. Also used in coastal defense."},
    {"id": "microwave_early_warning", "name": "Chain Home Low Radar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 10, "electronics": 14, "copper": 8}, "production_time": 55,
     "special_flags": ["radar", "ground", "uk", "early_warning"],
     "description": "British coastal early-warning radar network component. Enabled Battle of Britain fighter control."},

    # ═══ NIGHT VISION & IR ════════════════════════════════════════════════════
    {"id": "m3_sniperscope", "name": "M3 Infrared Sniperscope", "category": "Sensors", "tier": 3,
     "reliability_bonus": 1,
     "cost": {"steel": 3, "electronics": 12, "optics": 8}, "production_time": 40,
     "special_flags": ["infrared", "night_fighting", "usa", "infantry"],
     "description": "U.S. infantry IR scope and illuminator. Limited Pacific night operations."},
    {"id": "british_tabby_scope", "name": "Tabby IR Tank Scope", "category": "Sensors", "tier": 3,
     "reliability_bonus": 2,
     "cost": {"steel": 4, "electronics": 14, "optics": 10}, "production_time": 45,
     "special_flags": ["infrared", "night_fighting", "uk", "tank"],
     "description": "British infrared vision for Cromwell and Churchill night operations."},
    {"id": "vampir_infantry_package", "name": "Vampir IR Package", "category": "Sensors", "tier": 4,
     "reliability_bonus": 2,
     "cost": {"steel": 5, "electronics": 16, "optics": 12, "rare_earths": 4}, "production_time": 55,
     "special_flags": ["infrared", "night_fighting", "germany", "combined_arms"],
     "description": "German man-portable IR sight and StG 44 integration. Rare but effective in 1945 trials."},
    {"id": "u2_night_fighter_radar_combo", "name": "U2 Night Fighter Radar Suite", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 4, "electronics": 18, "optics": 8}, "production_time": 50,
     "special_flags": ["radar", "infrared", "night_fighter", "combined"],
     "description": "Representative combined AI radar + IR sight fit for late-war night fighters."},

    # ═══ AIRCRAFT · MACHINE GUNS & CANNONS ════════════════════════════════════
    {"id": "browning_an_m2_heavy", "name": "AN/M2 .50 cal Heavy", "category": "MainWeapon", "tier": 2,
     "soft_attack": 22, "hard_attack": 10, "piercing": 20, "air_attack": 40,
     "cost": {"steel": 5, "aluminum": 2}, "production_time": 28,
     "special_flags": ["aircraft_gun", "usa", "heavy_machine_gun"],
     "description": "Aircraft-mounted M2 Browning. Standard U.S. fighter and bomber defensive armament."},
    {"id": "browning_an_m3_gun", "name": "AN/M3 .50 cal (High ROF)", "category": "MainWeapon", "tier": 3,
     "soft_attack": 26, "hard_attack": 12, "piercing": 22, "air_attack": 44,
     "cost": {"steel": 6, "aluminum": 2}, "production_time": 32,
     "special_flags": ["aircraft_gun", "usa", "late_war"],
     "description": "Higher rate-of-fire M3 for P-51K and late B-17 mounts."},
    {"id": "hispano_mk5_cannon", "name": "Hispano Mk V", "category": "MainWeapon", "tier": 3,
     "soft_attack": 26, "hard_attack": 16, "piercing": 34, "air_attack": 46,
     "cost": {"steel": 7, "aluminum": 3}, "production_time": 36,
     "special_flags": ["aircraft_gun", "uk", "20mm"],
     "description": "Compact high-velocity 20 mm for Spitfire and Tempest wings."},
    {"id": "oerlikon_ff_mk2", "name": "Oerlikon FF Mk II", "category": "MainWeapon", "tier": 2,
     "soft_attack": 20, "hard_attack": 12, "piercing": 28, "air_attack": 36,
     "cost": {"steel": 6, "aluminum": 3}, "production_time": 30,
     "special_flags": ["aircraft_gun", "naval", "20mm", "swiss_design"],
     "description": "Swiss-designed 20 mm used on naval mounts and some aircraft."},
    {"id": "berezin_b20_cannon", "name": "Berezin B-20", "category": "MainWeapon", "tier": 3,
     "soft_attack": 28, "hard_attack": 18, "piercing": 36, "air_attack": 44,
     "cost": {"steel": 7, "aluminum": 4}, "production_time": 38,
     "special_flags": ["aircraft_gun", "ussr", "20mm"],
     "description": "Soviet 20 mm cannon for Il-2 and late fighters. Higher muzzle velocity than ShVAK."},
    {"id": "n37_37mm_cannon", "name": "N-37 37mm", "category": "MainWeapon", "tier": 3,
     "soft_attack": 32, "hard_attack": 28, "piercing": 48, "air_attack": 38,
     "cost": {"steel": 10, "aluminum": 5}, "production_time": 42,
     "special_flags": ["aircraft_gun", "ussr", "anti_tank_air"],
     "description": "Il-2 and Yak-9T cannon. Devastating vs tanks and bombers."},
    {"id": "m4_37mm_cannon", "name": "M4 37mm Autocannon", "category": "MainWeapon", "tier": 3,
     "soft_attack": 30, "hard_attack": 26, "piercing": 46, "air_attack": 36,
     "cost": {"steel": 9, "aluminum": 4}, "production_time": 40,
     "special_flags": ["aircraft_gun", "usa", "p39_tank_buster"],
     "description": "P-39 Airacobra and P-63 nose cannon. Tank-busting fighter armament."},
    {"id": "mk108_30mm_aircraft", "name": "MK 108 30mm (Aircraft)", "category": "MainWeapon", "tier": 3,
     "soft_attack": 34, "hard_attack": 24, "piercing": 40, "air_attack": 52,
     "cost": {"steel": 8, "explosives": 4}, "production_time": 40,
     "special_flags": ["aircraft_gun", "germany", "30mm"],
     "description": "Compact 30 mm for Me 262 and late fighters. Few hits destroy bombers."},
    {"id": "type99_mk2_model2", "name": "Type 99 Mk 2 Model 2", "category": "MainWeapon", "tier": 3,
     "soft_attack": 24, "hard_attack": 14, "piercing": 30, "air_attack": 42,
     "cost": {"steel": 6, "aluminum": 2}, "production_time": 34,
     "special_flags": ["aircraft_gun", "japan", "20mm"],
     "description": "Improved Japanese 20 mm with higher velocity for Zero and Ki-84."},
    {"id": "defa_30mm_cannon", "name": "DEFA 30mm", "category": "MainWeapon", "tier": 4,
     "soft_attack": 36, "hard_attack": 26, "piercing": 44, "air_attack": 50,
     "cost": {"steel": 9, "aluminum": 5}, "production_time": 48,
     "special_flags": ["aircraft_gun", "france", "cold_war", "30mm"],
     "description": "French jet fighter cannon derived from German MK 108 lineage."},

    # ═══ AIRCRAFT · BOMBS · ROCKETS · NAPALM ══════════════════════════════════
    {"id": "napalm_m47", "name": "M47 Napalm Tank", "category": "MainWeapon", "tier": 3,
     "soft_attack": 95, "hard_attack": 8, "piercing": 4, "air_attack": 6,
     "cost": {"steel": 4, "explosives": 20, "chemicals": 18}, "production_time": 35,
     "special_flags": ["incendiary", "napalm", "usa", "anti_soft"],
     "description": "Gel incendiary tanks for fighter-bombers. Devastating vs personnel and light structures."},
    {"id": "napalm_improved_m74", "name": "M74 Napalm Cluster", "category": "MainWeapon", "tier": 4,
     "soft_attack": 105, "hard_attack": 10, "piercing": 5, "air_attack": 8,
     "cost": {"steel": 5, "explosives": 24, "chemicals": 22}, "production_time": 42,
     "special_flags": ["incendiary", "napalm", "usa", "korean_war"],
     "description": "Improved napalm composition used in Korea. Longer burn and better dispersion."},
    {"id": "tallboy_earthquake_bomb", "name": "Tallboy 12,000 lb", "category": "MainWeapon", "tier": 4,
     "soft_attack": 88, "hard_attack": 55, "piercing": 80, "air_attack": 6,
     "cost": {"steel": 12, "explosives": 55}, "production_time": 70,
     "special_flags": ["earthquake_bomb", "uk", "anti_structure", "penetrator"],
     "description": "RAF deep-penetration bomb for U-boat pens and Tirpitz. Requires heavy bomber."},
    {"id": "grand_slam_bomb", "name": "Grand Slam 22,000 lb", "category": "MainWeapon", "tier": 5,
     "soft_attack": 120, "hard_attack": 70, "piercing": 95, "air_attack": 5,
     "cost": {"steel": 18, "explosives": 90}, "production_time": 95,
     "special_flags": ["earthquake_bomb", "uk", "anti_structure"],
     "description": "Largest conventional bomb of WWII. Collapsed Bielefeld viaduct and U-boat shelters."},
    {"id": "hvar_rocket", "name": "HVAR 5-inch Rocket", "category": "MainWeapon", "tier": 3,
     "soft_attack": 42, "hard_attack": 28, "piercing": 35, "air_attack": 12,
     "cost": {"steel": 6, "explosives": 10}, "production_time": 32,
     "special_flags": ["rocket", "usa", "ground_attack"],
     "description": "High-velocity aircraft rocket for P-47 and naval attack aircraft."},
    {"id": "rp3_rocket", "name": "RP-3 Rocket", "category": "MainWeapon", "tier": 2,
     "soft_attack": 38, "hard_attack": 22, "piercing": 28, "air_attack": 10,
     "cost": {"steel": 5, "explosives": 8}, "production_time": 28,
     "special_flags": ["rocket", "uk", "ground_attack"],
     "description": "British 60 lb rocket on Typhoon and Hurricane. Effective vs armor and shipping."},
    {"id": "wfr_gr21_rocket", "name": "Wfr. Gr. 21 Rocket", "category": "MainWeapon", "tier": 3,
     "soft_attack": 55, "hard_attack": 20, "piercing": 25, "air_attack": 14,
     "cost": {"steel": 6, "explosives": 14}, "production_time": 30,
     "special_flags": ["rocket", "germany", "bomber_destroyer"],
     "description": "BR 21 air-launched rocket for bomber interception (Sturmböcke tactics)."},
    {"id": "phosphorus_incendiary_bomb", "name": "Phosphorus Incendiary Bomb", "category": "MainWeapon", "tier": 2,
     "soft_attack": 78, "hard_attack": 6, "piercing": 4, "air_attack": 5,
     "cost": {"steel": 3, "explosives": 14, "chemicals": 10}, "production_time": 30,
     "special_flags": ["incendiary", "area_denial"],
     "description": "WP incendiary for area denial and marking targets."},
    {"id": "razon_guided_bomb", "name": "Razon Guided Bomb", "category": "MainWeapon", "tier": 4,
     "soft_attack": 50, "hard_attack": 45, "piercing": 40, "air_attack": 8,
     "cost": {"steel": 6, "electronics": 18, "explosives": 22}, "production_time": 55,
     "special_flags": ["guided_weapon", "usa", "radio_guided"],
     "description": "Early radio-guided bomb (1945). Precursor to smart munitions."},
    {"id": "torpex_warhead_upgrade", "name": "Torpex Explosive Fill", "category": "Cargo", "tier": 3,
     "soft_attack": 5, "hard_attack": 8, "piercing": 2,
     "cost": {"explosives": 15, "chemicals": 8}, "production_time": 20,
     "special_flags": ["ammunition", "explosive_upgrade", "naval", "air"],
     "description": "Torpex-filled warheads replacing TNT. More powerful bombs and torpedoes."},
    {"id": "cluster_bomb_sc1", "name": "SC-1 Cluster Bomb", "category": "MainWeapon", "tier": 4,
     "soft_attack": 70, "hard_attack": 12, "piercing": 6, "air_attack": 8,
     "cost": {"steel": 5, "explosives": 28}, "production_time": 45,
     "special_flags": ["cluster", "usa", "anti_personnel", "late_war"],
     "description": "Early cluster munition experiments. Area effect vs airfield dispersal."},

    # ═══ SHIP & AIRCRAFT ENGINES ══════════════════════════════════════════════
    {"id": "geared_steam_turbine_60k", "name": "Geared Steam Turbine (60k shp)", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": -6, "speed_bonus": 10,
     "cost": {"steel": 40, "copper": 10}, "production_time": 110,
     "special_flags": ["naval", "steam", "destroyer", "cruiser"],
     "description": "Standard U.S./RN destroyer and cruiser powerplant package."},
    {"id": "carrier_boiler_yarrow", "name": "Yarrow Boiler Plant", "category": "Engine", "tier": 3,
     "reliability_bonus": 6, "fuel_efficiency": -8, "speed_bonus": 8,
     "cost": {"steel": 35, "copper": 8}, "production_time": 100,
     "special_flags": ["naval", "steam", "carrier"],
     "description": "High-pressure boilers for fleet carriers. Supplies steam for turbines and catapults."},
    {"id": "iowa_class_turbine_212k", "name": "Iowa-class Turbine (212k shp)", "category": "Engine", "tier": 5,
     "reliability_bonus": 10, "fuel_efficiency": -10, "speed_bonus": 14,
     "cost": {"steel": 65, "chromium": 8, "copper": 12}, "production_time": 150,
     "special_flags": ["naval", "steam", "battleship", "fast_capital"],
     "description": "Westinghouse geared turbines on Iowa-class battleships. Exceptional speed for capital ship."},
    {"id": "pratt_r2800_corsair", "name": "Pratt R-2800 (Corsair)", "category": "Engine", "tier": 3,
     "reliability_bonus": 11, "fuel_efficiency": 4, "speed_bonus": 13,
     "cost": {"steel": 12, "aluminum": 14}, "production_time": 54,
     "special_flags": ["fighter_powerplant", "usa", "carrier_capable"],
     "description": "F4U Corsair and carrier-capable variants. Rugged naval fighter engine."},
    {"id": "wright_r3350_b29", "name": "Wright R-3350 Duplex-Cyclone", "category": "Engine", "tier": 4,
     "reliability_bonus": 6, "fuel_efficiency": 2, "speed_bonus": 10,
     "cost": {"steel": 14, "aluminum": 16, "rubber": 3}, "production_time": 62,
     "special_flags": ["bomber_powerplant", "usa"],
     "description": "B-29 Superfortress engine. Complex but essential for strategic bombing range."},
    {"id": "bristol_hercules_radial", "name": "Bristol Hercules", "category": "Engine", "tier": 3,
     "reliability_bonus": 7, "fuel_efficiency": 5, "speed_bonus": 11,
     "cost": {"steel": 11, "aluminum": 12}, "production_time": 50,
     "special_flags": ["fighter_powerplant", "uk", "twin_engine"],
     "description": "Beaufighter, Wellington, and transport aircraft. Reliable twin-row radial."},
    {"id": "jumo_213_fighter_engine", "name": "Jumo 213A", "category": "Engine", "tier": 3,
     "reliability_bonus": 3, "fuel_efficiency": 4, "speed_bonus": 15,
     "cost": {"steel": 12, "aluminum": 14}, "production_time": 52,
     "special_flags": ["fighter_powerplant", "germany"],
     "description": "Fw 190D and late German fighters. High-altitude performance."},
    {"id": "wasp_r1340_carrier_scout", "name": "Wasp R-1340 (Carrier Scout)", "category": "Engine", "tier": 2,
     "reliability_bonus": 9, "fuel_efficiency": 5, "speed_bonus": 9,
     "cost": {"steel": 9, "aluminum": 10}, "production_time": 44,
     "special_flags": ["carrier_capable", "usa", "scout_aircraft"],
     "description": "F4F Wildcat and OS2U Kingfisher powerplant. Standard U.S. carrier aviation engine."},
    {"id": "rolls_royce_merlin_carrier", "name": "Merlin 55 (Carrier Fighter)", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": 5, "speed_bonus": 12,
     "cost": {"steel": 12, "aluminum": 15}, "production_time": 56,
     "special_flags": ["carrier_capable", "uk", "seafire_firefly"],
     "description": "Merlin variant for Seafire and Firefly. Navalized for carrier operations."},

    # ═══ CARRIER SYSTEMS ════════════════════════════════════════════════════════
    {"id": "carrier_armored_flight_deck", "name": "Armored Flight Deck", "category": "Armor", "tier": 4,
     "armor_bonus": 38, "top_armor_bonus": 55, "reliability_penalty": -8,
     "cost": {"steel": 70, "chromium": 6}, "production_time": 120,
     "special_flags": ["carrier", "uk", "illustrious_class"],
     "description": "British armored carrier flight deck. Withstands bomb hits that would cripple U.S. wooden decks."},
    {"id": "carrier_wooden_flight_deck", "name": "Wooden Flight Deck", "category": "Armor", "tier": 2,
     "armor_bonus": 8, "top_armor_bonus": 18, "reliability_penalty": -4,
     "cost": {"steel": 25, "rubber": 6}, "production_time": 70,
     "special_flags": ["carrier", "usa", "essex_class"],
     "description": "U.S. carrier wooden deck with steel support. Easier repair; vulnerable to armor-piercing bombs."},
    {"id": "carrier_hydraulic_catapult", "name": "Hydraulic Catapult H1", "category": "Sensors", "tier": 3,
     "reliability_bonus": 2,
     "cost": {"steel": 18, "electronics": 8, "rubber": 4}, "production_time": 65,
     "special_flags": ["carrier", "catapult", "usa"],
     "description": "Hydraulic aircraft catapult for fleet carriers. Enables heavier aircraft launch."},
    {"id": "carrier_steam_catapult", "name": "Steam Catapult Mk C11", "category": "Sensors", "tier": 4,
     "reliability_bonus": 4,
     "cost": {"steel": 22, "electronics": 12, "copper": 6}, "production_time": 75,
     "special_flags": ["carrier", "catapult", "uk", "late_war"],
     "description": "British steam catapult. Higher launch weight for Firefly and torpedo bombers."},
    {"id": "carrier_arrestor_wire", "name": "Arrestor Wire System", "category": "Sensors", "tier": 2,
     "reliability_bonus": 3,
     "cost": {"steel": 12, "rubber": 8}, "production_time": 40,
     "special_flags": ["carrier", "arrestor_gear"],
     "description": "Hydraulic arrestor wires and barriers. Essential for carrier landing operations."},
    {"id": "carrier_air_wing_bunker", "name": "Air Wing Hangar Storage", "category": "Cargo", "tier": 3,
     "reliability_bonus": 0,
     "cost": {"steel": 30, "aluminum": 8}, "production_time": 80,
     "special_flags": ["carrier", "hangar", "aircraft_capacity"],
     "description": "Hangar deck arrangement and aviation fuel stowage. Determines effective air group size."},
    {"id": "carrier_aa_bofors_40mm", "name": "40mm Bofors AA Battery", "category": "AntiAir", "tier": 3,
     "soft_attack": 12, "hard_attack": 6, "air_attack": 42, "anti_air": 45,
     "cost": {"steel": 10, "aluminum": 4, "electronics": 4}, "production_time": 45,
     "special_flags": ["carrier", "anti_air", "usa", "uk"],
     "description": "Quad 40 mm Bofors mounts on carrier sponsons. Primary close-range AA defense."},
    {"id": "carrier_aa_20mm_oerlikon", "name": "20mm Oerlikon AA Belt", "category": "AntiAir", "tier": 2,
     "soft_attack": 10, "hard_attack": 4, "air_attack": 32, "anti_air": 35,
     "cost": {"steel": 6, "aluminum": 3}, "production_time": 32,
     "special_flags": ["carrier", "anti_air"],
     "description": "Supplementary 20 mm close-in weapon ring on carriers and escort carriers."},
    {"id": "carrier_island_superstructure", "name": "Island Superstructure", "category": "Armor", "tier": 2,
     "armor_bonus": 12, "top_armor_bonus": 8, "reliability_penalty": -2,
     "cost": {"steel": 35, "electronics": 6}, "production_time": 75,
     "special_flags": ["carrier", "command"],
     "description": "Carrier island with bridge, radar mounts, and flight control positions."},
    {"id": "carrier_deck_elevator", "name": "Aircraft Elevator System", "category": "Sensors", "tier": 3,
     "reliability_bonus": 2,
     "cost": {"steel": 20, "electronics": 6}, "production_time": 60,
     "special_flags": ["carrier", "elevator"],
     "description": "Heavy elevator connecting hangar to flight deck. Through-deck or edge designs."},
    {"id": "carrier_lso_system", "name": "Landing Signal Officer System", "category": "Sensors", "tier": 2,
     "reliability_bonus": 4,
     "cost": {"steel": 2, "electronics": 6, "optics": 4}, "production_time": 28,
     "special_flags": ["carrier", "flight_ops"],
     "description": "LSO paddles and later mirror landing aids. Reduces carrier landing losses."},
    {"id": "carrier_cic_director", "name": "Carrier CIC Station", "category": "Sensors", "tier": 3,
     "reliability_bonus": 5,
     "cost": {"steel": 8, "electronics": 16}, "production_time": 55,
     "special_flags": ["carrier", "radar", "command"],
     "description": "Combat Information Center integrating SK radar, fighter direction, and AA fire control."},
    {"id": "escort_carrier_hanger", "name": "Escort Carrier (CVE) Layout", "category": "Cargo", "tier": 2,
     "reliability_bonus": 1,
     "cost": {"steel": 22, "aluminum": 4}, "production_time": 65,
     "special_flags": ["carrier", "escort_carrier", "asw_aviation"],
     "description": "Smaller hangar optimized for ASW air groups (Wildcat/Avenger, FIDO support)."},
    {"id": "flakvierling_38_quad", "name": "2 cm Flakvierling 38", "category": "AntiAir", "tier": 3,
     "soft_attack": 14, "hard_attack": 6, "air_attack": 38, "anti_air": 40,
     "cost": {"steel": 8, "aluminum": 3}, "production_time": 38,
     "special_flags": ["carrier", "anti_air", "germany", "naval"],
     "description": "Quad 2 cm mount for Kriegsmarine carriers and capital ships. Standard close-range AA."},
    {"id": "angled_deck_prototype", "name": "Angled Flight Deck (Proto)", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 40, "electronics": 10}, "production_time": 90,
     "special_flags": ["carrier", "prototype", "cold_war", "uk"],
     "description": "Royal Navy 1952 prototype angled deck. Allows simultaneous launch and recovery."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\nSpecialized equipment: {created} created, {skipped} skipped, {total} total modules.")


if __name__ == "__main__":
    main()
