#!/usr/bin/env python3
"""2020s–2030s unit templates including planned systems (F-47, Trump-class, etc.)."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    # ─── USA ───────────────────────────────────────────────────────────────────
    {
        "id": "m1a2_sep_v4_abrams",
        "name": "M1A2 SEP v4",
        "design_family": "us_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 128,
        "base_stats": {"speed": 32, "reliability": 86, "fuel_consumption": 18, "supply_need": 26,
                      "armor": 90, "top_armor": 68, "hardness": 98},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256a1_120mm_gun", "Engine": "agt1500_turbine",
                         "Armor": "m1a2_sep_v4_armor", "Sensors": "trophy_aps_usa",
                         "Cargo": "m829a4_apfsds"},
        "unlock_tech": ["us_mbt_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "abramsx_prototype",
        "name": "AbramsX (Prototype)",
        "design_family": "us_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 135,
        "base_stats": {"speed": 34, "reliability": 82, "fuel_consumption": 12, "supply_need": 24,
                      "armor": 88, "top_armor": 65, "hardness": 97},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256_l55_gun", "Engine": "abramsx_hybrid_package",
                         "Armor": "m1a2_sep_v4_armor", "Sensors": "ai_targeting_suite"},
        "unlock_tech": ["us_mbt_twenty_twenties", "prototype"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f47_ngad_proto",
        "name": "F-47 NGAD (Development)",
        "design_family": "us_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 160,
        "base_stats": {"speed": 118, "reliability": 76, "fuel_consumption": 22, "supply_need": 24,
                      "armor": 8, "hardness": 26},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1},
                  "DroneAttachment": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim260_jatm", "Engine": "ngad_adaptive_engine",
                         "Sensors": "aesa_radar_gen2", "DroneAttachment": "cca_loyal_wingman"},
        "unlock_tech": ["us_fighters_twenty_twenties", "ngad", "planned"],
        "can_mount_drones": True,
        "is_vehicle": True,
    },
    {
        "id": "f35a_block4",
        "name": "F-35A Block 4",
        "design_family": "us_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 130,
        "base_stats": {"speed": 110, "reliability": 80, "fuel_consumption": 20, "supply_need": 20,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim120d_amraam", "Engine": "pratt_f135_engine",
                         "Sensors": "f35_block4_package"},
        "unlock_tech": ["us_fighters_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "b21_raider",
        "name": "B-21 Raider",
        "design_family": "us_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "bomber",
        "crew_required": 2,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 200,
        "base_stats": {"speed": 95, "reliability": 78, "fuel_consumption": 28, "supply_need": 28,
                      "armor": 12, "hardness": 30},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "agm158_jassm", "Engine": "b21_raider_package",
                         "Sensors": "stealth_coating_proto"},
        "unlock_tech": ["us_bombers_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "trump_class_battleship",
        "name": "Trump-class Battleship",
        "design_family": "us_naval_planned",
        "base_type": "Naval",
        "size_category": "SuperHeavy",
        "visual_archetype": "battleship",
        "crew_required": 1200,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 320,
        "base_stats": {"speed": 28, "reliability": 72, "fuel_consumption": 120, "supply_need": 150,
                      "armor": 95, "deck_armor": 70, "hardness": 88},
        "slots": {
            "NavalGun": {"max": 2},
            "SecondaryWeapon": {"max": 2},
            "Armor": {"max": 1},
            "Sensors": {"max": 2},
            "AntiAir": {"max": 2},
        },
        "module_loadout": {
            "NavalGun": "trump_class_16inch_modern",
            "SecondaryWeapon": "trump_class_vls_farm",
            "Armor": "trump_class_hull",
            "Sensors": "ddgx_combat_system",
            "AntiAir": "hel_mdi_laser",
        },
        "unlock_tech": ["us_naval_planned", "trump_class", "battleship_revival"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "ddgx_destroyer",
        "name": "DDG(X)",
        "design_family": "us_naval_planned",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "destroyer",
        "crew_required": 280,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 200,
        "base_stats": {"speed": 32, "reliability": 80, "fuel_consumption": 70, "supply_need": 85,
                      "armor": 45, "deck_armor": 28, "hardness": 72},
        "slots": {"SecondaryWeapon": {"max": 2}, "Sensors": {"max": 2}, "AntiAir": {"max": 2}},
        "module_loadout": {"SecondaryWeapon": "trump_class_vls_farm", "Sensors": "ddgx_combat_system",
                         "AntiAir": "aegis_bmd_package"},
        "unlock_tech": ["us_naval_planned"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m1e3_abrams_2030",
        "name": "M1E3 Abrams",
        "design_family": "us_armored_twenty_thirties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 140,
        "base_stats": {"speed": 34, "reliability": 88, "fuel_consumption": 14, "supply_need": 26,
                      "armor": 95, "top_armor": 72, "hardness": 99},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256_l55a1_gun", "Engine": "abramsx_hybrid_package",
                         "Armor": "m1e3_abrams_package", "Sensors": "ai_targeting_suite",
                         "Cargo": "xm1147_amp_round"},
        "unlock_tech": ["us_mbt_twenty_thirties", "planned"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f47_operational",
        "name": "F-47 (Operational)",
        "design_family": "us_air_twenty_thirties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 44,
        "max_experience_level": 100,
        "base_production_days": 175,
        "base_stats": {"speed": 120, "reliability": 82, "fuel_consumption": 22, "supply_need": 26,
                      "armor": 8, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1},
                  "DroneAttachment": {"max": 2}},
        "module_loadout": {"MainWeapon": "aim260_jatm", "Engine": "f47_ngad_package",
                         "Sensors": "f47_operational_fit", "DroneAttachment": "cca_loyal_wingman"},
        "unlock_tech": ["us_fighters_twenty_thirties", "sixth_gen"],
        "can_mount_drones": True,
        "is_vehicle": True,
    },
    # ─── RUSSIA ────────────────────────────────────────────────────────────────
    {
        "id": "t90m_mbt",
        "name": "T-90M",
        "design_family": "russian_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 35, "reliability": 76, "fuel_consumption": 13, "supply_need": 16,
                      "armor": 68, "top_armor": 42, "hardness": 93},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "2a46m5_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t90m_armor_package", "Cargo": "3bm69_apfsds"},
        "unlock_tech": ["russian_mbt_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "su57_felon_serial",
        "name": "Su-57 (Serial)",
        "design_family": "russian_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 112, "reliability": 74, "fuel_consumption": 22, "supply_need": 18,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "DroneAttachment": {"max": 1}},
        "module_loadout": {"MainWeapon": "r77_1_adder", "Engine": "su57_serial_package",
                         "DroneAttachment": "okhotnik_ucav"},
        "unlock_tech": ["russian_fighters_twenty_twenties"],
        "can_mount_drones": True,
        "is_vehicle": True,
    },
    # ─── CHINA ─────────────────────────────────────────────────────────────────
    {
        "id": "type99a_phase3",
        "name": "Type 99A (Phase III)",
        "design_family": "chinese_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 108,
        "base_stats": {"speed": 36, "reliability": 78, "fuel_consumption": 13, "supply_need": 16,
                      "armor": 72, "top_armor": 45, "hardness": 95},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "zpt98_125mm_gun", "Engine": "ws10b_engine",
                         "Armor": "type99a_phase3_armor"},
        "unlock_tech": ["chinese_mbt_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "j20a_fighter",
        "name": "J-20A",
        "design_family": "chinese_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 140,
        "base_stats": {"speed": 112, "reliability": 78, "fuel_consumption": 22, "supply_need": 18,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "pl15e_missile", "Engine": "j20a_operational",
                         "Sensors": "aesa_radar_gen2"},
        "unlock_tech": ["chinese_fighters_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "fujian_carrier",
        "name": "CNS Fujian",
        "design_family": "chinese_naval_twenty_twenties",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "carrier",
        "crew_required": 2600,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 300,
        "base_stats": {"speed": 30, "reliability": 78, "fuel_consumption": 100, "supply_need": 130,
                      "armor": 55, "deck_armor": 40, "hardness": 75},
        "slots": {"Cargo": {"max": 1}, "Sensors": {"max": 2}, "AntiAir": {"max": 2}},
        "module_loadout": {"Cargo": "fujian_emals_carrier", "Sensors": "type055_destroyer_vls",
                         "AntiAir": "hq9b_sam"},
        "unlock_tech": ["chinese_carriers_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── FRANCE / UK / GERMANY / ISRAEL ────────────────────────────────────────
    {
        "id": "rafale_f4",
        "name": "Rafale F4",
        "design_family": "french_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 108, "reliability": 82, "fuel_consumption": 16, "supply_need": 14,
                      "armor": 10, "hardness": 26},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "mica_ng_missile", "Engine": "rafale_package",
                         "Sensors": "rafale_f4_package"},
        "unlock_tech": ["french_fighters_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "challenger3_mbt",
        "name": "Challenger 3",
        "design_family": "uk_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 125,
        "base_stats": {"speed": 28, "reliability": 82, "fuel_consumption": 15, "supply_need": 22,
                      "armor": 80, "top_armor": 56, "hardness": 98},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "challenger3_package", "Engine": "mtu_mb873_engine",
                         "Armor": "challenger3_armor", "Sensors": "hunter_killer_fcs"},
        "unlock_tech": ["uk_mbt_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "gcas_tempest_2030",
        "name": "GCAP Tempest",
        "design_family": "uk_air_twenty_thirties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 180,
        "base_stats": {"speed": 118, "reliability": 80, "fuel_consumption": 22, "supply_need": 24,
                      "armor": 8, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "DroneAttachment": {"max": 1}},
        "module_loadout": {"MainWeapon": "meteor_missile", "Engine": "gcas_tempest_engine",
                         "DroneAttachment": "cca_loyal_wingman"},
        "unlock_tech": ["uk_fighters_twenty_thirties", "planned"],
        "can_mount_drones": True,
        "is_vehicle": True,
    },
    {
        "id": "leopard2a8",
        "name": "Leopard 2A8",
        "design_family": "german_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 36, "reliability": 90, "fuel_consumption": 12, "supply_need": 18,
                      "armor": 82, "top_armor": 58, "hardness": 98},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh120_l55_gun", "Engine": "mtu_mb873_engine",
                         "Armor": "leopard2a8_package", "Sensors": "trophy_aps_usa"},
        "unlock_tech": ["german_mbt_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mgcs_prototype_2030",
        "name": "MGCS (Prototype)",
        "design_family": "german_armored_twenty_thirties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 160,
        "base_stats": {"speed": 38, "reliability": 88, "fuel_consumption": 11, "supply_need": 20,
                      "armor": 85, "top_armor": 55, "hardness": 99},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "mgcs_main_gun", "Engine": "abramsx_hybrid_package",
                         "Armor": "mgcs_armor_package", "Sensors": "ai_targeting_suite"},
        "unlock_tech": ["german_mbt_twenty_thirties", "franco_german", "planned"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "merkava_mk4_barak",
        "name": "Merkava Mk 4 Barak",
        "design_family": "israeli_armored_twenty_twenties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 118,
        "base_stats": {"speed": 30, "reliability": 86, "fuel_consumption": 14, "supply_need": 18,
                      "armor": 78, "top_armor": 48, "hardness": 96},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "merkava_mk4m_120mm", "Engine": "merkava_avds_engine",
                         "Armor": "merkava_mk4_barak", "Sensors": "trophy_aps_israel"},
        "unlock_tech": ["israeli_mbt_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f35i_adir_block4",
        "name": "F-35I Adir Block 4",
        "design_family": "israeli_air_twenty_twenties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 140,
        "base_stats": {"speed": 110, "reliability": 82, "fuel_consumption": 20, "supply_need": 20,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "python5_missile", "Engine": "pratt_f135_engine",
                         "Sensors": "f35i_adir_block4"},
        "unlock_tech": ["israeli_fighters_twenty_twenties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if tpl["id"] in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\n2020s–2030s templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
