#!/usr/bin/env python3
"""2026 scenario naval fleet: surface combatants for every scenario nation."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "data"
MODULES_DIR = ROOT / "modules"
TEMPLATES_DIR = ROOT / "unit_templates"

T2026 = ["naval_2026", "twenty_twenties_naval"]

# fmt: off
MODULES: list[dict] = [
    {"id": "fremm_frigate_suite", "name": "FREMM Frigate Suite", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 12, "electronics": 42, "aluminum": 10}, "production_time": 88,
     "special_flags": ["france", "italy", "export", "frigate", "twenty_twenties"],
     "description": "FREMM multi-mission frigate combat system. ASW, AAW, and land-attack capable."},
    {"id": "baden_wurttemberg_f125", "name": "Baden-Württemberg F125", "category": "Armor", "tier": 6,
     "armor_bonus": 32, "top_armor_bonus": 22, "reliability_bonus": 6,
     "cost": {"steel": 50, "electronics": 28, "aluminum": 15}, "production_time": 130,
     "special_flags": ["germany", "frigate", "twenty_twenties"],
     "description": "German F125 frigate optimized for stabilization and littoral missions."},
    {"id": "halifax_class_system", "name": "Halifax-class Combat System", "category": "Sensors", "tier": 6,
     "reliability_bonus": 7,
     "cost": {"steel": 10, "electronics": 38, "aluminum": 8}, "production_time": 82,
     "special_flags": ["canada", "frigate", "twenty_twenties"],
     "description": "Royal Canadian Navy Halifax-class with ESSM and Harpoon."},
    {"id": "hobart_auk_system", "name": "Hobart Aegis System", "category": "Sensors", "tier": 7,
     "reliability_bonus": 9,
     "cost": {"steel": 12, "electronics": 48, "aluminum": 12}, "production_time": 95,
     "special_flags": ["australia", "destroyer", "aegis", "twenty_twenties"],
     "description": "RAN Hobart-class Aegis destroyer based on Spanish F100 design."},
    {"id": "gorshkov_frigate_suite", "name": "Admiral Gorshkov Suite", "category": "Sensors", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 14, "electronics": 35, "aluminum": 10}, "production_time": 85,
     "special_flags": ["russia", "frigate", "twenty_twenties"],
     "description": "Project 22350 frigate with Kalibr and Poliment-Redut air defense."},
    {"id": "kolkata_class_destroyer", "name": "Kolkata-class Destroyer", "category": "Sensors", "tier": 6,
     "reliability_bonus": 7,
     "cost": {"steel": 14, "electronics": 40, "aluminum": 12}, "production_time": 90,
     "special_flags": ["india", "destroyer", "twenty_twenties"],
     "description": "Indian guided-missile destroyer with Barak-8 and BrahMos."},
    {"id": "maya_class_aegis_japan", "name": "Maya-class Aegis", "category": "Sensors", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 12, "electronics": 50, "aluminum": 14}, "production_time": 98,
     "special_flags": ["japan", "destroyer", "aegis", "twenty_twenties"],
     "description": "JMSDF Maya-class with Cooperative Engagement Capability."},
    {"id": "sejong_kdx3_aegis", "name": "Sejong KDX-III Aegis", "category": "Sensors", "tier": 7,
     "reliability_bonus": 9,
     "cost": {"steel": 14, "electronics": 52, "aluminum": 12}, "production_time": 100,
     "special_flags": ["south_korea", "destroyer", "aegis", "twenty_twenties"],
     "description": "ROK Sejong the Great-class with Aegis and cruise missile strike."},
    {"id": "f100_aegis_spain", "name": "F100 Álvaro de Bazán", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 12, "electronics": 42, "aluminum": 10}, "production_time": 88,
     "special_flags": ["spain", "frigate", "aegis", "twenty_twenties"],
     "description": "Spanish Aegis frigate design exported to Australia and Norway."},
    {"id": "saar6_corvette", "name": "Sa'ar 6 Corvette", "category": "Armor", "tier": 6,
     "armor_bonus": 28, "top_armor_bonus": 18, "reliability_bonus": 8,
     "cost": {"steel": 35, "electronics": 38, "aluminum": 12}, "production_time": 110,
     "special_flags": ["israel", "corvette", "twenty_twenties"],
     "description": "Israeli corvette with Iron Dome naval and Barak interceptors."},
    {"id": "nansen_frigate", "name": "Fridtjof Nansen-class", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 40, "aluminum": 10}, "production_time": 85,
     "special_flags": ["norway", "frigate", "aegis", "twenty_twenties"],
     "description": "Norwegian Aegis frigate with NSM anti-ship missiles."},
    {"id": "visby_stealth_corvette", "name": "Visby-class Stealth", "category": "Armor", "tier": 5,
     "armor_bonus": 22, "top_armor_bonus": 15, "reliability_bonus": 6,
     "cost": {"steel": 28, "electronics": 32, "aluminum": 18}, "production_time": 95,
     "special_flags": ["sweden", "corvette", "stealth", "twenty_twenties"],
     "description": "Swedish composite stealth corvette for Baltic operations."},
    {"id": "sigma_frigate_export", "name": "SIGMA Frigate Export", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 10, "electronics": 30, "aluminum": 10}, "production_time": 78,
     "special_flags": ["netherlands", "export", "frigate", "twenty_twenties"],
     "description": "Damen SIGMA modular frigate family. Indonesia, Mexico, and others."},
    {"id": "moudge_iran_frigate", "name": "Moudge-class Frigate", "category": "Sensors", "tier": 5,
     "reliability_bonus": 4,
     "cost": {"steel": 12, "electronics": 28, "aluminum": 8}, "production_time": 80,
     "special_flags": ["iran", "frigate", "twenty_twenties"],
     "description": "Iranian domestically built frigate derived from Alvand class."},
    {"id": "istanbul_class_turkey", "name": "Istanbul-class Frigate", "category": "Sensors", "tier": 6,
     "reliability_bonus": 7,
     "cost": {"steel": 12, "electronics": 36, "aluminum": 10}, "production_time": 86,
     "special_flags": ["turkey", "frigate", "twenty_twenties"],
     "description": "Turkish MILGEM-derived frigate with indigenous combat system."},
    {"id": "tamandare_class_brazil", "name": "Tamandaré-class Frigate", "category": "Armor", "tier": 5,
     "armor_bonus": 30, "top_armor_bonus": 20, "reliability_bonus": 6,
     "cost": {"steel": 40, "electronics": 28, "aluminum": 12}, "production_time": 105,
     "special_flags": ["brazil", "frigate", "twenty_twenties"],
     "description": "Brazilian Tamandaré (MEKO) frigate program with European systems."},
    {"id": "miecznik_poland_planned", "name": "Miecznik Frigate (Planned)", "category": "Sensors", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 11, "electronics": 35, "aluminum": 10}, "production_time": 88,
     "special_flags": ["poland", "frigate", "planned", "twenty_twenties"],
     "description": "Polish triple frigate program based on Miecznik/Babcock Arrowhead 140."},
    {"id": "reformador_mexico", "name": "Reformador-class", "category": "Sensors", "tier": 5,
     "reliability_bonus": 5,
     "cost": {"steel": 10, "electronics": 28, "aluminum": 8}, "production_time": 75,
     "special_flags": ["mexico", "frigate", "twenty_twenties"],
     "description": "Mexican SIGMA 10514 long-range patrol frigate."},
    {"id": "al_riyadh_saudi", "name": "Al Riyadh-class", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 11, "electronics": 32, "aluminum": 9}, "production_time": 80,
     "special_flags": ["saudi_arabia", "frigate", "twenty_twenties"],
     "description": "Saudi La Fayette-derived frigate with French combat systems."},
    {"id": "gyurza_patrol_ukr", "name": "Gyurza-M Patrol", "category": "NavalGun", "tier": 4,
     "soft_attack": 18, "hard_attack": 22, "piercing": 20, "anti_ship": 35,
     "cost": {"steel": 8, "electronics": 15, "explosives": 6}, "production_time": 55,
     "special_flags": ["ukraine", "patrol", "riverine", "twenty_twenties"],
     "description": "Ukrainian armored patrol boat for river and coastal defense."},
    {"id": "ivar_huitfeldt_denmark", "name": "Iver Huitfeldt-class", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 11, "electronics": 38, "aluminum": 10}, "production_time": 84,
     "special_flags": ["denmark", "frigate", "twenty_twenties"],
     "description": "Danish air-defense frigate with Mk 41 VLS and Harpoon."},
    {"id": "hamina_missile_boat", "name": "Hamina-class FAC", "category": "SecondaryWeapon", "tier": 5,
     "soft_attack": 28, "hard_attack": 32, "piercing": 25, "anti_ship": 70,
     "cost": {"steel": 8, "electronics": 25, "explosives": 12}, "production_time": 70,
     "special_flags": ["finland", "missile_boat", "twenty_twenties"],
     "description": "Finnish fast attack craft with Gabriel anti-ship missiles."},
    {"id": "anzac_frigate_nzl", "name": "Anzac Frigate", "category": "Sensors", "tier": 5,
     "reliability_bonus": 7,
     "cost": {"steel": 10, "electronics": 32, "aluminum": 9}, "production_time": 80,
     "special_flags": ["new_zealand", "australia", "frigate", "twenty_twenties"],
     "description": "Anzac-class frigate operated by Australia and New Zealand."},
    {"id": "martadinata_indonesia", "name": "Martadinata-class", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 10, "electronics": 30, "aluminum": 9}, "production_time": 78,
     "special_flags": ["indonesia", "frigate", "twenty_twenties"],
     "description": "Indonesian SIGMA 10514 frigate."},
    {"id": "dw3000f_thailand", "name": "DW3000F Frigate", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 10, "electronics": 30, "aluminum": 9}, "production_time": 76,
     "special_flags": ["thailand", "frigate", "twenty_twenties"],
     "description": "Thai DW3000F frigate with South Korean-derived systems."},
    {"id": "maharaja_lela_malaysia", "name": "Maharaja Lela-class", "category": "Sensors", "tier": 6,
     "reliability_bonus": 7,
     "cost": {"steel": 12, "electronics": 34, "aluminum": 10}, "production_time": 85,
     "special_flags": ["malaysia", "frigate", "twenty_twenties"],
     "description": "Malaysian LCS frigate with reduced radar cross-section."},
    {"id": "knud_rasmussen_patrol", "name": "Knud Rasmussen OPV", "category": "Armor", "tier": 4,
     "armor_bonus": 18, "top_armor_bonus": 12, "reliability_bonus": 8,
     "cost": {"steel": 22, "electronics": 18, "aluminum": 8}, "production_time": 65,
     "special_flags": ["greenland", "denmark", "patrol", "twenty_twenties"],
     "description": "Danish Arctic offshore patrol vessel operated in Greenland."},
    {"id": "independence_lcs_sgp", "name": "Independence LCS (Export)", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 8, "electronics": 32, "aluminum": 14}, "production_time": 72,
     "special_flags": ["singapore", "lcs", "twenty_twenties"],
     "description": "Littoral combat ship style multi-role vessel for Singapore."},
    {"id": "de_zeven_provincien", "name": "De Zeven Provinciën", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 12, "electronics": 42, "aluminum": 10}, "production_time": 88,
     "special_flags": ["netherlands", "frigate", "twenty_twenties"],
     "description": "Dutch air-defense frigate with APAR radar and SM-2."},
    {"id": "coast_guard_patrol_minor", "name": "Coastal Patrol Package", "category": "NavalGun", "tier": 3,
     "soft_attack": 12, "hard_attack": 14, "piercing": 15, "anti_ship": 25,
     "cost": {"steel": 5, "electronics": 10, "explosives": 4}, "production_time": 40,
     "special_flags": ["patrol", "export", "twenty_twenties"],
     "description": "Light patrol craft for minor navies and coast guards."},
]


def warship_2026(
    id_: str, name: str, family: str, loadout: dict, nation_tags: list[str],
    archetype: str = "destroyer", size: str = "Heavy", days: int = 165,
    crew: int = 280, training: int = 36,
    stats: dict | None = None,
) -> dict:
    base = stats or {
        "speed": 30, "reliability": 80, "fuel_consumption": 65,
        "supply_need": 80, "armor": 38, "deck_armor": 24, "hardness": 68,
    }
    if archetype == "corvette" or size == "Light":
        base = stats or {
            "speed": 32, "reliability": 78, "fuel_consumption": 40,
            "supply_need": 50, "armor": 25, "deck_armor": 16, "hardness": 52,
        }
    return {
        "id": id_, "name": name, "design_family": family,
        "base_type": "Naval", "size_category": size,
        "visual_archetype": archetype,
        "crew_required": crew, "base_training_level": training,
        "max_experience_level": 100, "base_production_days": days,
        "base_stats": base,
        "slots": {
            "NavalGun": {"max": 1}, "SecondaryWeapon": {"max": 2},
            "Engine": {"max": 1}, "Sensors": {"max": 2}, "AntiAir": {"max": 2},
            "Armor": {"max": 1},
        },
        "module_loadout": loadout,
        "unlock_tech": T2026 + nation_tags,
        "can_mount_drones": False,
        "is_vehicle": True,
    }


def sub_2026(id_: str, name: str, family: str, loadout: dict, nation_tags: list[str], **kw) -> dict:
    base = kw.get("stats", {
        "speed": 22, "reliability": 78, "fuel_consumption": 35,
        "supply_need": 45, "armor": 35, "hardness": 48,
    })
    return {
        "id": id_, "name": name, "design_family": family,
        "base_type": "Submarine", "size_category": kw.get("size", "Medium"),
        "visual_archetype": "submarine",
        "crew_required": kw.get("crew", 45), "base_training_level": kw.get("training", 36),
        "max_experience_level": 100, "base_production_days": kw.get("days", 140),
        "base_stats": base,
        "slots": {
            "MainWeapon": {"max": 2}, "SecondaryWeapon": {"max": 2},
            "Engine": {"max": 1}, "Sensors": {"max": 2}, "Armor": {"max": 1},
        },
        "module_loadout": loadout,
        "unlock_tech": T2026 + nation_tags,
        "can_mount_drones": False,
        "is_vehicle": True,
    }


TEMPLATES: list[dict] = [
    # ─── Major powers · destroyers / cruisers ────────────────────────────────────
    warship_2026("arleigh_burke_class_2026", "Arleigh Burke-class", "us_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "aegis_spy1_radar", "AntiAir": "aegis_bmd_package",
                  "Engine": "geared_steam_turbine_60k"},
                 ["us_naval_2026", "destroyer"], days=175, crew=320, training=38),
    warship_2026("constellation_class_2026", "Constellation-class", "us_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "aegis_spy1_radar", "Armor": "constellation_ffg_package",
                  "AntiAir": "aegis_bmd_package"},
                 ["us_naval_2026", "frigate"], size="Medium", days=155, crew=200),
    warship_2026("type055_class_2026", "Type 055 Renhai", "chinese_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "type055_cruiser_vls",
                  "Sensors": "type055_destroyer_vls", "AntiAir": "hq9b_sam",
                  "Engine": "geared_steam_turbine_60k"},
                 ["chinese_naval_2026", "cruiser"], days=210, crew=280, training=37),
    warship_2026("type052d_class_2026", "Type 052D Luyang III", "chinese_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "type055_destroyer_vls",
                  "Sensors": "type055_destroyer_vls", "AntiAir": "hq9b_sam"},
                 ["chinese_naval_2026", "destroyer"], days=165, crew=260),
    warship_2026("admiral_gorshkov_2026", "Admiral Gorshkov-class", "russian_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "kalibr_vls_sub",
                  "Sensors": "gorshkov_frigate_suite", "AntiAir": "s400_triumf"},
                 ["russian_naval_2026", "frigate"], days=170, crew=210),
    warship_2026("baden_wurttemberg_2026", "Baden-Württemberg-class", "german_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "iris_t_slm",
                  "Sensors": "fremm_frigate_suite", "Armor": "baden_wurttemberg_f125",
                  "AntiAir": "iris_t_slm"},
                 ["german_naval_2026", "frigate"], size="Medium", days=160, crew=120),
    warship_2026("type45_daring_2026", "Type 45 Daring", "uk_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "aster30_sam",
                  "Sensors": "sea_viper_sam", "AntiAir": "sea_viper_sam"},
                 ["uk_naval_2026", "destroyer"], days=170, crew=190, training=37),
    warship_2026("type26_frigate_2026", "Type 26 Frigate", "uk_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "type26_frigate_package", "AntiAir": "sea_viper_sam"},
                 ["uk_naval_2026", "frigate"], size="Medium", days=150, crew=118),
    warship_2026("fremm_frigate_2026", "FREMM Frigate", "french_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "fremm_frigate_suite", "AntiAir": "aster30_sam"},
                 ["french_naval_2026", "frigate"], size="Medium", days=158, crew=108),
    warship_2026("fremm_italy_2026", "FREMM (Italy)", "italian_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "fremm_frigate_suite", "AntiAir": "aster30_sam"},
                 ["italian_naval_2026", "frigate"], size="Medium", days=158, crew=110),
    warship_2026("f100_spain_2026", "Álvaro de Bazán-class", "spanish_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "f100_aegis_spain", "AntiAir": "aegis_bmd_package"},
                 ["spanish_naval_2026", "frigate"], days=162, crew=200),
    warship_2026("maya_class_2026", "Maya-class", "japanese_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "maya_class_aegis_japan", "AntiAir": "aegis_bmd_package"},
                 ["japanese_naval_2026", "destroyer"], days=172, crew=300, training=38),
    warship_2026("kolkata_class_2026", "Kolkata-class", "indian_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "brahmos_air_launched",
                  "Sensors": "kolkata_class_destroyer", "AntiAir": "barak8_sam"},
                 ["indian_naval_2026", "destroyer"], days=168, crew=290, training=36),
    warship_2026("sejong_class_2026", "Sejong the Great-class", "korean_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "sejong_kdx3_aegis", "AntiAir": "aegis_bmd_package"},
                 ["korean_naval_2026", "destroyer"], days=175, crew=300, training=38),

    # ─── Middle tier NATO / allies ───────────────────────────────────────────────
    warship_2026("halifax_class_2026", "Halifax-class", "canadian_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "harpoon_sub_launch",
                  "Sensors": "halifax_class_system", "AntiAir": "mim23_hawk_sam"},
                 ["canadian_naval_2026", "frigate"], size="Medium", days=155, crew=225),
    warship_2026("hobart_class_2026", "Hobart-class", "australian_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "hobart_auk_system", "AntiAir": "aegis_bmd_package"},
                 ["australian_naval_2026", "destroyer"], days=168, crew=186),
    warship_2026("nansen_class_2026", "Fridtjof Nansen-class", "norwegian_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "nansen_frigate", "AntiAir": "aegis_bmd_package"},
                 ["norwegian_naval_2026", "frigate"], size="Medium", days=148, crew=120),
    warship_2026("ivar_huitfeldt_2026", "Iver Huitfeldt-class", "danish_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "ivar_huitfeldt_denmark", "AntiAir": "mim23_hawk_sam"},
                 ["danish_naval_2026", "frigate"], size="Medium", days=145, crew=115),
    warship_2026("de_zeven_provincien_2026", "De Zeven Provinciën-class", "dutch_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "de_zeven_provincien", "AntiAir": "aster30_sam"},
                 ["dutch_naval_2026", "frigate"], days=160, crew=230),
    warship_2026("visby_class_2026", "Visby-class", "swedish_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "harpoon_sub_launch",
                  "Sensors": "aesa_radar_gen1", "Armor": "visby_stealth_corvette",
                  "AntiAir": "iris_t_slm"},
                 ["swedish_naval_2026", "corvette"], size="Light", days=120, crew=45),
    warship_2026("hamina_class_2026", "Hamina-class", "finnish_naval_2026",
                 {"SecondaryWeapon": "hamina_missile_boat", "Sensors": "aesa_radar_gen1",
                  "AntiAir": "iris_t_slm"},
                 ["finnish_naval_2026", "corvette"], size="Light", days=95, crew=30, training=34),
    warship_2026("anzac_class_2026", "Anzac-class", "new_zealand_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "harpoon_sub_launch",
                  "Sensors": "anzac_frigate_nzl", "AntiAir": "mim23_hawk_sam"},
                 ["new_zealand_naval_2026", "frigate"], size="Medium", days=140, crew=160),
    warship_2026("istanbul_class_2026", "Istanbul-class", "turkish_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "istanbul_class_turkey", "AntiAir": "mim23_hawk_sam"},
                 ["turkish_naval_2026", "frigate"], size="Medium", days=150, crew=125),
    warship_2026("poland_miecznik_2026", "Miecznik-class (Planned)", "polish_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "mk41_vls_destroyer",
                  "Sensors": "miecznik_poland_planned", "AntiAir": "iris_t_slm"},
                 ["polish_naval_2026", "frigate"], size="Medium", days=155, crew=100, training=34),

    # ─── Middle East / regional ──────────────────────────────────────────────────
    warship_2026("saar6_class_2026", "Sa'ar 6-class", "israeli_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "barak8_sam",
                  "Sensors": "aesa_radar_gen1", "Armor": "saar6_corvette",
                  "AntiAir": "iron_dome_interceptor"},
                 ["israeli_naval_2026", "corvette"], size="Medium", days=130, crew=70, training=38),
    warship_2026("al_riyadh_class_2026", "Al Riyadh-class", "saudi_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "al_riyadh_saudi", "AntiAir": "mim23_hawk_sam"},
                 ["saudi_naval_2026", "frigate"], size="Medium", days=145, crew=95),
    warship_2026("moudge_class_2026", "Moudge-class", "iranian_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "moudge_iran_frigate", "AntiAir": "tor_sam"},
                 ["iranian_naval_2026", "frigate"], size="Medium", days=140, crew=140, training=32),
    warship_2026("fremm_egypt_2026", "FREMM (Egypt)", "egyptian_naval_2026",
                 {"NavalGun": "uk_4_5inch_mk6", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "fremm_frigate_suite", "AntiAir": "mica_air_missile"},
                 ["egyptian_naval_2026", "frigate"], size="Medium", days=150, crew=125),

    # ─── Americas / Asia-Pacific ─────────────────────────────────────────────────
    warship_2026("tamandare_class_2026", "Tamandaré-class", "brazilian_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "tamandare_class_brazil", "Armor": "tamandare_class_brazil",
                  "AntiAir": "mim23_hawk_sam"},
                 ["brazilian_naval_2026", "frigate"], size="Medium", days=155, crew=115),
    warship_2026("reformador_class_2026", "Reformador-class", "mexican_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "reformador_mexico", "AntiAir": "mim23_hawk_sam"},
                 ["mexican_naval_2026", "frigate"], size="Medium", days=130, crew=90),
    warship_2026("martadinata_class_2026", "Martadinata-class", "indonesian_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "martadinata_indonesia", "AntiAir": "mim23_hawk_sam"},
                 ["indonesian_naval_2026", "frigate"], size="Medium", days=125, crew=95),
    warship_2026("dw3000f_thailand_2026", "DW3000F", "thai_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "dw3000f_thailand", "AntiAir": "mim23_hawk_sam"},
                 ["thai_naval_2026", "frigate"], size="Medium", days=125, crew=100),
    warship_2026("maharaja_lela_2026", "Maharaja Lela-class", "malaysian_naval_2026",
                 {"NavalGun": "ger_15cm_tb", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "maharaja_lela_malaysia", "AntiAir": "mim23_hawk_sam"},
                 ["malaysian_naval_2026", "frigate"], size="Medium", days=130, crew=105),
    warship_2026("independence_lcs_sgp_2026", "Independence-class LCS", "singapore_naval_2026",
                 {"SecondaryWeapon": "harpoon_sub_launch", "Sensors": "independence_lcs_sgp",
                  "AntiAir": "barak8_sam"},
                 ["singapore_naval_2026", "corvette"], size="Light", days=110, crew=75, training=37),

    # ─── Smaller / patrol navies (scenario nations) ──────────────────────────────
    warship_2026("gyurza_class_2026", "Gyurza-M-class", "ukrainian_naval_2026",
                 {"NavalGun": "gyurza_patrol_ukr", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "aesa_radar_gen1"},
                 ["ukrainian_naval_2026", "patrol"], size="Light", days=80, crew=35, training=32,
                 stats={"speed": 28, "reliability": 70, "fuel_consumption": 20, "supply_need": 25,
                        "armor": 15, "deck_armor": 8, "hardness": 40}),
    warship_2026("knud_rasmussen_2026", "Knud Rasmussen-class", "greenland_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "Sensors": "knud_rasmussen_patrol",
                  "Armor": "knud_rasmussen_patrol"},
                 ["greenland_naval_2026", "danish_naval_2026", "patrol"], size="Light",
                 days=70, crew=25, training=30),
    warship_2026("iceland_patrol_2026", "Þór-class OPV", "icelandic_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "Sensors": "aesa_radar_gen1"},
                 ["icelandic_naval_2026", "patrol"], size="Light", days=65, crew=20, training=28),
    warship_2026("panama_patrol_2026", "Panama Coast Guard", "panamanian_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "Sensors": "coast_guard_patrol_minor"},
                 ["panamanian_naval_2026", "patrol"], size="Light", days=55, crew=18),
    warship_2026("iraq_patrol_2026", "Fatah-class Patrol", "iraqi_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "coast_guard_patrol_minor"},
                 ["iraqi_naval_2026", "patrol"], size="Light", days=60, crew=25, training=30),
    warship_2026("syria_patrol_2026", "Tartus Patrol Craft", "syrian_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "Sensors": "naval_fire_control_mk37"},
                 ["syrian_naval_2026", "patrol"], size="Light", days=50, crew=20, training=28,
                 stats={"speed": 26, "reliability": 55, "fuel_consumption": 18, "supply_need": 22,
                        "armor": 10, "deck_armor": 6, "hardness": 35}),
    warship_2026("nigeria_patrol_2026", "Okpoku-class OPV", "nigerian_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "Sensors": "coast_guard_patrol_minor"},
                 ["nigerian_naval_2026", "patrol"], size="Light", days=58, crew=22),
    warship_2026("colombia_frigate_2026", "Almirante Padilla-class", "colombian_naval_2026",
                 {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "exocet_sm39",
                  "Sensors": "sigma_frigate_export", "AntiAir": "mim23_hawk_sam"},
                 ["colombian_naval_2026", "frigate"], size="Medium", days=120, crew=95),
    warship_2026("azerbai_patrol_2026", "Kalkan-class Patrol", "azerbaijani_naval_2026",
                 {"NavalGun": "coast_guard_patrol_minor", "Sensors": "aesa_radar_gen1"},
                 ["azerbaijani_naval_2026", "patrol"], size="Light", days=52, crew=20),

    # ─── 2026 diesel / AIP submarines (nations without SSBN focus) ───────────────
    sub_2026("type212_germany_2026", "Type 212A (Germany)", "german_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
              "Engine": "fuel_cell_aip_212", "Sensors": "optronic_mast", "Armor": "pressure_hull_fleet"},
             ["german_naval_2026", "submarine"], crew=27, days=140),
    sub_2026("kalvari_india_2026", "Kalvari-class", "indian_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "exocet_sm39",
              "Engine": "man_m6v40_uboat_diesel", "Armor": "anechoic_tiles"},
             ["indian_naval_2026", "submarine"], crew=35, days=125),
    sub_2026("gotland_sweden_2026", "Gotland-class", "swedish_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
              "Engine": "stirling_aip_engine", "Sensors": "passive_sonar_ww2"},
             ["swedish_naval_2026", "submarine"], crew=25, days=118),
    sub_2026("collins_australia_2026", "Collins-class", "australian_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
              "Engine": "man_m6v40_uboat_diesel", "Sensors": "towed_array_sonar"},
             ["australian_naval_2026", "submarine"], crew=42, days=165),
    sub_2026("kilo_turkey_2026", "Improved Kilo (Turkey)", "turkish_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "kalibr_vls_sub",
              "Engine": "man_m6v40_uboat_diesel", "Armor": "anechoic_tiles"},
             ["turkish_naval_2026", "submarine"], crew=52, days=130),
    sub_2026("orp_orzel_poland_2026", "Orka-class (Planned)", "polish_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
              "Engine": "fuel_cell_aip_212", "Sensors": "optronic_mast"},
             ["polish_naval_2026", "submarine", "planned"], crew=30, days=135),
    sub_2026("saab_kockums_brazil_2026", "Riachuelo-class", "brazilian_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "black_shark_torpedo",
              "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2"},
             ["brazilian_naval_2026", "submarine"], crew=35, days=128),
    sub_2026("israeli_dolphin_2026", "Dolphin-class", "israeli_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "harpoon_sub_launch",
              "Engine": "fuel_cell_aip_212", "Sensors": "passive_sonar_ww2"},
             ["israeli_naval_2026", "submarine"], crew=35, days=140),
    sub_2026("kss3_korea_2026", "KSS-III", "korean_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "cj10_china_cruise",
              "Engine": "fuel_cell_aip_212", "Sensors": "flank_array_sonar", "Cargo": "vls_missile_compartment"},
             ["korean_naval_2026", "submarine"], size="Heavy", crew=50, days=175),
    sub_2026("soryu_japan_2026", "Taigei-class", "japanese_sub_2026",
             {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
              "Engine": "fuel_cell_aip_212", "Sensors": "optronic_mast"},
             ["japanese_naval_2026", "submarine"], crew=70, days=155),
]


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing_m = {p.stem for p in MODULES_DIR.glob("*.json")}
    existing_t = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    mc = tc = 0
    for mod in MODULES:
        if mod["id"] in existing_m:
            continue
        path = MODULES_DIR / f"{mod['id']}.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        mc += 1
        print(f"  + module {mod['id']}.json")
    for tpl in TEMPLATES:
        if tpl["id"] in existing_t:
            continue
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        tc += 1
        print(f"  + template {tpl['id']}.json")
    mods = {p.stem for p in MODULES_DIR.glob("*.json")}
    errs = []
    for p in TEMPLATES_DIR.glob("*.json"):
        try:
            d = json.loads(p.read_text())
        except json.JSONDecodeError:
            continue
        for slot, mid in d.get("module_loadout", {}).items():
            if mid and mid not in mods:
                errs.append(f"{p.name}: {slot} -> {mid}")
    print(f"\n2026 naval fleet: {mc} modules, {tc} templates. Missing refs: {len(errs)}")
    for e in errs:
        print(f"  ! {e}")


if __name__ == "__main__":
    main()
