#!/usr/bin/env python3
"""Fleet and escort carrier templates using specialized equipment modules."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    {
        "id": "essex_class_carrier",
        "name": "Essex-class Carrier",
        "design_family": "us_naval_ww2",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "carrier",
        "crew_required": 2800,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 280,
        "base_stats": {
            "speed": 30,
            "reliability": 82,
            "fuel_consumption": 95,
            "supply_need": 120,
            "armor": 28,
            "deck_armor": 22,
            "hardness": 62,
        },
        "slots": {
            "Armor": {"max": 1},
            "Engine": {"max": 1},
            "Cargo": {"max": 1},
            "Sensors": {"max": 2},
            "AntiAir": {"max": 2},
        },
        "module_loadout": {
            "Armor": "carrier_wooden_flight_deck",
            "Engine": "carrier_boiler_yarrow",
            "Cargo": "carrier_air_wing_bunker",
            "Sensors": "sk_surface_radar",
            "AntiAir": "carrier_aa_bofors_40mm",
        },
        "unlock_tech": ["us_carriers", "fleet_carriers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "yorktown_class_carrier",
        "name": "Yorktown-class Carrier",
        "design_family": "us_naval_ww2",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "carrier",
        "crew_required": 2200,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 240,
        "base_stats": {
            "speed": 32,
            "reliability": 75,
            "fuel_consumption": 88,
            "supply_need": 105,
            "armor": 26,
            "deck_armor": 20,
            "hardness": 58,
        },
        "slots": {
            "Armor": {"max": 1},
            "Engine": {"max": 1},
            "Cargo": {"max": 1},
            "Sensors": {"max": 2},
            "AntiAir": {"max": 2},
        },
        "module_loadout": {
            "Armor": "carrier_wooden_flight_deck",
            "Engine": "geared_steam_turbine_60k",
            "Cargo": "carrier_air_wing_bunker",
            "Sensors": "sg_surface_radar",
            "AntiAir": "carrier_aa_20mm_oerlikon",
        },
        "unlock_tech": ["us_carriers", "interwar_naval"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "illustrious_class_carrier",
        "name": "Illustrious-class Carrier",
        "design_family": "uk_naval_ww2",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "carrier",
        "crew_required": 1600,
        "base_training_level": 33,
        "max_experience_level": 100,
        "base_production_days": 260,
        "base_stats": {
            "speed": 28,
            "reliability": 80,
            "fuel_consumption": 82,
            "supply_need": 98,
            "armor": 42,
            "deck_armor": 48,
            "hardness": 65,
        },
        "slots": {
            "Armor": {"max": 1},
            "Engine": {"max": 1},
            "Cargo": {"max": 1},
            "Sensors": {"max": 2},
            "AntiAir": {"max": 2},
        },
        "module_loadout": {
            "Armor": "carrier_armored_flight_deck",
            "Engine": "carrier_boiler_yarrow",
            "Cargo": "carrier_air_wing_bunker",
            "Sensors": "type281_surface_radar",
            "AntiAir": "carrier_aa_bofors_40mm",
        },
        "unlock_tech": ["uk_carriers", "armored_carriers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "akagi_carrier",
        "name": "Akagi",
        "design_family": "japanese_naval_ww2",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "carrier",
        "crew_required": 2000,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 300,
        "base_stats": {
            "speed": 31,
            "reliability": 72,
            "fuel_consumption": 90,
            "supply_need": 110,
            "armor": 30,
            "deck_armor": 18,
            "hardness": 60,
        },
        "slots": {
            "Armor": {"max": 1},
            "Engine": {"max": 1},
            "Cargo": {"max": 1},
            "Sensors": {"max": 1},
            "AntiAir": {"max": 2},
        },
        "module_loadout": {
            "Armor": "carrier_wooden_flight_deck",
            "Engine": "geared_steam_turbine_60k",
            "Cargo": "carrier_air_wing_bunker",
            "Sensors": "naval_radar_type22",
            "AntiAir": "carrier_aa_20mm_oerlikon",
        },
        "unlock_tech": ["japanese_carriers", "kido_butai"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "graf_zeppelin_carrier",
        "name": "Graf Zeppelin",
        "design_family": "german_naval_ww2",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "carrier",
        "crew_required": 1760,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 320,
        "base_stats": {
            "speed": 33,
            "reliability": 65,
            "fuel_consumption": 85,
            "supply_need": 100,
            "armor": 35,
            "deck_armor": 25,
            "hardness": 62,
        },
        "slots": {
            "Armor": {"max": 1},
            "Engine": {"max": 1},
            "Cargo": {"max": 1},
            "Sensors": {"max": 1},
            "AntiAir": {"max": 2},
        },
        "module_loadout": {
            "Armor": "carrier_island_superstructure",
            "Engine": "geared_steam_turbine_60k",
            "Cargo": "carrier_air_wing_bunker",
            "Sensors": "wurzburg_ground_radar",
            "AntiAir": "flakvierling_38_quad",
        },
        "unlock_tech": ["german_carriers", "german_paper_naval"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "casablanca_escort_carrier",
        "name": "Casablanca-class CVE",
        "design_family": "us_naval_ww2",
        "base_type": "Naval",
        "size_category": "Medium",
        "visual_archetype": "carrier",
        "crew_required": 860,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {
            "speed": 19,
            "reliability": 70,
            "fuel_consumption": 55,
            "supply_need": 65,
            "armor": 18,
            "deck_armor": 14,
            "hardness": 45,
        },
        "slots": {
            "Cargo": {"max": 1},
            "Engine": {"max": 1},
            "Sensors": {"max": 1},
            "AntiAir": {"max": 1},
            "SecondaryWeapon": {"max": 1},
        },
        "module_loadout": {
            "Cargo": "escort_carrier_hanger",
            "Engine": "geared_steam_turbine_60k",
            "Sensors": "sonar_qcba",
            "AntiAir": "carrier_aa_20mm_oerlikon",
            "SecondaryWeapon": "mk24_fido_torpedo",
        },
        "unlock_tech": ["us_escort_carriers", "asw_aviation"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "fletcher_asw_destroyer",
        "name": "Fletcher-class (ASW Fit)",
        "design_family": "us_naval_ww2",
        "base_type": "Naval",
        "size_category": "Light",
        "visual_archetype": "destroyer",
        "crew_required": 320,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 125,
        "base_stats": {
            "speed": 34,
            "reliability": 78,
            "fuel_consumption": 45,
            "supply_need": 55,
            "armor": 22,
            "deck_armor": 12,
            "hardness": 55,
        },
        "slots": {
            "NavalGun": {"max": 2},
            "SecondaryWeapon": {"max": 2},
            "Engine": {"max": 1},
            "Sensors": {"max": 2},
        },
        "module_loadout": {
            "NavalGun": "us_5inch_38_gun",
            "SecondaryWeapon": "hedgehog_sprengbombe",
            "Engine": "geared_steam_turbine_60k",
            "Sensors": "sonar_gdcs",
        },
        "unlock_tech": ["us_destroyers", "asw_doctrine"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "p47d_ground_attack",
        "name": "P-47D (Ground Attack)",
        "design_family": "us_air_ww2",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 52,
        "base_stats": {
            "speed": 86,
            "reliability": 78,
            "fuel_consumption": 15,
            "supply_need": 12,
            "armor": 22,
            "hardness": 30,
        },
        "slots": {
            "MainWeapon": {"max": 2},
            "Engine": {"max": 1},
            "Sensors": {"max": 1},
        },
        "module_loadout": {
            "MainWeapon": "hvar_rocket",
            "Engine": "pratt_r2800_corsair",
            "Sensors": "scr_520_airborne_radar",
        },
        "unlock_tech": ["us_fighters", "ground_attack"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "avenger_asw_aircraft",
        "name": "TBF/TBM Avenger (ASW)",
        "design_family": "us_air_ww2",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "bomber",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 58,
        "base_stats": {
            "speed": 62,
            "reliability": 76,
            "fuel_consumption": 18,
            "supply_need": 14,
            "armor": 18,
            "hardness": 28,
        },
        "slots": {
            "MainWeapon": {"max": 1},
            "SecondaryWeapon": {"max": 1},
            "Engine": {"max": 1},
            "Sensors": {"max": 1},
        },
        "module_loadout": {
            "MainWeapon": "mk24_fido_torpedo",
            "SecondaryWeapon": "depth_charge_mk9",
            "Engine": "wasp_r1340_carrier_scout",
            "Sensors": "scr_520_airborne_radar",
        },
        "unlock_tech": ["us_naval_aviation", "asw_aviation"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if tpl["id"] in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\nCarrier/ASW templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
