#!/usr/bin/env python3
"""Generate unit template JSON files for Epochs of Ascendancy."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

# Each template: full dict matching UnitTemplate JSON schema
TEMPLATES: list[dict] = [
    # ═══ WWII · USA LAND ═══════════════════════════════════════════════════════
    {
        "id": "m4a3e8_sherman_medium",
        "name": "M4A3E8 Sherman (76 mm)",
        "design_family": "us_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 72,
        "base_stats": {"speed": 36, "reliability": 76, "fuel_consumption": 9, "supply_need": 13,
                      "armor": 52, "top_armor": 26, "hardness": 83},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "76mm_m1_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "ford_gaa_v8_engine", "Armor": "m4_applique_armor",
                         "Communications": "scr_508_radio"},
        "unlock_tech": ["medium_tanks", "us_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m26_pershing_heavy",
        "name": "M26 Pershing",
        "design_family": "us_armored_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 5,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 30, "reliability": 70, "fuel_consumption": 12, "supply_need": 18,
                      "armor": 62, "top_armor": 30, "hardness": 90},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "90mm_m3_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "ford_gaa_v8_engine", "Armor": "m4_applique_armor",
                         "Communications": "scr_508_radio"},
        "unlock_tech": ["heavy_tanks", "us_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWII · UK LAND ════════════════════════════════════════════════════════
    {
        "id": "churchill_mk7_heavy",
        "name": "Churchill Mk VII",
        "design_family": "uk_armored_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 5,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 88,
        "base_stats": {"speed": 22, "reliability": 68, "fuel_consumption": 11, "supply_need": 16,
                      "armor": 58, "top_armor": 30, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "qf_75mm_roqf", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "bedford_twin_six_engine", "Armor": "churchill_cast_armor",
                         "Communications": "wireless_set_no19"},
        "unlock_tech": ["heavy_tanks", "uk_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "cromwell_mk4_medium",
        "name": "Cromwell Mk IV",
        "design_family": "uk_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 26,
        "max_experience_level": 100,
        "base_production_days": 68,
        "base_stats": {"speed": 40, "reliability": 74, "fuel_consumption": 8, "supply_need": 12,
                      "armor": 48, "top_armor": 24, "hardness": 80},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "qf_6pdr_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "rolls_royce_meteor", "Communications": "wireless_set_no19"},
        "unlock_tech": ["medium_tanks", "uk_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWII · GERMANY LAND ═══════════════════════════════════════════════════
    {
        "id": "panzer_iv_h_medium",
        "name": "Panzer IV Ausf. H",
        "design_family": "german_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 32, "reliability": 66, "fuel_consumption": 10, "supply_need": 14,
                      "armor": 50, "top_armor": 24, "hardness": 81},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_40_75mm_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "man_maybach_600_engine", "Armor": "schurzen_armor_skirts",
                         "Communications": "fug_16_zyf_radio"},
        "unlock_tech": ["medium_tanks", "german_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "panzer_iii_j_medium",
        "name": "Panzer III Ausf. J",
        "design_family": "german_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 24,
        "max_experience_level": 100,
        "base_production_days": 62,
        "base_stats": {"speed": 34, "reliability": 70, "fuel_consumption": 9, "supply_need": 12,
                      "armor": 42, "top_armor": 20, "hardness": 76},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_38_50mm_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "maybach_hl120_trm", "Communications": "fug_16_zyf_radio"},
        "unlock_tech": ["medium_tanks", "german_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "panther_g_medium",
        "name": "Panther Ausf. G",
        "design_family": "german_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 92,
        "base_stats": {"speed": 35, "reliability": 62, "fuel_consumption": 11, "supply_need": 16,
                      "armor": 56, "top_armor": 28, "hardness": 86},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_42_75mm_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "man_maybach_600_engine", "Armor": "schurzen_armor_skirts",
                         "Communications": "fug_16_zyf_radio"},
        "unlock_tech": ["medium_tanks", "german_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWII · USSR LAND ══════════════════════════════════════════════════════
    {
        "id": "t34_76_medium",
        "name": "T-34/76 Model 1942",
        "design_family": "soviet_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 26,
        "max_experience_level": 100,
        "base_production_days": 58,
        "base_stats": {"speed": 38, "reliability": 72, "fuel_consumption": 8, "supply_need": 11,
                      "armor": 44, "top_armor": 22, "hardness": 84},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "76mm_f34_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "v2_diesel_engine", "Armor": "t34_sloped_armor",
                         "Communications": "radio_71tk1"},
        "unlock_tech": ["medium_tanks", "soviet_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t34_85_medium",
        "name": "T-34/85",
        "design_family": "soviet_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 62,
        "base_stats": {"speed": 36, "reliability": 74, "fuel_consumption": 8, "supply_need": 12,
                      "armor": 46, "top_armor": 24, "hardness": 85},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "85mm_d5t_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "v2_diesel_engine", "Armor": "t34_sloped_armor",
                         "Communications": "radio_71tk1"},
        "unlock_tech": ["medium_tanks", "soviet_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "is2_heavy",
        "name": "IS-2 Model 1944",
        "design_family": "soviet_armored_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 98,
        "base_stats": {"speed": 28, "reliability": 64, "fuel_consumption": 13, "supply_need": 20,
                      "armor": 54, "top_armor": 30, "hardness": 92},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "122mm_d25t_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "mikulin_v12_engine", "Armor": "is2_heavy_armor",
                         "Communications": "radio_71tk1"},
        "unlock_tech": ["heavy_tanks", "soviet_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWII · JAPAN / ITALY / FRANCE LAND ═══════════════════════════════════
    {
        "id": "chi_nu_medium",
        "name": "Type 3 Chi-Nu",
        "design_family": "japanese_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 24,
        "max_experience_level": 100,
        "base_production_days": 65,
        "base_stats": {"speed": 30, "reliability": 66, "fuel_consumption": 9, "supply_need": 12,
                      "armor": 38, "top_armor": 18, "hardness": 74},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "type3_75mm_gun", "Engine": "mitsubishi_al_engine",
                         "Armor": "japanese_riveted_armor", "Communications": "type3_ku_radio"},
        "unlock_tech": ["medium_tanks", "japanese_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "p40_heavy_tank",
        "name": "P40 Heavy Tank",
        "design_family": "italian_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 22,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 28, "reliability": 58, "fuel_consumption": 10, "supply_need": 13,
                      "armor": 42, "top_armor": 20, "hardness": 76},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "75mm_ansaldo_l34_gun", "Engine": "spa_diesel_v8_engine",
                         "Armor": "italian_riveted_armor", "Communications": "rf2ca_radio"},
        "unlock_tech": ["medium_tanks", "italian_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "somua_s35_medium",
        "name": "SOMUA S35",
        "design_family": "french_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 22,
        "max_experience_level": 100,
        "base_production_days": 68,
        "base_stats": {"speed": 32, "reliability": 68, "fuel_consumption": 9, "supply_need": 12,
                      "armor": 46, "top_armor": 22, "hardness": 78},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 1}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "47mm_sa37_gun", "SecondaryWeapon": "coaxial_mg_mount",
                         "Engine": "renault_v6_engine", "Armor": "french_cast_armor",
                         "Communications": "er538_radio"},
        "unlock_tech": ["medium_tanks", "french_armored_ww2"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWII · AIR (additional) ═══════════════════════════════════════════════
    {
        "id": "spitfire_mk9_fighter",
        "name": "Spitfire Mk IX",
        "design_family": "uk_air_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 45,
        "base_stats": {"speed": 94, "reliability": 76, "fuel_consumption": 10, "supply_need": 8,
                      "armor": 18, "hardness": 26},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "hispano_mk2_cannon", "SecondaryWeapon": "browning_303_battery",
                         "Engine": "merlin_xx_engine", "Communications": "wireless_set_no19",
                         "Sensors": "mk14_gyro_sight"},
        "unlock_tech": ["uk_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "fw190a_fighter",
        "name": "Fw 190A-8",
        "design_family": "german_air_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 46,
        "base_stats": {"speed": 90, "reliability": 72, "fuel_consumption": 11, "supply_need": 8,
                      "armor": 20, "hardness": 28},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "mg151_20_cannon", "SecondaryWeapon": "mg17_machine_gun",
                         "Engine": "bmw_801_radial_engine", "Communications": "fug_16_zyf_radio"},
        "unlock_tech": ["german_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "p47d_thunderbolt",
        "name": "P-47D Thunderbolt",
        "design_family": "us_air_ww2",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 50,
        "base_stats": {"speed": 88, "reliability": 78, "fuel_consumption": 14, "supply_need": 10,
                      "armor": 22, "hardness": 30},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "m2_browning_gun_pod", "Engine": "pratt_whitney_r2800",
                         "Communications": "scr_522_radio"},
        "unlock_tech": ["us_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "p51d_mustang",
        "name": "P-51D Mustang",
        "design_family": "us_air_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 48,
        "base_stats": {"speed": 96, "reliability": 80, "fuel_consumption": 10, "supply_need": 8,
                      "armor": 16, "hardness": 24},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "m2_browning_gun_pod", "Engine": "packard_merlin_v1650",
                         "Communications": "scr_522_radio", "Sensors": "us_mark_iii_sight"},
        "unlock_tech": ["us_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "a6m_zero_fighter",
        "name": "A6M5 Zero",
        "design_family": "japanese_air_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 44,
        "base_stats": {"speed": 92, "reliability": 70, "fuel_consumption": 8, "supply_need": 7,
                      "armor": 12, "hardness": 22},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "type99_mk2_cannon", "SecondaryWeapon": "type97_7_7mm_gun",
                         "Engine": "sakae_radial_engine", "Communications": "type3_ku_radio"},
        "unlock_tech": ["japanese_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "il2_sturmovik",
        "name": "Il-2M Sturmovik",
        "design_family": "soviet_air_ww2",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "bomber",
        "crew_required": 2,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 52,
        "base_stats": {"speed": 68, "reliability": 74, "fuel_consumption": 11, "supply_need": 10,
                      "armor": 28, "hardness": 35},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "shvak_20mm_cannon", "SecondaryWeapon": "berezin_ub_gun",
                         "Engine": "ash82_radial_engine"},
        "unlock_tech": ["soviet_cas"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "lancaster_bomber",
        "name": "Avro Lancaster B Mk I",
        "design_family": "uk_air_ww2",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "bomber",
        "crew_required": 7,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 82,
        "base_stats": {"speed": 70, "reliability": 74, "fuel_consumption": 20, "supply_need": 18,
                      "armor": 28, "hardness": 32},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "uk_4000lb_bomb_load", "Engine": "merlin_xx_engine",
                         "Communications": "wireless_set_no19"},
        "unlock_tech": ["uk_heavy_bombers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWII · NAVAL ══════════════════════════════════════════════════════════
    {
        "id": "fletcher_class_destroyer",
        "name": "Fletcher-class Destroyer",
        "design_family": "us_naval_ww2",
        "base_type": "Naval",
        "size_category": "Light",
        "visual_archetype": "destroyer",
        "crew_required": 320,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 34, "reliability": 78, "fuel_consumption": 45, "supply_need": 55,
                      "armor": 22, "deck_armor": 12, "hardness": 55},
        "slots": {"NavalGun": {"max": 2}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"NavalGun": "us_5inch_38_gun", "SecondaryWeapon": "mk15_torpedo_tube",
                         "Engine": "us_parsons_turbine", "Armor": "naval_deck_armor_scheme",
                         "Communications": "scr_522_radio", "Sensors": "naval_fire_control_mk37"},
        "unlock_tech": ["us_destroyers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "queen_elizabeth_battleship",
        "name": "Queen Elizabeth-class Battleship",
        "design_family": "uk_naval_ww2",
        "base_type": "Naval",
        "size_category": "SuperHeavy",
        "visual_archetype": "battleship",
        "crew_required": 1200,
        "base_training_level": 35,
        "max_experience_level": 100,
        "base_production_days": 280,
        "base_stats": {"speed": 24, "reliability": 72, "fuel_consumption": 90, "supply_need": 120,
                      "armor": 55, "deck_armor": 28, "hardness": 82},
        "slots": {"NavalGun": {"max": 2}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"NavalGun": "uk_15inch_mk1", "Engine": "us_parsons_turbine",
                         "Armor": "naval_belt_armor_scheme", "Sensors": "naval_fire_control_mk37",
                         "Communications": "wireless_set_no19"},
        "unlock_tech": ["uk_battleships"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "bismarck_battleship",
        "name": "Bismarck",
        "design_family": "german_naval_ww2",
        "base_type": "Naval",
        "size_category": "SuperHeavy",
        "visual_archetype": "battleship",
        "crew_required": 2200,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 300,
        "base_stats": {"speed": 28, "reliability": 68, "fuel_consumption": 95, "supply_need": 130,
                      "armor": 58, "deck_armor": 30, "hardness": 84},
        "slots": {"NavalGun": {"max": 2}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"NavalGun": "ger_15inch_skc34", "SecondaryWeapon": "g7a_torpedo",
                         "Engine": "german_wagner_turbine", "Armor": "naval_belt_armor_scheme",
                         "Communications": "fug_16_zyf_radio", "Sensors": "naval_fire_control_mk37"},
        "unlock_tech": ["german_battleships"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "yamato_battleship",
        "name": "Yamato",
        "design_family": "japanese_naval_ww2",
        "base_type": "Naval",
        "size_category": "SuperHeavy",
        "visual_archetype": "battleship",
        "crew_required": 2700,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 360,
        "base_stats": {"speed": 26, "reliability": 70, "fuel_consumption": 110, "supply_need": 150,
                      "armor": 65, "deck_armor": 35, "hardness": 90},
        "slots": {"NavalGun": {"max": 2}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Communications": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"NavalGun": "ijn_18inch_type94", "SecondaryWeapon": "type93_long_lance",
                         "Engine": "ijn_kampon_turbine", "Armor": "naval_deck_armor_scheme",
                         "Communications": "type3_ku_radio", "Sensors": "naval_radar_type22"},
        "unlock_tech": ["japanese_battleships"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "us_northampton_cruiser",
        "name": "Northampton-class Heavy Cruiser",
        "design_family": "us_naval_ww2",
        "base_type": "Naval",
        "size_category": "Heavy",
        "visual_archetype": "cruiser",
        "crew_required": 700,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 200,
        "base_stats": {"speed": 30, "reliability": 74, "fuel_consumption": 60, "supply_need": 80,
                      "armor": 38, "deck_armor": 18, "hardness": 68},
        "slots": {"NavalGun": {"max": 2}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"NavalGun": "us_8inch_55_gun", "SecondaryWeapon": "mk15_torpedo_tube",
                         "Engine": "us_parsons_turbine", "Armor": "naval_belt_armor_scheme",
                         "Sensors": "naval_fire_control_mk37"},
        "unlock_tech": ["us_cruisers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWI · LAND ════════════════════════════════════════════════════════════
    {
        "id": "renault_ft_light",
        "name": "Renault FT",
        "design_family": "french_armored_ww1",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 2,
        "base_training_level": 12,
        "max_experience_level": 80,
        "base_production_days": 40,
        "base_stats": {"speed": 18, "reliability": 72, "fuel_consumption": 4, "supply_need": 6,
                      "armor": 18, "top_armor": 10, "hardness": 55},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "sa_18_37mm_tank_gun", "SecondaryWeapon": "hotchkiss_8mm_mount",
                         "Engine": "renault_4cyl_ft_engine"},
        "unlock_tech": ["ww1_tanks", "light_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mark_iv_heavy",
        "name": "Mark IV",
        "design_family": "uk_armored_ww1",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 8,
        "base_training_level": 10,
        "max_experience_level": 70,
        "base_production_days": 55,
        "base_stats": {"speed": 8, "reliability": 50, "fuel_consumption": 6, "supply_need": 10,
                      "armor": 28, "top_armor": 12, "hardness": 60},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "qf_6pdr_ww1_hotchkiss", "SecondaryWeapon": "vickers_machine_gun",
                         "Engine": "daimler_knight_engine"},
        "unlock_tech": ["ww1_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "a7v_heavy",
        "name": "A7V Sturmpanzerwagen",
        "design_family": "german_armored_ww1",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 18,
        "base_training_level": 10,
        "max_experience_level": 70,
        "base_production_days": 60,
        "base_stats": {"speed": 10, "reliability": 45, "fuel_consumption": 8, "supply_need": 12,
                      "armor": 32, "top_armor": 14, "hardness": 62},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_57mm_a7v_gun", "SecondaryWeapon": "mg08_machine_gun",
                         "Engine": "daimler_knight_engine"},
        "unlock_tech": ["ww1_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ WWI · AIR ═════════════════════════════════════════════════════════════
    {
        "id": "spad_xiii_fighter",
        "name": "SPAD S.XIII",
        "design_family": "french_air_ww1",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 20,
        "max_experience_level": 80,
        "base_production_days": 38,
        "base_stats": {"speed": 72, "reliability": 68, "fuel_consumption": 7, "supply_need": 6,
                      "armor": 8, "hardness": 18},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "vickers_machine_gun", "SecondaryWeapon": "hotchkiss_8mm_mount",
                         "Engine": "hispano_suiza_8a_engine"},
        "unlock_tech": ["ww1_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "fokker_dvii_fighter",
        "name": "Fokker D.VII",
        "design_family": "german_air_ww1",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 22,
        "max_experience_level": 80,
        "base_production_days": 36,
        "base_stats": {"speed": 70, "reliability": 70, "fuel_consumption": 7, "supply_need": 6,
                      "armor": 8, "hardness": 18},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "spandau_lmg_08", "Engine": "mercedes_diii_engine"},
        "unlock_tech": ["ww1_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ INTERWAR · LAND (1920s–1939) ══════════════════════════════════════════
    {
        "id": "lt_vz_35_light",
        "name": "LT vz. 35",
        "design_family": "czech_armored_interwar",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 4,
        "base_training_level": 18,
        "max_experience_level": 90,
        "base_production_days": 48,
        "base_stats": {"speed": 32, "reliability": 70, "fuel_consumption": 6, "supply_need": 8,
                      "armor": 28, "top_armor": 14, "hardness": 68},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "skoda_37mm_a7", "Engine": "spa_diesel_v8_engine"},
        "unlock_tech": ["interwar_tanks", "czech_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t26_light",
        "name": "T-26 Model 1933",
        "design_family": "soviet_armored_interwar",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 3,
        "base_training_level": 16,
        "max_experience_level": 90,
        "base_production_days": 45,
        "base_stats": {"speed": 28, "reliability": 66, "fuel_consumption": 6, "supply_need": 8,
                      "armor": 24, "top_armor": 12, "hardness": 65},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "45mm_m1937_gun", "Engine": "v2_diesel_engine"},
        "unlock_tech": ["interwar_tanks", "soviet_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "bt7_fast_tank",
        "name": "BT-7",
        "design_family": "soviet_armored_interwar",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 3,
        "base_training_level": 20,
        "max_experience_level": 90,
        "base_production_days": 50,
        "base_stats": {"speed": 52, "reliability": 62, "fuel_consumption": 8, "supply_need": 9,
                      "armor": 22, "top_armor": 12, "hardness": 62},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Suspension": {"max": 1}},
        "module_loadout": {"MainWeapon": "45mm_m1937_gun", "Engine": "v2_diesel_engine",
                         "Suspension": "christie_suspension_bt"},
        "unlock_tech": ["interwar_tanks", "soviet_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "cv33_tankette",
        "name": "L3/33 Tankette",
        "design_family": "italian_armored_interwar",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 2,
        "base_training_level": 12,
        "max_experience_level": 80,
        "base_production_days": 35,
        "base_stats": {"speed": 22, "reliability": 60, "fuel_consumption": 4, "supply_need": 5,
                      "armor": 14, "top_armor": 8, "hardness": 50},
        "slots": {"SecondaryWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"SecondaryWeapon": "fiat_revelli_mg", "Engine": "fiat_spa_cv33_engine"},
        "unlock_tech": ["interwar_tanks", "tankettes"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "polish_7tp_light",
        "name": "7TP",
        "design_family": "polish_armored_interwar",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 3,
        "base_training_level": 18,
        "max_experience_level": 90,
        "base_production_days": 46,
        "base_stats": {"speed": 30, "reliability": 72, "fuel_consumption": 6, "supply_need": 8,
                      "armor": 26, "top_armor": 14, "hardness": 66},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "bofors_37mm_at", "Engine": "spa_diesel_v8_engine"},
        "unlock_tech": ["interwar_tanks", "polish_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "romanian_r2_light",
        "name": "R-2 (LT vz. 35)",
        "design_family": "romanian_armored_interwar",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 4,
        "base_training_level": 16,
        "max_experience_level": 85,
        "base_production_days": 44,
        "base_stats": {"speed": 30, "reliability": 68, "fuel_consumption": 6, "supply_need": 8,
                      "armor": 26, "top_armor": 12, "hardness": 64},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "romanian_r2_tank_gun", "Engine": "spa_diesel_v8_engine"},
        "unlock_tech": ["interwar_tanks", "romanian_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ═══ INTERWAR · ARTILLERY (towed) ══════════════════════════════════════════
    {
        "id": "m1897_field_gun_battery",
        "name": "75 mm M1897 Battery",
        "design_family": "us_artillery_ww1",
        "base_type": "Land",
        "size_category": "Light",
        "visual_archetype": "artillery",
        "crew_required": 6,
        "base_training_level": 18,
        "max_experience_level": 90,
        "base_production_days": 35,
        "base_stats": {"speed": 12, "reliability": 80, "fuel_consumption": 2, "supply_need": 8,
                      "armor": 4, "hardness": 15},
        "slots": {"MainWeapon": {"max": 1}, "Suspension": {"max": 1}},
        "module_loadout": {"MainWeapon": "m1897_75mm_field_gun", "Suspension": "m1897_towed_carriage"},
        "unlock_tech": ["field_artillery", "ww1_artillery"],
        "can_mount_drones": False,
        "is_vehicle": False,
    },
    {
        "id": "qf_25pdr_artillery",
        "name": "QF 25-pdr Battery",
        "design_family": "uk_artillery_interwar",
        "base_type": "Land",
        "size_category": "Light",
        "visual_archetype": "artillery",
        "crew_required": 6,
        "base_training_level": 22,
        "max_experience_level": 100,
        "base_production_days": 40,
        "base_stats": {"speed": 14, "reliability": 82, "fuel_consumption": 3, "supply_need": 10,
                      "armor": 4, "hardness": 15},
        "slots": {"MainWeapon": {"max": 1}, "Suspension": {"max": 1}},
        "module_loadout": {"MainWeapon": "qf_25pdr_gun", "Suspension": "m1897_towed_carriage"},
        "unlock_tech": ["field_artillery"],
        "can_mount_drones": False,
        "is_vehicle": False,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in TEMPLATES_DIR.glob("*.json")}
    created = 0
    skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\nUnit templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
