#!/usr/bin/env python3
"""Generate WWI, minor-nation, and naval equipment module JSON files."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════════
    # WWI · UNITED STATES
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1897_75mm_field_gun", "name": "75 mm M1897 Field Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 62, "hard_attack": 12, "piercing": 22, "air_attack": 1,
     "cost": {"steel": 10, "explosives": 6}, "production_time": 40,
     "special_flags": ["ww1", "excellent_vs_soft", "artillery"],
     "description": "French-designed 'French 75' used by AEF. Rapid, accurate indirect fire; weak vs armor."},
    {"id": "m1916_37mm_tank_gun", "name": "37 mm M1916 Tank Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 28, "hard_attack": 18, "piercing": 38, "air_attack": 2,
     "cost": {"steel": 7}, "production_time": 32,
     "special_flags": ["ww1", "light_tank"],
     "description": "Renault FT and M1917 light tank gun. Adequate vs WWI tanks; obsolete by WWII."},
    {"id": "m1903_springfield_rifle", "name": "M1903 Springfield", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 18, "hard_attack": 2, "piercing": 4, "air_attack": 0,
     "cost": {"steel": 2}, "production_time": 10,
     "special_flags": ["ww1", "infantry"],
     "description": "Standard U.S. rifle of WWI. Represents infantry small-arms in early combined-arms modules."},
    {"id": "liberty_l12_engine", "name": "Liberty L-12", "category": "Engine", "tier": 1,
     "reliability_bonus": 2, "fuel_efficiency": 2, "speed_bonus": 8,
     "cost": {"steel": 10, "aluminum": 8}, "production_time": 42,
     "special_flags": ["ww1", "aircraft"],
     "description": "400 hp V-12 on DH-4 and early U.S. bombers. Mass-produced American aviation engine."},
    {"id": "lewis_gun_mount", "name": "Lewis Gun Mount", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 2, "piercing": 3, "air_attack": 12,
     "cost": {"steel": 3}, "production_time": 12,
     "special_flags": ["ww1", "aircraft"],
     "description": "Drum-fed light machine gun on early aircraft and vehicles."},

    # ═══════════════════════════════════════════════════════════════════════════
    # WWI · BRITISH EMPIRE
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "qf_18pdr_field_gun", "name": "QF 18-pdr Field Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 58, "hard_attack": 10, "piercing": 18, "air_attack": 1,
     "cost": {"steel": 9, "explosives": 5}, "production_time": 38,
     "special_flags": ["ww1", "artillery"],
     "description": "Primary British field gun 1916–1940. Huge numbers produced; still used in WWII secondary roles."},
    {"id": "qf_13pdr_tank_gun", "name": "QF 13-pdr Mk I", "category": "MainWeapon", "tier": 1,
     "soft_attack": 32, "hard_attack": 20, "piercing": 42, "air_attack": 3,
     "cost": {"steel": 8}, "production_time": 35,
     "special_flags": ["ww1", "light_tank"],
     "description": "Medium Mk A Whippet and early cavalry tank gun."},
    {"id": "qf_6pdr_ww1_hotchkiss", "name": "QF 6-pdr Hotchkiss", "category": "MainWeapon", "tier": 1,
     "soft_attack": 26, "hard_attack": 16, "piercing": 35, "air_attack": 2,
     "cost": {"steel": 7}, "production_time": 30,
     "special_flags": ["ww1"],
     "description": "Naval/tank 6-pounder used on early British armored cars and ships."},
    {"id": "vickers_machine_gun", "name": "Vickers Machine Gun", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 16, "hard_attack": 3, "piercing": 5, "air_attack": 8,
     "cost": {"steel": 3}, "production_time": 12,
     "special_flags": ["ww1"],
     "description": "Water-cooled .303 machine gun. Standard British infantry and aircraft defensive armament."},
    {"id": "rolls_royce_eagle_engine", "name": "Rolls-Royce Eagle", "category": "Engine", "tier": 1,
     "reliability_bonus": 4, "fuel_efficiency": 3, "speed_bonus": 9,
     "cost": {"steel": 11, "aluminum": 10}, "production_time": 48,
     "special_flags": ["ww1", "aircraft"],
     "description": "360 hp V-12 on Handley Page O/400 and naval aircraft."},

    # ═══════════════════════════════════════════════════════════════════════════
    # WWI · FRANCE
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "canet_75mm_coastal", "name": "75 mm Canet Coastal Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 40, "hard_attack": 14, "piercing": 28, "air_attack": 2, "anti_ship": 22,
     "cost": {"steel": 12}, "production_time": 45,
     "special_flags": ["ww1", "coastal"],
     "description": "Quick-firing coastal and fortress gun used by France and exported widely."},
    {"id": "sa_18_37mm_tank_gun", "name": "SA 18 37 mm", "category": "MainWeapon", "tier": 1,
     "soft_attack": 26, "hard_attack": 16, "piercing": 36, "air_attack": 2,
     "cost": {"steel": 6}, "production_time": 30,
     "special_flags": ["ww1", "light_tank"],
     "description": "Renault FT Puteaux gun. First mass-produced tank cannon."},
    {"id": "hotchkiss_8mm_mount", "name": "Hotchkiss M1914", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 2, "piercing": 3, "air_attack": 6,
     "cost": {"steel": 2}, "production_time": 10,
     "special_flags": ["ww1"],
     "description": "French medium machine gun for infantry and tank co-axial mounts."},
    {"id": "hispano_suiza_8a_engine", "name": "Hispano-Suiza 8A", "category": "Engine", "tier": 1,
     "reliability_bonus": 5, "fuel_efficiency": 4, "speed_bonus": 10,
     "cost": {"steel": 9, "aluminum": 9}, "production_time": 44,
     "special_flags": ["ww1", "aircraft"],
     "description": "200 hp V-8 on SPAD S.XIII. Top Allied fighter engine of 1918."},

    # ═══════════════════════════════════════════════════════════════════════════
    # WWI · GERMANY
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "fk_96_77mm_field_gun", "name": "7.7 cm FK 96 n.A.", "category": "MainWeapon", "tier": 1,
     "soft_attack": 52, "hard_attack": 10, "piercing": 20, "air_attack": 1,
     "cost": {"steel": 9, "explosives": 4}, "production_time": 36,
     "special_flags": ["ww1", "artillery"],
     "description": "Modernized field gun backbone of German divisions in WWI."},
    {"id": "kwk_57mm_a7v_gun", "name": "5.7 cm KwK L/30", "category": "MainWeapon", "tier": 1,
     "soft_attack": 30, "hard_attack": 22, "piercing": 44, "air_attack": 2,
     "cost": {"steel": 9}, "production_time": 38,
     "special_flags": ["ww1", "heavy_tank"],
     "description": "A7V Sturmpanzerwagen main gun. Slow-firing but dangerous to Allied light tanks."},
    {"id": "mg08_machine_gun", "name": "MG 08", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 17, "hard_attack": 3, "piercing": 5, "air_attack": 6,
     "cost": {"steel": 4}, "production_time": 14,
     "special_flags": ["ww1"],
     "description": "German Maxim derivative. Dominant infantry support weapon 1914–18."},
    {"id": "spandau_lmg_08", "name": "LMG 08/15", "category": "MainWeapon", "tier": 1,
     "soft_attack": 12, "hard_attack": 4, "piercing": 6, "air_attack": 20,
     "cost": {"steel": 4}, "production_time": 16,
     "special_flags": ["ww1", "aircraft"],
     "description": "Synchronized 'Spandau' aircraft machine gun on Fokker and Albatros fighters."},
    {"id": "mercedes_diii_engine", "name": "Mercedes D.III", "category": "Engine", "tier": 1,
     "reliability_bonus": 3, "fuel_efficiency": 3, "speed_bonus": 9,
     "cost": {"steel": 10, "aluminum": 8}, "production_time": 42,
     "special_flags": ["ww1", "aircraft"],
     "description": "160 hp inline on Albatros D.III and early Fokker D.VII variants."},

    # ═══════════════════════════════════════════════════════════════════════════
    # WWI · RUSSIA / AUSTRIA-HUNGARY / OTTOMAN
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1902_76mm_field_gun", "name": "76.2 mm M1902", "category": "MainWeapon", "tier": 1,
     "soft_attack": 50, "hard_attack": 10, "piercing": 18, "air_attack": 1,
     "cost": {"steel": 8, "explosives": 4}, "production_time": 34,
     "special_flags": ["ww1", "artillery"],
     "description": "Standard Russian divisional gun. Remained in use into WWII with smaller nations."},
    {"id": "m1910_122mm_howitzer", "name": "122 mm M1910 Howitzer", "category": "MainWeapon", "tier": 1,
     "soft_attack": 72, "hard_attack": 8, "piercing": 12, "air_attack": 1,
     "cost": {"steel": 14, "explosives": 10}, "production_time": 50,
     "special_flags": ["ww1", "artillery", "excellent_vs_soft"],
     "description": "Russian corps howitzer. Heavy barrage weapon; limited anti-tank use."},
    {"id": "skoda_75mm_m15", "name": "7.5 cm Skoda M.15", "category": "MainWeapon", "tier": 1,
     "soft_attack": 48, "hard_attack": 12, "piercing": 24, "air_attack": 1,
     "cost": {"steel": 10}, "production_time": 38,
     "special_flags": ["ww1", "mountain_gun"],
     "description": "Austro-Hungarian mountain and field gun. Exported to Bulgaria and successor states."},
    {"id": "skoda_100mm_m14", "name": "10.4 cm Skoda M.14", "category": "MainWeapon", "tier": 1,
     "soft_attack": 65, "hard_attack": 14, "piercing": 30, "air_attack": 2,
     "cost": {"steel": 16, "explosives": 8}, "production_time": 48,
     "special_flags": ["ww1", "artillery"],
     "description": "Heavy field howitzer of Austria-Hungary. Used on Italian front fortifications."},
    {"id": "ottoman_mauser_rifle", "name": "Mauser 1903 Pattern", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 15, "hard_attack": 2, "piercing": 3, "air_attack": 0,
     "cost": {"steel": 2}, "production_time": 8,
     "special_flags": ["ww1", "ottoman", "infantry"],
     "description": "Ottoman infantry rifle (German-supplied). Represents under-equipped army small arms."},

    # ═══════════════════════════════════════════════════════════════════════════
    # WWI · ITALY / BELGIUM / SERBIA
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "ansaldo_65mm_mountain", "name": "65 mm Ansaldo Mountain Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 38, "hard_attack": 8, "piercing": 16, "air_attack": 1,
     "cost": {"steel": 7}, "production_time": 32,
     "special_flags": ["ww1", "mountain_gun"],
     "description": "Italian mountain artillery for Alpine front. Light and portable."},
    {"id": "fiat_revelli_mg", "name": "Fiat-Revelli M1914", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 13, "hard_attack": 2, "piercing": 3, "air_attack": 5,
     "cost": {"steel": 3}, "production_time": 11,
     "special_flags": ["ww1", "italy"],
     "description": "Italian water-cooled machine gun. Mediocre reliability but widely issued."},
    {"id": "cockerill_47mm_gun", "name": "Cockerill 47 mm", "category": "MainWeapon", "tier": 1,
     "soft_attack": 24, "hard_attack": 14, "piercing": 32, "air_attack": 2,
     "cost": {"steel": 6}, "production_time": 28,
     "special_flags": ["ww1", "belgium"],
     "description": "Belgian anti-tank and fortification gun (1914). One of the first dedicated AT guns."},
    {"id": "serbian_m1904_75mm", "name": "75 mm M1904 Schneider", "category": "MainWeapon", "tier": 1,
     "soft_attack": 46, "hard_attack": 10, "piercing": 18, "air_attack": 1,
     "cost": {"steel": 8}, "production_time": 34,
     "special_flags": ["ww1", "serbia"],
     "description": "French-supplied Serbian field gun. Obsolete but still fielded in Balkan wars."},

    # ═══════════════════════════════════════════════════════════════════════════
    # MINOR / SMALL NATIONS · SURPLUS & LICENSED (WWI–INTERWAR → WWII)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "skoda_37mm_a7", "name": "37 mm Škoda A7", "category": "MainWeapon", "tier": 1,
     "soft_attack": 30, "hard_attack": 20, "piercing": 48, "air_attack": 3,
     "cost": {"steel": 8}, "production_time": 36,
     "special_flags": ["interwar", "czech"],
     "description": "LT vz. 35 gun. Exported to Romania and Bulgaria; obsolete vs WWII mediums."},
    {"id": "bofors_37mm_at", "name": "Bofors 37 mm AT Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 28, "hard_attack": 26, "piercing": 62, "air_attack": 3,
     "cost": {"steel": 9, "aluminum": 2}, "production_time": 38,
     "special_flags": ["interwar", "sweden", "netherlands"],
     "description": "Swedish anti-tank gun used by Netherlands, Poland, and Finland."},
    {"id": "vz24_rifle_system", "name": "vz. 24 Rifle System", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 16, "hard_attack": 2, "piercing": 4, "air_attack": 0,
     "cost": {"steel": 2}, "production_time": 9,
     "special_flags": ["czech", "romania", "china"],
     "description": "Czech Mauser export rifle. Equips many minor armies in 1936 scenarios."},
    {"id": "fiat_spa_cv33_engine", "name": "Fiat SPA CV3 Engine", "category": "Engine", "tier": 1,
     "reliability_bonus": -2, "fuel_efficiency": 4, "speed_bonus": 2,
     "cost": {"steel": 6}, "production_time": 28,
     "special_flags": ["interwar", "italy", "light_tank"],
     "description": "Tiny tankette powerplant used by Italy, Hungary, and export customers."},
    {"id": "polish_wz35_at", "name": "wz. 35 Anti-Tank Rifle", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 8, "hard_attack": 12, "piercing": 28, "air_attack": 0,
     "cost": {"steel": 3}, "production_time": 14,
     "special_flags": ["poland", "1939"],
     "description": "Uruguay-pattern AT rifle. Limited effectiveness even in 1939."},
    {"id": "finnish_20mm_l39", "name": "20 mm L-39 Lahti", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 12, "hard_attack": 18, "piercing": 42, "air_attack": 4,
     "cost": {"steel": 5}, "production_time": 22,
     "special_flags": ["finland", "winter_war"],
     "description": "Finnish anti-tank rifle effective vs early Soviet light armor."},
    {"id": "chinese_hanyang_rifle", "name": "Hanyang 88 Rifle", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 2, "piercing": 3, "air_attack": 0,
     "cost": {"steel": 2}, "production_time": 8,
     "special_flags": ["china", "warlord"],
     "description": "Locally copied Gewehr 88. Represents poorly standardized Chinese arsenals."},
    {"id": "hungarian_40mm_zf2", "name": "40 mm 40M Anti-Tank", "category": "MainWeapon", "tier": 1,
     "soft_attack": 26, "hard_attack": 28, "piercing": 58, "air_attack": 2,
     "cost": {"steel": 8}, "production_time": 36,
     "special_flags": ["hungary", "license"],
     "description": "Swedish Bofors 40 mm license built in Hungary. Adequate vs light tanks."},
    {"id": "romanian_r2_tank_gun", "name": "37 mm R-2 Tank Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 28, "hard_attack": 18, "piercing": 44, "air_attack": 2,
     "cost": {"steel": 7}, "production_time": 32,
     "special_flags": ["romania", "czech_license"],
     "description": "License LT vz. 35 (R-2). Romania's primary pre-war tank armament."},
    {"id": "bulgarian_76mm_m1902", "name": "76.2 mm M1902 (Bulgarian)", "category": "MainWeapon", "tier": 1,
     "soft_attack": 44, "hard_attack": 10, "piercing": 16, "air_attack": 1,
     "cost": {"steel": 7}, "production_time": 30,
     "special_flags": ["bulgaria", "ww1_surplus"],
     "description": "Surplus Russian field guns still in Bulgarian service in WWII."},
    {"id": "greek_65mm_mountain", "name": "65 mm Schneider Mountain", "category": "MainWeapon", "tier": 1,
     "soft_attack": 36, "hard_attack": 8, "piercing": 14, "air_attack": 1,
     "cost": {"steel": 6}, "production_time": 28,
     "special_flags": ["greece", "mountain"],
     "description": "Interwar Greek mountain artillery. Light but dated."},
    {"id": "spanish_47mm_saonica", "name": "47 mm Saónica AT Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 26, "hard_attack": 22, "piercing": 50, "air_attack": 2,
     "cost": {"steel": 7}, "production_time": 32,
     "special_flags": ["spain", "civil_war"],
     "description": "Mixed arsenal Spanish anti-tank piece from Civil War era stockpiles."},
    {"id": "portuguese_75mm_m1917", "name": "75 mm m/917 Field Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 48, "hard_attack": 10, "piercing": 18, "air_attack": 1,
     "cost": {"steel": 8}, "production_time": 32,
     "special_flags": ["portugal", "ww1_surplus"],
     "description": "Portuguese designation for French 75 copies. Neutral nation standard artillery."},
    {"id": "dutch_47mm_kni", "name": "47 mm KNI Bombard", "category": "MainWeapon", "tier": 1,
     "soft_attack": 30, "hard_attack": 20, "piercing": 46, "air_attack": 2,
     "cost": {"steel": 7}, "production_time": 30,
     "special_flags": ["netherlands", "1939"],
     "description": "Dutch Indies anti-tank gun. Too light vs Japanese medium tanks."},
    {"id": "norwegian_75mm_krupp", "name": "75 mm Krupp M1908", "category": "MainWeapon", "tier": 1,
     "soft_attack": 46, "hard_attack": 10, "piercing": 17, "air_attack": 1,
     "cost": {"steel": 8}, "production_time": 34,
     "special_flags": ["norway", "ww1"],
     "description": "Norwegian fortress and field artillery. Captured stocks used by Germany."},
    {"id": "swedish_37mm_bofors_tank", "name": "37 mm Bofors Strv m/37", "category": "MainWeapon", "tier": 1,
     "soft_attack": 32, "hard_attack": 22, "piercing": 52, "air_attack": 3,
     "cost": {"steel": 9, "aluminum": 2}, "production_time": 38,
     "special_flags": ["sweden", "neutral"],
     "description": "Swedish light tank gun. Modern for a small nation but limited production."},

    # ═══════════════════════════════════════════════════════════════════════════
    # NAVAL · LIGHT / DESTROYER (3–5 inch)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "us_5inch_38_gun", "name": "5\"/38 Mark 12", "category": "NavalGun", "tier": 3,
     "soft_attack": 42, "hard_attack": 28, "piercing": 52, "air_attack": 18, "anti_ship": 38, "anti_air": 22,
     "cost": {"steel": 18, "explosives": 6}, "production_time": 55,
     "special_flags": ["naval", "dual_purpose", "usa"],
     "description": "Standard U.S. destroyer/cruiser DP gun WWII. Excellent AA and solid anti-surface."},
    {"id": "uk_4_7inch_qf", "name": "QF 4.7-inch Mk IX", "category": "NavalGun", "tier": 2,
     "soft_attack": 36, "hard_attack": 24, "piercing": 44, "air_attack": 8, "anti_ship": 32,
     "cost": {"steel": 14}, "production_time": 48,
     "special_flags": ["naval", "destroyer", "uk"],
     "description": "Interwar British destroyer gun. Workhorse of RN destroyer flotillas."},
    {"id": "ger_10_5cm_tb", "name": "10.5 cm SK C/32", "category": "NavalGun", "tier": 2,
     "soft_attack": 38, "hard_attack": 26, "piercing": 46, "air_attack": 12, "anti_ship": 34,
     "cost": {"steel": 15}, "production_time": 50,
     "special_flags": ["naval", "destroyer", "germany"],
     "description": "Kriegsmarine destroyer gun. Balanced surface and moderate AA."},
    {"id": "ijn_12_7cm_type89", "name": "12.7 cm Type 89", "category": "NavalGun", "tier": 2,
     "soft_attack": 40, "hard_attack": 27, "piercing": 48, "air_attack": 14, "anti_ship": 36,
     "cost": {"steel": 14}, "production_time": 48,
     "special_flags": ["naval", "destroyer", "japan"],
     "description": "Imperial Japanese destroyer dual-purpose gun."},
    {"id": "ww1_4inch_qf_mk4", "name": "QF 4-inch Mk IV", "category": "NavalGun", "tier": 1,
     "soft_attack": 28, "hard_attack": 18, "piercing": 32, "air_attack": 6, "anti_ship": 24,
     "cost": {"steel": 10}, "production_time": 38,
     "special_flags": ["naval", "ww1", "destroyer"],
     "description": "WWI British destroyer gun. Still on escorts and older ships in WWII."},

    # ═══════════════════════════════════════════════════════════════════════════
    # NAVAL · CRUISER (6–8 inch)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "us_6inch_47_gun", "name": "6\"/47 Mark 16", "category": "NavalGun", "tier": 3,
     "soft_attack": 55, "hard_attack": 42, "piercing": 72, "air_attack": 10, "anti_ship": 58,
     "cost": {"steel": 22, "explosives": 4}, "production_time": 65,
     "special_flags": ["naval", "light_cruiser", "usa"],
     "description": "U.S. light cruiser automatic rifle. High rate of fire with good AP."},
    {"id": "us_8inch_55_gun", "name": "8\"/55 Mark 12", "category": "NavalGun", "tier": 3,
     "soft_attack": 62, "hard_attack": 52, "piercing": 88, "air_attack": 6, "anti_ship": 72,
     "cost": {"steel": 28, "explosives": 6}, "production_time": 75,
     "special_flags": ["naval", "heavy_cruiser", "usa"],
     "description": "Treaty heavy cruiser gun (Portland, Northampton classes)."},
    {"id": "uk_6inch_bl_mk12", "name": "BL 6-inch Mk XII", "category": "NavalGun", "tier": 2,
     "soft_attack": 50, "hard_attack": 38, "piercing": 65, "air_attack": 6, "anti_ship": 52,
     "cost": {"steel": 20}, "production_time": 60,
     "special_flags": ["naval", "light_cruiser", "uk"],
     "description": "County-class cruiser gun. Standard RN light cruiser armament interwar."},
    {"id": "uk_8inch_mk8", "name": "BL 8-inch Mk VIII", "category": "NavalGun", "tier": 3,
     "soft_attack": 60, "hard_attack": 50, "piercing": 85, "air_attack": 5, "anti_ship": 70,
     "cost": {"steel": 26}, "production_time": 72,
     "special_flags": ["naval", "heavy_cruiser", "uk"],
     "description": "York and Kent class 8-inch gun. Treaty cruiser standard."},
    {"id": "ijn_8inch_type3", "name": "20 cm Type 3 No.1", "category": "NavalGun", "tier": 3,
     "soft_attack": 58, "hard_attack": 48, "piercing": 82, "air_attack": 5, "anti_ship": 68,
     "cost": {"steel": 24}, "production_time": 70,
     "special_flags": ["naval", "heavy_cruiser", "japan"],
     "description": "Myoko and Takao class 8-inch. Long-range cruiser killer."},
    {"id": "ger_15cm_tb", "name": "15 cm SK C/25", "category": "NavalGun", "tier": 2,
     "soft_attack": 48, "hard_attack": 36, "piercing": 60, "air_attack": 8, "anti_ship": 48,
     "cost": {"steel": 18}, "production_time": 55,
     "special_flags": ["naval", "light_cruiser", "germany"],
     "description": "Königsberg-class light cruiser gun. Common on German cruisers and capital ship secondaries."},

    # ═══════════════════════════════════════════════════════════════════════════
    # NAVAL · BATTLESHIP (12–16 inch) · WWI & WWII
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "uk_12inch_mk10", "name": "BL 12-inch Mk X", "category": "NavalGun", "tier": 1,
     "soft_attack": 58, "hard_attack": 48, "piercing": 78, "air_attack": 2, "anti_ship": 62,
     "cost": {"steel": 32, "explosives": 8}, "production_time": 80,
     "special_flags": ["naval", "ww1", "dreadnought", "uk"],
     "description": "Dreadnought and Iron Duke class 12-inch. Obsolete by WWII but on reserve ships."},
    {"id": "uk_13_5inch_mk5", "name": "BL 13.5-inch Mk V", "category": "NavalGun", "tier": 1,
     "soft_attack": 65, "hard_attack": 55, "piercing": 88, "air_attack": 2, "anti_ship": 72,
     "cost": {"steel": 36, "explosives": 10}, "production_time": 88,
     "special_flags": ["naval", "ww1", "dreadnought", "uk"],
     "description": "Queen Elizabeth class super-dreadnought gun. Still dangerous in WWII secondary roles."},
    {"id": "uk_14inch_mk7", "name": "BL 14-inch Mk VII", "category": "NavalGun", "tier": 2,
     "soft_attack": 72, "hard_attack": 62, "piercing": 98, "air_attack": 3, "anti_ship": 82,
     "cost": {"steel": 40, "explosives": 12}, "production_time": 95,
     "special_flags": ["naval", "battleship", "uk"],
     "description": "King George V class main armament. Modern RN battleship standard."},
    {"id": "uk_15inch_mk1", "name": "BL 15-inch Mk I", "category": "NavalGun", "tier": 2,
     "soft_attack": 78, "hard_attack": 68, "piercing": 108, "air_attack": 3, "anti_ship": 90,
     "cost": {"steel": 44, "explosives": 14}, "production_time": 100,
     "special_flags": ["naval", "battleship", "uk"],
     "description": "Queen Elizabeth and Renown class. Legendary RN capital ship gun."},
    {"id": "us_14inch_45_gun", "name": "14\"/45 Mark 8", "category": "NavalGun", "tier": 1,
     "soft_attack": 70, "hard_attack": 60, "piercing": 92, "air_attack": 2, "anti_ship": 78,
     "cost": {"steel": 38, "explosives": 10}, "production_time": 90,
     "special_flags": ["naval", "ww1", "dreadnought", "usa"],
     "description": "New York and Texas class. WWI-era U.S. battleship main battery."},
    {"id": "us_16inch_45_gun", "name": "16\"/45 Mark 6", "category": "NavalGun", "tier": 3,
     "soft_attack": 85, "hard_attack": 78, "piercing": 125, "air_attack": 4, "anti_ship": 105,
     "cost": {"steel": 52, "explosives": 18, "chromium": 6}, "production_time": 120,
     "special_flags": ["naval", "battleship", "usa", "excellent_ap"],
     "description": "North Carolina and South Dakota class. Superb balance of penetration and shell weight."},
    {"id": "us_16inch_50_gun", "name": "16\"/50 Mark 7", "category": "NavalGun", "tier": 4,
     "soft_attack": 90, "hard_attack": 85, "piercing": 138, "air_attack": 4, "anti_ship": 115,
     "cost": {"steel": 58, "explosives": 22, "chromium": 8}, "production_time": 135,
     "special_flags": ["naval", "battleship", "usa", "excellent_ap"],
     "description": "Iowa class. Premier U.S. battleship gun with extreme range and penetration."},
    {"id": "ger_11inch_skc34", "name": "28 cm SK C/34", "category": "NavalGun", "tier": 2,
     "soft_attack": 68, "hard_attack": 58, "piercing": 92, "air_attack": 3, "anti_ship": 76,
     "cost": {"steel": 36, "explosives": 10}, "production_time": 88,
     "special_flags": ["naval", "pocket_battleship", "germany"],
     "description": "Deutschland-class 'pocket battleship' main gun. Outranges cruisers."},
    {"id": "ger_15inch_skc34", "name": "38 cm SK C/34", "category": "NavalGun", "tier": 3,
     "soft_attack": 82, "hard_attack": 74, "piercing": 118, "air_attack": 3, "anti_ship": 98,
     "cost": {"steel": 48, "explosives": 16, "chromium": 5}, "production_time": 115,
     "special_flags": ["naval", "battleship", "germany"],
     "description": "Bismarck and Scharnhorst class 15-inch equivalent. Highly effective AP shells."},
    {"id": "ijn_14inch_type94", "name": "36 cm Type 94", "category": "NavalGun", "tier": 2,
     "soft_attack": 74, "hard_attack": 66, "piercing": 102, "air_attack": 3, "anti_ship": 86,
     "cost": {"steel": 42, "explosives": 12}, "production_time": 98,
     "special_flags": ["naval", "battleship", "japan"],
     "description": "Ise and Nagato class 14-inch. Powerful but superseded by 18-inch on Yamato."},
    {"id": "ijn_18inch_type94", "name": "46 cm Type 94", "category": "NavalGun", "tier": 4,
     "soft_attack": 98, "hard_attack": 92, "piercing": 145, "air_attack": 4, "anti_ship": 125,
     "cost": {"steel": 65, "explosives": 28, "chromium": 10}, "production_time": 150,
     "special_flags": ["naval", "battleship", "japan", "super_heavy"],
     "description": "Yamato class 18.1-inch. Largest battleship gun ever deployed."},
    {"id": "ita_12inch_m1914", "name": "305 mm Model 1914", "category": "NavalGun", "tier": 1,
     "soft_attack": 60, "hard_attack": 50, "piercing": 80, "air_attack": 2, "anti_ship": 64,
     "cost": {"steel": 30}, "production_time": 78,
     "special_flags": ["naval", "ww1", "italy"],
     "description": "Andrea Doria class 12-inch. Obsolete WWII battleship armament."},
    {"id": "fra_13_4inch_m1934", "name": "340 mm Model 1934", "category": "NavalGun", "tier": 2,
     "soft_attack": 76, "hard_attack": 68, "piercing": 104, "air_attack": 3, "anti_ship": 88,
     "cost": {"steel": 40, "explosives": 12}, "production_time": 95,
     "special_flags": ["naval", "battleship", "france"],
     "description": "Dunkerque and Richelieu class main gun. Modern French capital ship armament."},

    # ═══════════════════════════════════════════════════════════════════════════
    # NAVAL · TORPEDOES · ASW · FIRE CONTROL
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "mk15_torpedo_tube", "name": "Mark 15 Torpedo", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 20, "hard_attack": 35, "piercing": 25, "anti_ship": 55,
     "cost": {"steel": 8, "explosives": 12, "aluminum": 4}, "production_time": 40,
     "special_flags": ["naval", "torpedo", "usa"],
     "description": "Standard U.S. destroyer/cruiser torpedo. Devastating vs capital ships if hits scored."},
    {"id": "type93_long_lance", "name": "Type 93 'Long Lance'", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 18, "hard_attack": 40, "piercing": 28, "anti_ship": 72,
     "cost": {"steel": 10, "explosives": 16, "aluminum": 6}, "production_time": 55,
     "special_flags": ["naval", "torpedo", "japan", "oxygen_torpedo"],
     "description": "Imperial Japanese oxygen torpedo. Longest range and largest warhead of WWII."},
    {"id": "g7a_torpedo", "name": "G7a Torpedo", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 16, "hard_attack": 32, "piercing": 22, "anti_ship": 48,
     "cost": {"steel": 8, "explosives": 10}, "production_time": 42,
     "special_flags": ["naval", "torpedo", "germany"],
     "description": "Standard Kriegsmarine steam torpedo for destroyers and U-boats."},
    {"id": "ww1_18inch_torpedo", "name": "18-inch Mk VIII Torpedo", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 26, "piercing": 18, "anti_ship": 38,
     "cost": {"steel": 6, "explosives": 8}, "production_time": 35,
     "special_flags": ["naval", "torpedo", "ww1", "uk"],
     "description": "WWI Royal Navy torpedo. Still in use on older destroyers early WWII."},
    {"id": "depth_charge_rail", "name": "Depth Charge Rail", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 8, "hard_attack": 45, "piercing": 15, "anti_ship": 28,
     "cost": {"steel": 4, "explosives": 10}, "production_time": 25,
     "special_flags": ["naval", "asw", "anti_submarine"],
     "description": "Destroyer stern racks and K-guns for anti-submarine warfare."},
    {"id": "naval_fire_control_mk37", "name": "Mk 37 GFCS", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 6, "electronics": 16, "optics": 10}, "production_time": 65,
     "special_flags": ["naval", "fire_control", "usa"],
     "description": "U.S. naval gunfire control radar and director. Major accuracy boost for surface combat."},
    {"id": "naval_radar_type22", "name": "Type 22 Radar", "category": "Sensors", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 4, "electronics": 12}, "production_time": 50,
     "special_flags": ["naval", "radar", "uk"],
     "description": "Early British naval surface search radar set."},
    {"id": "submarine_torpedo_tube", "name": "Submarine Torpedo Tube", "category": "MainWeapon", "tier": 2,
     "soft_attack": 12, "hard_attack": 38, "piercing": 24, "anti_ship": 62,
     "cost": {"steel": 10, "explosives": 14, "rubber": 4}, "production_time": 48,
     "special_flags": ["naval", "submarine", "torpedo"],
     "description": "Bow/stern torpedo installation for submarines. Primary U-boat and fleet boat weapon."},
    {"id": "naval_belt_armor_scheme", "name": "Belt Armor Scheme", "category": "Armor", "tier": 2,
     "armor_bonus": 35, "top_armor_bonus": 8, "reliability_penalty": -5,
     "cost": {"steel": 55, "chromium": 4}, "production_time": 90,
     "special_flags": ["naval", "battleship"],
     "description": "Representative main belt and bulkhead protection for capital ships."},
    {"id": "naval_deck_armor_scheme", "name": "Deck Armor Scheme", "category": "Armor", "tier": 2,
     "armor_bonus": 12, "top_armor_bonus": 28, "reliability_penalty": -4,
     "cost": {"steel": 40}, "production_time": 75,
     "special_flags": ["naval", "plunging_fire"],
     "description": "Armored decks against plunging fire and bombs (treats as top/deck armor)."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        mid = mod["id"]
        path = MODULES_DIR / f"{mid}.json"
        if mid in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"Done: {created} created, {skipped} skipped, {total} total JSON modules.")


if __name__ == "__main__":
    main()
