#!/usr/bin/env python3
"""1980s–1990s unit templates for USA, USSR/Russia, China, France, UK, Germany, Israel."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    # ─── USA ───────────────────────────────────────────────────────────────────
    {
        "id": "m1_abrams",
        "name": "M1 Abrams",
        "design_family": "us_armored_eighties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 110,
        "base_stats": {"speed": 32, "reliability": 78, "fuel_consumption": 18, "supply_need": 22,
                      "armor": 64, "top_armor": 48, "hardness": 94},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256_120mm_gun", "Engine": "agt1500_turbine",
                         "Armor": "m1_abrams_armor", "Sensors": "thermal_imager_an_vsg3",
                         "Cargo": "m829_apfsds"},
        "unlock_tech": ["us_mbt_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m1a2_abrams",
        "name": "M1A2 Abrams",
        "design_family": "us_armored_nineties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 32, "reliability": 82, "fuel_consumption": 18, "supply_need": 24,
                      "armor": 78, "top_armor": 58, "hardness": 96},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256a1_120mm_gun", "Engine": "agt1500_turbine",
                         "Armor": "m1a2_sep_armor", "Sensors": "hunter_killer_fcs",
                         "Cargo": "m829a1_apfsds"},
        "unlock_tech": ["us_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m2a2_bradley",
        "name": "M2A2 Bradley",
        "design_family": "us_armored_eighties",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "apc",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 75,
        "base_stats": {"speed": 38, "reliability": 76, "fuel_consumption": 12, "supply_need": 14,
                      "armor": 28, "top_armor": 16, "hardness": 70},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "m242_bushmaster", "SecondaryWeapon": "m2_bradley_tow",
                         "Engine": "avds_1790_engine"},
        "unlock_tech": ["us_ifv_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f15c_eagle",
        "name": "F-15C Eagle",
        "design_family": "us_air_eighties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 85,
        "base_stats": {"speed": 105, "reliability": 82, "fuel_consumption": 24, "supply_need": 18,
                      "armor": 14, "hardness": 28},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim120_amraam", "SecondaryWeapon": "aim9_sidewinder",
                         "Engine": "pratt_f100_f15"},
        "unlock_tech": ["us_fighters_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f16c_fighting_falcon",
        "name": "F-16C Fighting Falcon",
        "design_family": "us_air_eighties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 72,
        "base_stats": {"speed": 102, "reliability": 80, "fuel_consumption": 18, "supply_need": 14,
                      "armor": 10, "hardness": 24},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim9x_sidewinder", "Engine": "f110_ge_engine"},
        "unlock_tech": ["us_fighters_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "ah64_apache",
        "name": "AH-64 Apache",
        "design_family": "us_air_eighties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "helicopter",
        "crew_required": 2,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 55, "reliability": 78, "fuel_consumption": 16, "supply_need": 16,
                      "armor": 18, "hardness": 35},
        "slots": {"MainWeapon": {"max": 2}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "ah64_hellfire", "Sensors": "thermal_imager_an_vsg3"},
        "unlock_tech": ["us_attack_helicopters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── USSR / RUSSIA ─────────────────────────────────────────────────────────
    {
        "id": "t72b_mbt",
        "name": "T-72B",
        "design_family": "soviet_armored_eighties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 34, "reliability": 74, "fuel_consumption": 12, "supply_need": 15,
                      "armor": 58, "top_armor": 35, "hardness": 90},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "2a46m_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t72b_kontakt5", "Cargo": "3bm32_apfsds"},
        "unlock_tech": ["soviet_mbt_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t80u_mbt",
        "name": "T-80U",
        "design_family": "soviet_armored_eighties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 36, "reliability": 70, "fuel_consumption": 16, "supply_need": 16,
                      "armor": 60, "top_armor": 36, "hardness": 91},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}},
        "module_loadout": {"MainWeapon": "2a46m_125mm_gun", "Engine": "gtd1000t_turbine",
                         "Armor": "t80_composite_armor"},
        "unlock_tech": ["soviet_mbt_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t90_mbt",
        "name": "T-90",
        "design_family": "russian_armored_nineties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 98,
        "base_stats": {"speed": 35, "reliability": 76, "fuel_consumption": 13, "supply_need": 16,
                      "armor": 62, "top_armor": 38, "hardness": 92},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "2a46m5_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t90_armor_package", "Sensors": "shtora_soft_kill",
                         "Cargo": "3bm42_mango_apfsds"},
        "unlock_tech": ["russian_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mig29_fulcrum",
        "name": "MiG-29 Fulcrum",
        "design_family": "soviet_air_eighties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 68,
        "base_stats": {"speed": 108, "reliability": 72, "fuel_consumption": 16, "supply_need": 12,
                      "armor": 10, "hardness": 24},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "r73_archer_missile", "Engine": "rd33_mig29_engine"},
        "unlock_tech": ["soviet_fighters_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "su27_flanker",
        "name": "Su-27 Flanker",
        "design_family": "soviet_air_eighties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 88,
        "base_stats": {"speed": 110, "reliability": 74, "fuel_consumption": 22, "supply_need": 16,
                      "armor": 12, "hardness": 26},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "r27_alamo_missile", "Engine": "al31f_engine"},
        "unlock_tech": ["soviet_fighters_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── CHINA ─────────────────────────────────────────────────────────────────
    {
        "id": "type88_mbt",
        "name": "Type 88",
        "design_family": "chinese_armored_eighties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 88,
        "base_stats": {"speed": 32, "reliability": 70, "fuel_consumption": 13, "supply_need": 15,
                      "armor": 50, "top_armor": 28, "hardness": 86},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "type80_105mm_gun", "Engine": "12150l_diesel",
                         "Armor": "type85_iim_armor"},
        "unlock_tech": ["chinese_mbt_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "type96_mbt",
        "name": "Type 96",
        "design_family": "chinese_armored_nineties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 92,
        "base_stats": {"speed": 34, "reliability": 72, "fuel_consumption": 12, "supply_need": 15,
                      "armor": 55, "top_armor": 32, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "type96_125mm_gun", "Engine": "12150l_diesel",
                         "Armor": "type85_iim_armor"},
        "unlock_tech": ["chinese_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "j8ii_finback",
        "name": "J-8II Finback",
        "design_family": "chinese_air_eighties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 98, "reliability": 68, "fuel_consumption": 16, "supply_need": 12,
                      "armor": 8, "hardness": 22},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "pl8_air_missile", "Engine": "wp13f_j8_engine"},
        "unlock_tech": ["chinese_fighters_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── FRANCE ────────────────────────────────────────────────────────────────
    {
        "id": "leclerc_mbt",
        "name": "Leclerc",
        "design_family": "french_armored_nineties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 115,
        "base_stats": {"speed": 40, "reliability": 84, "fuel_consumption": 12, "supply_need": 17,
                      "armor": 65, "top_armor": 40, "hardness": 93},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "cn120_26_leclerc_gun", "Engine": "leclerc_hispano_engine",
                         "Armor": "leclerc_armor", "Sensors": "hunter_killer_fcs",
                         "Cargo": "du_apfsds_gen3"},
        "unlock_tech": ["french_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mirage2000_fighter",
        "name": "Mirage 2000",
        "design_family": "french_air_eighties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 75,
        "base_stats": {"speed": 104, "reliability": 78, "fuel_consumption": 16, "supply_need": 13,
                      "armor": 10, "hardness": 24},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "super530d_missile", "Engine": "mirage2000_package"},
        "unlock_tech": ["french_fighters_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── UK ────────────────────────────────────────────────────────────────────
    {
        "id": "challenger1_mbt",
        "name": "Challenger 1",
        "design_family": "uk_armored_eighties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 110,
        "base_stats": {"speed": 28, "reliability": 76, "fuel_consumption": 15, "supply_need": 20,
                      "armor": 66, "top_armor": 48, "hardness": 95},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "l30_120mm_rifled", "Engine": "perkins_cv12_engine",
                         "Armor": "challenger1_chobham", "Cargo": "du_apfsds_gen3"},
        "unlock_tech": ["uk_mbt_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "challenger2_mbt",
        "name": "Challenger 2",
        "design_family": "uk_armored_nineties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 118,
        "base_stats": {"speed": 28, "reliability": 80, "fuel_consumption": 15, "supply_need": 21,
                      "armor": 74, "top_armor": 52, "hardness": 96},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "l30_120mm_rifled", "Engine": "perkins_cv12_engine",
                         "Armor": "challenger2_armor", "Sensors": "hunter_killer_fcs",
                         "Cargo": "du_apfsds_gen3"},
        "unlock_tech": ["uk_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "tornado_gr4",
        "name": "Tornado GR.4",
        "design_family": "uk_air_eighties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "bomber",
        "crew_required": 2,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 92, "reliability": 74, "fuel_consumption": 20, "supply_need": 16,
                      "armor": 12, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "brimstone_proto", "Engine": "tornado_gr4_package",
                         "Sensors": "gps_ins_navigation"},
        "unlock_tech": ["uk_strike_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── GERMANY ───────────────────────────────────────────────────────────────
    {
        "id": "leopard2a4",
        "name": "Leopard 2A4",
        "design_family": "german_armored_eighties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 108,
        "base_stats": {"speed": 36, "reliability": 88, "fuel_consumption": 12, "supply_need": 17,
                      "armor": 60, "top_armor": 38, "hardness": 93},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh120_l44_gun", "Engine": "mtu_mb873_engine",
                         "Armor": "leopard2a4_armor", "Cargo": "dm33_apfsds"},
        "unlock_tech": ["german_mbt_eighties", "nato_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "leopard2a5",
        "name": "Leopard 2A5",
        "design_family": "german_armored_nineties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 115,
        "base_stats": {"speed": 36, "reliability": 88, "fuel_consumption": 12, "supply_need": 18,
                      "armor": 70, "top_armor": 48, "hardness": 95},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh120_l44_gun", "Engine": "mtu_mb873_engine",
                         "Armor": "leopard2a5_wedge_armor", "Sensors": "hunter_killer_fcs",
                         "Cargo": "dm43_apfsds"},
        "unlock_tech": ["german_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ISRAEL ────────────────────────────────────────────────────────────────
    {
        "id": "merkava_mk3",
        "name": "Merkava Mk III",
        "design_family": "israeli_armored_nineties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 105,
        "base_stats": {"speed": 30, "reliability": 82, "fuel_consumption": 14, "supply_need": 18,
                      "armor": 62, "top_armor": 38, "hardness": 92},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "SecondaryWeapon": {"max": 1}},
        "module_loadout": {"MainWeapon": "imi_120mm_gun", "Engine": "merkava_avds_engine",
                         "Armor": "merkava_mk3_armor", "SecondaryWeapon": "spike_atgm"},
        "unlock_tech": ["israeli_mbt_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "magach7_mbt",
        "name": "Magach 7",
        "design_family": "israeli_armored_eighties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 85,
        "base_stats": {"speed": 30, "reliability": 76, "fuel_consumption": 14, "supply_need": 17,
                      "armor": 50, "top_armor": 30, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "m68a1_105mm_gun", "Engine": "avds_1790_engine",
                         "Armor": "magach7_era"},
        "unlock_tech": ["israeli_mbt_eighties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f15i_raam",
        "name": "F-15I Ra'am",
        "design_family": "israeli_air_nineties",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 2,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 104, "reliability": 82, "fuel_consumption": 24, "supply_need": 18,
                      "armor": 14, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "derby_bvr_missile", "Engine": "pratt_f100_f15",
                         "Sensors": "kfir2000_package"},
        "unlock_tech": ["israeli_fighters_nineties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if tpl["id"] in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\n1980s–1990s templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
