#!/usr/bin/env python3
"""Generate WWII equipment module JSON files for Epochs of Ascendancy."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ─── USA · TANK GUNS ───────────────────────────────────────────────────
    {"id": "37mm_m6_gun", "name": "37mm M6 Gun", "category": "MainWeapon", "tier": 1,
     "soft_attack": 32, "hard_attack": 22, "piercing": 52, "air_attack": 4,
     "cost": {"steel": 8}, "production_time": 35,
     "special_flags": ["early_war", "light_tank"],
     "description": "Standard U.S. light tank gun (M3/M5 Stuart). Adequate in 1941–42; obsolete against medium tanks."},
    {"id": "76mm_m1_gun", "name": "76mm M1 Gun", "category": "MainWeapon", "tier": 2,
     "soft_attack": 50, "hard_attack": 38, "piercing": 78, "air_attack": 5,
     "cost": {"steel": 16, "rubber": 1}, "production_time": 55,
     "special_flags": ["decent_ap"],
     "description": "Up-gunned Sherman (M4A1/A3 76 mm). Much improved AP performance vs Panther and early Tigers."},
    {"id": "90mm_m3_gun", "name": "90mm M3 Gun", "category": "MainWeapon", "tier": 3,
     "soft_attack": 58, "hard_attack": 55, "piercing": 105, "air_attack": 6,
     "cost": {"steel": 24, "explosives": 3}, "production_time": 75,
     "special_flags": ["excellent_ap", "late_war"],
     "description": "M36 Jackson and M26 Pershing main gun. Primary U.S. late-war tank killer."},
    # ─── USA · TANK ENGINES / ARMOR / COMMS ──────────────────────────────────
    {"id": "ford_gaa_v8_engine", "name": "Ford GAA V-8", "category": "Engine", "tier": 2,
     "reliability_bonus": 10, "fuel_efficiency": 4, "speed_bonus": 6,
     "cost": {"steel": 12, "aluminum": 6}, "production_time": 40,
     "description": "500 hp gasoline V-8 for Sherman variants. Reliable and mass-produced."},
    {"id": "chrysler_multibank_engine", "name": "Chrysler A57 Multibank", "category": "Engine", "tier": 2,
     "reliability_bonus": -6, "fuel_efficiency": -2, "speed_bonus": 4,
     "cost": {"steel": 14, "rubber": 2}, "production_time": 45,
     "special_flags": ["complex"],
     "description": "Five-car-engine Sherman powerplant (M4A4). Notorious maintenance burden."},
    {"id": "m4_applique_armor", "name": "M4 Appliqué Armor Kit", "category": "Armor", "tier": 2,
     "armor_bonus": 18, "top_armor_bonus": 8, "reliability_penalty": -3,
     "cost": {"steel": 16}, "production_time": 35,
     "description": "Field-applied armor plates for Sherman hull and turret. Modest upgrade without new chassis."},
    {"id": "scr_508_radio", "name": "SCR-508 Tank Radio", "category": "Communications", "tier": 2,
     "reliability_bonus": 4,
     "cost": {"steel": 2, "electronics": 5, "copper": 3}, "production_time": 20,
     "special_flags": ["tank_platoon"],
     "description": "Standard U.S. armored vehicle FM radio for platoon coordination."},
    # ─── USA · AIR ───────────────────────────────────────────────────────────
    {"id": "m2_browning_gun_pod", "name": "M2 Browning Gun Pod", "category": "MainWeapon", "tier": 2,
     "soft_attack": 20, "hard_attack": 8, "piercing": 18, "air_attack": 38,
     "cost": {"steel": 5, "aluminum": 2}, "production_time": 25,
     "special_flags": ["air_superiority"],
     "description": "Representative .50 cal armament (P-47, P-51, B-17). High volume of fire vs aircraft."},
    {"id": "anm2_20mm_cannon", "name": "AN/M2 20mm Cannon", "category": "MainWeapon", "tier": 3,
     "soft_attack": 26, "hard_attack": 16, "piercing": 34, "air_attack": 44,
     "cost": {"steel": 7, "aluminum": 4}, "production_time": 38,
     "description": "Hispano-derived 20 mm for P-39 and some late-war fighters/bombers."},
    {"id": "allison_v1710_engine", "name": "Allison V-1710", "category": "Engine", "tier": 2,
     "reliability_bonus": 6, "fuel_efficiency": 5, "speed_bonus": 12,
     "cost": {"steel": 10, "aluminum": 12}, "production_time": 48,
     "description": "1,475 hp V-12 on P-38, P-39, early P-51. Strong at low altitude; weaker high-altitude performance."},
    {"id": "pratt_whitney_r2800", "name": "Pratt & Whitney R-2800", "category": "Engine", "tier": 3,
     "reliability_bonus": 12, "fuel_efficiency": 4, "speed_bonus": 15,
     "cost": {"steel": 12, "aluminum": 14, "rubber": 2}, "production_time": 55,
     "special_flags": ["fighter_powerplant"],
     "description": "2,000 hp Double Wasp on P-47 Thunderbolt. Excellent power and ruggedness."},
    {"id": "us_1000lb_bomb_load", "name": "1,000 lb Bomb Load", "category": "MainWeapon", "tier": 2,
     "soft_attack": 72, "hard_attack": 16, "piercing": 10, "air_attack": 10,
     "cost": {"steel": 4, "explosives": 28}, "production_time": 40,
     "special_flags": ["tactical_bombing"],
     "description": "Medium bomber / fighter-bomber load (B-25, A-36, P-47 ground attack)."},
    {"id": "us_mark_iii_sight", "name": "Mark III Gyro Sight", "category": "Sensors", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 3, "electronics": 8, "optics": 4}, "production_time": 35,
     "special_flags": ["fighter_aiming"],
     "description": "Lead-computing gunsight for U.S. fighters. Improves deflection shooting accuracy."},

    # ─── UK · TANK GUNS ────────────────────────────────────────────────────
    {"id": "qf_2pdr_gun", "name": "QF 2-pdr", "category": "MainWeapon", "tier": 1,
     "soft_attack": 28, "hard_attack": 20, "piercing": 48, "air_attack": 3,
     "cost": {"steel": 7}, "production_time": 32,
     "description": "Early-war British cruiser/light tank gun. Outclassed by 1942."},
    {"id": "qf_6pdr_gun", "name": "QF 6-pdr Mk III", "category": "MainWeapon", "tier": 2,
     "soft_attack": 44, "hard_attack": 36, "piercing": 72, "air_attack": 4,
     "cost": {"steel": 12}, "production_time": 48,
     "special_flags": ["decent_ap"],
     "description": "Churchill and Crusader up-gun. Credible threat to Panzer III/IV."},
    {"id": "qf_17pdr_gun", "name": "QF 17-pdr", "category": "MainWeapon", "tier": 3,
     "soft_attack": 52, "hard_attack": 58, "piercing": 115, "air_attack": 5,
     "cost": {"steel": 22, "explosives": 2}, "production_time": 72,
     "special_flags": ["excellent_ap"],
     "description": "Firefly Sherman and Challenger gun. One of the best Allied anti-tank guns."},
    {"id": "qf_25pdr_gun", "name": "QF 25-pdr Field Gun", "category": "MainWeapon", "tier": 2,
     "soft_attack": 78, "hard_attack": 14, "piercing": 28, "air_attack": 2,
     "cost": {"steel": 14, "explosives": 10}, "production_time": 58,
     "special_flags": ["excellent_vs_soft", "artillery"],
     "description": "Bishop/Crusader CS and towed artillery. Outstanding HE; limited tank AP."},
    # ─── UK · TANK ENGINES / ARMOR / COMMS ───────────────────────────────────
    {"id": "rolls_royce_meteor", "name": "Rolls-Royce Meteor", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": 3, "speed_bonus": 7,
     "cost": {"steel": 16, "aluminum": 8}, "production_time": 50,
     "description": "Merlin-derived 600 hp V-12 for Cromwell and Comet. Reliable for a British tank engine."},
    {"id": "bedford_twin_six_engine", "name": "Bedford Twin-Six", "category": "Engine", "tier": 2,
     "reliability_bonus": 5, "fuel_efficiency": 2, "speed_bonus": 4,
     "cost": {"steel": 10}, "production_time": 38,
     "description": "Churchill tank powerplant. Underpowered but dependable."},
    {"id": "churchill_cast_armor", "name": "Churchill Cast Armor", "category": "Armor", "tier": 3,
     "armor_bonus": 46, "top_armor_bonus": 20, "reliability_penalty": -6,
     "cost": {"steel": 40}, "production_time": 65,
     "special_flags": ["heavy_armor"],
     "description": "Thick cast armor on Churchill Mk VII. Excellent protection; very slow."},
    {"id": "wireless_set_no19", "name": "Wireless Set No. 19", "category": "Communications", "tier": 2,
     "reliability_bonus": 4,
     "cost": {"steel": 2, "electronics": 7, "copper": 3}, "production_time": 24,
     "description": "Standard British tank brigade radio (infantry/tank liaison capable)."},
    # ─── UK · AIR ────────────────────────────────────────────────────────────
    {"id": "hispano_mk2_cannon", "name": "Hispano Mk II", "category": "MainWeapon", "tier": 3,
     "soft_attack": 25, "hard_attack": 15, "piercing": 33, "air_attack": 45,
     "cost": {"steel": 7, "aluminum": 3}, "production_time": 36,
     "description": "20 mm cannon on Spitfire, Typhoon, and many RAF types."},
    {"id": "browning_303_battery", "name": ".303 Browning Battery", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 4, "piercing": 6, "air_attack": 22,
     "cost": {"steel": 4}, "production_time": 18,
     "description": "Early-war rifle-caliber wing guns (Hurricane, Spitfire Mk I)."},
    {"id": "merlin_xx_engine", "name": "Rolls-Royce Merlin XX", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": 6, "speed_bonus": 14,
     "cost": {"steel": 12, "aluminum": 16}, "production_time": 58,
     "special_flags": ["supercharged"],
     "description": "1,480 hp Merlin for Spitfire, Hurricane, and Lancaster. Legendary high-altitude performance."},
    {"id": "griffon_engine", "name": "Rolls-Royce Griffon", "category": "Engine", "tier": 4,
     "reliability_bonus": 6, "fuel_efficiency": 4, "speed_bonus": 16,
     "cost": {"steel": 14, "aluminum": 18}, "production_time": 62,
     "description": "Late-war 2,000+ hp engine for Spitfire Mk XIV and naval aircraft."},
    {"id": "uk_4000lb_bomb_load", "name": "4,000 lb Cookie Load", "category": "MainWeapon", "tier": 3,
     "soft_attack": 92, "hard_attack": 20, "piercing": 12, "air_attack": 8,
     "cost": {"steel": 5, "explosives": 44}, "production_time": 52,
     "special_flags": ["strategic_bombing", "area_damage"],
     "description": "Lancaster block-buster load. Devastating against urban and industrial targets."},
    {"id": "mk14_gyro_sight", "name": "Mk XIV Gyro Gunsight", "category": "Sensors", "tier": 3,
     "reliability_bonus": 3,
     "cost": {"electronics": 10, "optics": 6}, "production_time": 42,
     "description": "British lead-computing sight. Major boost to fighter effectiveness."},

    # ─── GERMANY · TANK GUNS (supplement existing) ─────────────────────────
    {"id": "kwk_38_50mm_gun", "name": "5 cm KwK 38 L/42", "category": "MainWeapon", "tier": 1,
     "soft_attack": 38, "hard_attack": 28, "piercing": 58, "air_attack": 4,
     "cost": {"steel": 12}, "production_time": 42,
     "description": "Panzer III Ausf. J main armament. Fine vs 1941 targets; inadequate by 1943."},
    {"id": "kwk_40_75mm_gun", "name": "7.5 cm KwK 40 L/48", "category": "MainWeapon", "tier": 2,
     "soft_attack": 48, "hard_attack": 42, "piercing": 82, "air_attack": 5,
     "cost": {"steel": 18, "explosives": 2}, "production_time": 58,
     "special_flags": ["decent_ap"],
     "description": "Panzer IV Ausf. G–J gun. Backbone of German medium anti-tank firepower."},
    {"id": "kwk_43_88mm_gun", "name": "8.8 cm KwK 43 L/71", "category": "MainWeapon", "tier": 4,
     "soft_attack": 56, "hard_attack": 68, "piercing": 135, "air_attack": 4,
     "cost": {"steel": 32, "explosives": 5, "chromium": 4}, "production_time": 95,
     "special_flags": ["excellent_ap", "long_range"],
     "description": "Tiger II and late Jagdpanther gun. Superb penetration at all ranges."},
    {"id": "man_maybach_600_engine", "name": "Maybach HL 230 (Panther)", "category": "Engine", "tier": 3,
     "reliability_bonus": -6, "fuel_efficiency": -3, "speed_bonus": 5,
     "cost": {"steel": 17, "aluminum": 4}, "production_time": 52,
     "description": "Panther Ausf. G powerplant. Powerful but prone to final-drive failures."},
    {"id": "schurzen_armor_skirts", "name": "Schürzen Side Skirts", "category": "Armor", "tier": 2,
     "armor_bonus": 12, "top_armor_bonus": 0, "reliability_penalty": -2,
     "cost": {"steel": 8}, "production_time": 20,
     "special_flags": ["anti_cumulative", "anti_heat"],
     "description": "Hinged side plates vs Soviet AT rifles and early hollow-charge warheads."},
    # ─── GERMANY · AIR (supplement) ────────────────────────────────────────
    {"id": "mk108_30mm_cannon", "name": "MK 108 30mm", "category": "MainWeapon", "tier": 3,
     "soft_attack": 32, "hard_attack": 22, "piercing": 40, "air_attack": 52,
     "cost": {"steel": 8, "explosives": 4}, "production_time": 42,
     "special_flags": ["bomber_killer"],
     "description": "Low-velocity but devastating 30 mm (Bf 109K, Fw 190, Me 262). Few hits destroy bombers."},
    {"id": "sc1000_bomb_rack", "name": "SC 1000 Bomb Rack", "category": "MainWeapon", "tier": 3,
     "soft_attack": 105, "hard_attack": 14, "piercing": 8, "air_attack": 10,
     "cost": {"steel": 10, "explosives": 38}, "production_time": 48,
     "description": "1,000 kg general-purpose bomb for Ju 88 and He 111."},

    # ─── USSR · TANK GUNS ────────────────────────────────────────────────────
    {"id": "45mm_m1937_gun", "name": "45 mm M1937", "category": "MainWeapon", "tier": 1,
     "soft_attack": 34, "hard_attack": 24, "piercing": 55, "air_attack": 4,
     "cost": {"steel": 7}, "production_time": 34,
     "description": "BT-7 and T-26 gun. Adequate early war; quickly outranged."},
    {"id": "76mm_f34_gun", "name": "76.2 mm F-34", "category": "MainWeapon", "tier": 2,
     "soft_attack": 46, "hard_attack": 36, "piercing": 74, "air_attack": 5,
     "cost": {"steel": 13}, "production_time": 50,
     "special_flags": ["decent_ap"],
     "description": "T-34/76 main gun. Well-balanced medium tank armament for 1942–43."},
    {"id": "85mm_d5t_gun", "name": "85 mm D-5T", "category": "MainWeapon", "tier": 3,
     "soft_attack": 54, "hard_attack": 48, "piercing": 95, "air_attack": 6,
     "cost": {"steel": 20, "explosives": 2}, "production_time": 68,
     "description": "T-34/85 and SU-85 gun. Restores Soviet AP parity vs Panther."},
    {"id": "122mm_d25t_gun", "name": "122 mm D-25T", "category": "MainWeapon", "tier": 4,
     "soft_attack": 70, "hard_attack": 65, "piercing": 128, "air_attack": 4,
     "cost": {"steel": 30, "explosives": 6}, "production_time": 90,
     "special_flags": ["excellent_ap", "excellent_vs_soft"],
     "description": "IS-2 heavy tank gun. Devastating HE and AP; slow reload."},
    # ─── USSR · TANK ENGINES / ARMOR / COMMS ─────────────────────────────────
    {"id": "v2_diesel_engine", "name": "V-2-34 Diesel", "category": "Engine", "tier": 2,
     "reliability_bonus": 6, "fuel_efficiency": 8, "speed_bonus": 5,
     "cost": {"steel": 14}, "production_time": 44,
     "special_flags": ["diesel"],
     "description": "500 hp diesel for T-34. Safer fuel; good cold-weather starting with effort."},
    {"id": "mikulin_v12_engine", "name": "Mikulin V-12 (Klimov)", "category": "Engine", "tier": 3,
     "reliability_bonus": 2, "fuel_efficiency": 4, "speed_bonus": 6,
     "cost": {"steel": 15, "aluminum": 5}, "production_time": 48,
     "description": "IS-series and KV engines. High power; maintenance-intensive."},
    {"id": "t34_sloped_armor", "name": "T-34 Sloped Armor", "category": "Armor", "tier": 2,
     "armor_bonus": 38, "top_armor_bonus": 16, "reliability_penalty": -2,
     "cost": {"steel": 28}, "production_time": 48,
     "special_flags": ["sloped_armor"],
     "description": "45 mm sloped plates at 60°. Excellent effective protection for weight."},
    {"id": "is2_heavy_armor", "name": "IS-2 Heavy Armor", "category": "Armor", "tier": 4,
     "armor_bonus": 50, "top_armor_bonus": 22, "reliability_penalty": -7,
     "cost": {"steel": 44, "chromium": 4}, "production_time": 72,
     "description": "120 mm frontal casting on IS-2. Top-tier protection with mobility cost."},
    {"id": "radio_71tk1", "name": "71-TK-1 Radio", "category": "Communications", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 2, "electronics": 5, "copper": 2}, "production_time": 22,
     "description": "Standard Soviet tank brigade radio (mid-war onward)."},
    # ─── USSR · AIR ──────────────────────────────────────────────────────────
    {"id": "shvak_20mm_cannon", "name": "ShVAK 20mm", "category": "MainWeapon", "tier": 2,
     "soft_attack": 23, "hard_attack": 13, "piercing": 30, "air_attack": 42,
     "cost": {"steel": 6, "aluminum": 3}, "production_time": 34,
     "description": "LaGG-3, La-5, and Il-2 wing cannon. Reliable Soviet autocannon."},
    {"id": "berezin_ub_gun", "name": "Berezin UB", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 16, "hard_attack": 6, "piercing": 14, "air_attack": 26,
     "cost": {"steel": 4}, "production_time": 20,
     "description": "12.7 mm heavy machine gun supplement on Il-2 and fighters."},
    {"id": "klimov_m105_engine", "name": "Klimov M-105", "category": "Engine", "tier": 2,
     "reliability_bonus": 4, "fuel_efficiency": 5, "speed_bonus": 11,
     "cost": {"steel": 10, "aluminum": 11}, "production_time": 46,
     "description": "Hispano-Suiza derived V-12 for Yak and MiG fighters."},
    {"id": "ash82_radial_engine", "name": "Shvetsov ASh-82", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": 4, "speed_bonus": 13,
     "cost": {"steel": 11, "aluminum": 12}, "production_time": 50,
     "description": "1,700 hp radial for La-5/7. Excellent low-altitude fighter engine."},
    {"id": "fab250_bomb_load", "name": "FAB-250 Bomb Load", "category": "MainWeapon", "tier": 2,
     "soft_attack": 68, "hard_attack": 12, "piercing": 8, "air_attack": 9,
     "cost": {"steel": 4, "explosives": 22}, "production_time": 38,
     "description": "Standard Pe-2 / Il-4 tactical bomb load."},
    {"id": "fab500_bomb_load", "name": "FAB-500 Bomb Load", "category": "MainWeapon", "tier": 3,
     "soft_attack": 85, "hard_attack": 18, "piercing": 10, "air_attack": 10,
     "cost": {"steel": 5, "explosives": 32}, "production_time": 45,
     "description": "Heavier Soviet tactical bombing load for Il-4 and Tu-2."},

    # ─── JAPAN · TANK GUNS ───────────────────────────────────────────────────
    {"id": "type97_57mm_gun", "name": "Type 97 57 mm", "category": "MainWeapon", "tier": 1,
     "soft_attack": 36, "hard_attack": 18, "piercing": 42, "air_attack": 3,
     "cost": {"steel": 9}, "production_time": 38,
     "special_flags": ["excellent_vs_soft"],
     "description": "Chi-Ha main gun. Good HE for infantry support; weak AP."},
    {"id": "type1_47mm_gun", "name": "Type 1 47 mm AT Gun", "category": "MainWeapon", "tier": 2,
     "soft_attack": 30, "hard_attack": 32, "piercing": 70, "air_attack": 3,
     "cost": {"steel": 11}, "production_time": 45,
     "description": "Chi-Ha Kai / Shinhoto. Credible AP for a light medium tank."},
    {"id": "type3_75mm_gun", "name": "Type 3 75 mm", "category": "MainWeapon", "tier": 2,
     "soft_attack": 44, "hard_attack": 34, "piercing": 68, "air_attack": 4,
     "cost": {"steel": 14}, "production_time": 52,
     "description": "Chi-Nu and late-war tank destroyer gun. Modest but workable AP."},
    {"id": "type99_88mm_gun", "name": "Type 99 88 mm", "category": "MainWeapon", "tier": 3,
     "soft_attack": 50, "hard_attack": 46, "piercing": 88, "air_attack": 4,
     "cost": {"steel": 20}, "production_time": 70,
     "description": "Chi-Ri II prototype gun. Rare; competitive on paper but few built."},
    # ─── JAPAN · TANK ENGINES / ARMOR / COMMS ────────────────────────────────
    {"id": "mitsubishi_al_engine", "name": "Mitsubishi AL Type", "category": "Engine", "tier": 2,
     "reliability_bonus": 3, "fuel_efficiency": 3, "speed_bonus": 4,
     "cost": {"steel": 10, "aluminum": 4}, "production_time": 40,
     "description": "Air-cooled diesel for Chi-Ha family. Modest power; suited to jungle logistics."},
    {"id": "japanese_riveted_armor", "name": "Japanese Riveted Armor", "category": "Armor", "tier": 1,
     "armor_bonus": 22, "top_armor_bonus": 10, "reliability_penalty": -4,
     "cost": {"steel": 18}, "production_time": 35,
     "special_flags": ["weak_vs_ap"],
     "description": "Typical riveted plates on Chi-Ha and Ke-Ni. Vulnerable to Allied medium guns."},
    {"id": "type3_ku_radio", "name": "Type 3 Ku Radio", "category": "Communications", "tier": 2,
     "reliability_bonus": 1,
     "cost": {"steel": 2, "electronics": 4, "copper": 2}, "production_time": 24,
     "description": "Standard IJA tank company radio. Shorter range than Western sets."},
    # ─── JAPAN · AIR ─────────────────────────────────────────────────────────
    {"id": "type99_mk2_cannon", "name": "Type 99 Mk II 20mm", "category": "MainWeapon", "tier": 2,
     "soft_attack": 22, "hard_attack": 12, "piercing": 28, "air_attack": 40,
     "cost": {"steel": 6, "aluminum": 2}, "production_time": 32,
     "description": "Zero and Ki-43 cannon. Light but effective with good agility."},
    {"id": "type97_7_7mm_gun", "name": "Type 97 7.7 mm", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 11, "hard_attack": 3, "piercing": 5, "air_attack": 16,
     "cost": {"steel": 3}, "production_time": 14,
     "description": "Rifle-caliber supplement on early Zero and Ki-27."},
    {"id": "sakae_radial_engine", "name": "Sakae 21 Radial", "category": "Engine", "tier": 2,
     "reliability_bonus": 5, "fuel_efficiency": 6, "speed_bonus": 11,
     "cost": {"steel": 9, "aluminum": 10}, "production_time": 44,
     "description": "1,130 hp engine for A6M Zero. Excellent range and agility enabler."},
    {"id": "kinsei_radial_engine", "name": "Kinsei 51 Radial", "category": "Engine", "tier": 3,
     "reliability_bonus": 4, "fuel_efficiency": 4, "speed_bonus": 12,
     "cost": {"steel": 10, "aluminum": 11}, "production_time": 48,
     "description": "1,560 hp on Ki-61 and D3A. More power for heavier airframes."},
    {"id": "type99_800kg_bomb", "name": "Type 99 800 kg Bomb", "category": "MainWeapon", "tier": 2,
     "soft_attack": 78, "hard_attack": 14, "piercing": 8, "air_attack": 9,
     "cost": {"steel": 5, "explosives": 26}, "production_time": 42,
     "description": "Kate and Val dive/tactical bomb load."},

    # ─── ITALY · TANK GUNS ───────────────────────────────────────────────────
    {"id": "47mm_ansaldo_gun", "name": "47 mm Ansaldo", "category": "MainWeapon", "tier": 1,
     "soft_attack": 30, "hard_attack": 26, "piercing": 58, "air_attack": 3,
     "cost": {"steel": 9}, "production_time": 40,
     "description": "M13/40 and M14/41 gun. Weak HE; acceptable AP in 1940–41."},
    {"id": "75mm_ansaldo_l34_gun", "name": "75 mm Ansaldo L/34", "category": "MainWeapon", "tier": 2,
     "soft_attack": 42, "hard_attack": 30, "piercing": 62, "air_attack": 4,
     "cost": {"steel": 13}, "production_time": 50,
     "description": "P40 and Semovente 75/34. Best Italian medium tank gun."},
    {"id": "90mm_ansaldo_gun", "name": "90 mm Ansaldo L/53", "category": "MainWeapon", "tier": 3,
     "soft_attack": 50, "hard_attack": 44, "piercing": 85, "air_attack": 4,
     "cost": {"steel": 19}, "production_time": 68,
     "description": "P43 and Semovente 90/53. Strong on paper; very few produced."},
    # ─── ITALY · TANK ENGINES / ARMOR / COMMS ────────────────────────────────
    {"id": "spa_diesel_v8_engine", "name": "SPA 8T Diesel V-8", "category": "Engine", "tier": 2,
     "reliability_bonus": -2, "fuel_efficiency": 5, "speed_bonus": 3,
     "cost": {"steel": 11}, "production_time": 42,
     "description": "Underpowered diesel on M13/40–M14/41. Notorious reliability issues."},
    {"id": "italian_riveted_armor", "name": "Italian Riveted Armor", "category": "Armor", "tier": 1,
     "armor_bonus": 20, "top_armor_bonus": 8, "reliability_penalty": -3,
     "cost": {"steel": 16}, "production_time": 32,
     "description": "Thin riveted armor on Italian mediums. Poor survivability after 1942."},
    {"id": "rf2ca_radio", "name": "RF 2CA Radio", "category": "Communications", "tier": 1,
     "reliability_bonus": 0,
     "cost": {"steel": 2, "electronics": 3, "copper": 2}, "production_time": 22,
     "description": "Basic Italian armored vehicle radio. Limited range and reliability."},
    # ─── ITALY · AIR ─────────────────────────────────────────────────────────
    {"id": "breda_safat_12_7mm", "name": "Breda-SAFAT 12.7 mm", "category": "MainWeapon", "tier": 1,
     "soft_attack": 18, "hard_attack": 8, "piercing": 16, "air_attack": 30,
     "cost": {"steel": 5}, "production_time": 24,
     "description": "Macchi C.200 and SM.79 defensive armament. Underpowered vs Allied fighters."},
    {"id": "mauser_mg151_italy", "name": "Mauser MG 151/20 (license)", "category": "MainWeapon", "tier": 2,
     "soft_attack": 22, "hard_attack": 13, "piercing": 30, "air_attack": 40,
     "cost": {"steel": 6, "aluminum": 2}, "production_time": 32,
     "description": "License-built 20 mm on Macchi C.202/205 and Bf 109G-6 (Co-Belligerent)."},
    {"id": "alfa_romeo_ra1000", "name": "Alfa Romeo RA.1000", "category": "Engine", "tier": 2,
     "reliability_bonus": 3, "fuel_efficiency": 4, "speed_bonus": 10,
     "cost": {"steel": 10, "aluminum": 10}, "production_time": 46,
     "description": "License DB 601 on C.202 Folgore. Competitive Italian fighter engine."},
    {"id": "ap50_bomb_load", "name": "AP 50 Bomb Load", "category": "MainWeapon", "tier": 1,
     "soft_attack": 55, "hard_attack": 10, "piercing": 6, "air_attack": 8,
     "cost": {"steel": 3, "explosives": 16}, "production_time": 32,
     "description": "Light tactical load for SM.79 and CR.42 ground attack."},

    # ─── FRANCE · TANK GUNS ──────────────────────────────────────────────────
    {"id": "47mm_sa37_gun", "name": "47 mm SA 37", "category": "MainWeapon", "tier": 2,
     "soft_attack": 32, "hard_attack": 30, "piercing": 66, "air_attack": 3,
     "cost": {"steel": 10}, "production_time": 42,
     "description": "Char B1 bis and S35 gun. Good AP for 1940; limited HE."},
    {"id": "75mm_sa35_gun", "name": "75 mm SA 35", "category": "MainWeapon", "tier": 1,
     "soft_attack": 52, "hard_attack": 16, "piercing": 32, "air_attack": 2,
     "cost": {"steel": 12, "explosives": 4}, "production_time": 45,
     "special_flags": ["excellent_vs_soft"],
     "description": "Char B1 hull howitzer. Excellent vs infantry; poor anti-tank."},
    {"id": "75mm_sa44_gun", "name": "75 mm SA 44", "category": "MainWeapon", "tier": 2,
     "soft_attack": 44, "hard_attack": 32, "piercing": 64, "air_attack": 4,
     "cost": {"steel": 13}, "production_time": 48,
     "description": "AMX-13 prototype lineage / late Char upgrades. Balanced medium gun."},
    # ─── FRANCE · TANK ENGINES / ARMOR / COMMS ───────────────────────────────
    {"id": "renault_v6_engine", "name": "Renault V-6", "category": "Engine", "tier": 1,
     "reliability_bonus": 2, "fuel_efficiency": 2, "speed_bonus": 2,
     "cost": {"steel": 8}, "production_time": 35,
     "description": "Char B1 and R35 powerplant. Underpowered and cramped."},
    {"id": "french_cast_armor", "name": "French Cast Armor", "category": "Armor", "tier": 2,
     "armor_bonus": 32, "top_armor_bonus": 14, "reliability_penalty": -4,
     "cost": {"steel": 26}, "production_time": 50,
     "description": "Char B1 and S35 cast sections. Good protection for 1940; heavy."},
    {"id": "er538_radio", "name": "ER 538 Radio", "category": "Communications", "tier": 1,
     "reliability_bonus": 1,
     "cost": {"steel": 2, "electronics": 4}, "production_time": 22,
     "description": "French tank squadron radio (1940 standard)."},
    # ─── FRANCE · AIR ────────────────────────────────────────────────────────
    {"id": "hs404_20mm_cannon", "name": "Hispano-Suiza HS.404", "category": "MainWeapon", "tier": 2,
     "soft_attack": 24, "hard_attack": 14, "piercing": 31, "air_attack": 42,
     "cost": {"steel": 7, "aluminum": 3}, "production_time": 34,
     "description": "D.520 and late MS.406 armament. Competitive 20 mm cannon."},
    {"id": "gnome_rhone_14n", "name": "Gnome-Rhône 14N", "category": "Engine", "tier": 2,
     "reliability_bonus": 4, "fuel_efficiency": 5, "speed_bonus": 10,
     "cost": {"steel": 9, "aluminum": 9}, "production_time": 44,
     "description": "Dewoitine D.520 radial. One of the best French fighter engines."},
    {"id": "french_250kg_bomb", "name": "250 kg Bomb Load", "category": "MainWeapon", "tier": 2,
     "soft_attack": 62, "hard_attack": 12, "piercing": 8, "air_attack": 8,
     "cost": {"steel": 3, "explosives": 18}, "production_time": 36,
     "description": "Amiot 143 and LeO 451 tactical bombing load."},

    # ─── SHARED / SPECIAL ────────────────────────────────────────────────────
    {"id": "coaxial_mg_mount", "name": "Coaxial MG Mount", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 4, "piercing": 8, "air_attack": 2,
     "cost": {"steel": 3}, "production_time": 12,
     "description": "Generic coaxial machine gun for tanks (MG 34, Browning, DT). Anti-infantry supplement."},
    {"id": "hull_mg_mount", "name": "Hull MG Mount", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 12, "hard_attack": 3, "piercing": 6, "air_attack": 2,
     "cost": {"steel": 2}, "production_time": 10,
     "description": "Bow machine gun for suppressing infantry and soft targets."},
    {"id": "extra_fuel_tanks", "name": "Extra Fuel Tanks", "category": "ExtraFuel", "tier": 1,
     "reliability_bonus": -3, "fuel_efficiency": -8, "speed_bonus": 0,
     "cost": {"steel": 4, "rubber": 2}, "production_time": 15,
     "special_flags": ["extended_range", "fire_risk"],
     "description": "External or enlarged fuel stowage. Extends operational range at increased fire risk."},
    {"id": "nbc_protection_kit", "name": "NBC Protection Kit", "category": "NBC_Protection", "tier": 3,
     "reliability_bonus": -2,
     "cost": {"steel": 6, "rubber": 4, "chemicals": 6}, "production_time": 30,
     "special_flags": ["chemical_warfare"],
     "description": "Sealed fighting compartment and filtration. Rare pre-1945 but available for late scenarios."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = 0
    skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    print(f"\nDone: {created} created, {skipped} skipped (already exist), {len(list(MODULES_DIR.glob('*.json')))} total modules.")


if __name__ == "__main__":
    main()
