#!/usr/bin/env python3
"""Submarine modules and unit templates: pre-WWI through 2030s, all major players."""

from __future__ import annotations

from template_export import write_unit_template
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "data"
MODULES_DIR = ROOT / "modules"
TEMPLATES_DIR = ROOT / "unit_templates"

# fmt: off
MODULES: list[dict] = [
    # ─── Torpedoes (submarine-launched) ────────────────────────────────────────
    {"id": "whitehead_18in_torpedo", "name": "Whitehead 18\" Torpedo", "category": "SecondaryWeapon", "tier": 1,
     "soft_attack": 14, "hard_attack": 28, "piercing": 18, "anti_ship": 42,
     "cost": {"steel": 6, "explosives": 8}, "production_time": 38,
     "special_flags": ["naval", "torpedo", "pre_ww1", "submarine"],
     "description": "Early submarine torpedo on Holland and British coastal boats."},
    {"id": "g7a_torpedo_sub", "name": "G7a Torpedo (U-boat)", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 16, "hard_attack": 32, "piercing": 22, "anti_ship": 48,
     "cost": {"steel": 8, "explosives": 10}, "production_time": 42,
     "special_flags": ["germany", "naval", "torpedo", "ww2", "submarine"],
     "description": "Steam torpedo standard on Type VII and IX U-boats."},
    {"id": "g7es_acoustic_homing", "name": "G7es Acoustic Homing", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 18, "hard_attack": 38, "piercing": 24, "anti_ship": 58,
     "cost": {"steel": 8, "explosives": 12, "electronics": 6}, "production_time": 50,
     "special_flags": ["germany", "homing", "ww2", "submarine", "late_war"],
     "description": "T5 Zaunkönig acoustic homing torpedo. Allied countermeasures developed rapidly."},
    {"id": "mk14_torpedo_us", "name": "Mk 14 Torpedo", "category": "SecondaryWeapon", "tier": 2,
     "soft_attack": 15, "hard_attack": 34, "piercing": 23, "anti_ship": 52,
     "cost": {"steel": 8, "explosives": 12, "electronics": 4}, "production_time": 45,
     "special_flags": ["usa", "ww2", "submarine", "torpedo"],
     "description": "Standard U.S. submarine torpedo early WWII. Controversial reliability problems."},
    {"id": "mk37_torpedo", "name": "Mk 37 Torpedo", "category": "SecondaryWeapon", "tier": 5,
     "soft_attack": 22, "hard_attack": 48, "piercing": 30, "anti_ship": 72,
     "cost": {"steel": 10, "electronics": 22, "explosives": 14}, "production_time": 62,
     "special_flags": ["usa", "cold_war", "submarine", "homing"],
     "description": "Electric homing torpedo for postwar U.S. submarines."},
    {"id": "type95_sub_torpedo", "name": "Type 95 Sub Torpedo", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 17, "hard_attack": 36, "piercing": 25, "anti_ship": 55,
     "cost": {"steel": 8, "explosives": 12}, "production_time": 46,
     "special_flags": ["japan", "ww2", "submarine", "oxygen_torpedo"],
     "description": "Oxygen-powered torpedo on IJN submarines. Long range and wakeless."},
    {"id": "spearfish_torpedo_uk", "name": "Spearfish Torpedo", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 26, "hard_attack": 52, "piercing": 34, "anti_ship": 82,
     "cost": {"steel": 12, "electronics": 32, "explosives": 16}, "production_time": 72,
     "special_flags": ["uk", "submarine", "cold_war", "homing"],
     "description": "Heavyweight torpedo for Royal Navy nuclear and conventional subs."},
    {"id": "va111_shkval_supercavitating", "name": "VA-111 Shkval", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 30, "hard_attack": 55, "piercing": 40, "anti_ship": 90,
     "cost": {"steel": 14, "electronics": 28, "explosives": 22}, "production_time": 80,
     "special_flags": ["russia", "rocket_torpedo", "submarine", "cold_war"],
     "description": "Supercavitating rocket torpedo. Very fast but limited guidance."},
    {"id": "black_shark_torpedo", "name": "Black Shark Torpedo", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 24, "hard_attack": 50, "piercing": 32, "anti_ship": 80,
     "cost": {"steel": 10, "electronics": 30, "explosives": 15}, "production_time": 70,
     "special_flags": ["italy", "export", "submarine", "wire_guided"],
     "description": "Italian heavyweight torpedo on Scorpene and export subs."},
    {"id": "yu6_china_torpedo", "name": "Yu-6 Torpedo", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 24, "hard_attack": 48, "piercing": 30, "anti_ship": 78,
     "cost": {"steel": 10, "electronics": 28, "explosives": 14}, "production_time": 68,
     "special_flags": ["china", "submarine", "homing", "twenty_tens"],
     "description": "Chinese wire-guided heavyweight torpedo for Shang and Yuan classes."},

    # ─── Missiles (SLBM / SLCM) ────────────────────────────────────────────────
    {"id": "polaris_a3_slbm", "name": "Polaris A3 SLBM", "category": "MainWeapon", "tier": 5,
     "soft_attack": 95, "hard_attack": 88, "piercing": 75, "air_attack": 5,
     "cost": {"steel": 20, "electronics": 45, "explosives": 80, "uranium": 12}, "production_time": 120,
     "special_flags": ["usa", "uk", "slbm", "cold_war", "nuclear"],
     "description": "First operational submarine-launched ballistic missile on Resolution and Lafayette classes."},
    {"id": "trident_d5_slbm", "name": "Trident II D5", "category": "MainWeapon", "tier": 8,
     "soft_attack": 120, "hard_attack": 110, "piercing": 90, "air_attack": 8,
     "cost": {"steel": 25, "electronics": 65, "explosives": 100, "uranium": 25}, "production_time": 160,
     "special_flags": ["usa", "uk", "slbm", "nuclear", "twenty_tens"],
     "description": "Ohio and Vanguard SSBN strategic missile. MIRV nuclear deterrent."},
    {"id": "harpoon_sub_launch", "name": "Harpoon (Sub Launch)", "category": "SecondaryWeapon", "tier": 5,
     "soft_attack": 42, "hard_attack": 55, "piercing": 40, "anti_ship": 92,
     "cost": {"steel": 8, "electronics": 28, "explosives": 18}, "production_time": 68,
     "special_flags": ["usa", "anti_ship", "submarine", "cruise_missile"],
     "description": "Submarine-launched anti-ship missile from VLS or capsule."},
    {"id": "exocet_sm39", "name": "Exocet SM39", "category": "SecondaryWeapon", "tier": 5,
     "soft_attack": 40, "hard_attack": 52, "piercing": 38, "anti_ship": 90,
     "cost": {"steel": 8, "electronics": 26, "explosives": 16}, "production_time": 65,
     "special_flags": ["france", "anti_ship", "submarine"],
     "description": "Submarine-launched Exocet. Falklands and multiple export successes."},
    {"id": "kalibr_vls_sub", "name": "Kalibr VLS (Sub)", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 55, "hard_attack": 58, "piercing": 45, "anti_ship": 85, "air_attack": 8,
     "cost": {"steel": 12, "electronics": 38, "explosives": 32}, "production_time": 85,
     "special_flags": ["russia", "cruise_missile", "submarine", "vls"],
     "description": "Kalibr land-attack and anti-ship from improved Kilo and Yasen VLS."},
    {"id": "cj10_china_cruise", "name": "CJ-10 Cruise Missile", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 52, "hard_attack": 55, "piercing": 42, "anti_ship": 82,
     "cost": {"steel": 12, "electronics": 35, "explosives": 28}, "production_time": 80,
     "special_flags": ["china", "cruise_missile", "submarine"],
     "description": "Chinese submarine-launched cruise missile on Shang and Type 093A."},
    {"id": "jl3_slbm_china", "name": "JL-3 SLBM", "category": "MainWeapon", "tier": 8,
     "soft_attack": 115, "hard_attack": 105, "piercing": 88,
     "cost": {"steel": 22, "electronics": 60, "explosives": 95, "uranium": 20}, "production_time": 150,
     "special_flags": ["china", "slbm", "nuclear", "twenty_twenties"],
     "description": "Next-generation Chinese SLBM for Type 096 SSBN."},
    {"id": "bulava_slbm", "name": "RSM-56 Bulava", "category": "MainWeapon", "tier": 7,
     "soft_attack": 110, "hard_attack": 100, "piercing": 85,
     "cost": {"steel": 22, "electronics": 55, "explosives": 90, "uranium": 22}, "production_time": 145,
     "special_flags": ["russia", "slbm", "nuclear", "borei"],
     "description": "Russian SLBM for Borei-class SSBN."},

    # ─── Propulsion ──────────────────────────────────────────────────────────────
    {"id": "holland_diesel_electric", "name": "Holland Diesel-Electric", "category": "Engine", "tier": 1,
     "reliability_bonus": 4, "fuel_efficiency": 6, "speed_bonus": 4,
     "cost": {"steel": 12, "electronics": 4}, "production_time": 55,
     "special_flags": ["usa", "diesel_electric", "pre_ww1", "submarine"],
     "description": "Early gasoline/electric submarine propulsion on Holland boats."},
    {"id": "man_m6v40_uboat_diesel", "name": "MAN M6V40 U-boat Diesel", "category": "Engine", "tier": 3,
     "reliability_bonus": 6, "fuel_efficiency": 4, "speed_bonus": 8,
     "cost": {"steel": 16, "aluminum": 6}, "production_time": 65,
     "special_flags": ["germany", "diesel_electric", "ww2", "uboat"],
     "description": "Type VII U-boat diesel suite. Surface speed and battery charging."},
    {"id": "fairbanks_morse_38d8", "name": "Fairbanks-Morse 38D8", "category": "Engine", "tier": 3,
     "reliability_bonus": 10, "fuel_efficiency": 6, "speed_bonus": 10,
     "cost": {"steel": 18, "aluminum": 8}, "production_time": 70,
     "special_flags": ["usa", "diesel_electric", "ww2", "fleet_boat"],
     "description": "Gato and Balao class opposed-piston diesels. Reliable Pacific workhorse."},
    {"id": "snorkel_fitting", "name": "Snorkel Fitting", "category": "Sensors", "tier": 4,
     "reliability_bonus": 8,
     "cost": {"steel": 8, "electronics": 6, "rubber": 4}, "production_time": 40,
     "special_flags": ["germany", "ww2", "late_war", "submarine", "stealth"],
     "description": "Schnorchel allowing diesel charging at periscope depth. Extended U-boat patrols."},
    {"id": "westinghouse_s5w_reactor", "name": "Westinghouse S5W Reactor", "category": "Engine", "tier": 6,
     "reliability_bonus": 14, "fuel_efficiency": 20, "speed_bonus": 18,
     "cost": {"steel": 25, "uranium": 35, "electronics": 30, "titanium": 8}, "production_time": 140,
     "special_flags": ["usa", "nuclear", "submarine", "cold_war"],
     "description": "Nautilus and Los Angeles lineage pressurized-water reactor. Unlimited endurance."},
    {"id": "ge_s9g_reactor", "name": "GE S9G Reactor", "category": "Engine", "tier": 7,
     "reliability_bonus": 16, "fuel_efficiency": 22, "speed_bonus": 20,
     "cost": {"steel": 28, "uranium": 40, "electronics": 38, "titanium": 12}, "production_time": 155,
     "special_flags": ["usa", "nuclear", "virginia", "twenty_tens"],
     "description": "Virginia-class reactor. Life-of-ship core with high power density."},
    {"id": "vm_reactor_soviet", "name": "VM Pressurized Reactor", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": 18, "speed_bonus": 16,
     "cost": {"steel": 28, "uranium": 38, "electronics": 28}, "production_time": 145,
     "special_flags": ["ussr", "russia", "nuclear", "submarine"],
     "description": "Soviet/Russian submarine reactor on November through Yasen classes."},
    {"id": "stirling_aip_engine", "name": "Stirling AIP Engine", "category": "Engine", "tier": 6,
     "reliability_bonus": 12, "fuel_efficiency": 14, "speed_bonus": 8,
     "cost": {"steel": 14, "aluminum": 10, "electronics": 12}, "production_time": 90,
     "special_flags": ["sweden", "japan", "aip", "submarine", "diesel_electric"],
     "description": "Air-independent propulsion on Gotland and Soryu classes. Weeks submerged without snorkeling."},
    {"id": "fuel_cell_aip_212", "name": "Fuel Cell AIP (Type 212)", "category": "Engine", "tier": 7,
     "reliability_bonus": 14, "fuel_efficiency": 16, "speed_bonus": 10,
     "cost": {"steel": 16, "electronics": 25, "aluminum": 12}, "production_time": 100,
     "special_flags": ["germany", "aip", "submarine", "fuel_cell"],
     "description": "Hydrogen fuel cells on German Type 212A. Very quiet patrol capability."},
    {"id": "pump_jet_propulsor", "name": "Pump-Jet Propulsor", "category": "Engine", "tier": 6,
     "reliability_bonus": 8, "fuel_efficiency": 4, "speed_bonus": 6,
     "cost": {"steel": 12, "electronics": 15, "titanium": 6}, "production_time": 75,
     "special_flags": ["uk", "france", "stealth", "submarine", "quiet"],
     "description": "Reduced cavitation propulsor on Astute and Barracuda. Lower acoustic signature."},

    # ─── Sensors / hull ──────────────────────────────────────────────────────────
    {"id": "passive_sonar_ww2", "name": "Passive Sonar (WWII)", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 6, "electronics": 14, "rubber": 6}, "production_time": 48,
     "special_flags": ["submarine", "sonar", "ww2"],
     "description": "Hydrophone ranging on U-boats and fleet boats. Primary ASW detection of era."},
    {"id": "bqq5_sonar_suite", "name": "AN/BQQ-5 Sonar", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 10, "electronics": 42, "rubber": 12}, "production_time": 85,
     "special_flags": ["usa", "sonar", "cold_war", "submarine"],
     "description": "Los Angeles class bow sonar and fire control suite."},
    {"id": "flank_array_sonar", "name": "Flank Array Sonar", "category": "Sensors", "tier": 6,
     "reliability_bonus": 9,
     "cost": {"steel": 12, "electronics": 38, "rubber": 14}, "production_time": 80,
     "special_flags": ["russia", "china", "sonar", "submarine"],
     "description": "Conformal flank arrays on Akula and improved Chinese subs."},
    {"id": "towed_array_sonar", "name": "Towed Array Sonar", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 8, "electronics": 40, "rubber": 10}, "production_time": 78,
     "special_flags": ["usa", "uk", "sonar", "submarine", "asw"],
     "description": "Long towed array for passive detection at standoff range."},
    {"id": "optronic_mast", "name": "Optronic Mast", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 6, "electronics": 45, "optics": 20}, "production_time": 90,
     "special_flags": ["usa", "germany", "stealth", "submarine", "twenty_tens"],
     "description": "Non-hull-penetrating photonic mast. Virginia and Type 212 feature."},
    {"id": "pressure_hull_light", "name": "Light Pressure Hull", "category": "Armor", "tier": 2,
     "armor_bonus": 28, "top_armor_bonus": 28, "reliability_penalty": -4,
     "cost": {"steel": 35, "chromium": 2}, "production_time": 70,
     "special_flags": ["submarine", "ww1", "coastal"],
     "description": "Coastal and early WWI submarine pressure hull. Limited depth."},
    {"id": "pressure_hull_fleet", "name": "Fleet Boat Pressure Hull", "category": "Armor", "tier": 3,
     "armor_bonus": 38, "top_armor_bonus": 38, "reliability_penalty": -6,
     "cost": {"steel": 50, "chromium": 4}, "production_time": 90,
     "special_flags": ["submarine", "ww2", "deep_diving"],
     "description": "Thick high-tensile steel hull for Pacific and Atlantic fleet submarines."},
    {"id": "anechoic_tiles", "name": "Anechoic Tiles", "category": "Armor", "tier": 5,
     "armor_bonus": 8, "top_armor_bonus": 8, "reliability_bonus": 4,
     "cost": {"steel": 5, "rubber": 20, "electronics": 8}, "production_time": 55,
     "special_flags": ["russia", "submarine", "stealth", "acoustic"],
     "description": "Rubber tile coating reducing active sonar returns on Kilo and Akula."},
    {"id": "hybrid_steel_hull_virginia", "name": "HY-100 Hybrid Hull", "category": "Armor", "tier": 7,
     "armor_bonus": 48, "top_armor_bonus": 48, "reliability_penalty": -5,
     "cost": {"steel": 55, "titanium": 12, "chromium": 8}, "production_time": 110,
     "special_flags": ["usa", "submarine", "deep_diving", "twenty_tens"],
     "description": "High-strength hull for Virginia-class deep operations."},
    {"id": "type21_hydrodynamic_hull", "name": "Type XXI Hydrodynamic Hull", "category": "Armor", "tier": 4,
     "armor_bonus": 35, "top_armor_bonus": 35, "reliability_bonus": 6,
     "cost": {"steel": 48, "chromium": 5}, "production_time": 95,
     "special_flags": ["germany", "ww2", "late_war", "prototype_influence"],
     "description": "Streamlined U-boat hull. Influenced postwar Soviet and Western designs."},
    {"id": "vls_missile_compartment", "name": "VLS Missile Compartment", "category": "Cargo", "tier": 6,
     "reliability_bonus": 4,
     "cost": {"steel": 30, "electronics": 25, "explosives": 20}, "production_time": 100,
     "special_flags": ["usa", "russia", "china", "vls", "submarine"],
     "description": "Vertical launch cells for Tomahawk, Kalibr, or SLBM tubes."},
    {"id": "lockheed_martin_orca_uuv", "name": "Orca XLUUV Suite", "category": "DroneAttachment", "tier": 7,
     "reliability_bonus": 6,
     "cost": {"steel": 8, "electronics": 55, "aluminum": 12}, "production_time": 110,
     "special_flags": ["usa", "uuv", "prototype", "twenty_twenties", "autonomous"],
     "description": "Extra-large UUV for mine warfare and ISR. Deployed from sub or shore."},
    {"id": "ssnx_reactor_proto", "name": "SSN(X) Reactor (Proto)", "category": "Engine", "tier": 9,
     "reliability_bonus": 18, "fuel_efficiency": 24, "speed_bonus": 22,
     "cost": {"steel": 30, "uranium": 45, "electronics": 45, "titanium": 15}, "production_time": 170,
     "special_flags": ["usa", "nuclear", "prototype", "twenty_thirties", "ssnx"],
     "description": "Planned U.S. fast-attack submarine with Virginia successor reactor."},
    {"id": "crewless_submarine_2030", "name": "Crewless Submarine (Proto)", "category": "Sensors", "tier": 8,
     "reliability_bonus": 4,
     "cost": {"steel": 12, "electronics": 65, "aluminum": 15}, "production_time": 130,
     "special_flags": ["usa", "china", "russia", "uuv", "prototype", "twenty_thirties"],
     "description": "Large autonomous underwater vehicle with strike or ISR payload."},
]


def sub_tpl(
    id_: str, name: str, family: str, loadout: dict, unlock: list[str],
    size: str = "Medium", days: int = 120, training: int = 30, crew: int = 45,
    stats: dict | None = None,
) -> dict:
    base = stats or {
        "speed": 22, "reliability": 72, "fuel_consumption": 35,
        "supply_need": 40, "armor": 32, "hardness": 45,
    }
    return {
        "id": id_, "name": name, "design_family": family,
        "base_type": "Submarine", "size_category": size,
        "visual_archetype": "submarine",
        "crew_required": crew, "base_training_level": training,
        "max_experience_level": 100, "base_production_days": days,
        "base_stats": base,
        "slots": {
            "MainWeapon": {"max": 2}, "SecondaryWeapon": {"max": 2},
            "Engine": {"max": 1}, "Sensors": {"max": 2},
            "Armor": {"max": 1}, "Communications": {"max": 1},
        },
        "module_loadout": loadout,
        "unlock_tech": unlock,
        "can_mount_drones": False,
        "is_vehicle": True,
    }


TEMPLATES: list[dict] = [
    # ═══ Pre-WWI / WWI ═══════════════════════════════════════════════════════════
    sub_tpl("holland_submarine", "Holland-class", "us_sub_pre_ww1",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "whitehead_18in_torpedo",
             "Engine": "holland_diesel_electric", "Sensors": "passive_sonar_ww2",
             "Armor": "pressure_hull_light", "Communications": "wireless_set_no19"},
            ["us_submarines", "pre_ww1", "submarine_warfare"], size="Light", days=80, crew=12, training=22,
            stats={"speed": 12, "reliability": 55, "fuel_consumption": 20, "supply_need": 18, "armor": 18, "hardness": 30}),
    sub_tpl("type_uboat_ww1", "Type U-19 (WWI)", "german_sub_ww1",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "g7a_torpedo_sub",
             "Engine": "holland_diesel_electric", "Armor": "pressure_hull_light"},
            ["german_submarines", "ww1", "unrestricted_submarine_warfare"], size="Light", days=85, crew=22),
    sub_tpl("e_class_submarine", "British E-class", "uk_sub_ww1",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "ww1_18inch_torpedo",
             "Engine": "holland_diesel_electric", "Armor": "pressure_hull_light"},
            ["uk_submarines", "ww1"], days=90, crew=28),
    sub_tpl("k_class_uk_sub", "British K-class", "uk_sub_ww1",
            {"MainWeapon": "submarine_torpedo_tube", "Engine": "geared_steam_turbine_60k",
             "Armor": "pressure_hull_light"},
            ["uk_submarines", "ww1", "steam_submarine", "prototype_failure"], days=100, crew=56,
            stats={"speed": 24, "reliability": 40, "fuel_consumption": 50, "supply_need": 45, "armor": 22, "hardness": 35}),

    # ═══ WWII ════════════════════════════════════════════════════════════════════
    sub_tpl("type_viic_uboat", "Type VIIC U-boat", "german_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "g7a_torpedo_sub",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2",
             "Armor": "pressure_hull_fleet", "Communications": "fug_16_zyf_radio"},
            ["german_submarines", "ww2", "battle_of_atlantic"], days=110, crew=44, training=34),
    sub_tpl("type_ixc_uboat", "Type IXC U-boat", "german_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "g7es_acoustic_homing",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "snorkel_fitting",
             "Armor": "pressure_hull_fleet"},
            ["german_submarines", "ww2", "long_range_patrol"], size="Heavy", days=125, crew=48),
    sub_tpl("type_xxi_uboat", "Type XXI U-boat", "german_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "g7es_acoustic_homing",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "snorkel_fitting",
             "Armor": "type21_hydrodynamic_hull"},
            ["german_submarines", "ww2", "late_war", "electro_boat"], days=130, crew=57, training=36),
    sub_tpl("type_xxiii_uboat", "Type XXIII U-boat", "german_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "g7a_torpedo_sub",
             "Engine": "man_m6v40_uboat_diesel", "Armor": "type21_hydrodynamic_hull"},
            ["german_submarines", "ww2", "late_war", "coastal"], size="Light", days=95, crew=14),
    sub_tpl("gato_class_submarine", "Gato-class", "us_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk14_torpedo_us",
             "Engine": "fairbanks_morse_38d8", "Sensors": "passive_sonar_ww2",
             "Armor": "pressure_hull_fleet"},
            ["us_submarines", "ww2", "pacific_war"], days=115, crew=65, training=35),
    sub_tpl("balao_class_submarine", "Balao-class", "us_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk14_torpedo_us",
             "Engine": "fairbanks_morse_38d8", "Sensors": "passive_sonar_ww2",
             "Armor": "pressure_hull_fleet"},
            ["us_submarines", "ww2", "pacific_war"], days=118, crew=66),
    sub_tpl("t_class_submarine", "T-class", "uk_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "ww1_18inch_torpedo",
             "Engine": "carrier_boiler_yarrow", "Sensors": "passive_sonar_ww2",
             "Armor": "pressure_hull_fleet"},
            ["uk_submarines", "ww2"], days=112, crew=62),
    sub_tpl("i400_sen_toku", "I-400 Sen-Toku", "japanese_sub_ww2",
            {"MainWeapon": "i400_submarine_tube", "SecondaryWeapon": "type95_sub_torpedo",
             "Engine": "carrier_boiler_yarrow", "Sensors": "passive_sonar_ww2",
             "Armor": "pressure_hull_fleet", "Cargo": "vls_missile_compartment"},
            ["japanese_submarines", "ww2", "submarine_carrier", "paper_strike"], size="SuperHeavy",
            days=200, crew=147, training=38,
            stats={"speed": 18, "reliability": 65, "fuel_consumption": 45, "supply_need": 80, "armor": 40, "hardness": 50}),
    sub_tpl("type_b1_ijn", "Type B1 (I-15)", "japanese_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "type95_sub_torpedo",
             "Engine": "carrier_boiler_yarrow", "Armor": "pressure_hull_fleet"},
            ["japanese_submarines", "ww2"], size="Heavy", days=140, crew=94),
    sub_tpl("s_class_uk_coastal", "S-class (Coastal)", "uk_sub_ww2",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "ww1_18inch_torpedo",
             "Engine": "holland_diesel_electric", "Armor": "pressure_hull_light"},
            ["uk_submarines", "ww2", "coastal"], size="Light", days=88, crew=39),

    # ═══ Cold War ════════════════════════════════════════════════════════════════
    sub_tpl("nautilus_ssn", "USS Nautilus", "us_sub_cold_war",
            {"Engine": "westinghouse_s5w_reactor", "SecondaryWeapon": "mk37_torpedo",
             "Sensors": "bqq5_sonar_suite", "Armor": "pressure_hull_fleet"},
            ["us_submarines", "nuclear", "cold_war", "first_nuclear"], days=180, crew=105, training=40),
    sub_tpl("los_angeles_ssn", "Los Angeles-class", "us_sub_cold_war",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
             "Engine": "westinghouse_s5w_reactor", "Sensors": "bqq5_sonar_suite",
             "Armor": "pressure_hull_fleet"},
            ["us_submarines", "ssn", "cold_war"], days=200, crew=127, training=38),
    sub_tpl("ohio_ssbn", "Ohio-class SSBN", "us_sub_cold_war",
            {"MainWeapon": "trident_d5_slbm", "Engine": "westinghouse_s5w_reactor",
             "Sensors": "towed_array_sonar", "Armor": "hybrid_steel_hull_virginia",
             "Cargo": "vls_missile_compartment"},
            ["us_submarines", "ssbn", "nuclear_deterrent"], size="SuperHeavy", days=280, crew=155, training=42),
    sub_tpl("lafayette_ssbn", "Lafayette-class SSBN", "us_sub_cold_war",
            {"MainWeapon": "polaris_a3_slbm", "Engine": "westinghouse_s5w_reactor",
             "SecondaryWeapon": "mk48_torpedo", "Armor": "pressure_hull_fleet"},
            ["us_submarines", "ssbn", "cold_war"], size="Heavy", days=240, crew=140),
    sub_tpl("resolution_ssbn", "Resolution-class", "uk_sub_cold_war",
            {"MainWeapon": "polaris_a3_slbm", "Engine": "vm_reactor_soviet",
             "SecondaryWeapon": "spearfish_torpedo_uk", "Sensors": "towed_array_sonar"},
            ["uk_submarines", "ssbn", "cold_war"], size="Heavy", days=235, crew=130),
    sub_tpl("vanguard_ssbn", "Vanguard-class SSBN", "uk_sub_modern",
            {"MainWeapon": "trident_d5_slbm", "Engine": "vm_reactor_soviet",
             "SecondaryWeapon": "spearfish_torpedo_uk", "Sensors": "towed_array_sonar",
             "Armor": "hybrid_steel_hull_virginia"},
            ["uk_submarines", "ssbn", "twenty_tens"], size="SuperHeavy", days=270, crew=135),
    sub_tpl("trafalgar_ssn", "Trafalgar-class", "uk_sub_cold_war",
            {"SecondaryWeapon": "spearfish_torpedo_uk", "Engine": "pump_jet_propulsor",
             "Sensors": "towed_array_sonar", "Armor": "pressure_hull_fleet"},
            ["uk_submarines", "ssn", "falklands"], days=195, crew=130),
    sub_tpl("astute_ssn", "Astute-class", "uk_sub_modern",
            {"SecondaryWeapon": "spearfish_torpedo_uk", "Engine": "pump_jet_propulsor",
             "Sensors": "optronic_mast", "Armor": "hybrid_steel_hull_virginia"},
            ["uk_submarines", "ssn", "twenty_tens"], days=210, crew=98, training=40),
    sub_tpl("akula_ssn", "Akula-class", "russian_sub_cold_war",
            {"SecondaryWeapon": "mk48_torpedo", "Engine": "vm_reactor_soviet",
             "Sensors": "flank_array_sonar", "Armor": "anechoic_tiles"},
            ["russian_submarines", "ssn", "cold_war"], days=205, crew=73, training=36),
    sub_tpl("typhoon_ssbn", "Typhoon-class SSBN", "russian_sub_cold_war",
            {"MainWeapon": "bulava_slbm", "Engine": "vm_reactor_soviet",
             "SecondaryWeapon": "va111_shkval_supercavitating", "Armor": "pressure_hull_fleet"},
            ["russian_submarines", "ssbn", "cold_war"], size="SuperHeavy", days=300, crew=160,
            stats={"speed": 20, "reliability": 68, "fuel_consumption": 50, "supply_need": 90, "armor": 55, "hardness": 60}),
    sub_tpl("kilo_class_submarine", "Kilo-class", "russian_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "kalibr_vls_sub",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2",
             "Armor": "anechoic_tiles"},
            ["russian_submarines", "diesel_electric", "export"], days=130, crew=52),
    sub_tpl("foxtrot_class", "Foxtrot-class", "soviet_sub_cold_war",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk37_torpedo",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2"},
            ["soviet_submarines", "cold_war", "export"], days=125, crew=75),
    sub_tpl("whiskey_class", "Whiskey-class", "soviet_sub_cold_war",
            {"MainWeapon": "submarine_torpedo_tube", "Engine": "man_m6v40_uboat_diesel",
             "Armor": "pressure_hull_fleet"},
            ["soviet_submarines", "cold_war"], days=115, crew=54),
    sub_tpl("type_033_romeo", "Type 033 (Romeo)", "chinese_sub_cold_war",
            {"MainWeapon": "submarine_torpedo_tube", "Engine": "man_m6v40_uboat_diesel",
             "Armor": "pressure_hull_fleet"},
            ["chinese_submarines", "cold_war"], days=118, crew=57),
    sub_tpl("type_035_ming", "Type 035 Ming", "chinese_sub_cold_war",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "yu6_china_torpedo",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2"},
            ["chinese_submarines", "cold_war"], days=120, crew=57),

    # ═══ Modern / 2000s–2020s ═══════════════════════════════════════════════════
    sub_tpl("virginia_ssn", "Virginia-class", "us_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "tomahawk_cruise_missile",
             "Engine": "ge_s9g_reactor", "Sensors": "optronic_mast",
             "Armor": "hybrid_steel_hull_virginia", "Cargo": "vls_missile_compartment"},
            ["us_submarines", "ssn", "twenty_tens"], days=220, crew=134, training=40),
    sub_tpl("seawolf_ssn", "Seawolf-class", "us_sub_modern",
            {"SecondaryWeapon": "mk48_torpedo", "Engine": "ge_s9g_reactor",
             "Sensors": "bqq5_sonar_suite", "Armor": "hybrid_steel_hull_virginia"},
            ["us_submarines", "ssn", "cold_war", "stealth"], size="Heavy", days=240, crew=140,
            stats={"speed": 28, "reliability": 88, "fuel_consumption": 40, "supply_need": 55, "armor": 52, "hardness": 55}),
    sub_tpl("columbia_ssbn", "Columbia-class SSBN", "us_sub_planned",
            {"MainWeapon": "trident_d5_slbm", "Engine": "ge_s9g_reactor",
             "Sensors": "optronic_mast", "Armor": "hybrid_steel_hull_virginia"},
            ["us_submarines", "ssbn", "planned", "twenty_twenties"], size="SuperHeavy", days=290, crew=155),
    sub_tpl("yasen_ssn", "Yasen-class", "russian_sub_modern",
            {"SecondaryWeapon": "kalibr_vls_sub", "Engine": "vm_reactor_soviet",
             "Sensors": "flank_array_sonar", "Armor": "hybrid_steel_hull_virginia",
             "Cargo": "vls_missile_compartment"},
            ["russian_submarines", "ssn", "twenty_tens"], size="Heavy", days=225, crew=90),
    sub_tpl("borei_ssbn", "Borei-class SSBN", "russian_sub_modern",
            {"MainWeapon": "bulava_slbm", "Engine": "vm_reactor_soviet",
             "SecondaryWeapon": "mk48_torpedo", "Armor": "pressure_hull_fleet"},
            ["russian_submarines", "ssbn", "twenty_tens"], size="SuperHeavy", days=275, crew=107),
    sub_tpl("type_093_shang", "Type 093 Shang", "chinese_sub_modern",
            {"SecondaryWeapon": "cj10_china_cruise", "Engine": "vm_reactor_soviet",
             "Sensors": "flank_array_sonar", "Armor": "pressure_hull_fleet"},
            ["chinese_submarines", "ssn", "twenty_tens"], days=210, crew=100),
    sub_tpl("type_094_jin", "Type 094 Jin", "chinese_sub_modern",
            {"MainWeapon": "jl3_slbm_china", "Engine": "vm_reactor_soviet",
             "SecondaryWeapon": "yu6_china_torpedo", "Armor": "pressure_hull_fleet"},
            ["chinese_submarines", "ssbn", "twenty_tens"], size="Heavy", days=250, crew=120),
    sub_tpl("type_039_song", "Type 039 Song", "chinese_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "yu6_china_torpedo",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2"},
            ["chinese_submarines", "diesel_electric", "twenty_tens"], days=125, crew=50),
    sub_tpl("type_212_aip", "Type 212A", "german_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
             "Engine": "fuel_cell_aip_212", "Sensors": "optronic_mast",
             "Armor": "pressure_hull_fleet"},
            ["german_submarines", "aip", "twenty_tens"], size="Medium", days=140, crew=27, training=38),
    sub_tpl("type_214_aip", "Type 214", "german_sub_export",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "black_shark_torpedo",
             "Engine": "fuel_cell_aip_212", "Sensors": "optronic_mast"},
            ["german_submarines", "export", "aip", "greece", "south_korea"], days=135, crew=27),
    sub_tpl("scorpene_class", "Scorpène-class", "french_sub_export",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "exocet_sm39",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2",
             "Armor": "anechoic_tiles"},
            ["french_submarines", "export", "india", "malaysia"], days=128, crew=31),
    sub_tpl("barracuda_class", "Barracuda-class", "french_sub_modern",
            {"SecondaryWeapon": "exocet_sm39", "Engine": "pump_jet_propulsor",
             "Sensors": "optronic_mast", "Armor": "hybrid_steel_hull_virginia"},
            ["french_submarines", "ssn", "twenty_tens"], days=200, crew=60),
    sub_tpl("soryu_class", "Soryu-class", "japanese_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
             "Engine": "stirling_aip_engine", "Sensors": "passive_sonar_ww2"},
            ["japanese_submarines", "aip", "twenty_tens"], days=145, crew=65),
    sub_tpl("taigei_class", "Taigei-class", "japanese_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
             "Engine": "fuel_cell_aip_212", "Sensors": "optronic_mast"},
            ["japanese_submarines", "twenty_twenties"], days=155, crew=70),
    sub_tpl("kss3_dosan_ahn", "KSS-III (Dosan Ahn Changho)", "korean_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "cj10_china_cruise",
             "Engine": "fuel_cell_aip_212", "Sensors": "flank_array_sonar",
             "Cargo": "vls_missile_compartment"},
            ["south_korean_submarines", "twenty_tens"], size="Heavy", days=175, crew=50),
    sub_tpl("gotland_aip", "Gotland-class", "swedish_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
             "Engine": "stirling_aip_engine", "Sensors": "passive_sonar_ww2"},
            ["swedish_submarines", "aip", "twenty_tens"], size="Medium", days=118, crew=25),
    sub_tpl("collins_class", "Collins-class", "australian_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "mk48_torpedo",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "towed_array_sonar"},
            ["australian_submarines", "twenty_tens"], days=165, crew=42),
    sub_tpl("tridente_class", "Tridente-class", "italian_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "black_shark_torpedo",
             "Engine": "fuel_cell_aip_212", "Sensors": "passive_sonar_ww2"},
            ["italian_submarines", "twenty_tens"], days=130, crew=27),
    sub_tpl("kalvari_class", "Kalvari-class", "indian_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "exocet_sm39",
             "Engine": "man_m6v40_uboat_diesel", "Armor": "anechoic_tiles"},
            ["indian_submarines", "scorpene", "twenty_tens"], days=125, crew=35),
    sub_tpl("israeli_dolphin", "Dolphin-class", "israeli_sub_modern",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "harpoon_sub_launch",
             "Engine": "fuel_cell_aip_212", "Sensors": "passive_sonar_ww2"},
            ["israeli_submarines", "german_export", "twenty_tens"], days=140, crew=35),
    sub_tpl("agosta_class", "Agosta-class", "french_sub_cold_war",
            {"MainWeapon": "submarine_torpedo_tube", "SecondaryWeapon": "exocet_sm39",
             "Engine": "man_m6v40_uboat_diesel", "Sensors": "passive_sonar_ww2"},
            ["french_submarines", "cold_war", "pakistan"], days=122, crew=54),

    # ═══ 2030s planned / prototypes ════════════════════════════════════════════════
    sub_tpl("ssnx_prototype", "SSN(X) (Prototype)", "us_sub_planned",
            {"SecondaryWeapon": "mk48_torpedo", "Engine": "ssnx_reactor_proto",
             "Sensors": "optronic_mast", "Armor": "hybrid_steel_hull_virginia",
             "DroneAttachment": "lockheed_martin_orca_uuv"},
            ["us_submarines", "prototype", "twenty_thirties", "ssnx"], days=250, crew=120, training=42),
    sub_tpl("orcus_xluuv", "Orca XLUUV", "us_sub_planned",
            {"Sensors": "lockheed_martin_orca_uuv", "Engine": "fuel_cell_aip_212"},
            ["us_submarines", "uuv", "autonomous", "twenty_twenties"], size="Medium", days=90, crew=0,
            stats={"speed": 15, "reliability": 75, "fuel_consumption": 8, "supply_need": 5, "armor": 5, "hardness": 8}),
    sub_tpl("crewless_strike_sub_2030", "Crewless Strike Sub (Proto)", "multinational_sub_planned",
            {"Sensors": "crewless_submarine_2030", "SecondaryWeapon": "kalibr_vls_sub",
             "Engine": "fuel_cell_aip_212"},
            ["prototype", "twenty_thirties", "autonomous_undersea"], size="Medium", days=100, crew=0,
            stats={"speed": 18, "reliability": 70, "fuel_consumption": 10, "supply_need": 6, "armor": 10, "hardness": 12}),
    sub_tpl("type_096_ssbn", "Type 096 SSBN (Planned)", "chinese_sub_planned",
            {"MainWeapon": "jl3_slbm_china", "Engine": "vm_reactor_soviet",
             "SecondaryWeapon": "cj10_china_cruise", "Sensors": "flank_array_sonar",
             "Armor": "hybrid_steel_hull_virginia"},
            ["chinese_submarines", "ssbn", "planned", "twenty_thirties"], size="SuperHeavy", days=280, crew=130),
]


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing_m = {p.stem for p in MODULES_DIR.glob("*.json")}
    existing_t = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    mc = tc = 0
    for mod in MODULES:
        if mod["id"] in existing_m:
            continue
        path = MODULES_DIR / f"{mod['id']}.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        mc += 1
        print(f"  + module {mod['id']}.json")
    for tpl in TEMPLATES:
        if tpl["id"] in existing_t:
            continue
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        write_unit_template(path, tpl)
        tc += 1
        print(f"  + template {tpl['id']}.json")
    mods = {p.stem for p in MODULES_DIR.glob("*.json")}
    errs = []
    for p in TEMPLATES_DIR.glob("*.json"):
        d = json.loads(p.read_text())
        for slot, mid in d.get("module_loadout", {}).items():
            if mid not in mods:
                errs.append(f"{p.name}: {slot} -> {mid}")
    print(f"\nSubmarine: {mc} modules, {tc} templates. Missing refs: {len(errs)}")
    for e in errs:
        print(f"  ! {e}")


if __name__ == "__main__":
    main()
