#!/usr/bin/env python3
"""1960s–1970s unit templates for major nations."""

from __future__ import annotations

from template_export import write_unit_template
import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    {
        "id": "m60a1_patton",
        "name": "M60A1 Patton",
        "design_family": "us_armored_vietnam",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 30, "reliability": 72, "fuel_consumption": 14, "supply_need": 18,
                      "armor": 50, "top_armor": 28, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m68a1_105mm_gun", "Engine": "avds_1790_engine",
                         "Armor": "m60a1_patton_armor", "Sensors": "laser_rangefinder_tank",
                         "Cargo": "m735_apfsds_ammo"},
        "unlock_tech": ["us_mbt_sixties", "nato_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t62_medium_tank",
        "name": "T-62",
        "design_family": "soviet_armored_sixties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 88,
        "base_stats": {"speed": 32, "reliability": 68, "fuel_consumption": 13, "supply_need": 16,
                      "armor": 48, "top_armor": 24, "hardness": 86},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "u5ts_115mm_smoothbore", "Engine": "v12_5_engine",
                         "Armor": "t62_cast_armor", "Sensors": "ballistic_computer_gpch"},
        "unlock_tech": ["soviet_mbt_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t72_mbt",
        "name": "T-72",
        "design_family": "soviet_armored_seventies",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 92,
        "base_stats": {"speed": 35, "reliability": 74, "fuel_consumption": 12, "supply_need": 15,
                      "armor": 55, "top_armor": 32, "hardness": 90},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "d81_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t72_composite_armor", "Sensors": "laser_rangefinder_tank"},
        "unlock_tech": ["soviet_mbt_seventies"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "type59_mbt",
        "name": "Type 59",
        "design_family": "chinese_armored_sixties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 85,
        "base_stats": {"speed": 28, "reliability": 65, "fuel_consumption": 13, "supply_need": 14,
                      "armor": 42, "top_armor": 20, "hardness": 82},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "type59_100mm_gun", "Engine": "12150l_diesel",
                         "Armor": "type59_cast_armor"},
        "unlock_tech": ["chinese_mbt_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "amx30_mbt",
        "name": "AMX-30",
        "design_family": "french_armored_sixties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 38, "reliability": 70, "fuel_consumption": 12, "supply_need": 16,
                      "armor": 38, "top_armor": 18, "hardness": 84},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "cn105f1_105mm_gun", "Engine": "hs110_diesel_amx30",
                         "Armor": "amx30_armor", "Sensors": "laser_rangefinder_tank"},
        "unlock_tech": ["french_mbt_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "chieftain_mk5",
        "name": "Chieftain Mk 5",
        "design_family": "uk_armored_sixties",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 105,
        "base_stats": {"speed": 26, "reliability": 58, "fuel_consumption": 16, "supply_need": 20,
                      "armor": 52, "top_armor": 30, "hardness": 92},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "l11a5_120mm_rifled", "Engine": "l60_engine_chieftain",
                         "Armor": "chieftain_armor", "Sensors": "laser_rangefinder_tank",
                         "Cargo": "hesh_fs_ammo"},
        "unlock_tech": ["uk_mbt_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "leopard_1a4",
        "name": "Leopard 1A4",
        "design_family": "german_armored_sixties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 92,
        "base_stats": {"speed": 36, "reliability": 82, "fuel_consumption": 11, "supply_need": 15,
                      "armor": 44, "top_armor": 22, "hardness": 86},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh105_105mm_leopard1", "Engine": "mtu_mb838_engine",
                         "Armor": "leopard1_armor", "Sensors": "laser_rangefinder_tank"},
        "unlock_tech": ["german_mbt_sixties", "nato_armor"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "leopard_2_proto",
        "name": "Leopard 2 (Prototype)",
        "design_family": "german_armored_seventies",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 115,
        "base_stats": {"speed": 34, "reliability": 85, "fuel_consumption": 13, "supply_need": 18,
                      "armor": 58, "top_armor": 38, "hardness": 94},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh120_120mm_smoothbore", "Engine": "mtu_mb838_engine",
                         "Armor": "leopard2_armor_proto", "Sensors": "thermal_sight_gen1"},
        "unlock_tech": ["german_mbt_seventies"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "merkava_mk1",
        "name": "Merkava Mk I",
        "design_family": "israeli_armored_seventies",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 28, "reliability": 78, "fuel_consumption": 14, "supply_need": 17,
                      "armor": 54, "top_armor": 32, "hardness": 90},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "SecondaryWeapon": {"max": 1}},
        "module_loadout": {"MainWeapon": "merkava_mk1_105mm", "Engine": "merkava_avds_engine",
                         "Armor": "merkava_mk1_armor", "SecondaryWeapon": "mg3_infantry_gun"},
        "unlock_tech": ["israeli_mbt_seventies"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "magach_6",
        "name": "Magach 6",
        "design_family": "israeli_armored_sixties",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 88,
        "base_stats": {"speed": 30, "reliability": 74, "fuel_consumption": 14, "supply_need": 17,
                      "armor": 48, "top_armor": 26, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}},
        "module_loadout": {"MainWeapon": "m68a1_105mm_gun", "Engine": "avds_1790_engine",
                         "Armor": "magach_m60_upgrade"},
        "unlock_tech": ["israeli_mbt_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f4e_phantom",
        "name": "F-4E Phantom II",
        "design_family": "us_air_vietnam",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 2,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 75,
        "base_stats": {"speed": 95, "reliability": 76, "fuel_consumption": 22, "supply_need": 16,
                      "armor": 12, "hardness": 25},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim7_sparrow", "SecondaryWeapon": "aim9_sidewinder",
                         "Engine": "pratt_j79_phantom"},
        "unlock_tech": ["us_fighters_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mig21bis_fighter",
        "name": "MiG-21bis",
        "design_family": "soviet_air_sixties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 55,
        "base_stats": {"speed": 98, "reliability": 70, "fuel_consumption": 14, "supply_need": 10,
                      "armor": 8, "hardness": 20},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "r60_atoll_missile", "Engine": "tumansky_r13_mig21"},
        "unlock_tech": ["soviet_fighters_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mirage_iii_fighter",
        "name": "Mirage III",
        "design_family": "french_air_sixties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 62,
        "base_stats": {"speed": 96, "reliability": 74, "fuel_consumption": 15, "supply_need": 11,
                      "armor": 10, "hardness": 22},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "defa550_30mm", "Engine": "atar9c_turbojet"},
        "unlock_tech": ["french_fighters_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "harrier_gr1",
        "name": "Harrier GR.1",
        "design_family": "uk_air_sixties",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 68,
        "base_stats": {"speed": 88, "reliability": 72, "fuel_consumption": 16, "supply_need": 12,
                      "armor": 10, "hardness": 22},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "red_top_missile", "Engine": "pegasus_harrier_engine"},
        "unlock_tech": ["uk_vstol_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "j7_fighter",
        "name": "J-7",
        "design_family": "chinese_air_seventies",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 58,
        "base_stats": {"speed": 95, "reliability": 68, "fuel_consumption": 14, "supply_need": 10,
                      "armor": 8, "hardness": 20},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "pl2_air_air_missile", "Engine": "wp7_turbojet_j7"},
        "unlock_tech": ["chinese_fighters_seventies"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "kfir_c2",
        "name": "Kfir C.2",
        "design_family": "israeli_air_seventies",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 65,
        "base_stats": {"speed": 94, "reliability": 76, "fuel_consumption": 15, "supply_need": 11,
                      "armor": 10, "hardness": 22},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "shafrir2_missile", "Engine": "kfir_j79_engine"},
        "unlock_tech": ["israeli_fighters_seventies"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "bmp1_ifv",
        "name": "BMP-1",
        "design_family": "soviet_armored_sixties",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "apc",
        "crew_required": 3,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 38, "reliability": 70, "fuel_consumption": 10, "supply_need": 12,
                      "armor": 22, "top_armor": 12, "hardness": 65},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "bmp1_73mm_grom", "SecondaryWeapon": "malyutka_at3_sagger",
                         "Engine": "v12_5_engine"},
        "unlock_tech": ["soviet_ifv_sixties"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if tpl["id"] in existing:
            skipped += 1
            continue
        write_unit_template(path, tpl)
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\n1960s–1970s templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
