#!/usr/bin/env python3
"""2020s–2030s modules: in-service and planned equipment for major nations."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 2020s (in service & fielding)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1a2_sep_v4_armor", "name": "M1A2 SEP v4 Armor", "category": "Armor", "tier": 8,
     "armor_bonus": 90, "top_armor_bonus": 68, "reliability_penalty": -5,
     "cost": {"steel": 58, "ceramics": 40, "uranium": 28, "titanium": 18, "kevlar": 16}, "production_time": 160,
     "special_flags": ["usa", "twenty_twenties", "m1a2", "trophy"],
     "description": "Latest Abrams with Trophy HV, improved DU, and Trophy-ready wiring. Standard U.S. Army MBT of 2020s."},
    {"id": "abramsx_hybrid_package", "name": "AbramsX Hybrid Package", "category": "Engine", "tier": 8,
     "reliability_bonus": 14, "fuel_efficiency": 18, "speed_bonus": 14,
     "cost": {"steel": 24, "aluminum": 20, "electronics": 35, "lithium": 12}, "production_time": 140,
     "special_flags": ["usa", "twenty_twenties", "hybrid", "abramsx", "prototype"],
     "description": "Diesel-electric hybrid demonstrator with reduced logistics footprint and silent watch."},
    {"id": "m829a4_apfsds", "name": "M829A4 APFSDS", "category": "Cargo", "tier": 8,
     "soft_attack": 14, "hard_attack": 34, "piercing": 58,
     "cost": {"uranium": 28, "tungsten": 8, "steel": 2}, "production_time": 58,
     "special_flags": ["usa", "ammunition", "apfsds", "twenty_twenties"],
     "description": "Latest U.S. long-rod penetrator with improved performance vs advanced ERA."},
    {"id": "xm1147_amp_round", "name": "XM1147 AMP-TH", "category": "Cargo", "tier": 8,
     "soft_attack": 25, "hard_attack": 20, "piercing": 35,
     "cost": {"electronics": 18, "explosives": 12, "steel": 3}, "production_time": 50,
     "special_flags": ["usa", "ammunition", "twenty_twenties", "programmable"],
     "description": "Advanced Multi-Purpose programmable fuze round. One round type for multiple targets."},
    {"id": "f47_ngad_package", "name": "F-47 NGAD Package", "category": "Engine", "tier": 9,
     "reliability_bonus": 16, "fuel_efficiency": 18, "speed_bonus": 42,
     "cost": {"steel": 26, "aluminum": 50, "titanium": 35, "electronics": 55}, "production_time": 200,
     "special_flags": ["usa", "twenty_twenties", "sixth_gen", "ngad", "planned", "f47"],
     "description": "Next Generation Air Dominance platform (F-47 designation 2025). Crewed sixth-gen fighter in development."},
    {"id": "ngad_adaptive_engine", "name": "NGAD Adaptive Cycle Engine", "category": "Engine", "tier": 9,
     "reliability_bonus": 18, "fuel_efficiency": 22, "speed_bonus": 44,
     "cost": {"steel": 28, "aluminum": 55, "titanium": 40, "electronics": 30}, "production_time": 210,
     "special_flags": ["usa", "jet_powerplant", "twenty_twenties", "adaptive_cycle", "ngad"],
     "description": "Three-stream adaptive engine for NGAD. Optimizes range, acceleration, and thermal management."},
    {"id": "aim260_jatm", "name": "AIM-260 JATM", "category": "MainWeapon", "tier": 8,
     "soft_attack": 16, "hard_attack": 14, "air_attack": 98, "anti_air": 94,
     "cost": {"steel": 8, "electronics": 55, "explosives": 12}, "production_time": 90,
     "special_flags": ["usa", "air_to_air", "twenty_twenties", "bvr", "planned"],
     "description": "Joint Advanced Tactical Missile to counter PL-15 and long-range threats. Internal bay compatible."},
    {"id": "b21_raider_package", "name": "B-21 Raider Package", "category": "Engine", "tier": 8,
     "reliability_bonus": 14, "fuel_efficiency": 16, "speed_bonus": 30,
     "cost": {"steel": 35, "aluminum": 60, "titanium": 30, "electronics": 50}, "production_time": 220,
     "special_flags": ["usa", "twenty_twenties", "stealth", "bomber"],
     "description": "B-21 stealth bomber entering service. Penetrating strike against peer adversaries."},
    {"id": "f35_block4_package", "name": "F-35 Block 4 Package", "category": "Sensors", "tier": 8,
     "reliability_bonus": 12,
     "cost": {"steel": 12, "electronics": 70, "aluminum": 25}, "production_time": 160,
     "special_flags": ["usa", "twenty_twenties", "f35", "tr3", "aesa"],
     "description": "Technology Refresh 3 with improved radar, EW, and computing. Fleet-wide upgrade path."},
    {"id": "prsm_precision_strike", "name": "PrSM", "category": "MainWeapon", "tier": 8,
     "soft_attack": 110, "hard_attack": 65, "piercing": 55, "air_attack": 8,
     "cost": {"steel": 14, "electronics": 45, "explosives": 40}, "production_time": 95,
     "special_flags": ["usa", "twenty_twenties", "precision", "artillery"],
     "description": "Precision Strike Missile replacing ATACMS. 499 km range; HIMARS and M270 compatible."},
    {"id": "lrhw_dark_eagle", "name": "LRHW (Dark Eagle)", "category": "MainWeapon", "tier": 8,
     "soft_attack": 140, "hard_attack": 85, "piercing": 75, "air_attack": 10,
     "cost": {"steel": 25, "electronics": 60, "explosives": 50}, "production_time": 130,
     "special_flags": ["usa", "twenty_twenties", "hypersonic", "planned"],
     "description": "Long-Range Hypersonic Weapon. Ground-launched boost-glide against time-critical targets."},
    {"id": "ddgx_combat_system", "name": "DDG(X) Combat System", "category": "Sensors", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 45, "electronics": 85, "aluminum": 20}, "production_time": 180,
     "special_flags": ["usa", "naval", "twenty_twenties", "destroyer", "planned"],
     "description": "Next-generation destroyer with SPY-6 derivatives, increased power for lasers and hypersonics."},
    {"id": "constellation_ffg_package", "name": "Constellation FFG Package", "category": "Armor", "tier": 6,
     "armor_bonus": 32, "top_armor_bonus": 20, "reliability_penalty": -3,
     "cost": {"steel": 55, "aluminum": 18, "electronics": 25}, "production_time": 140,
     "special_flags": ["usa", "naval", "twenty_twenties", "frigate"],
     "description": "Constellation-class guided-missile frigate. ASW and escort for carrier strike groups."},
    {"id": "trump_class_hull", "name": "Trump-class Battleship Hull", "category": "Armor", "tier": 9,
     "armor_bonus": 95, "top_armor_bonus": 70, "reliability_penalty": -12,
     "cost": {"steel": 180, "ceramics": 45, "titanium": 25, "kevlar": 20}, "production_time": 280,
     "special_flags": ["usa", "naval", "twenty_twenties", "battleship", "planned", "trump_class"],
     "description": "Proposed large surface combatant reviving battleship firepower with modern VLS and sensors. Program aspirational."},
    {"id": "trump_class_16inch_modern", "name": "Modernized 16-inch Battery", "category": "NavalGun", "tier": 9,
     "soft_attack": 120, "hard_attack": 95, "piercing": 145, "air_attack": 35, "anti_ship": 115, "anti_air": 40,
     "cost": {"steel": 90, "electronics": 40, "explosives": 80, "chromium": 15}, "production_time": 200,
     "special_flags": ["usa", "naval", "battleship", "planned", "trump_class"],
     "description": "Two triple 16-inch/50 cal batteries with GPS-guided shells and reduced crew via automation."},
    {"id": "trump_class_vls_farm", "name": "Trump-class VLS Farm", "category": "SecondaryWeapon", "tier": 8,
     "soft_attack": 60, "hard_attack": 70, "piercing": 50, "anti_ship": 100, "air_attack": 45,
     "cost": {"steel": 50, "electronics": 55, "explosives": 60}, "production_time": 150,
     "special_flags": ["usa", "naval", "vls", "planned", "trump_class"],
     "description": "128+ cell VLS for Tomahawk, SM-6, and hypersonic weapons alongside gun armament."},
    {"id": "cca_loyal_wingman", "name": "CCA Loyal Wingman", "category": "DroneAttachment", "tier": 8,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 55, "aluminum": 18}, "production_time": 95,
     "special_flags": ["usa", "twenty_twenties", "loyal_wingman", "ngad", "unmanned"],
     "description": "Collaborative Combat Aircraft escorting NGAD and F-35. Affordable mass for contested airspace."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 2030s (planned / projected)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1e3_abrams_package", "name": "M1E3 Abrams Package", "category": "Armor", "tier": 9,
     "armor_bonus": 95, "top_armor_bonus": 72, "reliability_penalty": -4,
     "cost": {"steel": 60, "ceramics": 45, "uranium": 30, "titanium": 20, "electronics": 25}, "production_time": 175,
     "special_flags": ["usa", "twenty_thirties", "m1e3", "planned"],
     "description": "AbramsX-derived production tank with hybrid drive, lighter hull, and standard Trophy."},
    {"id": "m256_l55a1_gun", "name": "120 mm M256A1 L/55", "category": "MainWeapon", "tier": 8,
     "soft_attack": 78, "hard_attack": 76, "piercing": 195, "air_attack": 5,
     "cost": {"steel": 38, "chromium": 12, "tungsten": 10}, "production_time": 115,
     "special_flags": ["usa", "twenty_thirties", "smoothbore"],
     "description": "Improved M256 with autoloader compatibility and higher chamber pressure."},
    {"id": "f47_operational_fit", "name": "F-47 Operational Fit", "category": "Sensors", "tier": 9,
     "reliability_bonus": 14,
     "cost": {"steel": 15, "electronics": 90, "rare_earths": 25}, "production_time": 200,
     "special_flags": ["usa", "twenty_thirties", "sixth_gen", "f47", "aesa"],
     "description": "Full-rate production F-47 with integrated CCA control and multi-spectral sensors."},
    {"id": "hel_mdi_laser", "name": "HELI-MD / DE M-SHORAD", "category": "AntiAir", "tier": 9,
     "soft_attack": 20, "hard_attack": 15, "air_attack": 95, "anti_air": 92,
     "cost": {"steel": 18, "electronics": 75, "chemicals": 20}, "production_time": 140,
     "special_flags": ["usa", "twenty_thirties", "directed_energy", "laser"],
     "description": "Mobile directed-energy weapon for drones and rockets. Unlimited magazine depth vs swarms."},
    {"id": "trump_class_full_combat", "name": "Trump-class Full Combat Suite", "category": "Sensors", "tier": 9,
     "reliability_bonus": 12,
     "cost": {"steel": 60, "electronics": 95, "aluminum": 30}, "production_time": 220,
     "special_flags": ["usa", "naval", "twenty_thirties", "battleship", "planned", "trump_class"],
     "description": "Integrated air/missile defense, railgun trials, and cooperative engagement for revived battleship concept."},
    {"id": "railgun_naval_proto", "name": "Electromagnetic Railgun (Naval)", "category": "NavalGun", "tier": 9,
     "soft_attack": 100, "hard_attack": 88, "piercing": 130, "anti_ship": 110, "air_attack": 20,
     "cost": {"steel": 40, "electronics": 80, "copper": 30}, "production_time": 190,
     "special_flags": ["usa", "naval", "twenty_thirties", "planned", "railgun"],
     "description": "Hypersonic-velocity projectile launcher for large surface combatants. 2030s technology demonstrator."},

    # ═══════════════════════════════════════════════════════════════════════════
    # RUSSIA · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "t90m_armor_package", "name": "T-90M Armor Package", "category": "Armor", "tier": 8,
     "armor_bonus": 68, "top_armor_bonus": 42, "reliability_penalty": -5,
     "cost": {"steel": 46, "ceramics": 22, "explosives": 16}, "production_time": 100,
     "special_flags": ["russia", "twenty_twenties", "t90m", "relikt"],
     "description": "T-90M Proryv with Relikt ERA, Kalina FCS, and 2A46M-5 gun. Ukraine combat record."},
    {"id": "t14_serial_package", "name": "T-14 Armata (Serial)", "category": "Armor", "tier": 8,
     "armor_bonus": 78, "top_armor_bonus": 52, "reliability_penalty": -9,
     "cost": {"steel": 52, "ceramics": 32, "electronics": 28}, "production_time": 170,
     "special_flags": ["russia", "twenty_twenties", "t14", "afghanit"],
     "description": "Limited serial T-14 with unmanned turret and crew capsule. Production constraints persist."},
    {"id": "3bm69_apfsds", "name": "3BM69 Vacuum-1", "category": "Cargo", "tier": 8,
     "soft_attack": 14, "hard_attack": 32, "piercing": 55,
     "cost": {"tungsten": 18, "uranium": 8, "steel": 2}, "production_time": 55,
     "special_flags": ["russia", "ammunition", "apfsds", "twenty_twenties"],
     "description": "Latest Russian long-rod penetrator for 125 mm smoothbore."},
    {"id": "su57_serial_package", "name": "Su-57 Felon (Serial)", "category": "Engine", "tier": 8,
     "reliability_bonus": 12, "fuel_efficiency": 14, "speed_bonus": 38,
     "cost": {"steel": 24, "aluminum": 42, "titanium": 28, "electronics": 40}, "production_time": 175,
     "special_flags": ["russia", "twenty_twenties", "su57", "stealth"],
     "description": "Serial Su-57 with improved engines and radar. Limited fleet; Ukraine operations."},
    {"id": "checkmate_lts_package", "name": "Su-75 Checkmate", "category": "Engine", "tier": 8,
     "reliability_bonus": 10, "fuel_efficiency": 14, "speed_bonus": 36,
     "cost": {"steel": 20, "aluminum": 38, "titanium": 22, "electronics": 35}, "production_time": 160,
     "special_flags": ["russia", "twenty_twenties", "export", "planned", "checkmate"],
     "description": "Light tactical stealth fighter for export. Single-engine fifth-gen at reduced cost."},
    {"id": "s500_prometey", "name": "S-500 Prometey", "category": "AntiAir", "tier": 9,
     "soft_attack": 20, "hard_attack": 18, "air_attack": 100, "anti_air": 98,
     "cost": {"steel": 40, "electronics": 90, "explosives": 30}, "production_time": 160,
     "special_flags": ["russia", "twenty_twenties", "sam", "strategic"],
     "description": "S-500 for ballistic missile and hypersonic defense. Complements S-400."},
    {"id": "zircon_hypersonic", "name": "3M22 Zircon", "category": "MainWeapon", "tier": 9,
     "soft_attack": 90, "hard_attack": 95, "piercing": 85, "anti_ship": 120, "air_attack": 12,
     "cost": {"steel": 16, "electronics": 55, "explosives": 45}, "production_time": 120,
     "special_flags": ["russia", "twenty_twenties", "hypersonic", "naval"],
     "description": "Mach 9+ anti-ship hypersonic missile. Frigate and submarine launched."},
    {"id": "kinzhal_aeroballistic", "name": "Kh-47M2 Kinzhal", "category": "MainWeapon", "tier": 8,
     "soft_attack": 130, "hard_attack": 80, "piercing": 70, "air_attack": 15,
     "cost": {"steel": 18, "electronics": 45, "explosives": 55}, "production_time": 110,
     "special_flags": ["russia", "twenty_twenties", "aeroballistic", "mig31"],
     "description": "Air-launched aeroballistic missile. Used against fixed targets in Ukraine."},
    {"id": "uran9_ugv_package", "name": "Uran-9 UGV", "category": "DroneAttachment", "tier": 6,
     "reliability_bonus": 2,
     "cost": {"steel": 12, "electronics": 30, "explosives": 8}, "production_time": 65,
     "special_flags": ["russia", "twenty_twenties", "ugv", "urban"],
     "description": "Armed unmanned ground vehicle. Mixed combat results in Syria and Ukraine."},
    {"id": "su75_operational_2030", "name": "Su-75 Operational (2030)", "category": "Engine", "tier": 9,
     "reliability_bonus": 14, "fuel_efficiency": 16, "speed_bonus": 38,
     "cost": {"steel": 22, "aluminum": 45, "titanium": 30}, "production_time": 185,
     "special_flags": ["russia", "twenty_thirties", "planned", "checkmate"],
     "description": "Projected full-rate Checkmate for export allies if production scales."},
    {"id": "okhotnik_ucav", "name": "S-70 Okhotnik", "category": "DroneAttachment", "tier": 8,
     "reliability_bonus": 6,
     "cost": {"steel": 14, "electronics": 50, "aluminum": 22}, "production_time": 110,
     "special_flags": ["russia", "twenty_thirties", "ucav", "loyal_wingman"],
     "description": "Heavy stealth UCAV teaming with Su-57. 2030s unmanned strike complement."},

    # ═══════════════════════════════════════════════════════════════════════════
    # CHINA · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "type99a_phase3_armor", "name": "Type 99A Phase III", "category": "Armor", "tier": 8,
     "armor_bonus": 72, "top_armor_bonus": 45, "reliability_penalty": -5,
     "cost": {"steel": 48, "ceramics": 26, "explosives": 14}, "production_time": 105,
     "special_flags": ["china", "twenty_twenties", "type99a"],
     "description": "Latest Type 99A with improved FY-4 ERA and battlefield networking."},
    {"id": "type15_light_tank", "name": "Type 15 Light Tank", "category": "MainWeapon", "tier": 6,
     "soft_attack": 58, "hard_attack": 52, "piercing": 125, "air_attack": 5,
     "cost": {"steel": 20, "aluminum": 8}, "production_time": 75,
     "special_flags": ["china", "twenty_twenties", "light_tank", "plateau"],
     "description": "105 mm light tank for mountain and amphibious terrain. High mobility in Tibet and South China Sea."},
    {"id": "j20a_operational", "name": "J-20A Operational", "category": "Engine", "tier": 8,
     "reliability_bonus": 14, "fuel_efficiency": 16, "speed_bonus": 40,
     "cost": {"steel": 26, "aluminum": 48, "titanium": 30, "electronics": 45}, "production_time": 185,
     "special_flags": ["china", "twenty_twenties", "j20", "stealth"],
     "description": "WS-15-powered J-20 in serial production. PLAAF premier air superiority fighter."},
    {"id": "j35_carrier_fighter", "name": "J-35", "category": "Engine", "tier": 8,
     "reliability_bonus": 12, "fuel_efficiency": 14, "speed_bonus": 36,
     "cost": {"steel": 22, "aluminum": 42, "titanium": 26, "electronics": 40}, "production_time": 170,
     "special_flags": ["china", "twenty_twenties", "carrier", "stealth"],
     "description": "Carrier-based fifth-gen fighter for Fujian and Shandong upgrades."},
    {"id": "pl15e_missile", "name": "PL-15E", "category": "MainWeapon", "tier": 8,
     "soft_attack": 15, "hard_attack": 13, "air_attack": 98, "anti_air": 94,
     "cost": {"steel": 8, "electronics": 52, "explosives": 12}, "production_time": 80,
     "special_flags": ["china", "twenty_twenties", "air_to_air", "bvr"],
     "description": "Export and improved PL-15 with extended range. Drives U.S. JATM requirement."},
    {"id": "pl21_missile", "name": "PL-21 (Projected)", "category": "MainWeapon", "tier": 9,
     "soft_attack": 17, "hard_attack": 15, "air_attack": 105, "anti_air": 100,
     "cost": {"steel": 9, "electronics": 60, "explosives": 14}, "production_time": 90,
     "special_flags": ["china", "twenty_thirties", "air_to_air", "planned", "very_long_range"],
     "description": "Next-generation very-long-range AAM for AWACS and tanker kill chains."},
    {"id": "fujian_emals_carrier", "name": "Fujian EMALS Carrier", "category": "Cargo", "tier": 8,
     "reliability_bonus": 6,
     "cost": {"steel": 150, "electronics": 70, "copper": 40}, "production_time": 250,
     "special_flags": ["china", "twenty_twenties", "carrier", "emals"],
     "description": "Type 003 Fujian with electromagnetic catapults. Enables J-35 and KJ-600 operations."},
    {"id": "type055_destroyer_vls", "name": "Type 055 VLS Suite", "category": "SecondaryWeapon", "tier": 8,
     "soft_attack": 65, "hard_attack": 75, "piercing": 55, "anti_ship": 105, "air_attack": 50,
     "cost": {"steel": 45, "electronics": 60, "explosives": 55}, "production_time": 160,
     "special_flags": ["china", "naval", "twenty_twenties", "destroyer"],
     "description": "112-cell VLS on Renhai cruiser. Area air defense and anti-ship strike."},
    {"id": "df27_hypersonic", "name": "DF-27 (Projected)", "category": "MainWeapon", "tier": 9,
     "soft_attack": 150, "hard_attack": 90, "piercing": 80, "anti_ship": 125, "air_attack": 12,
     "cost": {"steel": 30, "electronics": 70, "explosives": 65}, "production_time": 150,
     "special_flags": ["china", "twenty_thirties", "hypersonic", "planned"],
     "description": "Multi-role hypersonic IRBM for land and maritime strike. 2030s deterrent upgrade."},
    {"id": "type100_mbt_proto", "name": "Type 100 (Prototype)", "category": "Armor", "tier": 9,
     "armor_bonus": 80, "top_armor_bonus": 50, "reliability_penalty": -6,
     "cost": {"steel": 55, "ceramics": 35, "electronics": 30}, "production_time": 180,
     "special_flags": ["china", "twenty_thirties", "mbt", "planned"],
     "description": "Projected fourth-generation Chinese MBT with unmanned turret and active protection."},
    {"id": "h20_bomber_package", "name": "H-20 Stealth Bomber", "category": "Engine", "tier": 9,
     "reliability_bonus": 12, "fuel_efficiency": 18, "speed_bonus": 32,
     "cost": {"steel": 40, "aluminum": 65, "titanium": 35, "electronics": 60}, "production_time": 240,
     "special_flags": ["china", "twenty_thirties", "stealth", "bomber", "planned"],
     "description": "Flying-wing stealth bomber program. Strategic strike comparable to B-21."},

    # ═══════════════════════════════════════════════════════════════════════════
    # FRANCE · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "rafale_f4_package", "name": "Rafale F4", "category": "Sensors", "tier": 8,
     "reliability_bonus": 12,
     "cost": {"steel": 12, "electronics": 65, "aluminum": 22}, "production_time": 140,
     "special_flags": ["france", "twenty_twenties", "rafale"],
     "description": "Rafale F4 standard with RBE2 AA AESA and Talios pod. Export and French Air Force."},
    {"id": "jaguar_ebrc", "name": "Jaguar EBRC 40 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 42, "hard_attack": 32, "piercing": 55, "air_attack": 18,
     "cost": {"steel": 18, "electronics": 15, "aluminum": 10}, "production_time": 70,
     "special_flags": ["france", "twenty_twenties", "scorpion", "recon"],
     "description": "Jaguar armored reconnaissance vehicle from Scorpion program. MMP anti-tank missiles."},
    {"id": "griffon_apc_package", "name": "Griffon APC", "category": "Armor", "tier": 5,
     "armor_bonus": 30, "top_armor_bonus": 18, "reliability_penalty": -2,
     "cost": {"steel": 22, "aluminum": 12, "ceramics": 6}, "production_time": 55,
     "special_flags": ["france", "twenty_twenties", "scorpion", "apc"],
     "description": "Multi-role armored vehicle replacing VAB. Scorpion fleet backbone."},
    {"id": "mmp_atgm", "name": "MMP", "category": "MainWeapon", "tier": 7,
     "soft_attack": 40, "hard_attack": 72, "piercing": 155, "air_attack": 4,
     "cost": {"steel": 8, "electronics": 42, "explosives": 16}, "production_time": 68,
     "special_flags": ["france", "twenty_twenties", "atgm", "fire_and_forget"],
     "description": "Missile Moyenne Portée replacing MILAN. Man-in-loop and fire-and-forget."},
    {"id": "fcas_ngf_proto", "name": "FCAS NGF (Prototype)", "category": "Engine", "tier": 9,
     "reliability_bonus": 14, "fuel_efficiency": 18, "speed_bonus": 40,
     "cost": {"steel": 28, "aluminum": 55, "titanium": 38, "electronics": 60}, "production_time": 220,
     "special_flags": ["france", "germany_joint", "twenty_thirties", "sixth_gen", "planned", "fcas"],
     "description": "Future Combat Air System New Generation Fighter. Franco-German-Spanish 2035+ target."},
    {"id": "mgcs_main_gun", "name": "MGCS 140 mm (Planned)", "category": "MainWeapon", "tier": 9,
     "soft_attack": 82, "hard_attack": 80, "piercing": 210, "air_attack": 5,
     "cost": {"steel": 42, "chromium": 14, "tungsten": 12}, "production_time": 140,
     "special_flags": ["france", "germany_joint", "twenty_thirties", "mgcs", "planned"],
     "description": "Proposed 140 mm main gun for Main Ground Combat System replacing Leopard 2 and Leclerc."},
    {"id": "mgcs_armor_package", "name": "MGCS Armor Package", "category": "Armor", "tier": 9,
     "armor_bonus": 85, "top_armor_bonus": 55, "reliability_penalty": -6,
     "cost": {"steel": 55, "ceramics": 40, "titanium": 18, "electronics": 20}, "production_time": 170,
     "special_flags": ["france", "germany_joint", "twenty_thirties", "mgcs", "planned"],
     "description": "Modular armor and APS for Franco-German next-generation MBT."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED KINGDOM · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "challenger3_package", "name": "Challenger 3 Package", "category": "MainWeapon", "tier": 8,
     "soft_attack": 80, "hard_attack": 78, "piercing": 190, "air_attack": 5,
     "cost": {"steel": 34, "chromium": 12, "tungsten": 10}, "production_time": 120,
     "special_flags": ["uk", "twenty_twenties", "challenger3", "rh120_l55a1"],
     "description": "Challenger 3 with Rheinmetall L55A1 and new turret. Only 148 units; elite heavy brigade."},
    {"id": "challenger3_armor", "name": "Challenger 3 Armor", "category": "Armor", "tier": 8,
     "armor_bonus": 80, "top_armor_bonus": 56, "reliability_penalty": -5,
     "cost": {"steel": 55, "ceramics": 35, "titanium": 14, "kevlar": 12}, "production_time": 140,
     "special_flags": ["uk", "twenty_twenties", "challenger3"],
     "description": "New turret with improved modular armor and Trophy APS option."},
    {"id": "ajax_ifv_package", "name": "Ajax IFV Package", "category": "Sensors", "tier": 7,
     "reliability_bonus": 6,
     "cost": {"steel": 22, "electronics": 45, "optics": 25}, "production_time": 95,
     "special_flags": ["uk", "twenty_twenties", "ajax", "ct40"],
     "description": "Ajax with 40 mm CTA cannon and advanced sensors. Troubled program but 2020s fielding."},
    {"id": "type26_frigate_package", "name": "Type 26 Frigate Package", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 50, "electronics": 55, "aluminum": 18}, "production_time": 150,
     "special_flags": ["uk", "twenty_twenties", "naval", "asw"],
     "description": "City-class ASW frigate with Sonar 2087 and Mk 41 VLS."},
    {"id": "gcas_tempest_engine", "name": "GCAP Tempest Engine", "category": "Engine", "tier": 9,
     "reliability_bonus": 16, "fuel_efficiency": 20, "speed_bonus": 42,
     "cost": {"steel": 28, "aluminum": 58, "titanium": 40, "electronics": 50}, "production_time": 230,
     "special_flags": ["uk", "italy_joint", "japan_joint", "twenty_thirties", "sixth_gen", "planned", "gcas"],
     "description": "Global Combat Air Programme sixth-gen fighter (Tempest). UK-Italy-Japan 2035 entry."},
    {"id": "spear3_missile", "name": "SPEAR 3", "category": "MainWeapon", "tier": 8,
     "soft_attack": 50, "hard_attack": 58, "piercing": 70, "air_attack": 10,
     "cost": {"steel": 8, "electronics": 40, "explosives": 18}, "production_time": 75,
     "special_flags": ["uk", "twenty_twenties", "cruise_missile", "miniature"],
     "description": "Miniature cruise missile for F-35 internal bays. Swarming precision strike."},

    # ═══════════════════════════════════════════════════════════════════════════
    # GERMANY · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "leopard2a8_package", "name": "Leopard 2A8", "category": "Armor", "tier": 8,
     "armor_bonus": 82, "top_armor_bonus": 58, "reliability_penalty": -5,
     "cost": {"steel": 55, "ceramics": 35, "titanium": 16, "electronics": 18}, "production_time": 145,
     "special_flags": ["germany", "twenty_twenties", "leopard2", "trophy"],
     "description": "Leopard 2A8 with Trophy APS and improved armor for European deterrence."},
    {"id": "boxer_rcws_package", "name": "Boxer RCWS Package", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 30, "hard_attack": 18, "piercing": 40, "air_attack": 20,
     "cost": {"steel": 14, "electronics": 25, "aluminum": 12}, "production_time": 60,
     "special_flags": ["germany", "twenty_twenties", "wheeled", "ifv"],
     "description": "Boxer MRAV with remote weapon station and Spike integration."},
    {"id": "puma_vjtf_upgrade", "name": "Puma VJTF Upgrade", "category": "Armor", "tier": 8,
     "armor_bonus": 48, "top_armor_bonus": 32, "reliability_penalty": -5,
     "cost": {"steel": 38, "ceramics": 22, "electronics": 15}, "production_time": 100,
     "special_flags": ["germany", "twenty_twenties", "puma", "nato"],
     "description": "Puma enhancement for Very High Readiness Joint Task Force."},
    {"id": "fcas_ngf_germany", "name": "FCAS (Germany)", "category": "Sensors", "tier": 9,
     "reliability_bonus": 12,
     "cost": {"steel": 15, "electronics": 75, "aluminum": 25}, "production_time": 200,
     "special_flags": ["germany", "france_joint", "twenty_thirties", "planned", "fcas"],
     "description": "German participation in FCAS/NGF with Eurodrone and networked warfare."},
    {"id": "iris_t_slx", "name": "IRIS-T SLX", "category": "AntiAir", "tier": 8,
     "soft_attack": 14, "hard_attack": 12, "air_attack": 92, "anti_air": 88,
     "cost": {"steel": 20, "electronics": 48, "explosives": 14}, "production_time": 95,
     "special_flags": ["germany", "twenty_twenties", "sam", "extended_range"],
     "description": "Extended-range IRIS-T for European Sky Shield and national defense."},

    # ═══════════════════════════════════════════════════════════════════════════
    # ISRAEL · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "merkava_mk4_barak", "name": "Merkava Mk 4 Barak", "category": "Armor", "tier": 8,
     "armor_bonus": 78, "top_armor_bonus": 48, "reliability_penalty": -4,
     "cost": {"steel": 50, "ceramics": 28, "kevlar": 16, "electronics": 18}, "production_time": 120,
     "special_flags": ["israel", "twenty_twenties", "merkava", "trophy"],
     "description": "Merkava Mk 4M with Trophy APS and Barak FCS. Gaza operations 2020s."},
    {"id": "iron_beam_laser", "name": "Iron Beam", "category": "AntiAir", "tier": 9,
     "soft_attack": 18, "hard_attack": 14, "air_attack": 96, "anti_air": 94,
     "cost": {"steel": 12, "electronics": 70, "chemicals": 25}, "production_time": 130,
     "special_flags": ["israel", "twenty_twenties", "directed_energy", "laser"],
     "description": "High-power laser air defense vs rockets and drones. Complements Iron Dome."},
    {"id": "spike_lr5", "name": "Spike LR II", "category": "MainWeapon", "tier": 8,
     "soft_attack": 42, "hard_attack": 75, "piercing": 160, "air_attack": 5,
     "cost": {"steel": 9, "electronics": 48, "explosives": 18}, "production_time": 78,
     "special_flags": ["israel", "twenty_twenties", "atgm", "fire_and_forget"],
     "description": "Fifth-generation Spike with extended range and ECCM."},
    {"id": "f35i_adir_block4", "name": "F-35I Adir Block 4", "category": "Sensors", "tier": 8,
     "reliability_bonus": 12,
     "cost": {"steel": 12, "electronics": 75, "aluminum": 22}, "production_time": 165,
     "special_flags": ["israel", "twenty_twenties", "f35", "stealth"],
     "description": "Israeli F-35I with indigenous EW and strike packages. Regional strike role."},
    {"id": "merkava_mk5_proto", "name": "Merkava Mk V (Prototype)", "category": "Armor", "tier": 9,
     "armor_bonus": 85, "top_armor_bonus": 52, "reliability_penalty": -5,
     "cost": {"steel": 52, "ceramics": 32, "electronics": 28, "kevlar": 18}, "production_time": 150,
     "special_flags": ["israel", "twenty_thirties", "merkava", "planned"],
     "description": "Projected Merkava with hybrid drive, Trophy HV, and reduced crew via automation."},
    {"id": "arrow4_interceptor", "name": "Arrow 4 (Projected)", "category": "AntiAir", "tier": 9,
     "soft_attack": 20, "hard_attack": 18, "air_attack": 102, "anti_air": 100,
     "cost": {"steel": 15, "electronics": 80, "explosives": 25}, "production_time": 145,
     "special_flags": ["israel", "twenty_thirties", "bmd", "planned"],
     "description": "Next-tier ballistic missile defense vs hypersonic threats."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SHARED · 2020s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "aesa_radar_gen2", "name": "AESA Radar (Gen 2)", "category": "Sensors", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 10, "electronics": 80, "rare_earths": 22}, "production_time": 140,
     "special_flags": ["nato", "twenty_twenties", "aesa", "low_probability_intercept"],
     "description": "Second-generation AESA with improved jam resistance and multi-function capability."},
    {"id": "ai_targeting_suite", "name": "AI-Assisted Targeting", "category": "Sensors", "tier": 8,
     "reliability_bonus": 12,
     "cost": {"steel": 4, "electronics": 65}, "production_time": 90,
     "special_flags": ["global", "twenty_twenties", "ai", "fcs"],
     "description": "Machine-learning aided target recognition and prioritization in FCS and ISR."},
    {"id": "swarm_loitering_munition", "name": "Loitering Munition Swarm", "category": "DroneAttachment", "tier": 7,
     "reliability_bonus": 4,
     "cost": {"steel": 6, "electronics": 40, "explosives": 15}, "production_time": 55,
     "special_flags": ["global", "twenty_twenties", "swarm", "ukraine_lessons"],
     "description": "Switchblade-class and Shahed-style mass attack munitions reshaping battlefield economics."},
    {"id": "satcom_mosaic_warfare", "name": "Satcom / Mosaic Warfare", "category": "Sensors", "tier": 8,
     "reliability_bonus": 14,
     "cost": {"steel": 5, "electronics": 70}, "production_time": 100,
     "special_flags": ["nato", "twenty_twenties", "space", "datalink"],
     "description": "Starlink and military SATCOM enabling distributed kill chains and artillery coordination."},
    {"id": "autonomous_ugv_2030", "name": "Autonomous UGV (2030)", "category": "DroneAttachment", "tier": 9,
     "reliability_bonus": 8,
     "cost": {"steel": 15, "electronics": 65, "lithium": 18}, "production_time": 110,
     "special_flags": ["global", "twenty_thirties", "ugv", "autonomous"],
     "description": "Optionally manned and autonomous ground resupply and combat vehicles."},
    {"id": "quantum_ew_resistant_comms", "name": "Quantum-Resistant Comms", "category": "Communications", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 3, "electronics": 55}, "production_time": 85,
     "special_flags": ["nato", "twenty_thirties", "planned", "cyber"],
     "description": "Post-quantum cryptography for tactical networks in 2030s peer conflict."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\n2020s–2030s: {created} created, {skipped} skipped, {total} total modules.")


if __name__ == "__main__":
    main()
