#!/usr/bin/env python3
"""Space modules: rockets, satellites, stations, 1940s–2030s. NASA, USSR/Russia, Germany, ESA, SpaceX, China, others."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════════
    # GERMANY · 1940s (Aggregat / V-2)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "a4_v2_engine", "name": "A4/V-2 Rocket Engine", "category": "Engine", "tier": 3,
     "reliability_bonus": -8, "fuel_efficiency": -12, "speed_bonus": 28,
     "cost": {"steel": 12, "aluminum": 8, "explosives": 25}, "production_time": 80,
     "special_flags": ["germany", "space", "forties", "liquid_fuel", "ballistic"],
     "description": "Walter HWK 109-509 style ethanol/LOX engine on V-2. First long-range ballistic missile."},
    {"id": "v2_guidance_package", "name": "V-2 Guidance Package", "category": "Sensors", "tier": 2,
     "reliability_bonus": -4,
     "cost": {"steel": 4, "electronics": 6, "optics": 4}, "production_time": 45,
     "special_flags": ["germany", "space", "forties", "inertial"],
     "description": "Gyroscopic guidance for A4. Crude but revolutionary for 1944."},
    {"id": "aggregat4_stage", "name": "Aggregat 4 Stage Package", "category": "Cargo", "tier": 3,
     "reliability_bonus": -6,
     "cost": {"steel": 18, "aluminum": 10, "explosives": 40}, "production_time": 70,
     "special_flags": ["germany", "space", "forties", "single_stage_to_space_border"],
     "description": "Complete V-2 airframe and propellant tanks. Suborbital only; foundation of space age."},

    # ═══════════════════════════════════════════════════════════════════════════
    # USA · 1940s–1950s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "redstone_engine", "name": "Redstone Rocket Engine", "category": "Engine", "tier": 3,
     "reliability_bonus": 2, "fuel_efficiency": -8, "speed_bonus": 22,
     "cost": {"steel": 14, "aluminum": 6, "explosives": 20}, "production_time": 65,
     "special_flags": ["usa", "nasa", "space", "fifties", "ballistic"],
     "description": "Modified V-2 derived engine for Redstone. First U.S. IRBM and Mercury suborbital launcher."},
    {"id": "jupiter_irbm_stage", "name": "Jupiter IRBM Stage", "category": "Cargo", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 16, "explosives": 28, "electronics": 8}, "production_time": 72,
     "special_flags": ["usa", "space", "fifties"],
     "description": "Jupiter-C and Juno I upper stages. Launched Explorer 1."},
    {"id": "vanguard_second_stage", "name": "Vanguard Second Stage", "category": "Engine", "tier": 3,
     "reliability_bonus": 6, "fuel_efficiency": 4, "speed_bonus": 18,
     "cost": {"steel": 6, "aluminum": 8, "explosives": 12}, "production_time": 55,
     "special_flags": ["usa", "nasa", "space", "fifties", "satellite_launch"],
     "description": "Solid upper stage for Vanguard. Second U.S. satellite launcher after Explorer."},
    {"id": "explorer1_science_payload", "name": "Explorer 1 Science Package", "category": "Sensors", "tier": 2,
     "reliability_bonus": 8,
     "cost": {"steel": 2, "electronics": 10, "rare_earths": 2}, "production_time": 40,
     "special_flags": ["usa", "nasa", "space", "fifties", "science"],
     "description": "Van Allen radiation belt discovery payload. First U.S. satellite science instrument."},

    # ═══════════════════════════════════════════════════════════════════════════
    # USSR · 1940s–1950s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "r7_soyuz_engine", "name": "RD-107/108 (R-7)", "category": "Engine", "tier": 4,
     "reliability_bonus": 10, "fuel_efficiency": 2, "speed_bonus": 30,
     "cost": {"steel": 20, "aluminum": 12, "explosives": 35}, "production_time": 90,
     "special_flags": ["ussr", "space", "fifties", "kerolox", "iconic"],
     "description": "R-7 Semyorka booster engines. Launched Sputnik and still flies as Soyuz lineage."},
    {"id": "sputnik1_bus", "name": "Sputnik 1 Bus", "category": "Communications", "tier": 2,
     "reliability_bonus": 12,
     "cost": {"steel": 3, "electronics": 8, "aluminum": 4}, "production_time": 35,
     "special_flags": ["ussr", "space", "fifties", "beep", "first_satellite"],
     "description": "Simple radio beacon satellite. October 1957; opened the Space Age."},
    {"id": "luna_probe_bus", "name": "Luna Probe Bus", "category": "Sensors", "tier": 3,
     "reliability_bonus": 6,
     "cost": {"steel": 5, "electronics": 14, "aluminum": 6}, "production_time": 55,
     "special_flags": ["ussr", "space", "fifties", "lunar"],
     "description": "Early Soviet lunar flyby and impact probe avionics."},

    # ═══════════════════════════════════════════════════════════════════════════
    # USA · 1960s (Mercury, Gemini, Apollo, Saturn)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "f1_saturn_engine", "name": "F-1 (Saturn V)", "category": "Engine", "tier": 5,
     "reliability_bonus": 8, "fuel_efficiency": -14, "speed_bonus": 38,
     "cost": {"steel": 45, "aluminum": 20, "explosives": 80}, "production_time": 140,
     "special_flags": ["usa", "nasa", "space", "sixties", "lunar"],
     "description": "Most powerful single-chamber liquid rocket ever flown. Saturn V first stage."},
    {"id": "j2_upper_stage_engine", "name": "J-2 Upper Stage", "category": "Engine", "tier": 4,
     "reliability_bonus": 10, "fuel_efficiency": 4, "speed_bonus": 32,
     "cost": {"steel": 18, "aluminum": 14, "explosives": 30}, "production_time": 95,
     "special_flags": ["usa", "nasa", "space", "sixties", "hydrogen"],
     "description": "Saturn V second and third stage engine. LH2/LOX high-efficiency upper stage."},
    {"id": "apollo_csm_capsule", "name": "Apollo CSM Capsule", "category": "LifeSupport", "tier": 5,
     "reliability_bonus": 12,
     "cost": {"steel": 12, "aluminum": 18, "electronics": 25, "chemicals": 8}, "production_time": 110,
     "special_flags": ["usa", "nasa", "space", "sixties", "crewed", "lunar"],
     "description": "Command and service module for Apollo lunar missions. Three crew to Moon and back."},
    {"id": "apollo_lm_lander", "name": "Apollo Lunar Module", "category": "LifeSupport", "tier": 5,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "aluminum": 22, "electronics": 20}, "production_time": 105,
     "special_flags": ["usa", "nasa", "space", "sixties", "lunar_lander"],
     "description": "Two-man lunar lander. Ascent stage returns crew to CSM."},
    {"id": "gemini_capsule", "name": "Gemini Capsule", "category": "LifeSupport", "tier": 4,
     "reliability_bonus": 10,
     "cost": {"steel": 8, "aluminum": 12, "electronics": 18}, "production_time": 85,
     "special_flags": ["usa", "nasa", "space", "sixties", "crewed"],
     "description": "Two-crew spacecraft. Rendezvous and EVA practice for Apollo."},
    {"id": "telstar_comms_payload", "name": "Telstar Comms Payload", "category": "Communications", "tier": 4,
     "reliability_bonus": 10,
     "cost": {"steel": 4, "electronics": 22, "aluminum": 8}, "production_time": 65,
     "special_flags": ["usa", "space", "sixties", "comms", "transatlantic"],
     "description": "First active communications satellite relay. AT&T/NASA collaboration."},

    # ═══════════════════════════════════════════════════════════════════════════
    # USSR · 1960s (Vostok, Voskhod, Soyuz, Proton)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "soyuz_spacecraft_bus", "name": "Soyuz Spacecraft", "category": "LifeSupport", "tier": 5,
     "reliability_bonus": 14,
     "cost": {"steel": 10, "aluminum": 14, "electronics": 22}, "production_time": 100,
     "special_flags": ["ussr", "russia", "space", "sixties", "crewed", "soyuz"],
     "description": "Soyuz capsule and service module. Most-flown crewed spacecraft design in history."},
    {"id": "proton_rocket_stage", "name": "Proton First Stage", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6, "fuel_efficiency": -6, "speed_bonus": 34,
     "cost": {"steel": 35, "aluminum": 15, "explosives": 70}, "production_time": 120,
     "special_flags": ["ussr", "russia", "space", "sixties", "heavy_lift"],
     "description": "UR-500 Proton heavy launcher. Military and civilian modules to high orbit."},
    {"id": "salyut_station_module", "name": "Salyut Station Module", "category": "Cargo", "tier": 4,
     "reliability_bonus": 8,
     "cost": {"steel": 25, "aluminum": 20, "electronics": 30, "chemicals": 12}, "production_time": 130,
     "special_flags": ["ussr", "space", "seventies", "space_station"],
     "description": "First generation Soviet space station core. Military Almaz and civilian Salyut."},
    {"id": "lunokhod_rover_bus", "name": "Lunokhod Rover Bus", "category": "Sensors", "tier": 4,
     "reliability_bonus": 6,
     "cost": {"steel": 8, "electronics": 18, "aluminum": 10}, "production_time": 75,
     "special_flags": ["ussr", "space", "seventies", "lunar_rover"],
     "description": "Remote-controlled lunar rover. Soviet surface exploration first."},

    # ═══════════════════════════════════════════════════════════════════════════
    # USA · 1970s–1980s (Shuttle, Skylab, Hubble, GPS)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "ssme_shuttle_engine", "name": "RS-25 (Space Shuttle SSME)", "category": "Engine", "tier": 6,
     "reliability_bonus": 16, "fuel_efficiency": 8, "speed_bonus": 32,
     "cost": {"steel": 28, "aluminum": 25, "explosives": 40}, "production_time": 130,
     "special_flags": ["usa", "nasa", "space", "seventies", "reusable"],
     "description": "Space Shuttle main engine. Reusable high-performance hydrogen engine."},
    {"id": "shuttle_orbiter_package", "name": "Space Shuttle Orbiter", "category": "Cargo", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 80, "aluminum": 60, "electronics": 50, "ceramics": 15}, "production_time": 200,
     "special_flags": ["usa", "nasa", "space", "seventies", "reusable", "crewed"],
     "description": "Winged orbiter with payload bay. Crew and cargo to LEO 1981–2011."},
    {"id": "skylab_station", "name": "Skylab Station", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 60, "aluminum": 40, "electronics": 35}, "production_time": 160,
     "special_flags": ["usa", "nasa", "space", "seventies", "space_station"],
     "description": "Orbital workshop from Saturn V third stage. First U.S. space station."},
    {"id": "hubble_space_telescope", "name": "Hubble Space Telescope", "category": "Sensors", "tier": 6,
     "reliability_bonus": 14,
     "cost": {"steel": 8, "electronics": 45, "optics": 35, "aluminum": 12}, "production_time": 150,
     "special_flags": ["usa", "nasa", "esa_joint", "space", "eighties", "science"],
     "description": "2.4 m optical telescope in LEO. Serviced by Shuttle; revolutionized astronomy."},
    {"id": "gps_block1_payload", "name": "GPS Block I Payload", "category": "Communications", "tier": 5,
     "reliability_bonus": 12,
     "cost": {"steel": 4, "electronics": 35, "aluminum": 6}, "production_time": 90,
     "special_flags": ["usa", "nasa", "space", "seventies", "navigation"],
     "description": "Navstar global positioning satellite. Transformed warfare and civilian navigation."},
    {"id": "viking_mars_lander", "name": "Viking Mars Lander", "category": "Sensors", "tier": 5,
     "reliability_bonus": 10,
     "cost": {"steel": 10, "electronics": 30, "chemicals": 15}, "production_time": 100,
     "special_flags": ["usa", "nasa", "space", "seventies", "mars"],
     "description": "First successful Mars lander with life-detection experiments."},

    # ═══════════════════════════════════════════════════════════════════════════
    # EUROPE / ESA · 1970s–2000s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "ariane1_first_stage", "name": "Ariane 1 First Stage", "category": "Engine", "tier": 4,
     "reliability_bonus": 8, "fuel_efficiency": 2, "speed_bonus": 28,
     "cost": {"steel": 18, "aluminum": 12, "explosives": 35}, "production_time": 85,
     "special_flags": ["esa", "france", "space", "seventies", "ariane"],
     "description": "European expendable launcher debut 1979. Independent European space access."},
    {"id": "ariane5_core_stage", "name": "Ariane 5 Core Stage", "category": "Cargo", "tier": 6,
     "reliability_bonus": 12, "fuel_efficiency": 4, "speed_bonus": 34,
     "cost": {"steel": 40, "aluminum": 25, "explosives": 65}, "production_time": 130,
     "special_flags": ["esa", "space", "nineties", "ariane", "heavy_lift"],
     "description": "Ariane 5 ECA heavy lifter. Launched Rosetta, JWST, and Galileo."},
    {"id": "columbus_lab_module", "name": "Columbus Lab Module", "category": "Cargo", "tier": 6,
     "reliability_bonus": 14,
     "cost": {"steel": 35, "aluminum": 30, "electronics": 45}, "production_time": 160,
     "special_flags": ["esa", "space", "two_thousands", "iss"],
     "description": "ESA ISS laboratory module. Microgravity science for European astronauts."},
    {"id": "rosetta_comet_probe", "name": "Rosetta/Philae Package", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 8, "electronics": 40, "aluminum": 12}, "production_time": 140,
     "special_flags": ["esa", "space", "two_thousands", "comet", "science"],
     "description": "Comet 67P rendezvous and lander. Landmark ESA deep-space mission."},
    {"id": "vega_light_launcher", "name": "Vega Light Launcher", "category": "Engine", "tier": 5,
     "reliability_bonus": 10, "fuel_efficiency": 6, "speed_bonus": 26,
     "cost": {"steel": 12, "aluminum": 10, "explosives": 25}, "production_time": 75,
     "special_flags": ["esa", "italy", "space", "two_thousands", "small_sat"],
     "description": "Small satellite launcher for European institutional payloads."},

    # ═══════════════════════════════════════════════════════════════════════════
    # USSR/RUSSIA · 1980s–2000s (Energia, Buran, Mir, GLONASS)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "energia_booster", "name": "Energia Booster", "category": "Engine", "tier": 6,
     "reliability_bonus": 4, "fuel_efficiency": -4, "speed_bonus": 40,
     "cost": {"steel": 55, "aluminum": 30, "explosives": 100}, "production_time": 160,
     "special_flags": ["ussr", "space", "eighties", "super_heavy"],
     "description": "Soviet super-heavy launcher. Carried Buran and Polyus; canceled with USSR collapse."},
    {"id": "buran_orbiter", "name": "Buran Orbiter", "category": "Cargo", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 75, "aluminum": 55, "electronics": 45}, "production_time": 190,
     "special_flags": ["ussr", "space", "eighties", "reusable", "shuttle_like"],
     "description": "Soviet space shuttle. One autonomous flight 1988; program canceled."},
    {"id": "mir_core_module", "name": "Mir Core Module", "category": "Cargo", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 50, "aluminum": 35, "electronics": 40, "chemicals": 15}, "production_time": 170,
     "special_flags": ["ussr", "russia", "space", "eighties", "space_station"],
     "description": "Modular space station operated 1986–2001. Long-duration Soviet/Russian presence in LEO."},
    {"id": "glonass_payload", "name": "GLONASS Payload", "category": "Communications", "tier": 5,
     "reliability_bonus": 10,
     "cost": {"steel": 4, "electronics": 32, "aluminum": 6}, "production_time": 85,
     "special_flags": ["russia", "space", "nineties", "navigation"],
     "description": "Russian global navigation satellite system counterpart to GPS."},
    {"id": "proton_m_upgrade", "name": "Proton-M Upgrade", "category": "Cargo", "tier": 6,
     "reliability_bonus": 8, "fuel_efficiency": -4, "speed_bonus": 35,
     "cost": {"steel": 38, "aluminum": 18, "explosives": 75}, "production_time": 125,
     "special_flags": ["russia", "space", "two_thousands", "commercial"],
     "description": "Modernized Proton for ISS modules and commercial satellites."},

    # ═══════════════════════════════════════════════════════════════════════════
    # CHINA · 1970s–2020s (Long March, Shenzhou, Chang'e, Tiangong, BeiDou)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "long_march2_engine", "name": "Long March 2 Engine", "category": "Engine", "tier": 4,
     "reliability_bonus": 6, "fuel_efficiency": -2, "speed_bonus": 28,
     "cost": {"steel": 16, "aluminum": 10, "explosives": 30}, "production_time": 80,
     "special_flags": ["china", "space", "seventies", "casc"],
     "description": "LM-2 family engines. Launched FSW satellites and early crew program tests."},
    {"id": "long_march5_heavy", "name": "Long March 5", "category": "Cargo", "tier": 7,
     "reliability_bonus": 10, "fuel_efficiency": 4, "speed_bonus": 36,
     "cost": {"steel": 45, "aluminum": 30, "explosives": 80}, "production_time": 145,
     "special_flags": ["china", "space", "twenty_twenties", "heavy_lift"],
     "description": "CZ-5 heavy launcher for space station modules and Mars missions."},
    {"id": "shenzhou_capsule", "name": "Shenzhou Capsule", "category": "LifeSupport", "tier": 6,
     "reliability_bonus": 12,
     "cost": {"steel": 12, "aluminum": 16, "electronics": 28}, "production_time": 115,
     "special_flags": ["china", "space", "two_thousands", "crewed", "shenzhou"],
     "description": "Chinese crewed spacecraft derived from Soyuz architecture. First taikonaut 2003."},
    {"id": "tiangong_station_module", "name": "Tiangong Station Module", "category": "Cargo", "tier": 6,
     "reliability_bonus": 12,
     "cost": {"steel": 40, "aluminum": 32, "electronics": 38}, "production_time": 150,
     "special_flags": ["china", "space", "twenty_twenties", "space_station"],
     "description": "Tiangong and CSS modular station. Independent Chinese LEO presence."},
    {"id": "change_lunar_lander", "name": "Chang'e Lunar Lander", "category": "Sensors", "tier": 6,
     "reliability_bonus": 12,
     "cost": {"steel": 10, "electronics": 35, "aluminum": 14}, "production_time": 120,
     "special_flags": ["china", "space", "twenty_twenties", "lunar", "sample_return"],
     "description": "Chang'e lunar lander and sample return. Far side landing first."},
    {"id": "beidou_navigation_payload", "name": "BeiDou Navigation Payload", "category": "Communications", "tier": 6,
     "reliability_bonus": 14,
     "cost": {"steel": 4, "electronics": 38, "aluminum": 8}, "production_time": 95,
     "special_flags": ["china", "space", "twenty_twenties", "navigation"],
     "description": "Chinese global navigation constellation. Independent of GPS/GLONASS."},
    {"id": "tiangong_space_station_core", "name": "CSS Core Module (Tianhe)", "category": "Cargo", "tier": 7,
     "reliability_bonus": 14,
     "cost": {"steel": 48, "aluminum": 38, "electronics": 42}, "production_time": 165,
     "special_flags": ["china", "space", "twenty_twenties", "iss_class"],
     "description": "Chinese Space Station core. Permanent crew and international experiment racks."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SPACEX · 2000s–2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "merlin1d_engine", "name": "Merlin 1D", "category": "Engine", "tier": 6,
     "reliability_bonus": 14, "fuel_efficiency": 10, "speed_bonus": 30,
     "cost": {"steel": 10, "aluminum": 14, "explosives": 18}, "production_time": 70,
     "special_flags": ["spacex", "usa", "space", "twenty_twenties", "reusable"],
     "description": "Falcon 9 first-stage engine. Designed for reusability and high flight rate."},
    {"id": "falcon9_stage_package", "name": "Falcon 9 Stage Package", "category": "Cargo", "tier": 6,
     "reliability_bonus": 12,
     "cost": {"steel": 25, "aluminum": 22, "electronics": 30}, "production_time": 95,
     "special_flags": ["spacex", "usa", "space", "twenty_twenties", "reusable"],
     "description": "Falcon 9 booster with landing legs and grid fins. Dominant commercial launcher."},
    {"id": "falcon_heavy_core", "name": "Falcon Heavy Core", "category": "Cargo", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 70, "aluminum": 55, "electronics": 45}, "production_time": 140,
     "special_flags": ["spacex", "usa", "space", "twenty_twenties", "heavy_lift"],
     "description": "Three Falcon 9 cores strapped together. Heavy payloads and deep-space missions."},
    {"id": "dragon2_capsule", "name": "Crew Dragon", "category": "LifeSupport", "tier": 7,
     "reliability_bonus": 16,
     "cost": {"steel": 14, "aluminum": 20, "electronics": 40}, "production_time": 125,
     "special_flags": ["spacex", "usa", "nasa", "space", "twenty_twenties", "crewed"],
     "description": "Crew Dragon for ISS and commercial flights. Restored U.S. crew launch capability."},
    {"id": "starship_raptor_engine", "name": "Raptor (Starship)", "category": "Engine", "tier": 8,
     "reliability_bonus": 8, "fuel_efficiency": 12, "speed_bonus": 38,
     "cost": {"steel": 12, "aluminum": 18, "electronics": 25, "chemicals": 15}, "production_time": 90,
     "special_flags": ["spacex", "usa", "space", "twenty_twenties", "methalox", "mars"],
     "description": "Full-flow staged combustion methalox engine. Powers Starship super-heavy system."},
    {"id": "starship_vehicle_package", "name": "Starship Vehicle", "category": "Cargo", "tier": 9,
     "reliability_bonus": 6,
     "cost": {"steel": 90, "aluminum": 70, "electronics": 60, "chemicals": 40}, "production_time": 220,
     "special_flags": ["spacex", "usa", "space", "twenty_twenties", "super_heavy", "reusable"],
     "description": "Starship/Super Heavy fully reusable Mars-capable launch system in development."},
    {"id": "starlink_bus", "name": "Starlink v2 Bus", "category": "Communications", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 3, "electronics": 28, "aluminum": 5}, "production_time": 25,
     "special_flags": ["spacex", "usa", "space", "twenty_twenties", "mega_constellation"],
     "description": "Mass-produced broadband satellite. Defines LEO constellation warfare concerns."},
    {"id": "starship_mars_lander_fit", "name": "Starship Lunar/Mars Fit", "category": "LifeSupport", "tier": 9,
     "reliability_bonus": 8,
     "cost": {"steel": 50, "aluminum": 45, "electronics": 55, "chemicals": 25}, "production_time": 200,
     "special_flags": ["spacex", "usa", "nasa", "space", "twenty_thirties", "hls", "mars", "planned"],
     "description": "Starship HLS lunar lander and projected Mars surface missions. Artemis architecture."},

    # ═══════════════════════════════════════════════════════════════════════════
    # OTHER MAJOR PLAYERS · JAXA, ISRO, Blue Origin
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "h2a_launch_vehicle", "name": "H-IIA Launch Vehicle", "category": "Engine", "tier": 6,
     "reliability_bonus": 14, "fuel_efficiency": 6, "speed_bonus": 30,
     "cost": {"steel": 20, "aluminum": 16, "explosives": 35}, "production_time": 100,
     "special_flags": ["jaxa", "japan", "space", "two_thousands"],
     "description": "Japanese reliable launcher for science and reconnaissance satellites."},
    {"id": "hayabusa_probe_bus", "name": "Hayabusa Probe Bus", "category": "Sensors", "tier": 6,
     "reliability_bonus": 12,
     "cost": {"steel": 6, "electronics": 32, "aluminum": 10}, "production_time": 110,
     "special_flags": ["jaxa", "japan", "space", "two_thousands", "asteroid"],
     "description": "Asteroid sample return demonstrator. Ion propulsion and precision navigation."},
    {"id": "pslv_launcher", "name": "PSLV Launcher", "category": "Engine", "tier": 5,
     "reliability_bonus": 12, "fuel_efficiency": 8, "speed_bonus": 26,
     "cost": {"steel": 14, "aluminum": 10, "explosives": 22}, "production_time": 75,
     "special_flags": ["isro", "india", "space", "nineties", "small_sat"],
     "description": "Polar Satellite Launch Vehicle. Low-cost multi-satellite deployer."},
    {"id": "chandrayaan_lander", "name": "Chandrayaan Lander", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 8, "electronics": 28, "aluminum": 12}, "production_time": 100,
     "special_flags": ["isro", "india", "space", "twenty_twenties", "lunar"],
     "description": "Indian lunar south pole landing attempt. Growing indigenous deep-space capability."},
    {"id": "new_glenn_stage", "name": "New Glenn Stage", "category": "Cargo", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 35, "aluminum": 28, "electronics": 35}, "production_time": 130,
     "special_flags": ["blue_origin", "usa", "space", "twenty_twenties", "reusable"],
     "description": "Blue Origin heavy reusable launcher competing with Falcon 9 class."},
    {"id": "blue_moon_lander", "name": "Blue Moon Lander", "category": "LifeSupport", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 30, "aluminum": 28, "electronics": 40}, "production_time": 160,
     "special_flags": ["blue_origin", "usa", "nasa", "space", "twenty_twenties", "lunar", "planned"],
     "description": "Blue Origin lunar lander for Artemis cargo and crew variants."},

    # ═══════════════════════════════════════════════════════════════════════════
    # ISS / INTERNATIONAL · 1990s–2020s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "iss_zvezda_module", "name": "ISS Zvezda Module", "category": "Cargo", "tier": 6,
     "reliability_bonus": 14,
     "cost": {"steel": 42, "aluminum": 35, "electronics": 38}, "production_time": 155,
     "special_flags": ["russia", "nasa", "space", "nineties", "iss", "international"],
     "description": "Russian service module; ISS backbone for propulsion and living space."},
    {"id": "iss_destiny_lab", "name": "ISS Destiny Lab", "category": "Sensors", "tier": 6,
     "reliability_bonus": 14,
     "cost": {"steel": 38, "aluminum": 32, "electronics": 42}, "production_time": 150,
     "special_flags": ["usa", "nasa", "space", "nineties", "iss"],
     "description": "U.S. laboratory module for ISS science."},
    {"id": "jwst_telescope", "name": "James Webb Space Telescope", "category": "Sensors", "tier": 8,
     "reliability_bonus": 16,
     "cost": {"steel": 12, "electronics": 80, "optics": 60, "aluminum": 20}, "production_time": 280,
     "special_flags": ["nasa", "esa", "space", "twenty_twenties", "science", "lagrange"],
     "description": "Infrared space telescope at Sun-Earth L2. Successor to Hubble for deep universe."},
    {"id": "dream_chaser_spaceplane", "name": "Dream Chaser", "category": "Cargo", "tier": 6,
     "reliability_bonus": 12,
     "cost": {"steel": 25, "aluminum": 30, "electronics": 28}, "production_time": 120,
     "special_flags": ["usa", "space", "twenty_twenties", "cargo", "lifting_body"],
     "description": "Sierra Space lifting-body cargo vehicle for ISS resupply."},

    # ═══════════════════════════════════════════════════════════════════════════
    # PROTOTYPES & NEAR FUTURE · 2030s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "sls_block2_booster", "name": "SLS Block 2", "category": "Engine", "tier": 8,
     "reliability_bonus": 10, "fuel_efficiency": -8, "speed_bonus": 36,
     "cost": {"steel": 60, "aluminum": 35, "explosives": 90}, "production_time": 180,
     "special_flags": ["nasa", "usa", "space", "twenty_twenties", "artemis", "super_heavy"],
     "description": "Space Launch System for Artemis lunar missions. Shuttle-derived hardware."},
    {"id": "orion_spacecraft", "name": "Orion Spacecraft", "category": "LifeSupport", "tier": 7,
     "reliability_bonus": 14,
     "cost": {"steel": 18, "aluminum": 22, "electronics": 45}, "production_time": 140,
     "special_flags": ["nasa", "usa", "esa_joint", "space", "twenty_twenties", "crewed", "deep_space"],
     "description": "Orion crew capsule for Artemis beyond-LEO missions."},
    {"id": "gateway_lunar_station", "name": "Gateway Station Module", "category": "Cargo", "tier": 7,
     "reliability_bonus": 12,
     "cost": {"steel": 35, "aluminum": 30, "electronics": 50}, "production_time": 170,
     "special_flags": ["nasa", "esa", "space", "twenty_thirties", "lunar_orbit", "planned"],
     "description": "Artemis lunar orbit space station. International staging point for Moon landings."},
    {"id": "ariane6_launcher", "name": "Ariane 6", "category": "Engine", "tier": 7,
     "reliability_bonus": 12, "fuel_efficiency": 8, "speed_bonus": 32,
     "cost": {"steel": 28, "aluminum": 20, "explosives": 45}, "production_time": 110,
     "special_flags": ["esa", "space", "twenty_twenties", "ariane"],
     "description": "Next-generation European launcher replacing Ariane 5."},
    {"id": "new_glenn_2030_operational", "name": "New Glenn (Operational)", "category": "Cargo", "tier": 8,
     "reliability_bonus": 14,
     "cost": {"steel": 38, "aluminum": 32, "electronics": 40}, "production_time": 125,
     "special_flags": ["blue_origin", "usa", "space", "twenty_thirties"],
     "description": "Projected operational Blue Origin heavy lift with high flight rate."},
    {"id": "long_march9_superheavy", "name": "Long March 9", "category": "Cargo", "tier": 9,
     "reliability_bonus": 8,
     "cost": {"steel": 80, "aluminum": 55, "explosives": 120}, "production_time": 200,
     "special_flags": ["china", "space", "twenty_thirties", "super_heavy", "planned", "mars"],
     "description": "Chinese super-heavy launcher for lunar base and Mars aspirations."},
    {"id": "russian_oren_space_station", "name": "ROSS (Russian Orbital Station)", "category": "Cargo", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 45, "aluminum": 35, "electronics": 38}, "production_time": 160,
     "special_flags": ["russia", "space", "twenty_thirties", "space_station", "planned"],
     "description": "Planned Russian national station after ISS withdrawal."},
    {"id": "lunar_gateway_hab", "name": "Lunar Surface Hab (Proto)", "category": "LifeSupport", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 40, "aluminum": 35, "electronics": 45, "chemicals": 20}, "production_time": 180,
     "special_flags": ["nasa", "esa", "space", "twenty_thirties", "lunar", "planned"],
     "description": "Artemis base camp habitation module concept for sustained lunar presence."},
    {"id": "on_orbit_refueling_depot", "name": "On-Orbit Refueling Depot", "category": "Cargo", "tier": 8,
     "reliability_bonus": 12,
     "cost": {"steel": 25, "aluminum": 20, "electronics": 35, "chemicals": 30}, "production_time": 140,
     "special_flags": ["global", "space", "twenty_thirties", "planned", "infrastructure"],
     "description": "Propellant depot enabling deep-space missions and reusable tugs."},
    {"id": "space_tug_nuclear_thermal", "name": "Nuclear Thermal Space Tug", "category": "Engine", "tier": 9,
     "reliability_bonus": 6, "fuel_efficiency": 25, "speed_bonus": 42,
     "cost": {"steel": 30, "electronics": 50, "uranium": 40}, "production_time": 200,
     "special_flags": ["nasa", "space", "twenty_thirties", "planned", "nuclear"],
     "description": "DRACO-class nuclear propulsion for rapid cislunar transfer. 2030s technology goal."},
    {"id": "mega_constellation_asat", "name": "Co-Orbital ASAT Package", "category": "MainWeapon", "tier": 7,
     "soft_attack": 40, "hard_attack": 35, "piercing": 20, "air_attack": 30,
     "cost": {"steel": 8, "electronics": 40, "explosives": 12}, "production_time": 90,
     "special_flags": ["global", "space", "twenty_twenties", "asat", "dual_use"],
     "description": "Dual-use rendezvous satellites for inspection or kinetic anti-satellite roles."},
    {"id": "lasercom_interplanetary", "name": "Laser Optical Comms", "category": "Communications", "tier": 7,
     "reliability_bonus": 14,
     "cost": {"steel": 4, "electronics": 45, "optics": 25}, "production_time": 85,
     "special_flags": ["global", "space", "twenty_twenties", "deep_space"],
     "description": "Optical laser links for Mars and lunar missions. High bandwidth vs radio."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\nSpace modules: {created} created, {skipped} skipped, {total} total modules.")


if __name__ == "__main__":
    main()
