#!/usr/bin/env python3
"""1980s–1990s equipment modules: USA, USSR/Russia, China, France, UK, Germany, Israel."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 1980s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1_abrams_armor", "name": "M1 Abrams Armor Package", "category": "Armor", "tier": 6,
     "armor_bonus": 64, "top_armor_bonus": 48, "reliability_penalty": -6,
     "cost": {"steel": 48, "ceramics": 24, "titanium": 10, "kevlar": 8}, "production_time": 115,
     "special_flags": ["usa", "eighties", "composite", "m1_abrams"],
     "description": "Initial M1 Chobham-based armor. Decisive advantage vs T-72 during 1991 Gulf War."},
    {"id": "m1a1_ha_armor", "name": "M1A1 HA Depleted-Uranium Package", "category": "Armor", "tier": 7,
     "armor_bonus": 72, "top_armor_bonus": 55, "reliability_penalty": -8,
     "cost": {"steel": 50, "ceramics": 28, "uranium": 18, "titanium": 12}, "production_time": 130,
     "special_flags": ["usa", "eighties", "du_armor", "m1a1"],
     "description": "Heavy armor with DU mesh in turret and hull. Near-impenetrable to 125 mm APFSDS of the era."},
    {"id": "agt1500_turbine", "name": "AGT-1500 Gas Turbine", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": -4, "speed_bonus": 16,
     "cost": {"steel": 22, "aluminum": 28, "titanium": 14}, "production_time": 95,
     "special_flags": ["usa", "eighties", "gas_turbine", "m1_abrams"],
     "description": "M1 Abrams powerplant. Exceptional acceleration; high fuel consumption accepted for mobility."},
    {"id": "m829_apfsds", "name": "M829 APFSDS", "category": "Cargo", "tier": 6,
     "soft_attack": 8, "hard_attack": 24, "piercing": 38,
     "cost": {"uranium": 14, "tungsten": 6, "steel": 2}, "production_time": 45,
     "special_flags": ["usa", "ammunition", "apfsds", "eighties", "du_penetrator"],
     "description": "Depleted-uranium long-rod for M256. Standard U.S. tank kill round through late Cold War."},
    {"id": "m242_bushmaster", "name": "M242 Bushmaster 25 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 32, "hard_attack": 22, "piercing": 42, "air_attack": 18,
     "cost": {"steel": 10, "aluminum": 6, "electronics": 4}, "production_time": 48,
     "special_flags": ["usa", "eighties", "ifv", "m2_bradley"],
     "description": "M2 Bradley chain gun. Effective vs BMP and helicopters with API and HEI-T."},
    {"id": "m2_bradley_tow", "name": "M2 Bradley TOW-2", "category": "SecondaryWeapon", "tier": 5,
     "soft_attack": 38, "hard_attack": 65, "piercing": 135, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 20, "explosives": 14}, "production_time": 52,
     "special_flags": ["usa", "atgm", "eighties", "tow"],
     "description": "TOW-2 launcher on Bradley IFV. Defines U.S. combined-arms anti-armor doctrine."},
    {"id": "ah64_hellfire", "name": "AGM-114 Hellfire", "category": "MainWeapon", "tier": 6,
     "soft_attack": 42, "hard_attack": 68, "piercing": 140, "air_attack": 5,
     "cost": {"steel": 6, "electronics": 28, "explosives": 16}, "production_time": 65,
     "special_flags": ["usa", "atgm", "helicopter", "eighties", "laser_guided"],
     "description": "AH-64 Apache primary anti-tank weapon. Laser-guided; devastating in Gulf War."},
    {"id": "aim120_amraam", "name": "AIM-120 AMRAAM", "category": "MainWeapon", "tier": 6,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 82, "anti_air": 78,
     "cost": {"steel": 6, "electronics": 38, "explosives": 10}, "production_time": 75,
     "special_flags": ["usa", "air_to_air", "bvr", "eighties", "active_radar"],
     "description": "Fire-and-forget active-radar missile. F-15 and F-16 BVR dominance from late 1980s."},
    {"id": "aim54_phoenix", "name": "AIM-54 Phoenix", "category": "MainWeapon", "tier": 6,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 88, "anti_air": 85,
     "cost": {"steel": 10, "electronics": 42, "explosives": 14}, "production_time": 85,
     "special_flags": ["usa", "air_to_air", "eighties", "f14_tomcat"],
     "description": "F-14 long-range AAW missile. Engages bombers and cruise missiles at extreme range."},
    {"id": "f110_ge_engine", "name": "GE F110 Turbofan", "category": "Engine", "tier": 6,
     "reliability_bonus": 14, "fuel_efficiency": 10, "speed_bonus": 34,
     "cost": {"steel": 18, "aluminum": 32, "titanium": 12}, "production_time": 88,
     "special_flags": ["usa", "jet_powerplant", "eighties", "f16"],
     "description": "F-16C Block powerplant. High thrust-to-weight for energy fighting and strike missions."},
    {"id": "pratt_f100_f15", "name": "Pratt F100-PW-220", "category": "Engine", "tier": 6,
     "reliability_bonus": 12, "fuel_efficiency": 8, "speed_bonus": 35,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 14}, "production_time": 90,
     "special_flags": ["usa", "jet_powerplant", "eighties", "f15"],
     "description": "F-15 Eagle engine. Twin installation gives exceptional climb and sustained turn rate."},
    {"id": "mim104_patriot", "name": "MIM-104 Patriot", "category": "AntiAir", "tier": 7,
     "soft_attack": 14, "hard_attack": 12, "air_attack": 90, "anti_air": 92,
     "cost": {"steel": 28, "electronics": 55, "explosives": 20}, "production_time": 120,
     "special_flags": ["usa", "sam", "eighties", "tmd"],
     "description": "Theater air-defense system. Engages aircraft, ballistic missiles, and cruise missiles."},
    {"id": "aegis_spy1_radar", "name": "AN/SPY-1 Aegis", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 35, "electronics": 65, "aluminum": 12}, "production_time": 140,
     "special_flags": ["usa", "naval", "radar", "eighties", "aegis"],
     "description": "Phased-array naval radar on Ticonderoga and Arleigh Burke. Revolution in fleet air defense."},
    {"id": "tomahawk_cruise_missile", "name": "BGM-109 Tomahawk", "category": "MainWeapon", "tier": 6,
     "soft_attack": 55, "hard_attack": 60, "piercing": 45, "anti_ship": 75, "air_attack": 8,
     "cost": {"steel": 12, "electronics": 40, "explosives": 35}, "production_time": 95,
     "special_flags": ["usa", "cruise_missile", "eighties", "land_attack"],
     "description": "Subsonic cruise missile for land and naval strike. TLAM used extensively from 1991 onward."},
    {"id": "m270_mlrs", "name": "M270 MLRS", "category": "MainWeapon", "tier": 6,
     "soft_attack": 110, "hard_attack": 40, "piercing": 35, "air_attack": 6,
     "cost": {"steel": 30, "explosives": 45, "electronics": 12}, "production_time": 85,
     "special_flags": ["usa", "rocket_artillery", "eighties"],
     "description": "12-tube 227 mm rocket launcher. Area saturation and AT2 anti-tank mine delivery."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1a2_sep_armor", "name": "M1A2 SEP Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 78, "top_armor_bonus": 58, "reliability_penalty": -7,
     "cost": {"steel": 52, "ceramics": 32, "uranium": 22, "titanium": 14}, "production_time": 140,
     "special_flags": ["usa", "nineties", "m1a2", "system_enhancement"],
     "description": "System Enhancement Package with improved DU arrays and internal Kevlar spall liners."},
    {"id": "m829a1_apfsds", "name": "M829A1 APFSDS", "category": "Cargo", "tier": 7,
     "soft_attack": 10, "hard_attack": 28, "piercing": 45,
     "cost": {"uranium": 18, "tungsten": 8, "steel": 2}, "production_time": 50,
     "special_flags": ["usa", "ammunition", "apfsds", "nineties"],
     "description": "M829A1 'Silver Bullet' DU penetrator. Defeated Iraqi T-72 at extreme ranges in 1991."},
    {"id": "m256a1_120mm_gun", "name": "120 mm M256A1", "category": "MainWeapon", "tier": 7,
     "soft_attack": 72, "hard_attack": 70, "piercing": 168, "air_attack": 5,
     "cost": {"steel": 34, "chromium": 10, "tungsten": 8}, "production_time": 105,
     "special_flags": ["usa", "nineties", "smoothbore", "m1a2"],
     "description": "Improved M256 with better thermal sleeve and accuracy for M1A2 fleet."},
    {"id": "aim120c_amraam", "name": "AIM-120C AMRAAM", "category": "MainWeapon", "tier": 7,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 88, "anti_air": 85,
     "cost": {"steel": 6, "electronics": 42, "explosives": 10}, "production_time": 78,
     "special_flags": ["usa", "air_to_air", "nineties", "wvr_bvr"],
     "description": "Clipped-fin AMRAAM with improved ECCM. Standard U.S. air superiority missile of 1990s."},
    {"id": "aim9x_sidewinder", "name": "AIM-9X Sidewinder", "category": "MainWeapon", "tier": 7,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 75, "anti_air": 72,
     "cost": {"steel": 5, "electronics": 28, "explosives": 6}, "production_time": 62,
     "special_flags": ["usa", "air_to_air", "nineties", "hoobs"],
     "description": "High off-boresight IR missile with thrust vectoring. Dogfight dominance on F-15 and F/A-18."},
    {"id": "agm88_harm", "name": "AGM-88 HARM", "category": "MainWeapon", "tier": 6,
     "soft_attack": 40, "hard_attack": 35, "piercing": 20, "air_attack": 12,
     "cost": {"steel": 8, "electronics": 35, "explosives": 18}, "production_time": 72,
     "special_flags": ["usa", "anti_radiation", "nineties", "sead"],
     "description": "Anti-radiation missile for suppression of enemy air defenses. Essential in Kosovo and Iraq."},
    {"id": "javelin_atgm", "name": "FGM-148 Javelin", "category": "MainWeapon", "tier": 7,
     "soft_attack": 40, "hard_attack": 72, "piercing": 155, "air_attack": 4,
     "cost": {"steel": 8, "electronics": 38, "explosives": 16}, "production_time": 70,
     "special_flags": ["usa", "atgm", "nineties", "fire_and_forget"],
     "description": "Top-attack infrared guided ATGM. Man-portable; replaces Dragon in U.S. infantry."},
    {"id": "f119_f22_engine", "name": "Pratt F119", "category": "Engine", "tier": 7,
     "reliability_bonus": 16, "fuel_efficiency": 14, "speed_bonus": 38,
     "cost": {"steel": 20, "aluminum": 38, "titanium": 22}, "production_time": 120,
     "special_flags": ["usa", "jet_powerplant", "nineties", "supercruise", "f22_proto"],
     "description": "F-22 Raptor prototype engine. Thrust vectoring and supercruise capability."},
    {"id": "an_apg77_radar", "name": "AN/APG-77 AESA", "category": "Sensors", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 8, "electronics": 75, "rare_earths": 12}, "production_time": 130,
     "special_flags": ["usa", "radar", "nineties", "aesa", "stealth_fighter"],
     "description": "Active electronically scanned array for F-22. Low probability of intercept and high track count."},
    {"id": "thermal_imager_an_vsg3", "name": "AN/VSG-3 Thermal Imager", "category": "Sensors", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 5, "electronics": 38, "optics": 18, "rare_earths": 10}, "production_time": 70,
     "special_flags": ["usa", "thermal", "nineties", "tank_sight"],
     "description": "Second-generation FLIR for M1A2 commander and gunner. Standard U.S. tank night-fighting."},
    {"id": "gps_ins_navigation", "name": "GPS/INS Navigation Suite", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 3, "electronics": 35}, "production_time": 55,
     "special_flags": ["usa", "nineties", "precision_navigation"],
     "description": "Global Positioning System integration for armor and aircraft. Revolutionizes maneuver and fires."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SOVIET UNION / RUSSIA · 1980s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "gtd1000t_turbine", "name": "GTD-1000T Gas Turbine", "category": "Engine", "tier": 6,
     "reliability_bonus": 6, "fuel_efficiency": -6, "speed_bonus": 15,
     "cost": {"steel": 20, "aluminum": 24, "titanium": 10}, "production_time": 90,
     "special_flags": ["ussr", "eighties", "gas_turbine", "t80"],
     "description": "T-80 family gas turbine. High speed; fuel-hungry compared to T-72 diesel."},
    {"id": "t80_composite_armor", "name": "T-80 Composite Armor", "category": "Armor", "tier": 6,
     "armor_bonus": 58, "top_armor_bonus": 35, "reliability_penalty": -7,
     "cost": {"steel": 42, "ceramics": 14, "chromium": 6}, "production_time": 85,
     "special_flags": ["ussr", "eighties", "t80", "gas_turbine_tank"],
     "description": "T-80U armor with improved composite arrays. First Soviet MBT with gas turbine."},
    {"id": "t72b_kontakt5", "name": "Kontakt-5 ERA", "category": "Armor", "tier": 7,
     "armor_bonus": 32, "top_armor_bonus": 22, "reliability_penalty": -4,
     "cost": {"steel": 12, "explosives": 18, "electronics": 6}, "production_time": 58,
     "special_flags": ["ussr", "era", "eighties", "kontakt5", "anti_apfsds"],
     "description": "ERA effective against APFSDS, not only HEAT. Mounted on T-72B and T-80U."},
    {"id": "2a46m_125mm_gun", "name": "2A46M 125 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 72, "hard_attack": 70, "piercing": 158, "air_attack": 5,
     "cost": {"steel": 34, "chromium": 8, "tungsten": 6}, "production_time": 100,
     "special_flags": ["ussr", "eighties", "smoothbore", "t72b"],
     "description": "Improved 125 mm with better accuracy and autoloader compatibility for 3BM32 rounds."},
    {"id": "3bm32_apfsds", "name": "3BM32 APFSDS", "category": "Cargo", "tier": 6,
     "soft_attack": 8, "hard_attack": 22, "piercing": 36,
     "cost": {"tungsten": 14, "steel": 2}, "production_time": 42,
     "special_flags": ["ussr", "ammunition", "apfsds", "eighties"],
     "description": "Tungsten long-rod for Soviet 125 mm. Threat to early M1 until M829A1 fielded."},
    {"id": "9m119_refleks", "name": "9M119 Refleks (AT-11)", "category": "MainWeapon", "tier": 6,
     "soft_attack": 38, "hard_attack": 68, "piercing": 145, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 24, "explosives": 14}, "production_time": 62,
     "special_flags": ["ussr", "atgm", "eighties", "gun_launched"],
     "description": "Laser-guided gun-launched missile from T-72B and T-80. Extends effective range beyond gun."},
    {"id": "bmp2_30mm_autocannon", "name": "2A42 30 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 36, "hard_attack": 26, "piercing": 48, "air_attack": 22,
     "cost": {"steel": 10, "aluminum": 5}, "production_time": 50,
     "special_flags": ["ussr", "eighties", "bmp2", "ifv"],
     "description": "BMP-2 autocannon. High rate of fire vs infantry and light armor."},
    {"id": "konkursm_atgm", "name": "9M113M Konkurs-M", "category": "MainWeapon", "tier": 5,
     "soft_attack": 36, "hard_attack": 62, "piercing": 128, "air_attack": 4,
     "cost": {"steel": 5, "electronics": 18, "explosives": 12}, "production_time": 48,
     "special_flags": ["ussr", "atgm", "eighties"],
     "description": "Improved SACLOS wire-guided ATGM with tandem warhead."},
    {"id": "r73_archer_missile", "name": "R-73 Archer", "category": "MainWeapon", "tier": 6,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 78, "anti_air": 74,
     "cost": {"steel": 4, "electronics": 26, "explosives": 6}, "production_time": 58,
     "special_flags": ["ussr", "air_to_air", "eighties", "high_off_boresight"],
     "description": "MiG-29 thrust-vectoring dogfight missile. Shocked NATO with HOBS capability."},
    {"id": "r27_alamo_missile", "name": "R-27 Alamo", "category": "MainWeapon", "tier": 6,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 80, "anti_air": 76,
     "cost": {"steel": 6, "electronics": 32, "explosives": 10}, "production_time": 65,
     "special_flags": ["ussr", "air_to_air", "eighties", "bvr"],
     "description": "Su-27 and MiG-29 BVR missile family. Semi-active and active variants."},
    {"id": "al31f_engine", "name": "Saturn AL-31F", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": 8, "speed_bonus": 34,
     "cost": {"steel": 16, "aluminum": 30, "titanium": 12}, "production_time": 85,
     "special_flags": ["ussr", "jet_powerplant", "eighties", "su27"],
     "description": "Su-27 Flanker engine. High thrust and tolerance for extreme maneuver."},
    {"id": "rd33_mig29_engine", "name": "Klimov RD-33", "category": "Engine", "tier": 6,
     "reliability_bonus": 6, "fuel_efficiency": 6, "speed_bonus": 32,
     "cost": {"steel": 14, "aluminum": 26, "titanium": 10}, "production_time": 80,
     "special_flags": ["ussr", "jet_powerplant", "eighties", "mig29"],
     "description": "Twin-engine MiG-29 powerplant. Optimized for short-range air superiority."},
    {"id": "s300_pmu_sam", "name": "S-300 PMU", "category": "AntiAir", "tier": 7,
     "soft_attack": 16, "hard_attack": 14, "air_attack": 92, "anti_air": 94,
     "cost": {"steel": 30, "electronics": 60, "explosives": 22}, "production_time": 125,
     "special_flags": ["ussr", "sam", "eighties", "strategic"],
     "description": "Long-range SAM system. Export to China and Syria; cornerstone of Soviet air defense."},
    {"id": "tor_sam", "name": "9K330 Tor", "category": "AntiAir", "tier": 6,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 78, "anti_air": 80,
     "cost": {"steel": 18, "electronics": 35, "explosives": 12}, "production_time": 88,
     "special_flags": ["ussr", "sam", "eighties", "point_defense"],
     "description": "Tracked point-defense SAM for armored columns. Engages PGMs and helicopters."},
    {"id": "ssn19_shipwreck", "name": "P-700 Granit", "category": "MainWeapon", "tier": 7,
     "soft_attack": 50, "hard_attack": 65, "piercing": 50, "anti_ship": 105, "air_attack": 6,
     "cost": {"steel": 14, "electronics": 45, "explosives": 40}, "production_time": 110,
     "special_flags": ["ussr", "anti_ship", "eighties", "supersonic"],
     "description": "Supersonic anti-ship missile on Kirov and Oscar classes. Saturation threat to carrier groups."},

    # ═══════════════════════════════════════════════════════════════════════════
    # RUSSIA · 1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "t90_armor_package", "name": "T-90 Armor Package", "category": "Armor", "tier": 7,
     "armor_bonus": 62, "top_armor_bonus": 38, "reliability_penalty": -6,
     "cost": {"steel": 44, "ceramics": 18, "explosives": 14}, "production_time": 95,
     "special_flags": ["russia", "nineties", "t90", "kontakt5"],
     "description": "T-72B derivative with Kontakt-5 and Shtora soft-kill system. Export and Chechen combat."},
    {"id": "2a46m5_125mm_gun", "name": "2A46M-5 125 mm", "category": "MainWeapon", "tier": 7,
     "soft_attack": 74, "hard_attack": 72, "piercing": 165, "air_attack": 5,
     "cost": {"steel": 36, "chromium": 10, "tungsten": 8}, "production_time": 108,
     "special_flags": ["russia", "nineties", "smoothbore", "t90"],
     "description": "Latest Soviet/Russian 125 mm before 2A82. Fires 3BM42 Mango APFSDS."},
    {"id": "3bm42_mango_apfsds", "name": "3BM42 Mango", "category": "Cargo", "tier": 7,
     "soft_attack": 10, "hard_attack": 26, "piercing": 42,
     "cost": {"tungsten": 16, "uranium": 4, "steel": 2}, "production_time": 48,
     "special_flags": ["russia", "ammunition", "apfsds", "nineties"],
     "description": "Tungsten-composite penetrator with uranium tip. Peak Soviet 125 mm performance."},
    {"id": "shtora_soft_kill", "name": "Shtora-1", "category": "Sensors", "tier": 6,
     "reliability_bonus": 4,
     "cost": {"steel": 6, "electronics": 28, "optics": 12}, "production_time": 65,
     "special_flags": ["russia", "nineties", "soft_kill", "t90"],
     "description": "IR dazzler and aerosol countermeasures against laser-guided weapons."},
    {"id": "bmp3_100mm_gun", "name": "2A70 100 mm + 30 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 55, "hard_attack": 42, "piercing": 85, "air_attack": 15,
     "cost": {"steel": 18, "explosives": 10, "electronics": 8}, "production_time": 72,
     "special_flags": ["russia", "nineties", "bmp3", "ifv"],
     "description": "BMP-3 low-pressure 100 mm with 30 mm coaxial. Fires AT-10 Arkan missiles."},
    {"id": "r77_adder_missile", "name": "R-77 Adder", "category": "MainWeapon", "tier": 7,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 85, "anti_air": 82,
     "cost": {"steel": 6, "electronics": 38, "explosives": 10}, "production_time": 72,
     "special_flags": ["russia", "air_to_air", "nineties", "active_radar"],
     "description": "Active-radar AAM for MiG-29 and Su-27 upgrades. Russian AMRAAM equivalent."},
    {"id": "kh31_asm", "name": "Kh-31 Anti-Radiation", "category": "MainWeapon", "tier": 6,
     "soft_attack": 45, "hard_attack": 50, "piercing": 35, "air_attack": 10,
     "cost": {"steel": 8, "electronics": 32, "explosives": 22}, "production_time": 75,
     "special_flags": ["russia", "anti_radiation", "nineties", "sead"],
     "description": "Supersonic anti-radiation missile. SEAD weapon for Su-24 and export Flankers."},
    {"id": "s400_triumf_proto", "name": "S-300PMU-2 / S-400 Proto", "category": "AntiAir", "tier": 7,
     "soft_attack": 18, "hard_attack": 16, "air_attack": 95, "anti_air": 96,
     "cost": {"steel": 35, "electronics": 70, "explosives": 24}, "production_time": 135,
     "special_flags": ["russia", "sam", "nineties", "strategic"],
     "description": "Evolved long-range SAM with improved engagement of stealth and ballistic targets."},

    # ═══════════════════════════════════════════════════════════════════════════
    # CHINA · 1980s–1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "type80_105mm_gun", "name": "Type 80 105 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 58, "hard_attack": 54, "piercing": 115, "air_attack": 5,
     "cost": {"steel": 22, "explosives": 3}, "production_time": 75,
     "special_flags": ["china", "eighties", "type80"],
     "description": "Chinese L7 derivative on Type 80/88 MBT. First domestic second-generation tank gun."},
    {"id": "type85_iim_armor", "name": "Type 85-IIM Armor", "category": "Armor", "tier": 6,
     "armor_bonus": 50, "top_armor_bonus": 28, "reliability_penalty": -5,
     "cost": {"steel": 38, "ceramics": 10, "chromium": 4}, "production_time": 78,
     "special_flags": ["china", "eighties", "composite"],
     "description": "Improved composite protection on Type 85 family. Export success in Pakistan."},
    {"id": "type96_125mm_gun", "name": "Type 96 125 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 70, "hard_attack": 68, "piercing": 155, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 6, "tungsten": 5}, "production_time": 95,
     "special_flags": ["china", "nineties", "smoothbore", "type96"],
     "description": "Licensed 2A46 lineage on Type 96 MBT. PLA armored modernization centerpiece."},
    {"id": "type99_armor_proto", "name": "Type 99 Armor (Proto)", "category": "Armor", "tier": 7,
     "armor_bonus": 60, "top_armor_bonus": 36, "reliability_penalty": -6,
     "cost": {"steel": 42, "ceramics": 16, "explosives": 10}, "production_time": 92,
     "special_flags": ["china", "nineties", "era", "type99_proto"],
     "description": "Late-1990s Type 99 prototype with ERA and improved composite. Limited production."},
    {"id": "pl8_air_missile", "name": "PL-8", "category": "MainWeapon", "tier": 5,
     "soft_attack": 7, "hard_attack": 5, "air_attack": 65, "anti_air": 60,
     "cost": {"steel": 4, "electronics": 20, "explosives": 6}, "production_time": 52,
     "special_flags": ["china", "air_to_air", "eighties", "python_copy"],
     "description": "Israeli Python 3 technology transfer for J-7 and J-8II. Improved PLAAF dogfight capability."},
    {"id": "pl11_air_missile", "name": "PL-11", "category": "MainWeapon", "tier": 6,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 75, "anti_air": 70,
     "cost": {"steel": 5, "electronics": 28, "explosives": 8}, "production_time": 60,
     "special_flags": ["china", "air_to_air", "nineties", "semi_active"],
     "description": "Semi-active radar homing AAM for J-8II. Indigenous BVR development step."},
    {"id": "hq9_sam_proto", "name": "HQ-9 (Prototype)", "category": "AntiAir", "tier": 7,
     "soft_attack": 16, "hard_attack": 14, "air_attack": 88, "anti_air": 90,
     "cost": {"steel": 28, "electronics": 55, "explosives": 18}, "production_time": 115,
     "special_flags": ["china", "sam", "nineties", "strategic"],
     "description": "Long-range SAM combining S-300 and Patriot influences. Trials late 1990s."},
    {"id": "wp13f_j8_engine", "name": "WP-13F Turbojet", "category": "Engine", "tier": 5,
     "reliability_bonus": 6, "fuel_efficiency": 4, "speed_bonus": 30,
     "cost": {"steel": 14, "aluminum": 22}, "production_time": 72,
     "special_flags": ["china", "jet_powerplant", "eighties", "j8"],
     "description": "J-8II Finback engine. Twin layout for high-altitude interception."},
    {"id": "ws10_proto_turbofan", "name": "WS-10 (Prototype)", "category": "Engine", "tier": 6,
     "reliability_bonus": 4, "fuel_efficiency": 8, "speed_bonus": 32,
     "cost": {"steel": 16, "aluminum": 28, "titanium": 8}, "production_time": 95,
     "special_flags": ["china", "jet_powerplant", "nineties", "indigenous"],
     "description": "Indigenous turbofan development for J-10 and J-11 programs. Testing through late 1990s."},
    {"id": "red_arrow8_atgm", "name": "HJ-8 Red Arrow", "category": "MainWeapon", "tier": 5,
     "soft_attack": 34, "hard_attack": 58, "piercing": 120, "air_attack": 4,
     "cost": {"steel": 5, "electronics": 16, "explosives": 10}, "production_time": 45,
     "special_flags": ["china", "atgm", "eighties", "tow_copy"],
     "description": "Wire-guided ATGM analogous to TOW. Used in 1991 Gulf War by Iraqi forces (export)." },

    # ═══════════════════════════════════════════════════════════════════════════
    # FRANCE · 1980s–1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "cn120_26_leclerc_gun", "name": "CN120-26/52", "category": "MainWeapon", "tier": 7,
     "soft_attack": 74, "hard_attack": 72, "piercing": 162, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 8, "tungsten": 6}, "production_time": 102,
     "special_flags": ["france", "nineties", "smoothbore", "leclerc"],
     "description": "Leclerc autoloaded 120 mm. High-pressure smoothbore with excellent accuracy."},
    {"id": "leclerc_armor", "name": "Leclerc Modular Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 65, "top_armor_bonus": 40, "reliability_penalty": -5,
     "cost": {"steel": 44, "ceramics": 22, "titanium": 10, "kevlar": 8}, "production_time": 105,
     "special_flags": ["france", "nineties", "composite", "modular"],
     "description": "French modular composite with removable ERA blocks. Optimized for Middle East export."},
    {"id": "leclerc_hispano_engine", "name": "SEMT V8X Hyperbar", "category": "Engine", "tier": 7,
     "reliability_bonus": 14, "fuel_efficiency": 10, "speed_bonus": 18,
     "cost": {"steel": 20, "aluminum": 8}, "production_time": 88,
     "special_flags": ["france", "nineties", "diesel", "leclerc"],
     "description": "1500 hp diesel for Leclerc. Exceptional power-to-weight for European MBT."},
    {"id": "mirage2000_package", "name": "Mirage 2000 Package", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": 8, "speed_bonus": 32,
     "cost": {"steel": 16, "aluminum": 28, "titanium": 8}, "production_time": 82,
     "special_flags": ["france", "jet_powerplant", "eighties", "mirage2000"],
     "description": "M53-P2 turbofan for Mirage 2000. French air superiority and strike platform of 1980s."},
    {"id": "super530d_missile", "name": "Super 530D", "category": "MainWeapon", "tier": 6,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 78, "anti_air": 74,
     "cost": {"steel": 5, "electronics": 30, "explosives": 8}, "production_time": 62,
     "special_flags": ["france", "air_to_air", "eighties", "bvr"],
     "description": "Mirage 2000 BVR missile. Pulse-Doppler guidance vs low-altitude targets."},
    {"id": "magic2_missile", "name": "Magic II", "category": "MainWeapon", "tier": 6,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 72, "anti_air": 68,
     "cost": {"steel": 4, "electronics": 22, "explosives": 6}, "production_time": 55,
     "special_flags": ["france", "air_to_air", "eighties", "all_aspect"],
     "description": "Improved all-aspect IR missile for Mirage 2000 and export clients."},
    {"id": "mica_air_missile", "name": "MICA", "category": "MainWeapon", "tier": 7,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 85, "anti_air": 82,
     "cost": {"steel": 6, "electronics": 38, "explosives": 10}, "production_time": 72,
     "special_flags": ["france", "air_to_air", "nineties", "dual_seeker"],
     "description": "IR and radar dual-mode missile for Rafale and Mirage 2000-5. Fire-and-forget BVR."},
    {"id": "exocet_block2", "name": "Exocet Block 2", "category": "MainWeapon", "tier": 6,
     "soft_attack": 42, "hard_attack": 55, "piercing": 40, "anti_ship": 98, "air_attack": 5,
     "cost": {"steel": 8, "electronics": 35, "explosives": 20}, "production_time": 80,
     "special_flags": ["france", "anti_ship", "nineties"],
     "description": "Improved sea-skimming anti-ship missile with datalink retargeting."},
    {"id": "hot3_atgm", "name": "HOT-3", "category": "MainWeapon", "tier": 6,
     "soft_attack": 36, "hard_attack": 65, "piercing": 135, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 22, "explosives": 14}, "production_time": 55,
     "special_flags": ["france", "atgm", "nineties", "tandem_warhead"],
     "description": "Tandem-warhead SACLOS ATGM for Tiger and VAB. Defeats ERA of the 1990s."},
    {"id": "amx10rc_105mm", "name": "105 mm F2 (AMX-10RC)", "category": "MainWeapon", "tier": 5,
     "soft_attack": 56, "hard_attack": 52, "piercing": 110, "air_attack": 5,
     "cost": {"steel": 18, "aluminum": 6}, "production_time": 68,
     "special_flags": ["france", "eighties", "wheeled", "recon"],
     "description": "Wheeled tank destroyer gun. Rapid deployment for French rapid-action forces."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED KINGDOM · 1980s–1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "l30_120mm_rifled", "name": "120 mm L30A1", "category": "MainWeapon", "tier": 7,
     "soft_attack": 76, "hard_attack": 72, "piercing": 170, "air_attack": 5,
     "cost": {"steel": 30, "explosives": 6, "tungsten": 8}, "production_time": 105,
     "special_flags": ["uk", "nineties", "rifled", "challenger"],
     "description": "Challenger 1 and 2 rifled gun. CHARM APFSDS; highest-pressure rifled tank gun fielded."},
    {"id": "challenger1_chobham", "name": "Challenger 1 Chobham", "category": "Armor", "tier": 6,
     "armor_bonus": 66, "top_armor_bonus": 48, "reliability_penalty": -6,
     "cost": {"steel": 48, "ceramics": 26, "titanium": 10}, "production_time": 110,
     "special_flags": ["uk", "eighties", "challenger", "chobham"],
     "description": "Chobham Mk 2 on Challenger 1. Proven in Gulf War against T-55 and T-62."},
    {"id": "challenger2_armor", "name": "Challenger 2 Dorchester", "category": "Armor", "tier": 7,
     "armor_bonus": 74, "top_armor_bonus": 52, "reliability_penalty": -7,
     "cost": {"steel": 50, "ceramics": 30, "titanium": 12, "kevlar": 10}, "production_time": 125,
     "special_flags": ["uk", "nineties", "challenger2"],
     "description": "Second-generation Chobham on Challenger 2. Exceptional crew survivability record."},
    {"id": "perkins_cv12_engine", "name": "Perkins CV12", "category": "Engine", "tier": 6,
     "reliability_bonus": 12, "fuel_efficiency": 8, "speed_bonus": 12,
     "cost": {"steel": 20, "aluminum": 6}, "production_time": 75,
     "special_flags": ["uk", "eighties", "challenger", "diesel"],
     "description": "Challenger 1 diesel powerpack. Reliable 1200 hp engine derived from Chieftain lineage."},
    {"id": "warrior_ifv_30mm", "name": "RARDEN 30 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 34, "hard_attack": 24, "piercing": 45, "air_attack": 16,
     "cost": {"steel": 10, "aluminum": 5}, "production_time": 48,
     "special_flags": ["uk", "eighties", "warrior", "ifv"],
     "description": "Warrior IFV autocannon. Accurate but slow rate of fire vs Soviet BMP-2."},
    {"id": "asraam_missile", "name": "ASRAAM", "category": "MainWeapon", "tier": 7,
     "soft_attack": 9, "hard_attack": 7, "air_attack": 80, "anti_air": 76,
     "cost": {"steel": 5, "electronics": 32, "explosives": 6}, "production_time": 65,
     "special_flags": ["uk", "air_to_air", "nineties", "ir_imaging"],
     "description": "Imaging-infrared within-visual-range missile. Joint UK/Germany/Canada program."},
    {"id": "tornado_gr4_package", "name": "RB199 Turbofan", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": 9, "speed_bonus": 28,
     "cost": {"steel": 16, "aluminum": 26, "titanium": 8}, "production_time": 85,
     "special_flags": ["uk", "germany_joint", "eighties", "tornado"],
     "description": "Panavia Tornado twin-engine turbofan. Low-level strike and maritime attack."},
    {"id": "brimstone_proto", "name": "Brimstone (Prototype)", "category": "MainWeapon", "tier": 7,
     "soft_attack": 45, "hard_attack": 62, "piercing": 95, "air_attack": 6,
     "cost": {"steel": 8, "electronics": 35, "explosives": 16}, "production_time": 78,
     "special_flags": ["uk", "nineties", "fire_and_forget", "anti_armor"],
     "description": "Millimeter-wave guided anti-armor missile derived from AGM-114. Late-1990s development."},
    {"id": "rapier_fsc_sam", "name": "Rapier FSC", "category": "AntiAir", "tier": 6,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 76, "anti_air": 78,
     "cost": {"steel": 14, "electronics": 30, "explosives": 10}, "production_time": 75,
     "special_flags": ["uk", "sam", "nineties"],
     "description": "Improved Rapier with FLIR and improved guidance. Falklands lessons incorporated."},
    {"id": "eurofighter_ef2000_engine", "name": "EJ200 Turbofan", "category": "Engine", "tier": 7,
     "reliability_bonus": 14, "fuel_efficiency": 12, "speed_bonus": 36,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 14}, "production_time": 105,
     "special_flags": ["uk", "germany_joint", "nineties", "eurofighter"],
     "description": "Eurofighter Typhoon engine. First flight 1994; supercruise capability."},

    # ═══════════════════════════════════════════════════════════════════════════
    # GERMANY · 1980s–1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "leopard2a4_armor", "name": "Leopard 2A4 Armor", "category": "Armor", "tier": 6,
     "armor_bonus": 60, "top_armor_bonus": 38, "reliability_penalty": -5,
     "cost": {"steel": 44, "ceramics": 18, "chromium": 6}, "production_time": 95,
     "special_flags": ["germany", "eighties", "leopard2"],
     "description": "Standard Leopard 2 armor before 2A5 wedge upgrade. NATO benchmark MBT of 1980s."},
    {"id": "leopard2a5_wedge_armor", "name": "Leopard 2A5 Wedge Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 70, "top_armor_bonus": 48, "reliability_penalty": -6,
     "cost": {"steel": 48, "ceramics": 24, "titanium": 10}, "production_time": 110,
     "special_flags": ["germany", "nineties", "leopard2a5", "spaced_armor"],
     "description": "Arrow-head spaced armor on turret front. Response to 125 mm APFSDS threat."},
    {"id": "rh120_l44_gun", "name": "Rh-120 L/44", "category": "MainWeapon", "tier": 6,
     "soft_attack": 72, "hard_attack": 70, "piercing": 165, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 8, "tungsten": 6}, "production_time": 100,
     "special_flags": ["germany", "eighties", "smoothbore", "leopard2"],
     "description": "Leopard 2 standard 120 mm. NATO reference smoothbore; licensed to U.S. M256."},
    {"id": "dm33_apfsds", "name": "DM33 APFSDS", "category": "Cargo", "tier": 6,
     "soft_attack": 9, "hard_attack": 24, "piercing": 40,
     "cost": {"tungsten": 14, "steel": 2}, "production_time": 45,
     "special_flags": ["germany", "ammunition", "apfsds", "eighties"],
     "description": "Tungsten penetrator for Rh-120. Standard Bundeswehr anti-armor round."},
    {"id": "dm43_apfsds", "name": "DM43 APFSDS", "category": "Cargo", "tier": 7,
     "soft_attack": 10, "hard_attack": 28, "piercing": 44,
     "cost": {"tungsten": 16, "uranium": 6, "steel": 2}, "production_time": 50,
     "special_flags": ["germany", "ammunition", "apfsds", "nineties"],
     "description": "Improved 120 mm round with better performance vs Kontakt-5 protected targets."},
    {"id": "mtu_mb873_engine", "name": "MTU MB 873 Ka-501", "category": "Engine", "tier": 6,
     "reliability_bonus": 16, "fuel_efficiency": 10, "speed_bonus": 14,
     "cost": {"steel": 22, "aluminum": 8}, "production_time": 82,
     "special_flags": ["germany", "eighties", "leopard2", "diesel"],
     "description": "1500 hp diesel for Leopard 2. Renowned reliability and NATO interoperability."},
    {"id": "marder2_ifv_package", "name": "Marder 2 Package", "category": "Armor", "tier": 5,
     "armor_bonus": 32, "top_armor_bonus": 18, "reliability_penalty": -3,
     "cost": {"steel": 28, "aluminum": 8, "ceramics": 4}, "production_time": 70,
     "special_flags": ["germany", "nineties", "ifv"],
     "description": "Up-armored Marder 1A3 IFV. Carries MILAN and 20 mm Rh-202."},
    {"id": "pah1_cobra_atgm", "name": "PAH-1 HOT", "category": "MainWeapon", "tier": 5,
     "soft_attack": 36, "hard_attack": 62, "piercing": 130, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 20, "explosives": 12}, "production_time": 52,
     "special_flags": ["germany", "helicopter", "atgm", "eighties"],
     "description": "Bo-105 PAH-1 anti-tank helicopter with HOT missiles. Cold War Fulda Gap scenario."},
    {"id": "iris_t_sam_proto", "name": "IRIS-T (Development)", "category": "MainWeapon", "tier": 7,
     "soft_attack": 9, "hard_attack": 7, "air_attack": 78, "anti_air": 74,
     "cost": {"steel": 5, "electronics": 32, "explosives": 6}, "production_time": 68,
     "special_flags": ["germany", "air_to_air", "nineties", "wvr"],
     "description": "German-led IR imaging missile program beginning late 1990s. Replaces Sidewinder in Europe."},

    # ═══════════════════════════════════════════════════════════════════════════
    # ISRAEL · 1980s–1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "merkava_mk3_armor", "name": "Merkava Mk III Armor", "category": "Armor", "tier": 6,
     "armor_bonus": 62, "top_armor_bonus": 38, "reliability_penalty": -4,
     "cost": {"steel": 42, "ceramics": 16, "kevlar": 8}, "production_time": 90,
     "special_flags": ["israel", "eighties", "merkava", "front_engine"],
     "description": "Improved Merkava with modular armor and better belly protection vs mines."},
    {"id": "merkava_mk4_armor_proto", "name": "Merkava Mk IV (Proto)", "category": "Armor", "tier": 7,
     "armor_bonus": 68, "top_armor_bonus": 42, "reliability_penalty": -5,
     "cost": {"steel": 45, "ceramics": 20, "kevlar": 10, "electronics": 8}, "production_time": 100,
     "special_flags": ["israel", "nineties", "merkava", "aps_proto"],
     "description": "Late-1990s Merkava IV development with Trophy APS trials planned."},
    {"id": "imi_120mm_gun", "name": "IMI 120 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 72, "hard_attack": 70, "piercing": 160, "air_attack": 5,
     "cost": {"steel": 30, "chromium": 6, "tungsten": 5}, "production_time": 98,
     "special_flags": ["israel", "nineties", "smoothbore", "merkava3"],
     "description": "Indigenous 120 mm for Merkava Mk III. Compatible with NATO ammunition standards."},
    {"id": "magach7_era", "name": "Magach 7 ERA", "category": "Armor", "tier": 6,
     "armor_bonus": 48, "top_armor_bonus": 30, "reliability_penalty": -4,
     "cost": {"steel": 35, "explosives": 14, "electronics": 6}, "production_time": 75,
     "special_flags": ["israel", "eighties", "m60_derivative", "era"],
     "description": "M60-based Magach with Blazer/ERA and improved FCS. Lebanon and intifada service."},
    {"id": "python4_missile", "name": "Python 4", "category": "MainWeapon", "tier": 6,
     "soft_attack": 9, "hard_attack": 7, "air_attack": 76, "anti_air": 72,
     "cost": {"steel": 5, "electronics": 28, "explosives": 6}, "production_time": 58,
     "special_flags": ["israel", "air_to_air", "eighties", "all_aspect"],
     "description": "F-15 and F-16 IR missile. High off-boresight; export to multiple air forces."},
    {"id": "derby_bvr_missile", "name": "Derby", "category": "MainWeapon", "tier": 7,
     "soft_attack": 11, "hard_attack": 9, "air_attack": 82, "anti_air": 78,
     "cost": {"steel": 6, "electronics": 35, "explosives": 8}, "production_time": 68,
     "special_flags": ["israel", "air_to_air", "nineties", "active_radar"],
     "description": "Israeli active-radar BVR missile. Equips F-15I and export fighters."},
    {"id": "spike_atgm", "name": "Spike (Gill/MR)", "category": "MainWeapon", "tier": 7,
     "soft_attack": 38, "hard_attack": 70, "piercing": 145, "air_attack": 4,
     "cost": {"steel": 8, "electronics": 38, "explosives": 14}, "production_time": 72,
     "special_flags": ["israel", "atgm", "nineties", "fire_and_forget"],
     "description": "Fourth-generation EO-guided ATGM. Man-portable and vehicle mounts."},
    {"id": "gabriel3_anti_ship", "name": "Gabriel III", "category": "MainWeapon", "tier": 6,
     "soft_attack": 40, "hard_attack": 52, "piercing": 38, "anti_ship": 95, "air_attack": 5,
     "cost": {"steel": 8, "electronics": 30, "explosives": 18}, "production_time": 72,
     "special_flags": ["israel", "anti_ship", "eighties"],
     "description": "Sa'ar 4.5 missile boat weapon. Proven in Middle East naval engagements."},
    {"id": "lahat_gun_launched", "name": "LAHAT", "category": "MainWeapon", "tier": 6,
     "soft_attack": 36, "hard_attack": 65, "piercing": 138, "air_attack": 4,
     "cost": {"steel": 5, "electronics": 26, "explosives": 12}, "production_time": 60,
     "special_flags": ["israel", "atgm", "nineties", "gun_launched"],
     "description": "Laser homing anti-tank missile fired from 105 mm and 120 mm guns."},
    {"id": "kfir2000_package", "name": "Kfir 2000 Avionics", "category": "Sensors", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 6, "electronics": 35, "optics": 14}, "production_time": 75,
     "special_flags": ["israel", "eighties", "fighter_upgrade"],
     "description": "Multi-mode radar and avionics upgrade for Kfir and export fighters."},
    {"id": "nimrod_anti_tank_helo", "name": "Nimrod ATGM", "category": "MainWeapon", "tier": 5,
     "soft_attack": 34, "hard_attack": 58, "piercing": 115, "air_attack": 4,
     "cost": {"steel": 5, "electronics": 18, "explosives": 10}, "production_time": 48,
     "special_flags": ["israel", "helicopter", "atgm", "eighties"],
     "description": "Early Israeli helicopter-launched ATGM development before Spike-ER."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SHARED · 1980s–1990s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "du_apfsds_gen3", "name": "DU APFSDS (Gen 3)", "category": "Cargo", "tier": 7,
     "soft_attack": 12, "hard_attack": 30, "piercing": 48,
     "cost": {"uranium": 20, "tungsten": 4, "steel": 2}, "production_time": 55,
     "special_flags": ["nato", "ammunition", "nineties", "du_penetrator"],
     "description": "Third-generation depleted-uranium long-rods. Standard for Gulf War and Balkans."},
    {"id": "reactive_armor_era5", "name": "Third-Gen ERA Package", "category": "Armor", "tier": 6,
     "armor_bonus": 28, "top_armor_bonus": 18, "reliability_penalty": -3,
     "cost": {"steel": 10, "explosives": 16, "electronics": 4}, "production_time": 50,
     "special_flags": ["nato", "warsaw_pact", "eighties", "era"],
     "description": "Widespread ERA kits on T-72, M60, and export tanks. Defines late Cold War protection."},
    {"id": "hunter_killer_fcs", "name": "Hunter-Killer FCS", "category": "Sensors", "tier": 6,
     "reliability_bonus": 7,
     "cost": {"steel": 5, "electronics": 40, "optics": 16}, "production_time": 72,
     "special_flags": ["nato", "fcs", "nineties"],
     "description": "Independent commander thermal sight with digital fire control. Engage two targets rapidly."},
    {"id": "stealth_coating_proto", "name": "RAM Coating (Prototype)", "category": "Armor", "tier": 6,
     "armor_bonus": 5, "top_armor_bonus": 3, "reliability_penalty": -2,
     "cost": {"chemicals": 18, "electronics": 12, "rubber": 6}, "production_time": 60,
     "special_flags": ["usa", "nineties", "stealth", "aircraft"],
     "description": "Radar-absorbent material trials on F-117 and B-2. Reduces detection range."},
    {"id": "gps_guided_artillery", "name": "M982 Excalibur (Proto)", "category": "MainWeapon", "tier": 7,
     "soft_attack": 85, "hard_attack": 50, "piercing": 60, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 42, "explosives": 25}, "production_time": 85,
     "special_flags": ["usa", "nineties", "precision_guided", "artillery"],
     "description": "GPS-guided 155 mm projectile development. CEP under 10 m in late-1990s trials."},
    {"id": "rpg7v_upgrade", "name": "RPG-7V (Tandem)", "category": "SecondaryWeapon", "tier": 4,
     "soft_attack": 32, "hard_attack": 48, "piercing": 85, "air_attack": 2,
     "cost": {"steel": 3, "explosives": 8}, "production_time": 20,
     "special_flags": ["infantry", "eighties", "global"],
     "description": "Improved RPG warheads vs ERA. Ubiquitous threat to IFVs in asymmetric conflicts."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\n1980s–1990s: {created} created, {skipped} skipped, {total} total modules.")


if __name__ == "__main__":
    main()
