#!/usr/bin/env python3
"""Generate late-WWII and 1945–1955 unit templates including Axis paper designs."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    # ─── GERMANY · PROTOTYPES / PAPER (defeated Axis) ─────────────────────────
    {
        "id": "maus_superheavy",
        "name": "Panzer VIII Maus (Prototype)",
        "design_family": "german_paper_ww2",
        "base_type": "Armored",
        "size_category": "SuperHeavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 6,
        "base_training_level": 35,
        "max_experience_level": 100,
        "base_production_days": 180,
        "base_stats": {"speed": 14, "reliability": 40, "fuel_consumption": 22, "supply_need": 35,
                      "armor": 70, "top_armor": 40, "hardness": 98},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_44_128mm_gun", "Engine": "maybach_hl234_engine",
                         "Armor": "maus_superheavy_armor", "Sensors": "fg1250_infrared_scope"},
        "unlock_tech": ["german_paper_tanks", "superheavy_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "e50_medium_prototype",
        "name": "E-50 Standardpanzer (Paper)",
        "design_family": "german_paper_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 38, "reliability": 60, "fuel_consumption": 11, "supply_need": 15,
                      "armor": 54, "top_armor": 28, "hardness": 87},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_43_l71_88_extended", "Engine": "maybach_hl234_engine",
                         "Armor": "e50_standard_armor"},
        "unlock_tech": ["german_paper_tanks", "e_program"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "jagdtiger_heavy_td",
        "name": "Jagdtiger",
        "design_family": "german_armored_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 6,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 110,
        "base_stats": {"speed": 22, "reliability": 52, "fuel_consumption": 15, "supply_need": 22,
                      "armor": 60, "top_armor": 32, "hardness": 93},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "kwk_44_128mm_gun", "Engine": "maybach_hl230_engine",
                         "Armor": "krupp_tiger_armor"},
        "unlock_tech": ["german_heavy_tanks", "tank_destroyers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "sturmtiger_assault",
        "name": "Sturmtiger",
        "design_family": "german_armored_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 5,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 20, "reliability": 48, "fuel_consumption": 14, "supply_need": 20,
                      "armor": 52, "top_armor": 28, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "sturmtiger_380mm_mortar", "Engine": "maybach_hl230_engine"},
        "unlock_tech": ["german_assault_guns"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "me262a_fighter",
        "name": "Me 262A Schwalbe",
        "design_family": "german_jet_ww2",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 65,
        "base_stats": {"speed": 115, "reliability": 58, "fuel_consumption": 16, "supply_need": 12,
                      "armor": 14, "hardness": 20},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 2}, "Communications": {"max": 1}},
        "module_loadout": {"MainWeapon": "mk108_30mm_revolver", "Engine": "jumo_004_jet_engine",
                         "Communications": "fug_16_zyf_radio"},
        "unlock_tech": ["german_jet_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "he162_salamander",
        "name": "He 162 Volksjäger",
        "design_family": "german_jet_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 42,
        "base_stats": {"speed": 108, "reliability": 55, "fuel_consumption": 12, "supply_need": 8,
                      "armor": 10, "hardness": 18},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "mk108_30mm_revolver", "Engine": "bmw_003_jet_engine"},
        "unlock_tech": ["german_jet_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "ho229_prototype",
        "name": "Ho 229 (Prototype)",
        "design_family": "german_paper_ww2",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "stealth_bomber",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 112, "reliability": 50, "fuel_consumption": 14, "supply_need": 10,
                      "armor": 12, "hardness": 18},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 2}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "mk108_30mm_revolver", "Engine": "jumo_004_jet_engine",
                         "Armor": "ho229_flying_wing_airframe"},
        "unlock_tech": ["german_paper_planes", "german_jet_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "ta183_prototype",
        "name": "Ta 183 Huckebein (Paper)",
        "design_family": "german_paper_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 75,
        "base_stats": {"speed": 118, "reliability": 48, "fuel_consumption": 13, "supply_need": 9,
                      "armor": 12, "hardness": 19},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "mk214_50mm_cannon", "Engine": "hes_011_jet_prototype"},
        "unlock_tech": ["german_paper_planes"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── JAPAN · LATE / PROTOTYPE ──────────────────────────────────────────────
    {
        "id": "type4_chi_to_medium",
        "name": "Type 4 Chi-To",
        "design_family": "japanese_armored_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 72,
        "base_stats": {"speed": 32, "reliability": 64, "fuel_consumption": 10, "supply_need": 13,
                      "armor": 40, "top_armor": 20, "hardness": 76},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "type4_75mm_gun", "Engine": "mitsubishi_al_engine",
                         "Armor": "japanese_riveted_armor"},
        "unlock_tech": ["japanese_medium_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "type5_chi_ri_prototype",
        "name": "Type 5 Chi-Ri (Prototype)",
        "design_family": "japanese_paper_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 5,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 85,
        "base_stats": {"speed": 30, "reliability": 60, "fuel_consumption": 11, "supply_need": 14,
                      "armor": 44, "top_armor": 22, "hardness": 78},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "type5_75mm_l70_gun", "Engine": "mitsubishi_al_engine",
                         "Armor": "type5_chi_ri_armor"},
        "unlock_tech": ["japanese_paper_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "kikka_jet_prototype",
        "name": "Kikka (Prototype)",
        "design_family": "japanese_paper_ww2",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 100, "reliability": 52, "fuel_consumption": 12, "supply_need": 9,
                      "armor": 10, "hardness": 17},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "type99_mk2_cannon", "Engine": "ne20_jet_engine"},
        "unlock_tech": ["japanese_paper_planes"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ITALY · PAPER ─────────────────────────────────────────────────────────
    {
        "id": "p43_heavy_prototype",
        "name": "P43 (Paper)",
        "design_family": "italian_paper_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 26,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 26, "reliability": 54, "fuel_consumption": 11, "supply_need": 15,
                      "armor": 46, "top_armor": 22, "hardness": 80},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "p43_90mm_prototype", "Engine": "spa_diesel_v8_engine",
                         "Armor": "italian_riveted_armor"},
        "unlock_tech": ["italian_paper_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ALLIED LATE WW2 → 1950s ───────────────────────────────────────────────
    {
        "id": "is3_heavy",
        "name": "IS-3",
        "design_family": "soviet_armored_late_ww2",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 30, "reliability": 66, "fuel_consumption": 12, "supply_need": 18,
                      "armor": 56, "top_armor": 30, "hardness": 91},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "d10t_100mm_gun", "Engine": "v2_diesel_engine",
                         "Armor": "is2_heavy_armor"},
        "unlock_tech": ["soviet_heavy_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "su100_td",
        "name": "SU-100",
        "design_family": "soviet_armored_late_ww2",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 68,
        "base_stats": {"speed": 32, "reliability": 70, "fuel_consumption": 9, "supply_need": 12,
                      "armor": 42, "top_armor": 20, "hardness": 82},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "d10t_100mm_gun", "Engine": "v2_diesel_engine"},
        "unlock_tech": ["soviet_tank_destroyers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t54_medium",
        "name": "T-54",
        "design_family": "soviet_armored_cold_war",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 78,
        "base_stats": {"speed": 38, "reliability": 76, "fuel_consumption": 9, "supply_need": 13,
                      "armor": 48, "top_armor": 26, "hardness": 88},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "t54_100mm_d10t2s", "Engine": "v54_diesel_engine",
                         "Armor": "t54_cast_armor", "Sensors": "gun_stabilizer_m3"},
        "unlock_tech": ["soviet_medium_tanks", "cold_war_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m103_heavy",
        "name": "M103 Heavy Tank",
        "design_family": "us_armored_cold_war",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 5,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 28, "reliability": 68, "fuel_consumption": 14, "supply_need": 20,
                      "armor": 58, "top_armor": 30, "hardness": 90},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "m58_120mm_gun", "Engine": "av1790_engine",
                         "Armor": "m48_patton_armor"},
        "unlock_tech": ["us_heavy_tanks", "cold_war_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m48_patton_medium",
        "name": "M48 Patton",
        "design_family": "us_armored_cold_war",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 30,
        "max_experience_level": 100,
        "base_production_days": 82,
        "base_stats": {"speed": 36, "reliability": 74, "fuel_consumption": 11, "supply_need": 14,
                      "armor": 50, "top_armor": 26, "hardness": 84},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "m68_105mm_gun", "Engine": "av1790_engine",
                         "Armor": "m48_patton_armor", "Sensors": "gun_stabilizer_m3"},
        "unlock_tech": ["us_medium_tanks", "cold_war_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "centurion_mk3_medium",
        "name": "Centurion Mk 3",
        "design_family": "uk_armored_cold_war",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 85,
        "base_stats": {"speed": 35, "reliability": 78, "fuel_consumption": 10, "supply_need": 14,
                      "armor": 52, "top_armor": 26, "hardness": 86},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "l7_105mm_rifled", "Engine": "meteor_mk4_engine",
                         "Armor": "centurion_glacis_armor"},
        "unlock_tech": ["uk_medium_tanks", "cold_war_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "amx13_light",
        "name": "AMX-13",
        "design_family": "french_armored_cold_war",
        "base_type": "Armored",
        "size_category": "Light",
        "visual_archetype": "light_tank",
        "crew_required": 3,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 44, "reliability": 72, "fuel_consumption": 8, "supply_need": 10,
                      "armor": 32, "top_armor": 16, "hardness": 72},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "amx13_75mm_fl10", "Engine": "renault_v6_engine"},
        "unlock_tech": ["french_light_tanks", "cold_war_tanks"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mig15_fighter",
        "name": "MiG-15bis",
        "design_family": "soviet_air_cold_war",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 55,
        "base_stats": {"speed": 118, "reliability": 72, "fuel_consumption": 11, "supply_need": 9,
                      "armor": 14, "hardness": 22},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "nr23_cannon", "Engine": "vk1_jet_engine"},
        "unlock_tech": ["soviet_jet_fighters", "korean_war"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f86_sabre",
        "name": "F-86F Sabre",
        "design_family": "us_air_cold_war",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 52,
        "base_stats": {"speed": 115, "reliability": 78, "fuel_consumption": 12, "supply_need": 9,
                      "armor": 16, "hardness": 24},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "m2_browning_gun_pod", "Engine": "rolls_royce_nene"},
        "unlock_tech": ["us_jet_fighters", "korean_war"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f100_super_sabre",
        "name": "F-100D Super Sabre",
        "design_family": "us_air_cold_war",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 58,
        "base_stats": {"speed": 125, "reliability": 74, "fuel_consumption": 15, "supply_need": 11,
                      "armor": 18, "hardness": 26},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "m61_vulcan_pod", "Engine": "pratt_whitney_j57"},
        "unlock_tech": ["us_jet_fighters", "cold_war_air"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "hawker_hunter_fighter",
        "name": "Hawker Hunter F.6",
        "design_family": "uk_air_cold_war",
        "base_type": "Air",
        "size_category": "Light",
        "visual_archetype": "jet_fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 54,
        "base_stats": {"speed": 120, "reliability": 76, "fuel_consumption": 12, "supply_need": 9,
                      "armor": 16, "hardness": 24},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "aden_30mm_revolver", "Engine": "rolls_royce_nene"},
        "unlock_tech": ["uk_jet_fighters"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "forrest_sherman_destroyer",
        "name": "Forrest Sherman-class DD",
        "design_family": "us_naval_cold_war",
        "base_type": "Naval",
        "size_category": "Light",
        "visual_archetype": "destroyer",
        "crew_required": 320,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 130,
        "base_stats": {"speed": 36, "reliability": 80, "fuel_consumption": 42, "supply_need": 52,
                      "armor": 24, "deck_armor": 14, "hardness": 58},
        "slots": {"NavalGun": {"max": 2}, "SecondaryWeapon": {"max": 2}, "Engine": {"max": 1},
                  "AntiAir": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"NavalGun": "us_5inch_54_mk42", "SecondaryWeapon": "mk35_torpedo",
                         "AntiAir": "us_3inch_70_mk26", "Engine": "us_parsons_turbine",
                         "Sensors": "an_tps1_radar"},
        "unlock_tech": ["us_destroyers", "cold_war_naval"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\nLate templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
