#!/usr/bin/env python3
"""Carrier aircraft modules: naval fighters, strike, AEW, ASW — WWII through 2030s."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ─── Common naval aviation ─────────────────────────────────────────────────
    {"id": "carrier_operations_kit", "name": "Carrier Operations Kit", "category": "Sensors", "tier": 2,
     "reliability_bonus": 6,
     "cost": {"steel": 6, "aluminum": 8, "electronics": 4}, "production_time": 30,
     "special_flags": ["carrier_capable", "arrestor_hook", "folding_wings", "catapult"],
     "description": "Arrestor hook, folding wings, and catapult bridle fittings. Required for carrier deck operations."},
    {"id": "mk13_aerial_torpedo", "name": "Mk 13 Aerial Torpedo", "category": "MainWeapon", "tier": 3,
     "soft_attack": 35, "hard_attack": 48, "piercing": 25, "anti_ship": 85, "air_attack": 4,
     "cost": {"steel": 10, "explosives": 22, "electronics": 6}, "production_time": 55,
     "special_flags": ["usa", "naval_aviation", "torpedo", "ww2"],
     "description": "Standard U.S. carrier torpedo for TBD, TBF, and early Avenger strikes."},
    {"id": "type91_aerial_torpedo", "name": "Type 91 Aerial Torpedo", "category": "MainWeapon", "tier": 3,
     "soft_attack": 32, "hard_attack": 45, "piercing": 22, "anti_ship": 82, "air_attack": 4,
     "cost": {"steel": 9, "explosives": 20, "electronics": 4}, "production_time": 52,
     "special_flags": ["japan", "naval_aviation", "torpedo", "ww2"],
     "description": "Japanese carrier torpedo for Kate and Jill. Modified for shallow harbor drops."},
    {"id": "mk12_aerial_torpedo_uk", "name": "Mk XII Aerial Torpedo", "category": "MainWeapon", "tier": 3,
     "soft_attack": 30, "hard_attack": 42, "piercing": 20, "anti_ship": 78, "air_attack": 3,
     "cost": {"steel": 9, "explosives": 18, "electronics": 5}, "production_time": 50,
     "special_flags": ["uk", "naval_aviation", "torpedo", "ww2"],
     "description": "British aerial torpedo for Swordfish, Albacore, and Barracuda."},

    # ─── USA · WWII ────────────────────────────────────────────────────────────
    {"id": "f6f_gun_battery", "name": "F6F Gun Battery (6× .50)", "category": "MainWeapon", "tier": 3,
     "soft_attack": 42, "hard_attack": 14, "piercing": 28, "air_attack": 52,
     "cost": {"steel": 8, "aluminum": 4}, "production_time": 32,
     "special_flags": ["usa", "naval_aviation", "ww2", "f6f_hellcat"],
     "description": "Six Browning M2 machine guns on F6F Hellcat. Standard late-war carrier fighter armament."},
    {"id": "f4u_gun_battery", "name": "F4U Gun Battery (6× .50)", "category": "MainWeapon", "tier": 3,
     "soft_attack": 40, "hard_attack": 14, "piercing": 28, "air_attack": 50,
     "cost": {"steel": 8, "aluminum": 5}, "production_time": 34,
     "special_flags": ["usa", "naval_aviation", "ww2", "f4u_corsair"],
     "description": "Six .50 cal guns on F4U Corsair. Also used in ground-attack and interdiction roles."},
    {"id": "sbd_dive_bomb_package", "name": "SBD Dive Bomb Package", "category": "MainWeapon", "tier": 3,
     "soft_attack": 68, "hard_attack": 38, "piercing": 35, "anti_ship": 72, "air_attack": 8,
     "cost": {"steel": 5, "explosives": 24, "optics": 6}, "production_time": 45,
     "special_flags": ["usa", "naval_aviation", "ww2", "dive_bomber", "sbd_dauntless"],
     "description": "1,000 lb bomb and dive brakes for SBD Dauntless. Decisive at Coral Sea and Midway."},
    {"id": "sb2c_bomb_torpedo_load", "name": "SB2C Strike Load", "category": "MainWeapon", "tier": 4,
     "soft_attack": 75, "hard_attack": 42, "piercing": 38, "anti_ship": 70, "air_attack": 10,
     "cost": {"steel": 6, "explosives": 30, "electronics": 4}, "production_time": 50,
     "special_flags": ["usa", "naval_aviation", "ww2", "sb2c_helldiver"],
     "description": "Heavy bomb or torpedo load for SB2C Helldiver. Replaced SBD on Essex-class carriers."},
    {"id": "tbf_strike_torpedo_load", "name": "TBF Strike Torpedo Load", "category": "MainWeapon", "tier": 3,
     "soft_attack": 38, "hard_attack": 50, "piercing": 28, "anti_ship": 88, "air_attack": 6,
     "cost": {"steel": 8, "explosives": 26, "electronics": 5}, "production_time": 48,
     "special_flags": ["usa", "naval_aviation", "ww2", "tbf_avenger"],
     "description": "Torpedo and bomb bay load for TBF/TBM Avenger strike missions."},
    {"id": "wright_r2600_dauntless", "name": "Wright R-2600 (Dauntless)", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": 2, "speed_bonus": 10,
     "cost": {"steel": 11, "aluminum": 10}, "production_time": 48,
     "special_flags": ["usa", "carrier_capable", "ww2", "sbd_dauntless"],
     "description": "Twin Cyclone powering SBD Dauntless and some B-25 variants."},
    {"id": "pratt_r2800_hellcat", "name": "Pratt R-2800 (Hellcat)", "category": "Engine", "tier": 4,
     "reliability_bonus": 14, "fuel_efficiency": 4, "speed_bonus": 16,
     "cost": {"steel": 12, "aluminum": 14, "rubber": 2}, "production_time": 55,
     "special_flags": ["usa", "carrier_capable", "ww2", "f6f_hellcat"],
     "description": "2,000 hp Double Wasp on F6F Hellcat. Dominant U.S. carrier fighter of 1944–45."},
    {"id": "wright_r3350_helldiver", "name": "Wright R-3350 (Helldiver)", "category": "Engine", "tier": 4,
     "reliability_bonus": 4, "fuel_efficiency": -2, "speed_bonus": 14,
     "cost": {"steel": 14, "aluminum": 16}, "production_time": 58,
     "special_flags": ["usa", "carrier_capable", "ww2", "sb2c"],
     "description": "Duplex Cyclone on SB2C Helldiver. Powerful but suffered early reliability issues."},
    {"id": "f8f_bearcat_engine", "name": "Pratt R-2800 (Bearcat)", "category": "Engine", "tier": 4,
     "reliability_bonus": 12, "fuel_efficiency": 3, "speed_bonus": 20,
     "cost": {"steel": 12, "aluminum": 14}, "production_time": 52,
     "special_flags": ["usa", "carrier_capable", "ww2", "f8f_bearcat", "late_war"],
     "description": "Lightweight high-power R-2800 installation on F8F Bearcat. Fastest U.S. piston carrier fighter."},

    # ─── UK · WWII ─────────────────────────────────────────────────────────────
    {"id": "bristol_pegasus_swordfish", "name": "Bristol Pegasus (Swordfish)", "category": "Engine", "tier": 2,
     "reliability_bonus": 10, "fuel_efficiency": 0, "speed_bonus": 4,
     "cost": {"steel": 9, "aluminum": 6}, "production_time": 40,
     "special_flags": ["uk", "carrier_capable", "ww2", "biplane", "swordfish"],
     "description": "Reliable radial on Fairey Swordfish. 'Stringbag' torpedo bomber; Bismarck and Taranto fame."},
    {"id": "bristol_hercules_barracuda", "name": "Bristol Hercules (Barracuda)", "category": "Engine", "tier": 3,
     "reliability_bonus": 8, "fuel_efficiency": 1, "speed_bonus": 8,
     "cost": {"steel": 11, "aluminum": 10}, "production_time": 46,
     "special_flags": ["uk", "carrier_capable", "ww2", "barracuda"],
     "description": "Powerplant for Fairey Barracuda dive/torpedo bomber on British fleet carriers."},
    {"id": "fulmar_gun_battery", "name": "Fulmar Gun Battery", "category": "MainWeapon", "tier": 2,
     "soft_attack": 28, "hard_attack": 10, "piercing": 22, "air_attack": 38,
     "cost": {"steel": 6, "aluminum": 3}, "production_time": 28,
     "special_flags": ["uk", "naval_aviation", "ww2", "fulmar"],
     "description": "Eight .303 in and later 20 mm armament on Fairey Fulmar fleet fighter."},
    {"id": "firefly_strike_load", "name": "Firefly Strike Load", "category": "MainWeapon", "tier": 4,
     "soft_attack": 62, "hard_attack": 35, "piercing": 40, "anti_ship": 65, "air_attack": 12,
     "cost": {"steel": 6, "explosives": 22, "electronics": 4}, "production_time": 44,
     "special_flags": ["uk", "naval_aviation", "ww2", "firefly"],
     "description": "Rocket and bomb load for Fairey Firefly strike-fighter on British carriers."},

    # ─── Japan · WWII ──────────────────────────────────────────────────────────
    {"id": "d3a_val_dive_bomb", "name": "Val Dive Bomb Load", "category": "MainWeapon", "tier": 3,
     "soft_attack": 65, "hard_attack": 36, "piercing": 32, "anti_ship": 68, "air_attack": 8,
     "cost": {"steel": 4, "explosives": 22}, "production_time": 42,
     "special_flags": ["japan", "naval_aviation", "ww2", "d3a_val"],
     "description": "Fixed-undercarriage dive bomber load for Aichi D3A Val."},
    {"id": "b5n_kate_torpedo_load", "name": "Kate Torpedo Load", "category": "MainWeapon", "tier": 3,
     "soft_attack": 34, "hard_attack": 46, "piercing": 24, "anti_ship": 86, "air_attack": 5,
     "cost": {"steel": 5, "explosives": 20}, "production_time": 40,
     "special_flags": ["japan", "naval_aviation", "ww2", "b5n_kate"],
     "description": "Type 91 torpedo configuration for B5N Kate. Pearl Harbor and Coral Sea weapon."},
    {"id": "d4y_judy_strike_load", "name": "Judy Strike Load", "category": "MainWeapon", "tier": 4,
     "soft_attack": 70, "hard_attack": 40, "piercing": 36, "anti_ship": 62, "air_attack": 14,
     "cost": {"steel": 5, "explosives": 26, "electronics": 3}, "production_time": 46,
     "special_flags": ["japan", "naval_aviation", "ww2", "d4y_judy"],
     "description": "Fast Judy dive bomber / recon load for late-war Japanese carriers."},
    {"id": "a7m_reppu_proto_engine", "name": "Mitsubishi MK9 (Reppū Proto)", "category": "Engine", "tier": 4,
     "reliability_bonus": 2, "fuel_efficiency": 2, "speed_bonus": 18,
     "cost": {"steel": 12, "aluminum": 14, "electronics": 6}, "production_time": 65,
     "special_flags": ["japan", "carrier_capable", "ww2", "prototype", "a7m_reppu"],
     "description": "Planned A7M Reppū carrier fighter engine. Never reached operational squadrons."},

    # ─── Germany · WWII (designed / prototyped) ──────────────────────────────────
    {"id": "bf109t_carrier_package", "name": "Bf 109T Carrier Package", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 8, "aluminum": 10, "electronics": 4}, "production_time": 38,
     "special_flags": ["germany", "carrier_capable", "ww2", "bf109t", "graf_zeppelin"],
     "description": "Extended wings, arrestor hook, and catapult fittings for Graf Zeppelin air group."},
    {"id": "fi167_carrier_scout", "name": "Fi 167 Carrier Scout", "category": "Engine", "tier": 2,
     "reliability_bonus": 6, "fuel_efficiency": 2, "speed_bonus": 6,
     "cost": {"steel": 8, "aluminum": 6}, "production_time": 42,
     "special_flags": ["germany", "carrier_capable", "ww2", "prototype", "fi167"],
     "description": "Fieseler Fi 167 torpedo/scout biplane for Graf Zeppelin. Few built; program cancelled."},
    {"id": "me155_carrier_proto", "name": "Me 155B Carrier Proto", "category": "Engine", "tier": 4,
     "reliability_bonus": -2, "fuel_efficiency": 0, "speed_bonus": 22,
     "cost": {"steel": 10, "aluminum": 16, "electronics": 8}, "production_time": 70,
     "special_flags": ["germany", "carrier_capable", "ww2", "prototype", "me155"],
     "description": "Navalized Bf 109 development for Graf Zeppelin. Incomplete when carrier was abandoned."},

    # ─── USA · Cold War / modern carrier aviation ───────────────────────────────
    {"id": "j48_turbojet_f9f", "name": "J48 Turbojet (F9F)", "category": "Engine", "tier": 4,
     "reliability_bonus": 8, "fuel_efficiency": 0, "speed_bonus": 24,
     "cost": {"steel": 12, "aluminum": 20, "titanium": 2}, "production_time": 65,
     "special_flags": ["usa", "carrier_capable", "fifties", "f9f_panther"],
     "description": "F9F Panther carrier fighter jet. First U.S. Navy jet to score air-to-air kills in Korea."},
    {"id": "j52_skyhawk_engine", "name": "J52 Turbojet (A-4)", "category": "Engine", "tier": 5,
     "reliability_bonus": 12, "fuel_efficiency": 6, "speed_bonus": 26,
     "cost": {"steel": 14, "aluminum": 22}, "production_time": 72,
     "special_flags": ["usa", "carrier_capable", "sixties", "a4_skyhawk"],
     "description": "Lightweight turbojet on A-4 Skyhawk. 'Scooter' served on U.S. carriers for decades."},
    {"id": "j57_f8_crusader", "name": "J57 Afterburner (F-8)", "category": "Engine", "tier": 5,
     "reliability_bonus": 10, "fuel_efficiency": 2, "speed_bonus": 32,
     "cost": {"steel": 15, "aluminum": 26, "titanium": 4}, "production_time": 78,
     "special_flags": ["usa", "carrier_capable", "sixties", "f8_crusader"],
     "description": "Afterburning J57 on F-8 Crusader. Last U.S. gunfighter; Mach 1.7 capable."},
    {"id": "tf30_f14_engine", "name": "TF30 Turbofan (F-14)", "category": "Engine", "tier": 6,
     "reliability_bonus": 4, "fuel_efficiency": 8, "speed_bonus": 34,
     "cost": {"steel": 18, "aluminum": 32, "titanium": 10}, "production_time": 95,
     "special_flags": ["usa", "carrier_capable", "seventies", "f14_tomcat"],
     "description": "Twin TF30 on F-14 Tomcat. Powerful but maintenance-intensive early Tomcat operations."},
    {"id": "ge_f404_hornet", "name": "GE F404 (F/A-18)", "category": "Engine", "tier": 6,
     "reliability_bonus": 14, "fuel_efficiency": 10, "speed_bonus": 32,
     "cost": {"steel": 16, "aluminum": 30, "titanium": 8}, "production_time": 88,
     "special_flags": ["usa", "carrier_capable", "eighties", "fa18_hornet"],
     "description": "F/A-18 Hornet powerplant. Twin-engine reliability for carrier strike fighter."},
    {"id": "ge_f414_super_hornet", "name": "GE F414 (Super Hornet)", "category": "Engine", "tier": 7,
     "reliability_bonus": 16, "fuel_efficiency": 12, "speed_bonus": 34,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 12}, "production_time": 98,
     "special_flags": ["usa", "carrier_capable", "two_thousands", "fa18ef"],
     "description": "Upgraded Super Hornet engine. Higher thrust and improved durability."},
    {"id": "tf34_intruder_engine", "name": "TF34 (A-6 Intruder)", "category": "Engine", "tier": 5,
     "reliability_bonus": 12, "fuel_efficiency": 10, "speed_bonus": 22,
     "cost": {"steel": 16, "aluminum": 24}, "production_time": 80,
     "special_flags": ["usa", "carrier_capable", "sixties", "a6_intruder"],
     "description": "Non-afterburning turbofan on A-6 Intruder all-weather strike aircraft."},
    {"id": "a1_skyraider_loadout", "name": "A-1 Skyraider Strike Load", "category": "MainWeapon", "tier": 4,
     "soft_attack": 78, "hard_attack": 45, "piercing": 40, "anti_ship": 55, "air_attack": 12,
     "cost": {"steel": 6, "explosives": 32, "electronics": 4}, "production_time": 48,
     "special_flags": ["usa", "naval_aviation", "fifties", "a1_skyraider"],
     "description": "Heavy bomb and rocket load for A-1 Skyraider. Korea and Vietnam workhorse."},
    {"id": "e2c_hawkeye_radar", "name": "AN/APS-145 (E-2C)", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 12, "electronics": 55, "aluminum": 18}, "production_time": 100,
     "special_flags": ["usa", "carrier_capable", "aew", "eighties", "e2_hawkeye"],
     "description": "Carrier AEW rotodome radar. Fleet air defense coordination and over-the-horizon targeting."},
    {"id": "s3b_viking_asw_suite", "name": "S-3B ASW Suite", "category": "Sensors", "tier": 5,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 42, "aluminum": 12}, "production_time": 85,
     "special_flags": ["usa", "carrier_capable", "asw", "eighties", "s3_viking"],
     "description": "Sonobuoys, MAD, and surface-search radar for S-3 Viking carrier ASW."},
    {"id": "ea6b_ecm_suite", "name": "EA-6B ICAP III ECM", "category": "Sensors", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 8, "electronics": 48, "aluminum": 10}, "production_time": 90,
     "special_flags": ["usa", "carrier_capable", "ew", "nineties", "ea6_prowler"],
     "description": "Electronic warfare suite on EA-6B Prowler. Suppresses enemy SAM and radar networks."},
    {"id": "av8b_harrier_ii_engine", "name": "Pegasus F402 (AV-8B)", "category": "Engine", "tier": 6,
     "reliability_bonus": 12, "fuel_efficiency": 8, "speed_bonus": 28,
     "cost": {"steel": 16, "aluminum": 28, "titanium": 8}, "production_time": 92,
     "special_flags": ["usa", "uk", "carrier_capable", "vstol", "av8b"],
     "description": "Upgraded Pegasus on AV-8B Harrier II. STOVL ops from amphibious ships and light carriers."},

    # ─── UK · Cold War ─────────────────────────────────────────────────────────
    {"id": "rolls_royce_spey_phantom", "name": "Spey Mk 202 (Phantom FG.1)", "category": "Engine", "tier": 5,
     "reliability_bonus": 10, "fuel_efficiency": 6, "speed_bonus": 30,
     "cost": {"steel": 16, "aluminum": 28}, "production_time": 82,
     "special_flags": ["uk", "carrier_capable", "seventies", "phantom_naval"],
     "description": "British Spey on Phantom FG.1 for HMS Ark Royal. Higher thrust at sea level than J79."},
    {"id": "rolls_royce_mk104_buccaneer", "name": "Spey Mk 104 (Buccaneer)", "category": "Engine", "tier": 5,
     "reliability_bonus": 11, "fuel_efficiency": 5, "speed_bonus": 28,
     "cost": {"steel": 18, "aluminum": 26}, "production_time": 85,
     "special_flags": ["uk", "carrier_capable", "sixties", "buccaneer"],
     "description": "Twin Spey on Buccaneer S.2. Low-level maritime strike bomber for RN carriers."},
    {"id": "rolls_royce_avon_scimitar", "name": "Avon Mk 202 (Scimitar)", "category": "Engine", "tier": 4,
     "reliability_bonus": 6, "fuel_efficiency": 2, "speed_bonus": 26,
     "cost": {"steel": 14, "aluminum": 22}, "production_time": 75,
     "special_flags": ["uk", "carrier_capable", "fifties", "scimitar"],
     "description": "Twin Avon on Supermarine Scimitar. First RN swept-wing carrier jet fighter."},
    {"id": "sea_harrier_frs_package", "name": "Sea Harrier FRS Package", "category": "Sensors", "tier": 5,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 32, "aluminum": 14}, "production_time": 70,
     "special_flags": ["uk", "carrier_capable", "vstol", "falklands", "sea_harrier"],
     "description": "Blue Fox radar and AIM-9L integration on Sea Harrier FRS.1. Falklands War fleet defender."},
    {"id": "buccaneer_maritime_strike", "name": "Buccaneer Maritime Strike", "category": "MainWeapon", "tier": 5,
     "soft_attack": 72, "hard_attack": 55, "piercing": 48, "anti_ship": 80, "air_attack": 10,
     "cost": {"steel": 8, "explosives": 35, "electronics": 12}, "production_time": 65,
     "special_flags": ["uk", "naval_aviation", "sixties", "buccaneer"],
     "description": "Martel and conventional bomb load for Buccaneer anti-ship strike."},

    # ─── France ────────────────────────────────────────────────────────────────
    {"id": "snecma_atar_etendard", "name": "SNECMA Atar (Étendard)", "category": "Engine", "tier": 4,
     "reliability_bonus": 8, "fuel_efficiency": 4, "speed_bonus": 26,
     "cost": {"steel": 12, "aluminum": 20}, "production_time": 68,
     "special_flags": ["france", "carrier_capable", "sixties", "super_etendard"],
     "description": "Atar turbojet on Étendard IVM and Super Étendard. French carrier strike lineage."},
    {"id": "super_etendard_strike", "name": "Super Étendard Strike", "category": "MainWeapon", "tier": 5,
     "soft_attack": 55, "hard_attack": 58, "piercing": 42, "anti_ship": 95, "air_attack": 8,
     "cost": {"steel": 8, "electronics": 28, "explosives": 22}, "production_time": 72,
     "special_flags": ["france", "naval_aviation", "exocet", "eighties"],
     "description": "Exocet and laser-guided bomb fit on Super Étendard. Falklands and Gulf strikes."},
    {"id": "rafale_m_carrier_package", "name": "Rafale M Carrier Package", "category": "Sensors", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 14, "electronics": 45, "aluminum": 22, "titanium": 8}, "production_time": 110,
     "special_flags": ["france", "carrier_capable", "twenty_tens", "rafale_m"],
     "description": "Strengthened airframe, arrestor hook, and RBE2 AESA for Charles de Gaulle operations."},

    # ─── USSR / Russia ─────────────────────────────────────────────────────────
    {"id": "tumansky_r27_yak38", "name": "R-27 (Yak-38)", "category": "Engine", "tier": 4,
     "reliability_bonus": 2, "fuel_efficiency": -4, "speed_bonus": 22,
     "cost": {"steel": 14, "aluminum": 22}, "production_time": 70,
     "special_flags": ["ussr", "carrier_capable", "vstol", "yak38"],
     "description": "Lift/cruise engine package on Yak-38 Forger. Operated from Kiev-class carriers."},
    {"id": "al31fp_su33", "name": "AL-31FP (Su-33)", "category": "Engine", "tier": 6,
     "reliability_bonus": 12, "fuel_efficiency": 8, "speed_bonus": 34,
     "cost": {"steel": 18, "aluminum": 32, "titanium": 10}, "production_time": 95,
     "special_flags": ["russia", "carrier_capable", "su33", "kuznetsov"],
     "description": "Thrust-vectoring AL-31 on Su-33 Flanker-D. Admiral Kuznetsov air superiority fighter."},
    {"id": "rd33mk_mig29k", "name": "RD-33MK (MiG-29K)", "category": "Engine", "tier": 6,
     "reliability_bonus": 11, "fuel_efficiency": 8, "speed_bonus": 32,
     "cost": {"steel": 16, "aluminum": 30, "titanium": 8}, "production_time": 90,
     "special_flags": ["russia", "india", "carrier_capable", "mig29k"],
     "description": "Navalized Fulcrum engine for MiG-29K on Vikramaditya and planned Russian carriers."},
    {"id": "yak141_freestyle_proto", "name": "Yak-141 (Freestyle Proto)", "category": "Engine", "tier": 6,
     "reliability_bonus": 0, "fuel_efficiency": 2, "speed_bonus": 30,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 14, "electronics": 20}, "production_time": 105,
     "special_flags": ["russia", "carrier_capable", "vstol", "prototype", "yak141"],
     "description": "Supersonic STOVL prototype. Influenced F-35B lift-fan development; never operational."},

    # ─── China ─────────────────────────────────────────────────────────────────
    {"id": "ws10j_j15_engine", "name": "WS-10J (J-15)", "category": "Engine", "tier": 7,
     "reliability_bonus": 8, "fuel_efficiency": 10, "speed_bonus": 32,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 12, "electronics": 15}, "production_time": 100,
     "special_flags": ["china", "carrier_capable", "j15", "liaoning"],
     "description": "Indigenous turbofan for J-15 Flying Shark on Liaoning and Shandong."},

    # ─── 2020s–2030s planned ───────────────────────────────────────────────────
    {"id": "f35b_stovl_package", "name": "F-35B STOVL Package", "category": "Sensors", "tier": 8,
     "reliability_bonus": 12,
     "cost": {"steel": 20, "electronics": 55, "aluminum": 35, "titanium": 22}, "production_time": 150,
     "special_flags": ["usa", "uk", "carrier_capable", "vstol", "f35b", "queen_elizabeth"],
     "description": "Lift fan and roll-post system for F-35B on Queen Elizabeth and Wasp-class ships."},
    {"id": "f35c_carrier_package", "name": "F-35C Carrier Package", "category": "Sensors", "tier": 8,
     "reliability_bonus": 14,
     "cost": {"steel": 22, "electronics": 58, "aluminum": 38, "titanium": 24}, "production_time": 155,
     "special_flags": ["usa", "carrier_capable", "f35c", "catapult"],
     "description": "Larger wing, reinforced landing gear, and tailhook for catapult carrier ops."},
    {"id": "x47b_ucav_carrier", "name": "X-47B UCAV Carrier Suite", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 12, "electronics": 62, "aluminum": 20}, "production_time": 120,
     "special_flags": ["usa", "carrier_capable", "uav", "prototype", "twenty_tens"],
     "description": "Autonomous carrier landing and refueling demonstrator. Precursor to MQ-25 and UCLASS."},
    {"id": "ngad_carrier_proto_2030", "name": "NGAD Carrier Variant (Proto)", "category": "Sensors", "tier": 9,
     "reliability_bonus": 10,
     "cost": {"steel": 25, "electronics": 75, "aluminum": 45, "titanium": 35}, "production_time": 180,
     "special_flags": ["usa", "carrier_capable", "planned", "twenty_thirties", "ngad"],
     "description": "Planned sixth-generation U.S. Navy carrier fighter. Crewed and loyal-wingman integration."},

    # ─── WWII follow-ups ───────────────────────────────────────────────────────
    {"id": "b6n_jill_torpedo_load", "name": "B6N Jill Torpedo Load", "category": "MainWeapon", "tier": 4,
     "soft_attack": 36, "hard_attack": 48, "piercing": 26, "anti_ship": 88, "air_attack": 6,
     "cost": {"steel": 6, "explosives": 24, "electronics": 5}, "production_time": 48,
     "special_flags": ["japan", "naval_aviation", "ww2", "b6n_jill"],
     "description": "Improved carrier torpedo bomber load for B6N Jill. Replaced the B5N Kate from 1943."},
    {"id": "f2a_buffalo_gun_battery", "name": "F2A Buffalo Gun Battery", "category": "MainWeapon", "tier": 2,
     "soft_attack": 32, "hard_attack": 10, "piercing": 22, "air_attack": 40,
     "cost": {"steel": 6, "aluminum": 3}, "production_time": 28,
     "special_flags": ["usa", "naval_aviation", "ww2", "f2a_buffalo"],
     "description": "Four .50 cal guns on Brewster F2A. Outclassed in Pacific but used from early carriers."},
    {"id": "sea_hurricane_catapult_kit", "name": "Sea Hurricane Catapult Kit", "category": "Sensors", "tier": 3,
     "reliability_bonus": 5,
     "cost": {"steel": 8, "aluminum": 6, "electronics": 3}, "production_time": 35,
     "special_flags": ["uk", "carrier_capable", "ww2", "sea_hurricane", "catapult_fighter"],
     "description": "Catapult-launched Hurricane fit for CAM ships and merchant aircraft carriers."},
]


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if mod["id"] in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\nCarrier aircraft modules: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
