#!/usr/bin/env python3
"""1960s–1970s equipment modules: USA, USSR, China, France, UK, Germany, Israel."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m60a1_patton_armor", "name": "M60A1 Patton Armor", "category": "Armor", "tier": 5,
     "armor_bonus": 50, "top_armor_bonus": 28, "reliability_penalty": -5,
     "cost": {"steel": 38, "chromium": 6, "titanium": 2}, "production_time": 72,
     "special_flags": ["usa", "sixties", "main_battle_tank"],
     "description": "Cast turret and improved glacis on M60A1. Standard U.S. MBT through Vietnam and 1973."},
    {"id": "avds_1790_engine", "name": "AVDS-1790 Diesel", "category": "Engine", "tier": 5,
     "reliability_bonus": 12, "fuel_efficiency": 6, "speed_bonus": 10,
     "cost": {"steel": 18, "aluminum": 6}, "production_time": 62,
     "special_flags": ["usa", "sixties", "diesel_tank"],
     "description": "M60 and M48A5 powerplant. Reliable multi-fuel diesel for global deployments."},
    {"id": "m68a1_105mm_gun", "name": "105 mm M68A1", "category": "MainWeapon", "tier": 5,
     "soft_attack": 62, "hard_attack": 58, "piercing": 122, "air_attack": 5,
     "cost": {"steel": 24, "explosives": 4, "tungsten": 3}, "production_time": 82,
     "special_flags": ["usa", "sixties", "nato_standard"],
     "description": "M60A1 and M1 Abrams interim gun. Fires M735 APFSDS; benchmark Western tank armament."},
    {"id": "m735_apfsds_ammo", "name": "M735 APFSDS", "category": "Cargo", "tier": 5,
     "soft_attack": 6, "hard_attack": 18, "piercing": 28,
     "cost": {"steel": 2, "tungsten": 8, "explosives": 2}, "production_time": 35,
     "special_flags": ["usa", "ammunition", "apfsds", "seventies"],
     "description": "Tungsten long-rod penetrator for 105 mm guns. Restores lethality vs T-62 and T-72."},
    {"id": "m256_120mm_gun", "name": "120 mm M256", "category": "MainWeapon", "tier": 6,
     "soft_attack": 68, "hard_attack": 65, "piercing": 148, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 8, "tungsten": 6}, "production_time": 95,
     "special_flags": ["usa", "seventies", "smoothbore", "m1_abrams"],
     "description": "Rheinmetall-derived smoothbore for M1 Abrams prototype. Defines late-1970s U.S. tank firepower."},
    {"id": "m551_152mm_gun_launcher", "name": "152 mm M81 Gun/Launcher", "category": "MainWeapon", "tier": 5,
     "soft_attack": 72, "hard_attack": 55, "piercing": 95, "air_attack": 8,
     "cost": {"steel": 28, "explosives": 12, "electronics": 8}, "production_time": 88,
     "special_flags": ["usa", "sixties", "shillelagh", "airborne_tank"],
     "description": "M551 Sheridan combined gun and MGM-51 Shillelagh missile launcher. Ambitious but troubled."},
    {"id": "xm1_chobham_composite", "name": "Chobham Composite Package", "category": "Armor", "tier": 6,
     "armor_bonus": 62, "top_armor_bonus": 45, "reliability_penalty": -8,
     "cost": {"steel": 45, "ceramics": 20, "titanium": 8, "kevlar": 6}, "production_time": 110,
     "special_flags": ["usa", "uk_joint", "seventies", "composite_armor"],
     "description": "British-developed composite armor adopted for XM1 trials. Revolutionary vs KE penetrators."},
    {"id": "tow_atgm", "name": "BGM-71 TOW", "category": "MainWeapon", "tier": 5,
     "soft_attack": 35, "hard_attack": 62, "piercing": 130, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 22, "explosives": 14}, "production_time": 55,
     "special_flags": ["usa", "atgm", "wire_guided", "sixties"],
     "description": "Tube-launched optically tracked wire-guided missile. Standard U.S. helicopter and jeep ATGM."},
    {"id": "m47_dragon_atgm", "name": "M47 Dragon", "category": "MainWeapon", "tier": 4,
     "soft_attack": 28, "hard_attack": 48, "piercing": 95, "air_attack": 3,
     "cost": {"steel": 4, "electronics": 12, "explosives": 8}, "production_time": 40,
     "special_flags": ["usa", "atgm", "infantry", "sixties"],
     "description": "Man-portable SACLOS ATGM for infantry. Widely exported; replaced by Javelin lineage."},
    {"id": "agm65_maverick", "name": "AGM-65 Maverick", "category": "MainWeapon", "tier": 5,
     "soft_attack": 55, "hard_attack": 58, "piercing": 75, "air_attack": 6,
     "cost": {"steel": 8, "electronics": 28, "explosives": 18}, "production_time": 70,
     "special_flags": ["usa", "air_to_ground", "guided", "seventies"],
     "description": "TV-guided tactical air-to-surface missile. Devastating precision strike from A-7 and F-4."},
    {"id": "aim7_sparrow", "name": "AIM-7 Sparrow", "category": "MainWeapon", "tier": 5,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 72, "anti_air": 68,
     "cost": {"steel": 6, "electronics": 30, "explosives": 10}, "production_time": 65,
     "special_flags": ["usa", "air_to_air", "bvr", "sixties"],
     "description": "Semi-active radar homing medium-range AAM. F-4 Phantom primary BVR weapon in Vietnam."},
    {"id": "aim9_sidewinder", "name": "AIM-9 Sidewinder", "category": "MainWeapon", "tier": 4,
     "soft_attack": 6, "hard_attack": 4, "air_attack": 58, "anti_air": 55,
     "cost": {"steel": 4, "electronics": 18, "explosives": 6}, "production_time": 48,
     "special_flags": ["usa", "air_to_air", "ir_guided", "sixties"],
     "description": "Infrared dogfight missile. High off-boresight kills when rules of engagement permit."},
    {"id": "pratt_j79_phantom", "name": "Pratt & Whitney J79", "category": "Engine", "tier": 5,
     "reliability_bonus": 10, "fuel_efficiency": 2, "speed_bonus": 28,
     "cost": {"steel": 16, "aluminum": 28, "titanium": 4}, "production_time": 78,
     "special_flags": ["usa", "jet_powerplant", "sixties", "f4_phantom"],
     "description": "F-4 Phantom and F-104 engine. Afterburning turbojet defining 1960s U.S. air superiority."},
    {"id": "ge_f110_proto", "name": "GE F101/F110 Lineage", "category": "Engine", "tier": 6,
     "reliability_bonus": 14, "fuel_efficiency": 8, "speed_bonus": 32,
     "cost": {"steel": 18, "aluminum": 32, "titanium": 10}, "production_time": 95,
     "special_flags": ["usa", "jet_powerplant", "seventies", "turbofan"],
     "description": "High-bypass turbofan development for B-1 and later F-15/F-16. 1970s propulsion leap."},
    {"id": "m61a1_vulcan", "name": "M61A1 Vulcan", "category": "MainWeapon", "tier": 5,
     "soft_attack": 38, "hard_attack": 26, "piercing": 48, "air_attack": 65,
     "cost": {"steel": 12, "aluminum": 10, "electronics": 8}, "production_time": 68,
     "special_flags": ["usa", "gatling", "sixties", "f4_f15"],
     "description": "20 mm Gatling cannon on F-4, F-15, and F-16. Standard U.S. fighter gun through 1990s."},
    {"id": "m109_155mm_howitzer", "name": "M109 155 mm Howitzer", "category": "MainWeapon", "tier": 5,
     "soft_attack": 95, "hard_attack": 35, "piercing": 55, "air_attack": 3,
     "cost": {"steel": 35, "explosives": 20, "electronics": 6}, "production_time": 90,
     "special_flags": ["usa", "artillery", "sixties", "self_propelled"],
     "description": "Self-propelled 155 mm howitzer. Backbone of U.S. division artillery in Vietnam and NATO."},
    {"id": "m163_vulcan_air", "name": "M163 VADS", "category": "AntiAir", "tier": 5,
     "soft_attack": 18, "hard_attack": 8, "air_attack": 62, "anti_air": 65,
     "cost": {"steel": 14, "aluminum": 8, "electronics": 12}, "production_time": 58,
     "special_flags": ["usa", "spaag", "sixties", "vietnam"],
     "description": "M113 chassis with M61 Vulcan. Short-range air defense for convoys and air bases."},
    {"id": "mim23_hawk_sam", "name": "MIM-23 Hawk", "category": "AntiAir", "tier": 5,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 75, "anti_air": 78,
     "cost": {"steel": 20, "electronics": 35, "explosives": 12}, "production_time": 85,
     "special_flags": ["usa", "sam", "sixties", "nato"],
     "description": "Medium-range SAM protecting NATO divisions. Engaged Arab aircraft in 1973."},
    {"id": "harpoon_anti_ship", "name": "AGM-84 Harpoon", "category": "MainWeapon", "tier": 6,
     "soft_attack": 42, "hard_attack": 55, "piercing": 40, "anti_ship": 95, "air_attack": 5,
     "cost": {"steel": 10, "electronics": 32, "explosives": 22}, "production_time": 80,
     "special_flags": ["usa", "anti_ship", "guided", "seventies"],
     "description": "All-weather anti-ship missile entering service 1977. Standard Western naval strike weapon."},
    {"id": "phalanx_ciws", "name": "Phalanx CIWS", "category": "AntiAir", "tier": 6,
     "soft_attack": 22, "hard_attack": 10, "air_attack": 82, "anti_air": 85,
     "cost": {"steel": 16, "aluminum": 12, "electronics": 28}, "production_time": 90,
     "special_flags": ["usa", "naval", "ciws", "seventies"],
     "description": "Radar-guided 20 mm Gatling last-ditch defense. Entered trials late 1970s."},
    {"id": "mk48_torpedo", "name": "Mk 48 Torpedo", "category": "SecondaryWeapon", "tier": 6,
     "soft_attack": 28, "hard_attack": 55, "piercing": 35, "anti_ship": 88,
     "cost": {"steel": 12, "electronics": 30, "explosives": 20}, "production_time": 75,
     "special_flags": ["usa", "naval", "homing", "seventies", "submarine"],
     "description": "Advanced wire-guided submarine torpedo. Dominant Western undersea weapon of the late Cold War."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SOVIET UNION / RUSSIA · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "d10t2s_100mm_gun", "name": "D-10T2S 100 mm", "category": "MainWeapon", "tier": 4,
     "soft_attack": 54, "hard_attack": 50, "piercing": 108, "air_attack": 5,
     "cost": {"steel": 20}, "production_time": 70,
     "special_flags": ["ussr", "sixties", "t55"],
     "description": "T-55 main gun with stabilizer. Most numerous tank gun worldwide through export."},
    {"id": "u5ts_115mm_smoothbore", "name": "U-5TS 115 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 60, "hard_attack": 58, "piercing": 128, "air_attack": 5,
     "cost": {"steel": 26, "explosives": 4}, "production_time": 85,
     "special_flags": ["ussr", "sixties", "smoothbore", "t62"],
     "description": "World's first mass-produced smoothbore tank gun on T-62. Inspired Western APFSDS race."},
    {"id": "d81_125mm_gun", "name": "2A46 125 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 70, "hard_attack": 68, "piercing": 152, "air_attack": 5,
     "cost": {"steel": 34, "chromium": 6, "tungsten": 4}, "production_time": 98,
     "special_flags": ["ussr", "seventies", "smoothbore", "t72"],
     "description": "T-72 and T-64A main armament. Fires APFSDS and AT-8 Songster; NATO's primary threat."},
    {"id": "v12_5_engine", "name": "V-12-5 Diesel", "category": "Engine", "tier": 5,
     "reliability_bonus": 8, "fuel_efficiency": 5, "speed_bonus": 11,
     "cost": {"steel": 20, "aluminum": 4}, "production_time": 65,
     "special_flags": ["ussr", "sixties", "t62"],
     "description": "T-62 powerplant. Compact diesel enabling low silhouette Soviet MBT design."},
    {"id": "v46_6m_diesel", "name": "V-46-6M Diesel", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": 6, "speed_bonus": 13,
     "cost": {"steel": 22, "aluminum": 6}, "production_time": 72,
     "special_flags": ["ussr", "seventies", "t72"],
     "description": "T-72 autoloader tank engine. High power-to-weight for Soviet operational doctrine."},
    {"id": "t62_cast_armor", "name": "T-62 Cast Armor", "category": "Armor", "tier": 5,
     "armor_bonus": 48, "top_armor_bonus": 24, "reliability_penalty": -4,
     "cost": {"steel": 36, "chromium": 4}, "production_time": 68,
     "special_flags": ["ussr", "sixties", "mbt"],
     "description": "T-62 hull and turret protection. Thicker than T-55; vulnerable to 105 mm APFSDS."},
    {"id": "t72_composite_armor", "name": "T-72 Composite Armor", "category": "Armor", "tier": 6,
     "armor_bonus": 55, "top_armor_bonus": 32, "reliability_penalty": -6,
     "cost": {"steel": 40, "ceramics": 8, "chromium": 5}, "production_time": 78,
     "special_flags": ["ussr", "seventies", "composite"],
     "description": "Sandwich steel-glass-textile armor on T-72 glacis. Effective vs HEAT; upgraded with ERA later."},
    {"id": "kontakt1_era", "name": "Kontakt-1 ERA", "category": "Armor", "tier": 5,
     "armor_bonus": 22, "top_armor_bonus": 14, "reliability_penalty": -3,
     "cost": {"steel": 8, "explosives": 12}, "production_time": 45,
     "special_flags": ["ussr", "era", "seventies", "reactive"],
     "description": "First-generation explosive reactive armor blocks. Dramatically improves HEAT survivability."},
    {"id": "bmp1_73mm_grom", "name": "2A28 Grom 73 mm", "category": "MainWeapon", "tier": 4,
     "soft_attack": 48, "hard_attack": 38, "piercing": 72, "air_attack": 4,
     "cost": {"steel": 14, "explosives": 6}, "production_time": 55,
     "special_flags": ["ussr", "sixties", "ifv", "bmp1"],
     "description": "BMP-1 low-pressure gun. HEAT and 9M14 Malyutka launcher in one compact turret."},
    {"id": "malyutka_at3_sagger", "name": "9M14 Malyutka (AT-3)", "category": "MainWeapon", "tier": 4,
     "soft_attack": 30, "hard_attack": 52, "piercing": 105, "air_attack": 3,
     "cost": {"steel": 4, "electronics": 10, "explosives": 8}, "production_time": 38,
     "special_flags": ["ussr", "atgm", "wire_guided", "sixties"],
     "description": "MCLOS ATGM on BMP-1 and BRDM. Iconic Third World export; shocked Israelis in 1973."},
    {"id": "konkurs_at5_spandrel", "name": "9M113 Konkurs (AT-5)", "category": "MainWeapon", "tier": 5,
     "soft_attack": 35, "hard_attack": 60, "piercing": 125, "air_attack": 4,
     "cost": {"steel": 5, "electronics": 18, "explosives": 12}, "production_time": 50,
     "special_flags": ["ussr", "atgm", "saclos", "seventies"],
     "description": "SACLOS wire-guided ATGM replacing Sagger. Standard BMP-2 and infantry anti-tank."},
    {"id": "sa6_gainful_sam", "name": "2K12 Kub (SA-6)", "category": "AntiAir", "tier": 5,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 78, "anti_air": 82,
     "cost": {"steel": 18, "electronics": 32, "explosives": 14}, "production_time": 88,
     "special_flags": ["ussr", "sam", "sixties", "radar_guided"],
     "description": "Mobile SAM that devastated Israeli air power in 1973 when employed with discipline."},
    {"id": "sa7_strela", "name": "9K32 Strela-2 (SA-7)", "category": "AntiAir", "tier": 4,
     "soft_attack": 6, "hard_attack": 4, "air_attack": 48, "anti_air": 50,
     "cost": {"steel": 2, "electronics": 8, "explosives": 4}, "production_time": 30,
     "special_flags": ["ussr", "manpads", "sixties"],
     "description": "Infantry IR SAM. Forced low-level tactics worldwide; simple and prolific."},
    {"id": "sa8_gecko_sam", "name": "9K33 Osa (SA-8)", "category": "AntiAir", "tier": 5,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 72, "anti_air": 75,
     "cost": {"steel": 14, "electronics": 28, "explosives": 10}, "production_time": 75,
     "special_flags": ["ussr", "sam", "seventies"],
     "description": "All-weather short-range SAM on tracked chassis. Protects Soviet maneuver columns."},
    {"id": "r60_atoll_missile", "name": "R-60 Atoll", "category": "MainWeapon", "tier": 4,
     "soft_attack": 6, "hard_attack": 5, "air_attack": 55, "anti_air": 52,
     "cost": {"steel": 3, "electronics": 14, "explosives": 5}, "production_time": 42,
     "special_flags": ["ussr", "air_to_air", "ir_guided", "sixties"],
     "description": "MiG-21 and MiG-23 short-range IR missile. Export staple of Soviet client air forces."},
    {"id": "r23_apex_missile", "name": "R-23 Apex", "category": "MainWeapon", "tier": 5,
     "soft_attack": 8, "hard_attack": 7, "air_attack": 68, "anti_air": 65,
     "cost": {"steel": 5, "electronics": 22, "explosives": 8}, "production_time": 55,
     "special_flags": ["ussr", "air_to_air", "bvr", "seventies"],
     "description": "MiG-23 primary radar-guided missile. Improved kill probability vs Vietnam-era Sparrow."},
    {"id": "tumansky_r13_mig21", "name": "Tumansky R-13-300", "category": "Engine", "tier": 5,
     "reliability_bonus": 6, "fuel_efficiency": 3, "speed_bonus": 30,
     "cost": {"steel": 14, "aluminum": 22, "titanium": 3}, "production_time": 72,
     "special_flags": ["ussr", "jet_powerplant", "sixties", "mig21"],
     "description": "MiG-21F-13 engine. Most-produced supersonic fighter powerplant of the Cold War."},
    {"id": "tumansky_r29_mig23", "name": "Tumansky R-29B-300", "category": "Engine", "tier": 5,
     "reliability_bonus": 5, "fuel_efficiency": 2, "speed_bonus": 32,
     "cost": {"steel": 16, "aluminum": 24, "titanium": 5}, "production_time": 78,
     "special_flags": ["ussr", "jet_powerplant", "seventies", "variable_geometry"],
     "description": "MiG-23 swing-wing fighter engine. Afterburning thrust for intercept and strike."},
    {"id": "gsh301_30mm_cannon", "name": "GSh-30-1", "category": "MainWeapon", "tier": 5,
     "soft_attack": 40, "hard_attack": 30, "piercing": 52, "air_attack": 58,
     "cost": {"steel": 10, "aluminum": 6}, "production_time": 60,
     "special_flags": ["ussr", "seventies", "mig29_lineage"],
     "description": "Late-1970s Soviet fighter cannon development. High rate of fire for MiG-29 program."},
    {"id": "ssn2_styx_missile", "name": "P-15 Termit (SS-N-2)", "category": "MainWeapon", "tier": 4,
     "soft_attack": 38, "hard_attack": 48, "piercing": 35, "anti_ship": 82, "air_attack": 4,
     "cost": {"steel": 8, "electronics": 16, "explosives": 20}, "production_time": 65,
     "special_flags": ["ussr", "anti_ship", "guided", "sixties"],
     "description": "Soviet anti-ship missile. Sunk Eilat 1967; defined missile boat warfare."},
    {"id": "ak630_ciws", "name": "AK-630 CIWS", "category": "AntiAir", "tier": 6,
     "soft_attack": 25, "hard_attack": 12, "air_attack": 80, "anti_air": 82,
     "cost": {"steel": 18, "aluminum": 10, "electronics": 22}, "production_time": 85,
     "special_flags": ["ussr", "naval", "ciws", "seventies"],
     "description": "Six-barrel 30 mm Gatling naval CIWS. Soviet answer to Harpoon saturation attacks."},

    # ═══════════════════════════════════════════════════════════════════════════
    # CHINA · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "type59_100mm_gun", "name": "Type 59 100 mm", "category": "MainWeapon", "tier": 4,
     "soft_attack": 52, "hard_attack": 48, "piercing": 102, "air_attack": 5,
     "cost": {"steel": 18}, "production_time": 65,
     "special_flags": ["china", "sixties", "type59"],
     "description": "Licensed T-54A gun on Type 59 MBT. People's Liberation Army primary tank through 1980s."},
    {"id": "type69_100mm_gun", "name": "Type 69 100 mm (Improved)", "category": "MainWeapon", "tier": 5,
     "soft_attack": 56, "hard_attack": 52, "piercing": 112, "air_attack": 5,
     "cost": {"steel": 20, "explosives": 3}, "production_time": 72,
     "special_flags": ["china", "seventies", "type69"],
     "description": "Improved Type 69 MBT gun with stabilizer and better ammunition. Saw combat in 1979."},
    {"id": "type62_85mm_gun", "name": "Type 62 85 mm", "category": "MainWeapon", "tier": 3,
     "soft_attack": 44, "hard_attack": 38, "piercing": 78, "air_attack": 4,
     "cost": {"steel": 14}, "production_time": 55,
     "special_flags": ["china", "sixties", "light_tank"],
     "description": "Light tank gun for southern terrain and mountain warfare. Thin armor, high mobility."},
    {"id": "12150l_diesel", "name": "12150L Diesel", "category": "Engine", "tier": 4,
     "reliability_bonus": 4, "fuel_efficiency": 4, "speed_bonus": 9,
     "cost": {"steel": 16}, "production_time": 58,
     "special_flags": ["china", "sixties", "tank_engine"],
     "description": "Chinese copy of Soviet V-2/V-55 lineage. Powers Type 59 and Type 69 families."},
    {"id": "type59_cast_armor", "name": "Type 59 Armor Package", "category": "Armor", "tier": 4,
     "armor_bonus": 42, "top_armor_bonus": 20, "reliability_penalty": -4,
     "cost": {"steel": 30}, "production_time": 62,
     "special_flags": ["china", "sixties"],
     "description": "Domestic T-54 derivative armor. Mass-produced for PLA and export to Pakistan and Africa."},
    {"id": "hj73_atgm", "name": "HJ-73 ATGM", "category": "MainWeapon", "tier": 4,
     "soft_attack": 28, "hard_attack": 46, "piercing": 90, "air_attack": 3,
     "cost": {"steel": 4, "electronics": 8, "explosives": 6}, "production_time": 35,
     "special_flags": ["china", "atgm", "sixties", "sagger_copy"],
     "description": "Chinese copy of 9M14 Malyutka. Equips Type 63 and early anti-tank teams."},
    {"id": "hq2_sam", "name": "HQ-2 (SA-2 Copy)", "category": "AntiAir", "tier": 4,
     "soft_attack": 14, "hard_attack": 12, "air_attack": 70, "anti_air": 72,
     "cost": {"steel": 22, "electronics": 24, "explosives": 16}, "production_time": 80,
     "special_flags": ["china", "sam", "sixties", "strategic"],
     "description": "Licensed SA-2 Guideline. Backbone of PRC air defense; shot down U-2 over China."},
    {"id": "wp7_turbojet_j7", "name": "WP-7 Turbojet", "category": "Engine", "tier": 5,
     "reliability_bonus": 5, "fuel_efficiency": 2, "speed_bonus": 28,
     "cost": {"steel": 14, "aluminum": 20}, "production_time": 70,
     "special_flags": ["china", "jet_powerplant", "seventies", "j7"],
     "description": "MiG-21F-13 copy engine for J-7 fighter. China's first widespread supersonic fighter."},
    {"id": "type30_30mm_cannon", "name": "Type 30-1 30 mm", "category": "MainWeapon", "tier": 4,
     "soft_attack": 32, "hard_attack": 22, "piercing": 40, "air_attack": 48,
     "cost": {"steel": 8, "aluminum": 4}, "production_time": 45,
     "special_flags": ["china", "aircraft_gun", "sixties", "j6"],
     "description": "NRIET 30 mm cannon on J-6 and J-7. Soviet NR-30 lineage."},
    {"id": "pl2_air_air_missile", "name": "PL-2 Air-to-Air", "category": "MainWeapon", "tier": 4,
     "soft_attack": 6, "hard_attack": 4, "air_attack": 52, "anti_air": 48,
     "cost": {"steel": 3, "electronics": 12, "explosives": 5}, "production_time": 40,
     "special_flags": ["china", "air_to_air", "sixties", "k13_copy"],
     "description": "K-13/AA-2 Atoll copy for J-7. Basic IR homing missile for PLAAF."},
    {"id": "type63_107mm_rocket", "name": "Type 63 107 mm Rocket", "category": "MainWeapon", "tier": 3,
     "soft_attack": 65, "hard_attack": 18, "piercing": 12, "air_attack": 4,
     "cost": {"steel": 6, "explosives": 10}, "production_time": 28,
     "special_flags": ["china", "rocket_artillery", "sixties"],
     "description": "Truck-mounted rocket artillery. Simple, cheap saturation fires for PLA divisions."},

    # ═══════════════════════════════════════════════════════════════════════════
    # FRANCE · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "cn105f1_105mm_gun", "name": "CN-105-F1 105 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 60, "hard_attack": 56, "piercing": 118, "air_attack": 5,
     "cost": {"steel": 22, "explosives": 4}, "production_time": 80,
     "special_flags": ["france", "sixties", "amx30"],
     "description": "AMX-30 high-pressure 105 mm. Excellent APFSDS; lighter tank than contemporary Leopard."},
    {"id": "amx30_armor", "name": "AMX-30 Armor", "category": "Armor", "tier": 4,
     "armor_bonus": 38, "top_armor_bonus": 18, "reliability_penalty": -3,
     "cost": {"steel": 28, "chromium": 3}, "production_time": 58,
     "special_flags": ["france", "sixties", "mbt"],
     "description": "AMX-30 emphasis on mobility over armor. Acceptable vs Warsaw Pact HEAT at range."},
    {"id": "hs110_diesel_amx30", "name": "HS-110 Diesel", "category": "Engine", "tier": 5,
     "reliability_bonus": 6, "fuel_efficiency": 5, "speed_bonus": 14,
     "cost": {"steel": 18, "aluminum": 4}, "production_time": 65,
     "special_flags": ["france", "sixties", "multifuel"],
     "description": "720 hp engine giving AMX-30 exceptional speed. French doctrine favored maneuver."},
    {"id": "amx13_90mm_gun", "name": "90 mm D921", "category": "MainWeapon", "tier": 4,
     "soft_attack": 50, "hard_attack": 44, "piercing": 95, "air_attack": 4,
     "cost": {"steel": 16, "aluminum": 4}, "production_time": 62,
     "special_flags": ["france", "sixties", "light_tank", "oscillating"],
     "description": "Up-gunned AMX-13 for export. Oscillating turret on light chassis; popular in Third World."},
    {"id": "atar9c_turbojet", "name": "Atar 9C", "category": "Engine", "tier": 5,
     "reliability_bonus": 8, "fuel_efficiency": 4, "speed_bonus": 29,
     "cost": {"steel": 14, "aluminum": 24, "titanium": 3}, "production_time": 75,
     "special_flags": ["france", "jet_powerplant", "sixties", "mirage3"],
     "description": "Mirage III and Mirage 5 engine. French strategic independence in combat aircraft."},
    {"id": "mirage_f1_m53_engine", "name": "SNECMA M53", "category": "Engine", "tier": 6,
     "reliability_bonus": 10, "fuel_efficiency": 7, "speed_bonus": 31,
     "cost": {"steel": 16, "aluminum": 28, "titanium": 6}, "production_time": 88,
     "special_flags": ["france", "jet_powerplant", "seventies", "mirage_f1"],
     "description": "Mirage F1 turbofan. Improved range and payload vs Mirage III Atar."},
    {"id": "defa550_30mm", "name": "DEFA 550", "category": "MainWeapon", "tier": 5,
     "soft_attack": 38, "hard_attack": 26, "piercing": 46, "air_attack": 56,
     "cost": {"steel": 9, "aluminum": 5}, "production_time": 55,
     "special_flags": ["france", "aircraft_gun", "sixties"],
     "description": "Mirage standard revolver cannon. Exported with French fighters worldwide."},
    {"id": "magic1_air_missile", "name": "R.550 Magic", "category": "MainWeapon", "tier": 5,
     "soft_attack": 7, "hard_attack": 5, "air_attack": 62, "anti_air": 58,
     "cost": {"steel": 4, "electronics": 20, "explosives": 6}, "production_time": 52,
     "special_flags": ["france", "air_to_air", "seventies", "high_off_boresight"],
     "description": "All-aspect IR missile for Mirage F1. Competitive with AIM-9L development."},
    {"id": "entac_atgm", "name": "ENTAC ATGM", "category": "MainWeapon", "tier": 4,
     "soft_attack": 26, "hard_attack": 44, "piercing": 88, "air_attack": 3,
     "cost": {"steel": 4, "electronics": 10, "explosives": 6}, "production_time": 38,
     "special_flags": ["france", "atgm", "sixties", "wire_guided"],
     "description": "Early French wire-guided ATGM on AML and helicopters. Precursor to MILAN."},
    {"id": "milan_atgm", "name": "MILAN", "category": "MainWeapon", "tier": 5,
     "soft_attack": 32, "hard_attack": 58, "piercing": 120, "air_attack": 4,
     "cost": {"steel": 5, "electronics": 16, "explosives": 10}, "production_time": 48,
     "special_flags": ["france", "germany_joint", "atgm", "seventies", "saclos"],
     "description": "Franco-German SACLOS ATGM. Standard NATO infantry anti-tank from 1970s."},
    {"id": "exocet_mm38", "name": "Exocet MM38", "category": "MainWeapon", "tier": 6,
     "soft_attack": 40, "hard_attack": 52, "piercing": 38, "anti_ship": 92, "air_attack": 5,
     "cost": {"steel": 8, "electronics": 30, "explosives": 18}, "production_time": 78,
     "special_flags": ["france", "anti_ship", "seventies", "sea_skimmer"],
     "description": "Sea-skimming anti-ship missile. Famous 1982 Falklands strikes; developed in 1970s."},
    {"id": "hot_atgm", "name": "HOT", "category": "MainWeapon", "tier": 5,
     "soft_attack": 34, "hard_attack": 60, "piercing": 128, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 20, "explosives": 12}, "production_time": 55,
     "special_flags": ["france", "germany_joint", "atgm", "seventies", "helicopter"],
     "description": "Long-range SACLOS ATGM for Gazelle and AMX-10P. Franco-German successor to ENTAC."},
    {"id": "roland_sam", "name": "Roland SAM", "category": "AntiAir", "tier": 5,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 74, "anti_air": 76,
     "cost": {"steel": 16, "electronics": 28, "explosives": 10}, "production_time": 82,
     "special_flags": ["france", "germany_joint", "sam", "seventies"],
     "description": "Franco-German point-defense SAM. Protects armored columns from helicopters and aircraft."},
    {"id": "giat_120mm_cn120", "name": "CN-120-26 120 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 66, "hard_attack": 64, "piercing": 142, "air_attack": 5,
     "cost": {"steel": 30, "chromium": 6, "tungsten": 4}, "production_time": 92,
     "special_flags": ["france", "seventies", "smoothbore", "amx40_proto"],
     "description": "GIAT smoothbore for AMX-40 prototype. French entry in 120 mm NATO gun race."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED KINGDOM · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "l11a5_120mm_rifled", "name": "120 mm L11A5", "category": "MainWeapon", "tier": 5,
     "soft_attack": 64, "hard_attack": 60, "piercing": 132, "air_attack": 5,
     "cost": {"steel": 28, "explosives": 5, "tungsten": 4}, "production_time": 88,
     "special_flags": ["uk", "sixties", "chieftain", "rifled"],
     "description": "Chieftain MBT gun. HESH and APDS; exceptional kill range in 1970s NATO exercises."},
    {"id": "chieftain_armor", "name": "Chieftain Armor", "category": "Armor", "tier": 5,
     "armor_bonus": 52, "top_armor_bonus": 30, "reliability_penalty": -8,
     "cost": {"steel": 42, "chromium": 5}, "production_time": 75,
     "special_flags": ["uk", "sixties", "mbt"],
     "description": "Heavy frontal armor on Chieftain. Excellent protection; plagued by L60 engine reliability."},
    {"id": "l60_engine_chieftain", "name": "L60 Multifuel Engine", "category": "Engine", "tier": 4,
     "reliability_bonus": -6, "fuel_efficiency": 4, "speed_bonus": 8,
     "cost": {"steel": 20, "aluminum": 4}, "production_time": 70,
     "special_flags": ["uk", "sixties", "notorious"],
     "description": "Chieftain powerplant. Innovative but unreliable; replaced by Leyland in Mk 10."},
    {"id": "chobham_armor_uk", "name": "Chobham Armor", "category": "Armor", "tier": 6,
     "armor_bonus": 60, "top_armor_bonus": 42, "reliability_penalty": -6,
     "cost": {"steel": 40, "ceramics": 22, "titanium": 6}, "production_time": 105,
     "special_flags": ["uk", "seventies", "composite", "classified"],
     "description": "British composite armor on Shir 1 / Challenger development. Shared with U.S. XM1 program."},
    {"id": "royal_ordnance_l7a1", "name": "L7A1 105 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 60, "hard_attack": 56, "piercing": 120, "air_attack": 5,
     "cost": {"steel": 22, "explosives": 3}, "production_time": 78,
     "special_flags": ["uk", "sixties", "centurion", "nato_export"],
     "description": "Late Centurion and export gun. Still effective with L52 APFSDS in 1973 war."},
    {"id": "pegasus_harrier_engine", "name": "Rolls-Royce Pegasus", "category": "Engine", "tier": 6,
     "reliability_bonus": 8, "fuel_efficiency": 4, "speed_bonus": 24,
     "cost": {"steel": 18, "aluminum": 30, "titanium": 8}, "production_time": 100,
     "special_flags": ["uk", "vstol", "sixties", "harrier"],
     "description": "Harrier vectored-thrust engine. Enables STOVL operations from small carriers and forward bases."},
    {"id": "red_top_missile", "name": "Red Top", "category": "MainWeapon", "tier": 5,
     "soft_attack": 7, "hard_attack": 5, "air_attack": 60, "anti_air": 56,
     "cost": {"steel": 4, "electronics": 18, "explosives": 6}, "production_time": 50,
     "special_flags": ["uk", "air_to_air", "sixties"],
     "description": "Improved Firestreak IR missile for Lightning and Harrier. Limited all-aspect capability."},
    {"id": "skyflash_missile", "name": "Skyflash", "category": "MainWeapon", "tier": 5,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 70, "anti_air": 66,
     "cost": {"steel": 5, "electronics": 24, "explosives": 8}, "production_time": 58,
     "special_flags": ["uk", "air_to_air", "seventies", "sparrowski"],
     "description": "British Sparrow derivative for Phantom FG.1. Semi-active radar homing."},
    {"id": "swingfire_atgm", "name": "Swingfire", "category": "MainWeapon", "tier": 5,
     "soft_attack": 30, "hard_attack": 54, "piercing": 110, "air_attack": 3,
     "cost": {"steel": 5, "electronics": 14, "explosives": 10}, "production_time": 48,
     "special_flags": ["uk", "atgm", "sixties", "saclos"],
     "description": "British vehicle-mounted ATGM. FV438 and Striker; wide firing arc."},
    {"id": "rapier_sam", "name": "Rapier SAM", "category": "AntiAir", "tier": 5,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 72, "anti_air": 74,
     "cost": {"steel": 12, "electronics": 26, "explosives": 8}, "production_time": 70,
     "special_flags": ["uk", "sam", "seventies"],
     "description": "Optically guided point-defense SAM. Falklands and NATO low-level air defense."},
    {"id": "sea_dart_sam", "name": "Sea Dart", "category": "AntiAir", "tier": 6,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 80, "anti_air": 82,
     "cost": {"steel": 18, "electronics": 35, "explosives": 14}, "production_time": 95,
     "special_flags": ["uk", "naval", "sam", "seventies"],
     "description": "Type 42 destroyer area-defense missile. Falklands War demonstrated capability and limits."},
    {"id": "lynx_has_missile", "name": "Sea Skua (HAS.1)", "category": "MainWeapon", "tier": 5,
     "soft_attack": 35, "hard_attack": 42, "piercing": 30, "anti_ship": 75,
     "cost": {"steel": 6, "electronics": 22, "explosives": 14}, "production_time": 62,
     "special_flags": ["uk", "anti_ship", "helicopter", "seventies"],
     "description": "Lynx helicopter anti-ship missile development. Part of 1970s ASW and strike modernization."},

    # ═══════════════════════════════════════════════════════════════════════════
    # WEST GERMANY · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "rh105_105mm_leopard1", "name": "L7A3 105 mm (Leopard 1)", "category": "MainWeapon", "tier": 5,
     "soft_attack": 60, "hard_attack": 56, "piercing": 118, "air_attack": 5,
     "cost": {"steel": 22, "explosives": 3, "tungsten": 2}, "production_time": 78,
     "special_flags": ["germany", "sixties", "leopard1", "nato"],
     "description": "Rheinmetall-built L7 for Leopard 1. Western Europe's standard MBT gun in 1970s."},
    {"id": "leopard1_armor", "name": "Leopard 1 Armor", "category": "Armor", "tier": 4,
     "armor_bonus": 44, "top_armor_bonus": 22, "reliability_penalty": -3,
     "cost": {"steel": 32, "chromium": 4}, "production_time": 65,
     "special_flags": ["germany", "sixties", "mbt"],
     "description": "Leopard 1 armor emphasizing mobility. Upgraded with add-on kits in 1970s."},
    {"id": "mtu_mb838_engine", "name": "MTU MB 838", "category": "Engine", "tier": 5,
     "reliability_bonus": 14, "fuel_efficiency": 7, "speed_bonus": 12,
     "cost": {"steel": 18, "aluminum": 5}, "production_time": 68,
     "special_flags": ["germany", "sixties", "leopard1"],
     "description": "Leopard 1 multi-fuel diesel. Renowned reliability; export success across NATO."},
    {"id": "rh120_120mm_smoothbore", "name": "Rh-120 L/44", "category": "MainWeapon", "tier": 6,
     "soft_attack": 68, "hard_attack": 66, "piercing": 150, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 8, "tungsten": 6}, "production_time": 98,
     "special_flags": ["germany", "seventies", "smoothbore", "leopard2"],
     "description": "Leopard 2 main gun development completed 1979. NATO standard 120 mm smoothbore."},
    {"id": "leopard2_armor_proto", "name": "Leopard 2 Armor Package", "category": "Armor", "tier": 6,
     "armor_bonus": 58, "top_armor_bonus": 38, "reliability_penalty": -5,
     "cost": {"steel": 44, "ceramics": 12, "chromium": 6}, "production_time": 88,
     "special_flags": ["germany", "seventies", "mbt"],
     "description": "Leopard 2 composite and spaced armor. Designed to defeat 125 mm APFSDS at combat ranges."},
    {"id": "rh202_20mm_cannon", "name": "Rh 202 20 mm", "category": "MainWeapon", "tier": 4,
     "soft_attack": 24, "hard_attack": 14, "piercing": 32, "air_attack": 38,
     "cost": {"steel": 8, "aluminum": 4}, "production_time": 42,
     "special_flags": ["germany", "ifv", "spaag", "sixties"],
     "description": "Marder IFV and Gepard SPAAG autocannon. Versatile 20 mm for ground and air targets."},
    {"id": "gepard_spaag_system", "name": "Flakpanzer Gepard", "category": "AntiAir", "tier": 6,
     "soft_attack": 20, "hard_attack": 10, "air_attack": 78, "anti_air": 80,
     "cost": {"steel": 28, "aluminum": 12, "electronics": 24}, "production_time": 90,
     "special_flags": ["germany", "spaag", "seventies", "radar_guided"],
     "description": "Twin 35 mm radar-guided SPAAG on Leopard 1 chassis. Entered service 1976."},
    {"id": "mg3_infantry_gun", "name": "MG3 7.62 mm", "category": "SecondaryWeapon", "tier": 3,
     "soft_attack": 28, "hard_attack": 6, "piercing": 18, "air_attack": 8,
     "cost": {"steel": 4}, "production_time": 22,
     "special_flags": ["germany", "coaxial", "sixties"],
     "description": "Standard Bundeswehr machine gun on Leopard and Marder coaxial mounts."},
    {"id": "brdm2_scout", "name": "BRDM-2 Recon Package", "category": "Sensors", "tier": 3,
     "reliability_bonus": 3,
     "cost": {"steel": 8, "electronics": 10, "optics": 6}, "production_time": 40,
     "special_flags": ["ussr", "germany_captured", "recon", "sixties"],
     "description": "Warsaw Pact scout vehicle ubiquitous in NATO threat training. Used as OPFOR benchmark."},

    # ═══════════════════════════════════════════════════════════════════════════
    # ISRAEL · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "merkava_mk1_105mm", "name": "Merkava 105 mm", "category": "MainWeapon", "tier": 5,
     "soft_attack": 60, "hard_attack": 56, "piercing": 118, "air_attack": 5,
     "cost": {"steel": 24, "explosives": 4, "tungsten": 3}, "production_time": 82,
     "special_flags": ["israel", "seventies", "merkava"],
     "description": "Licensed L7 variant on Merkava Mk I. Optimized for APFSDS in desert combat."},
    {"id": "merkava_mk1_armor", "name": "Merkava Mk I Armor", "category": "Armor", "tier": 5,
     "armor_bonus": 54, "top_armor_bonus": 32, "reliability_penalty": -4,
     "cost": {"steel": 40, "chromium": 5, "ceramics": 6}, "production_time": 80,
     "special_flags": ["israel", "seventies", "front_engine", "mbt"],
     "description": "Front-engine layout protecting crew. Spaced armor lessons from 1973 Yom Kippur War."},
    {"id": "merkava_avds_engine", "name": "Teledyne AVDS-1790 (Merkava)", "category": "Engine", "tier": 5,
     "reliability_bonus": 12, "fuel_efficiency": 5, "speed_bonus": 10,
     "cost": {"steel": 18, "aluminum": 6}, "production_time": 65,
     "special_flags": ["israel", "seventies", "usa_origin"],
     "description": "American-origin diesel adapted for Merkava. Proven in desert heat and dust."},
    {"id": "blazer_era_package", "name": "Blazer ERA", "category": "Armor", "tier": 5,
     "armor_bonus": 24, "top_armor_bonus": 16, "reliability_penalty": -3,
     "cost": {"steel": 10, "explosives": 14, "electronics": 4}, "production_time": 50,
     "special_flags": ["israel", "era", "seventies", "magach"],
     "description": "Israeli explosive reactive armor for Magach (M48/M60) upgrades. Response to AT-3 and RPG-7."},
    {"id": "magach_m60_upgrade", "name": "Magach 6 Package", "category": "Armor", "tier": 4,
     "armor_bonus": 46, "top_armor_bonus": 24, "reliability_penalty": -4,
     "cost": {"steel": 32, "chromium": 4, "electronics": 6}, "production_time": 70,
     "special_flags": ["israel", "sixties", "m60_derivative"],
     "description": "Israeli M60A1 upgrade with improved FCS and armor. Workhorse until Merkava matured."},
    {"id": "shafrir2_missile", "name": "Shafrir 2", "category": "MainWeapon", "tier": 5,
     "soft_attack": 7, "hard_attack": 5, "air_attack": 62, "anti_air": 58,
     "cost": {"steel": 4, "electronics": 18, "explosives": 6}, "production_time": 50,
     "special_flags": ["israel", "air_to_air", "sixties"],
     "description": "Israeli IR missile on Mirage and Nesher. High kill ratio in 1973 air war."},
    {"id": "python3_missile", "name": "Python 3", "category": "MainWeapon", "tier": 6,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 72, "anti_air": 68,
     "cost": {"steel": 5, "electronics": 24, "explosives": 7}, "production_time": 58,
     "special_flags": ["israel", "air_to_air", "seventies", "all_aspect"],
     "description": "Advanced Israeli IR AAM entering development late 1970s. Export success followed."},
    {"id": "gabriel_mk2_missile", "name": "Gabriel Mk II", "category": "MainWeapon", "tier": 5,
     "soft_attack": 36, "hard_attack": 48, "piercing": 32, "anti_ship": 85, "air_attack": 4,
     "cost": {"steel": 8, "electronics": 24, "explosives": 16}, "production_time": 68,
     "special_flags": ["israel", "anti_ship", "seventies"],
     "description": "Israeli anti-ship missile on Sa'ar missile boats. Sank Arab craft in 1973."},
    {"id": "kfir_j79_engine", "name": "J79 (Kfir)", "category": "Engine", "tier": 5,
     "reliability_bonus": 9, "fuel_efficiency": 2, "speed_bonus": 28,
     "cost": {"steel": 16, "aluminum": 26}, "production_time": 75,
     "special_flags": ["israel", "jet_powerplant", "seventies", "kfir"],
     "description": "American J79 in Israeli Kfir fighter. Mirage 5 airframe with U.S. engine after embargo."},
    {"id": "neshot_missile", "name": "Nesher / Mirage 5", "category": "MainWeapon", "tier": 4,
     "soft_attack": 32, "hard_attack": 20, "piercing": 38, "air_attack": 42,
     "cost": {"steel": 6, "aluminum": 4}, "production_time": 45,
     "special_flags": ["israel", "aircraft_gun", "sixties", "french_origin"],
     "description": "DEFA-armed Israeli strike fighter. French Mirage 5 production before domestic Kfir."},
    {"id": "tow_launcher_idf", "name": "TOW (IDF)", "category": "MainWeapon", "tier": 5,
     "soft_attack": 35, "hard_attack": 62, "piercing": 130, "air_attack": 4,
     "cost": {"steel": 6, "electronics": 22, "explosives": 14}, "production_time": 52,
     "special_flags": ["israel", "usa", "atgm", "seventies"],
     "description": "U.S. TOW on M113 and jeeps. Critical anti-tank capability in 1973 Sinai fighting."},
    {"id": "m113_idf_apc", "name": "M113 IDF APC Package", "category": "Armor", "tier": 3,
     "armor_bonus": 18, "top_armor_bonus": 8, "reliability_penalty": -2,
     "cost": {"steel": 16, "aluminum": 6}, "production_time": 45,
     "special_flags": ["israel", "apc", "sixties", "usa_origin"],
     "description": "American M113 adapted for IDF with machine guns and TOW. Backbone of mechanized infantry."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SHARED NATO / WARSAW · 1960s–1970s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "apfsds_tungsten_rod", "name": "Tungsten APFSDS (Gen 2)", "category": "Cargo", "tier": 5,
     "soft_attack": 8, "hard_attack": 22, "piercing": 32,
     "cost": {"tungsten": 12, "steel": 2}, "production_time": 40,
     "special_flags": ["nato", "ammunition", "seventies", "apfsds"],
     "description": "Second-generation long-rod penetrators for 105 mm and 115 mm guns. Arms race centerpiece."},
    {"id": "hesh_fs_ammo", "name": "HESH-FS Round", "category": "Cargo", "tier": 4,
     "soft_attack": 18, "hard_attack": 14, "piercing": 8,
     "cost": {"steel": 2, "explosives": 10, "chemicals": 4}, "production_time": 28,
     "special_flags": ["uk", "ammunition", "sixties", "anti_armor"],
     "description": "British squash-head ammunition for L11 and L7. Effective vs Soviet tanks without high velocity."},
    {"id": "laser_rangefinder_tank", "name": "Tank Laser Rangefinder", "category": "Sensors", "tier": 5,
     "reliability_bonus": 5,
     "cost": {"steel": 4, "electronics": 24, "optics": 12, "rare_earths": 4}, "production_time": 55,
     "special_flags": ["nato", "fcs", "seventies"],
     "description": "Nd:YAG laser rangefinder for M60A2, Chieftain Mk 5, and Leopard 1A4. First-shot kill enabler."},
    {"id": "ballistic_computer_gpch", "name": "Ballistic Computer (GPCH)", "category": "Sensors", "tier": 4,
     "reliability_bonus": 4,
     "cost": {"steel": 3, "electronics": 18}, "production_time": 48,
     "special_flags": ["nato", "fcs", "sixties"],
     "description": "Analog ballistic computer for 1960s MBTs. Reduces engagement time vs manual ranging."},
    {"id": "thermal_sight_gen1", "name": "AN/VSG-2 Thermal Sight", "category": "Sensors", "tier": 6,
     "reliability_bonus": 4,
     "cost": {"steel": 5, "electronics": 32, "optics": 16, "rare_earths": 8}, "production_time": 75,
     "special_flags": ["usa", "thermal", "seventies", "night_fighting"],
     "description": "First-generation tank thermal imager trials. Game-changer for night engagements by 1980s."},
    {"id": "nbc_overpressure_kit", "name": "NBC Overpressure Kit", "category": "NBC_Protection", "tier": 4,
     "reliability_bonus": 2,
     "cost": {"steel": 6, "rubber": 8, "chemicals": 6}, "production_time": 35,
     "special_flags": ["nato", "warsaw_pact", "sixties", "nbc"],
     "description": "Collective protection for MBTs and IFVs. Standard on 1970s designs after chemical warfare fears."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\n1960s–1970s: {created} created, {skipped} skipped, {total} total modules.")


if __name__ == "__main__":
    main()
