#!/usr/bin/env python3
"""2000s–2010s unit templates: USA, Russia, China, France, UK, Germany, Israel."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    # ─── USA ───────────────────────────────────────────────────────────────────
    {
        "id": "m1a2_sep_abrams",
        "name": "M1A2 SEP Abrams",
        "design_family": "us_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 125,
        "base_stats": {"speed": 32, "reliability": 84, "fuel_consumption": 18, "supply_need": 24,
                      "armor": 82, "top_armor": 62, "hardness": 97},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256_l55_gun", "Engine": "agt1500_turbine",
                         "Armor": "m1a2_sep_v2_armor", "Sensors": "hunter_killer_fcs",
                         "Cargo": "m829a2_apfsds"},
        "unlock_tech": ["us_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "m1a2c_abrams",
        "name": "M1A2C Abrams",
        "design_family": "us_armored_twenty_tens",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 130,
        "base_stats": {"speed": 32, "reliability": 86, "fuel_consumption": 18, "supply_need": 26,
                      "armor": 88, "top_armor": 65, "hardness": 98},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "m256a1_120mm_gun", "Engine": "agt1500_turbine",
                         "Armor": "m1a2c_sep_v3_armor", "Sensors": "trophy_aps_usa",
                         "Cargo": "m829a3_apfsds"},
        "unlock_tech": ["us_mbt_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f22a_raptor",
        "name": "F-22A Raptor",
        "design_family": "us_air_two_thousands",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 115, "reliability": 80, "fuel_consumption": 26, "supply_need": 22,
                      "armor": 12, "hardness": 30},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim120d_amraam", "Engine": "f22a_package",
                         "Sensors": "an_apg77_radar"},
        "unlock_tech": ["us_fighters_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f35a_lightning",
        "name": "F-35A Lightning II",
        "design_family": "us_air_twenty_tens",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 140,
        "base_stats": {"speed": 108, "reliability": 78, "fuel_consumption": 20, "supply_need": 20,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "aim9x_block2", "Engine": "pratt_f135_engine",
                         "Sensors": "aesa_radar_gen1"},
        "unlock_tech": ["us_fighters_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mq9_reaper_uav",
        "name": "MQ-9 Reaper",
        "design_family": "us_air_two_thousands",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "drone",
        "crew_required": 2,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 65,
        "base_stats": {"speed": 48, "reliability": 82, "fuel_consumption": 10, "supply_need": 12,
                      "armor": 4, "hardness": 15},
        "slots": {"MainWeapon": {"max": 2}, "DroneAttachment": {"max": 1}},
        "module_loadout": {"MainWeapon": "ah64_hellfire", "DroneAttachment": "mq9_reaper_package"},
        "unlock_tech": ["us_uav_two_thousands"],
        "can_mount_drones": True,
        "is_vehicle": True,
    },
    # ─── RUSSIA ────────────────────────────────────────────────────────────────
    {
        "id": "t90a_mbt",
        "name": "T-90A",
        "design_family": "russian_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 35, "reliability": 76, "fuel_consumption": 13, "supply_need": 16,
                      "armor": 65, "top_armor": 40, "hardness": 93},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "2a46m4_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t90a_armor_package", "Cargo": "3bm59_apfsds"},
        "unlock_tech": ["russian_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t72b3_mbt",
        "name": "T-72B3",
        "design_family": "russian_armored_twenty_tens",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 88,
        "base_stats": {"speed": 34, "reliability": 74, "fuel_consumption": 12, "supply_need": 15,
                      "armor": 60, "top_armor": 36, "hardness": 91},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 2}},
        "module_loadout": {"MainWeapon": "2a46m4_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t72b3_armor_package"},
        "unlock_tech": ["russian_mbt_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "t14_armata",
        "name": "T-14 Armata",
        "design_family": "russian_armored_twenty_tens",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 140,
        "base_stats": {"speed": 36, "reliability": 68, "fuel_consumption": 14, "supply_need": 18,
                      "armor": 75, "top_armor": 50, "hardness": 95},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "2a82_125mm_gun", "Engine": "v46_6m_diesel",
                         "Armor": "t14_armata_package", "Sensors": "afghanit_aps"},
        "unlock_tech": ["russian_mbt_twenty_tens", "next_gen"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "su35s_flanker",
        "name": "Su-35S",
        "design_family": "russian_air_two_thousands",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 112, "reliability": 74, "fuel_consumption": 22, "supply_need": 16,
                      "armor": 12, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "r77_1_adder", "Engine": "su35_package"},
        "unlock_tech": ["russian_fighters_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "su57_felon",
        "name": "Su-57",
        "design_family": "russian_air_twenty_tens",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 150,
        "base_stats": {"speed": 110, "reliability": 70, "fuel_consumption": 22, "supply_need": 18,
                      "armor": 10, "hardness": 26},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "r77_1_adder", "Engine": "su57_package",
                         "Sensors": "aesa_radar_gen1"},
        "unlock_tech": ["russian_fighters_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── CHINA ─────────────────────────────────────────────────────────────────
    {
        "id": "type99a_mbt",
        "name": "Type 99A",
        "design_family": "chinese_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 105,
        "base_stats": {"speed": 36, "reliability": 76, "fuel_consumption": 13, "supply_need": 16,
                      "armor": 68, "top_armor": 42, "hardness": 94},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "zpt98_125mm_gun", "Engine": "ws10b_engine",
                         "Armor": "type99a_armor", "Cargo": "du_apfsds_gen4"},
        "unlock_tech": ["chinese_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "type96b_mbt",
        "name": "Type 96B",
        "design_family": "chinese_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 34, "reliability": 74, "fuel_consumption": 12, "supply_need": 15,
                      "armor": 58, "top_armor": 34, "hardness": 90},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "type96_125mm_gun", "Engine": "ws10b_engine",
                         "Armor": "type96b_mbt_package"},
        "unlock_tech": ["chinese_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "j10c_fighter",
        "name": "J-10C",
        "design_family": "chinese_air_twenty_tens",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 80,
        "base_stats": {"speed": 105, "reliability": 76, "fuel_consumption": 16, "supply_need": 12,
                      "armor": 8, "hardness": 24},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "pl12_air_missile", "Engine": "j10c_package",
                         "Sensors": "aesa_radar_gen1"},
        "unlock_tech": ["chinese_fighters_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "j20_fighter",
        "name": "J-20",
        "design_family": "chinese_air_twenty_tens",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 145,
        "base_stats": {"speed": 108, "reliability": 74, "fuel_consumption": 22, "supply_need": 18,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "pl15_air_missile", "Engine": "j20_package",
                         "Sensors": "aesa_radar_gen1"},
        "unlock_tech": ["chinese_fighters_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── FRANCE ────────────────────────────────────────────────────────────────
    {
        "id": "leclerc_xxi",
        "name": "Leclerc XXI",
        "design_family": "french_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 3,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 118,
        "base_stats": {"speed": 42, "reliability": 86, "fuel_consumption": 12, "supply_need": 18,
                      "armor": 70, "top_armor": 44, "hardness": 94},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "cn120_26_leclerc_gun", "Engine": "leclerc_hispano_engine",
                         "Armor": "leclerc_xei_armor", "Sensors": "network_centric_warfare",
                         "Cargo": "du_apfsds_gen4"},
        "unlock_tech": ["french_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "rafale_fighter",
        "name": "Rafale",
        "design_family": "french_air_two_thousands",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 106, "reliability": 80, "fuel_consumption": 16, "supply_need": 14,
                      "armor": 10, "hardness": 26},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "mica_ng_missile", "Engine": "rafale_package"},
        "unlock_tech": ["french_fighters_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── UK ────────────────────────────────────────────────────────────────────
    {
        "id": "challenger2_tes",
        "name": "Challenger 2 TES",
        "design_family": "uk_armored_twenty_tens",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "heavy_tank",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 28, "reliability": 80, "fuel_consumption": 15, "supply_need": 22,
                      "armor": 76, "top_armor": 54, "hardness": 97},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Cargo": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "l30_120mm_rifled", "Engine": "perkins_cv12_engine",
                         "Armor": "challenger2_dorchester_mk2", "Cargo": "du_apfsds_gen4",
                         "Sensors": "thermal_imager_an_vsg3"},
        "unlock_tech": ["uk_mbt_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "typhoon_fighter",
        "name": "Eurofighter Typhoon",
        "design_family": "uk_air_two_thousands",
        "base_type": "Air",
        "size_category": "Heavy",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 108, "reliability": 82, "fuel_consumption": 20, "supply_need": 16,
                      "armor": 12, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}},
        "module_loadout": {"MainWeapon": "meteor_missile", "Engine": "eurofighter_typhoon"},
        "unlock_tech": ["uk_fighters_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── GERMANY ───────────────────────────────────────────────────────────────
    {
        "id": "leopard2a6",
        "name": "Leopard 2A6",
        "design_family": "german_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 118,
        "base_stats": {"speed": 36, "reliability": 90, "fuel_consumption": 12, "supply_need": 18,
                      "armor": 72, "top_armor": 50, "hardness": 96},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Cargo": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh120_l55_gun", "Engine": "mtu_mb873_engine",
                         "Armor": "leopard2a6_armor", "Cargo": "dm63_apfsds",
                         "Sensors": "hunter_killer_fcs"},
        "unlock_tech": ["german_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "leopard2a7v",
        "name": "Leopard 2A7V",
        "design_family": "german_armored_twenty_tens",
        "base_type": "Armored",
        "size_category": "Heavy",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 125,
        "base_stats": {"speed": 36, "reliability": 90, "fuel_consumption": 12, "supply_need": 19,
                      "armor": 78, "top_armor": 55, "hardness": 97},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Cargo": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh120_l55_gun", "Engine": "mtu_mb873_engine",
                         "Armor": "leopard2a7_package", "Cargo": "du_apfsds_gen4"},
        "unlock_tech": ["german_mbt_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "puma_ifv",
        "name": "Puma IFV",
        "design_family": "german_armored_twenty_tens",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "apc",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 95,
        "base_stats": {"speed": 40, "reliability": 82, "fuel_consumption": 11, "supply_need": 14,
                      "armor": 42, "top_armor": 28, "hardness": 78},
        "slots": {"MainWeapon": {"max": 1}, "SecondaryWeapon": {"max": 1}, "Armor": {"max": 1}},
        "module_loadout": {"MainWeapon": "rh202_20mm_cannon", "SecondaryWeapon": "spike_lr2_atgm",
                         "Armor": "puma_ifv_package"},
        "unlock_tech": ["german_ifv_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ISRAEL ────────────────────────────────────────────────────────────────
    {
        "id": "merkava_mk4",
        "name": "Merkava Mk IV",
        "design_family": "israeli_armored_two_thousands",
        "base_type": "Armored",
        "size_category": "Medium",
        "visual_archetype": "medium_tank",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 115,
        "base_stats": {"speed": 30, "reliability": 84, "fuel_consumption": 14, "supply_need": 18,
                      "armor": 72, "top_armor": 45, "hardness": 95},
        "slots": {"MainWeapon": {"max": 1}, "Engine": {"max": 1}, "Armor": {"max": 1},
                  "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "merkava_mk4m_120mm", "Engine": "merkava_avds_engine",
                         "Armor": "merkava_mk4_armor", "Sensors": "trophy_aps_israel"},
        "unlock_tech": ["israeli_mbt_two_thousands"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "f35i_adir",
        "name": "F-35I Adir",
        "design_family": "israeli_air_twenty_tens",
        "base_type": "Air",
        "size_category": "Medium",
        "visual_archetype": "fighter",
        "crew_required": 1,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 145,
        "base_stats": {"speed": 108, "reliability": 80, "fuel_consumption": 20, "supply_need": 20,
                      "armor": 10, "hardness": 28},
        "slots": {"MainWeapon": {"max": 2}, "Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"MainWeapon": "python5_missile", "Engine": "pratt_f135_engine",
                         "Sensors": "f35i_adir_package"},
        "unlock_tech": ["israeli_fighters_twenty_tens"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if tpl["id"] in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\n2000s–2010s templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
