#!/usr/bin/env python3
"""2000s–2010s equipment modules: USA, Russia, China, France, UK, Germany, Israel."""

from __future__ import annotations

import json
from pathlib import Path

MODULES_DIR = Path(__file__).resolve().parents[1] / "data" / "modules"

# fmt: off
MODULES: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 2000s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1a2_sep_v2_armor", "name": "M1A2 SEP v2 Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 82, "top_armor_bonus": 62, "reliability_penalty": -6,
     "cost": {"steel": 55, "ceramics": 35, "uranium": 24, "titanium": 16, "kevlar": 12}, "production_time": 145,
     "special_flags": ["usa", "two_thousands", "m1a2", "du_armor"],
     "description": "Upgraded SEP with improved DU and CROW armor kits for Iraq and Afghanistan."},
    {"id": "m829a2_apfsds", "name": "M829A2 APFSDS", "category": "Cargo", "tier": 7,
     "soft_attack": 11, "hard_attack": 30, "piercing": 48,
     "cost": {"uranium": 22, "tungsten": 6, "steel": 2}, "production_time": 52,
     "special_flags": ["usa", "ammunition", "apfsds", "two_thousands"],
     "description": "Third-generation DU penetrator for M256. Standard U.S. tank ammunition in Iraq War."},
    {"id": "m256_l55_gun", "name": "120 mm M256 L/55", "category": "MainWeapon", "tier": 7,
     "soft_attack": 74, "hard_attack": 72, "piercing": 175, "air_attack": 5,
     "cost": {"steel": 36, "chromium": 10, "tungsten": 8}, "production_time": 108,
     "special_flags": ["usa", "two_thousands", "smoothbore", "leopard2a6_common"],
     "description": "Lengthened 120 mm gun on M1A1 AIM and export Abrams. Higher muzzle velocity."},
    {"id": "f22a_package", "name": "F-22A Raptor Package", "category": "Engine", "tier": 8,
     "reliability_bonus": 18, "fuel_efficiency": 16, "speed_bonus": 40,
     "cost": {"steel": 22, "aluminum": 42, "titanium": 28}, "production_time": 140,
     "special_flags": ["usa", "two_thousands", "stealth", "supercruise"],
     "description": "F-22 operational configuration. First fifth-generation fighter in U.S. service (2005)."},
    {"id": "aim120d_amraam", "name": "AIM-120D AMRAAM", "category": "MainWeapon", "tier": 7,
     "soft_attack": 14, "hard_attack": 12, "air_attack": 92, "anti_air": 88,
     "cost": {"steel": 6, "electronics": 48, "explosives": 10}, "production_time": 82,
     "special_flags": ["usa", "air_to_air", "two_thousands", "bvr"],
     "description": "Improved range and GPS/INS guidance. Standard U.S. BVR missile of 2010s."},
    {"id": "gbu39_sdb", "name": "GBU-39 SDB", "category": "MainWeapon", "tier": 7,
     "soft_attack": 58, "hard_attack": 52, "piercing": 55, "air_attack": 8,
     "cost": {"steel": 6, "electronics": 35, "explosives": 22}, "production_time": 70,
     "special_flags": ["usa", "precision_guided", "two_thousands", "gps"],
     "description": "Small Diameter Bomb. Precision GPS strike from fighters and bombers."},
    {"id": "jdam_guidance_kit", "name": "JDAM Guidance Kit", "category": "Cargo", "tier": 6,
     "soft_attack": 12, "hard_attack": 20, "piercing": 15,
     "cost": {"electronics": 28, "steel": 4}, "production_time": 45,
     "special_flags": ["usa", "precision_guided", "two_thousands", "gps"],
     "description": "GPS/INS tail kit converting unguided bombs. Backbone of post-9/11 air campaigns."},
    {"id": "stryker_m1126_package", "name": "Stryker ICV Package", "category": "Armor", "tier": 5,
     "armor_bonus": 28, "top_armor_bonus": 16, "reliability_penalty": -2,
     "cost": {"steel": 22, "aluminum": 10, "ceramics": 4}, "production_time": 55,
     "special_flags": ["usa", "two_thousands", "wheeled", "ifv"],
     "description": "Eight-wheeled interim combat vehicle for rapid deployment brigades."},
    {"id": "mrap_cougar_package", "name": "MRAP Cougar Package", "category": "Armor", "tier": 5,
     "armor_bonus": 32, "top_armor_bonus": 22, "reliability_penalty": -3,
     "cost": {"steel": 18, "ceramics": 8, "kevlar": 10}, "production_time": 48,
     "special_flags": ["usa", "two_thousands", "mine_protection", "irak"],
     "description": "V-hull MRAP for IED protection. Urgent fielding after Iraq/Afghanistan losses."},
    {"id": "mq9_reaper_package", "name": "MQ-9 Reaper Package", "category": "DroneAttachment", "tier": 6,
     "reliability_bonus": 5,
     "cost": {"steel": 8, "electronics": 45, "aluminum": 12}, "production_time": 75,
     "special_flags": ["usa", "two_thousands", "uav", "armed_drone"],
     "description": "Armed reconnaissance UAV with Hellfire and GBU-12. Defines 2000s counter-insurgency."},
    {"id": "aegis_bmd_package", "name": "Aegis BMD Package", "category": "Sensors", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 40, "electronics": 80, "aluminum": 15}, "production_time": 160,
     "special_flags": ["usa", "naval", "two_thousands", "ballistic_missile_defense"],
     "description": "SM-3 capable Aegis upgrade. Engages ballistic missile threats from sea."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED STATES · 2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "m1a2c_sep_v3_armor", "name": "M1A2C SEP v3 Armor", "category": "Armor", "tier": 8,
     "armor_bonus": 88, "top_armor_bonus": 65, "reliability_penalty": -5,
     "cost": {"steel": 58, "ceramics": 38, "uranium": 26, "titanium": 18, "kevlar": 14}, "production_time": 155,
     "special_flags": ["usa", "twenty_tens", "m1a2", "trophy_compatible"],
     "description": "Latest Abrams with improved armor, power, and Trophy APS compatibility."},
    {"id": "m829a3_apfsds", "name": "M829A3 APFSDS", "category": "Cargo", "tier": 8,
     "soft_attack": 12, "hard_attack": 32, "piercing": 52,
     "cost": {"uranium": 24, "tungsten": 8, "steel": 2}, "production_time": 55,
     "special_flags": ["usa", "ammunition", "apfsds", "twenty_tens"],
     "description": "Advanced DU penetrator optimized vs Relikt and late ERA. Peak U.S. KE performance."},
    {"id": "f35a_package", "name": "F-35A Lightning II Package", "category": "Engine", "tier": 8,
     "reliability_bonus": 14, "fuel_efficiency": 14, "speed_bonus": 36,
     "cost": {"steel": 24, "aluminum": 48, "titanium": 32, "electronics": 40}, "production_time": 180,
     "special_flags": ["usa", "twenty_tens", "stealth", "f35"],
     "description": "F-35 operational configuration. Sensor fusion and low observability for multi-role strike."},
    {"id": "pratt_f135_engine", "name": "Pratt & Whitney F135", "category": "Engine", "tier": 8,
     "reliability_bonus": 16, "fuel_efficiency": 15, "speed_bonus": 34,
     "cost": {"steel": 20, "aluminum": 45, "titanium": 30}, "production_time": 150,
     "special_flags": ["usa", "jet_powerplant", "twenty_tens", "f35"],
     "description": "F-35 single-engine turbofan. Most powerful fighter engine in production."},
    {"id": "aim9x_block2", "name": "AIM-9X Block II", "category": "MainWeapon", "tier": 7,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 82, "anti_air": 78,
     "cost": {"steel": 5, "electronics": 32, "explosives": 6}, "production_time": 68,
     "special_flags": ["usa", "air_to_air", "twenty_tens", "datalink"],
     "description": "Datalink-capable Sidewinder with lock-on-after-launch for F-35 and F-22."},
    {"id": "agm158_jassm", "name": "AGM-158 JASSM", "category": "MainWeapon", "tier": 7,
     "soft_attack": 55, "hard_attack": 58, "piercing": 50, "air_attack": 8,
     "cost": {"steel": 10, "electronics": 42, "explosives": 28}, "production_time": 88,
     "special_flags": ["usa", "cruise_missile", "twenty_tens", "stealth"],
     "description": "Stealthy air-launched cruise missile. Long-range precision strike vs hardened targets."},
    {"id": "trophy_aps_usa", "name": "Trophy APS (U.S. Fit)", "category": "Sensors", "tier": 8,
     "reliability_bonus": 6,
     "cost": {"steel": 12, "electronics": 45, "explosives": 8}, "production_time": 90,
     "special_flags": ["usa", "twenty_tens", "active_protection", "m1a2"],
     "description": "Israeli Trophy system on U.S. Abrams. Intercepts RPG and ATGM in close combat."},
    {"id": "m1128_mgs_105mm", "name": "M1128 MGS 105 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 62, "hard_attack": 56, "piercing": 125, "air_attack": 5,
     "cost": {"steel": 20, "electronics": 8}, "production_time": 65,
     "special_flags": ["usa", "twenty_tens", "stryker", "wheeled"],
     "description": "Stryker Mobile Gun System. 105 mm for direct fire support; retired 2022 but iconic 2010s."},

    # ═══════════════════════════════════════════════════════════════════════════
    # RUSSIA · 2000s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "t90a_armor_package", "name": "T-90A Armor Package", "category": "Armor", "tier": 7,
     "armor_bonus": 65, "top_armor_bonus": 40, "reliability_penalty": -5,
     "cost": {"steel": 44, "ceramics": 20, "explosives": 16}, "production_time": 98,
     "special_flags": ["russia", "two_thousands", "t90", "relikt"],
     "description": "T-90A with Relikt ERA and improved composite. Chechen and export combat record."},
    {"id": "2a46m4_125mm_gun", "name": "2A46M-4 125 mm", "category": "MainWeapon", "tier": 7,
     "soft_attack": 76, "hard_attack": 74, "piercing": 172, "air_attack": 5,
     "cost": {"steel": 36, "chromium": 10, "tungsten": 8}, "production_time": 110,
     "special_flags": ["russia", "two_thousands", "smoothbore", "t90"],
     "description": "Improved 125 mm for T-90A. Fires 3BM42 and 3BM59 rounds."},
    {"id": "3bm59_apfsds", "name": "3BM59 APFSDS", "category": "Cargo", "tier": 7,
     "soft_attack": 11, "hard_attack": 28, "piercing": 46,
     "cost": {"tungsten": 18, "uranium": 6, "steel": 2}, "production_time": 50,
     "special_flags": ["russia", "ammunition", "apfsds", "two_thousands"],
     "description": "Late Russian long-rod penetrator. Competitive with Western DU rounds."},
    {"id": "relikt_era", "name": "Relikt ERA", "category": "Armor", "tier": 7,
     "armor_bonus": 35, "top_armor_bonus": 24, "reliability_penalty": -3,
     "cost": {"steel": 14, "explosives": 20, "electronics": 8}, "production_time": 62,
     "special_flags": ["russia", "era", "two_thousands", "anti_apfsds"],
     "description": "Third-generation ERA effective vs tandem HEAT and reduced APFSDS threat."},
    {"id": "su35_package", "name": "Su-35S Package", "category": "Engine", "tier": 7,
     "reliability_bonus": 12, "fuel_efficiency": 10, "speed_bonus": 36,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 14}, "production_time": 100,
     "special_flags": ["russia", "two_thousands", "flanker", "supermaneuverable"],
     "description": "Su-35 with AL-41F1S engines and thrust vectoring. Export and Syria operations."},
    {"id": "r77_1_adder", "name": "R-77-1 (RVV-SD)", "category": "MainWeapon", "tier": 7,
     "soft_attack": 13, "hard_attack": 11, "air_attack": 88, "anti_air": 84,
     "cost": {"steel": 6, "electronics": 42, "explosives": 10}, "production_time": 75,
     "special_flags": ["russia", "air_to_air", "two_thousands", "active_radar"],
     "description": "Improved Adder with extended range. Standard Flanker BVR missile of 2010s."},
    {"id": "kh101_cruise_missile", "name": "Kh-101 Cruise Missile", "category": "MainWeapon", "tier": 7,
     "soft_attack": 58, "hard_attack": 62, "piercing": 48, "air_attack": 10,
     "cost": {"steel": 12, "electronics": 48, "explosives": 40}, "production_time": 100,
     "special_flags": ["russia", "cruise_missile", "two_thousands", "stealth"],
     "description": "Subsonic stealth cruise missile. Used against Syria and Ukraine from bombers."},
    {"id": "s400_triumf", "name": "S-400 Triumf", "category": "AntiAir", "tier": 8,
     "soft_attack": 18, "hard_attack": 16, "air_attack": 98, "anti_air": 96,
     "cost": {"steel": 38, "electronics": 85, "explosives": 28}, "production_time": 150,
     "special_flags": ["russia", "sam", "two_thousands", "strategic"],
     "description": "S-400 long-range SAM. Export to China and Turkey; cornerstone of Russian air defense."},
    {"id": "iskander_srbm", "name": "9K720 Iskander", "category": "MainWeapon", "tier": 7,
     "soft_attack": 120, "hard_attack": 70, "piercing": 60, "air_attack": 8,
     "cost": {"steel": 20, "electronics": 50, "explosives": 55}, "production_time": 110,
     "special_flags": ["russia", "two_thousands", "ballistic", "precision"],
     "description": "Short-range ballistic missile system. Precision strikes vs NATO rear areas."},

    # ═══════════════════════════════════════════════════════════════════════════
    # RUSSIA · 2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "t72b3_armor_package", "name": "T-72B3 Armor Package", "category": "Armor", "tier": 7,
     "armor_bonus": 60, "top_armor_bonus": 36, "reliability_penalty": -4,
     "cost": {"steel": 40, "ceramics": 16, "explosives": 14}, "production_time": 85,
     "special_flags": ["russia", "twenty_tens", "t72", "modernization"],
     "description": "T-72B3 mod with Relikt, Sosna-U sight, and improved FCS. Mass upgrade for budget constraints."},
    {"id": "t14_armata_package", "name": "T-14 Armata Package", "category": "Armor", "tier": 8,
     "armor_bonus": 75, "top_armor_bonus": 50, "reliability_penalty": -10,
     "cost": {"steel": 50, "ceramics": 30, "electronics": 25}, "production_time": 160,
     "special_flags": ["russia", "twenty_tens", "t14", "unmanned_turret"],
     "description": "T-14 Armata with unmanned turret and Afghanit APS. Limited production; doctrinal showcase."},
    {"id": "2a82_125mm_gun", "name": "2A82-1M 125 mm", "category": "MainWeapon", "tier": 8,
     "soft_attack": 78, "hard_attack": 76, "piercing": 185, "air_attack": 5,
     "cost": {"steel": 38, "chromium": 12, "tungsten": 10}, "production_time": 118,
     "special_flags": ["russia", "twenty_tens", "smoothbore", "t14"],
     "description": "Higher-pressure 125 mm for T-14 Armata. Peak Russian smoothbore development."},
    {"id": "afghanit_aps", "name": "Afghanit APS", "category": "Sensors", "tier": 8,
     "reliability_bonus": 7,
     "cost": {"steel": 14, "electronics": 55, "explosives": 12}, "production_time": 105,
     "special_flags": ["russia", "twenty_tens", "active_protection", "t14"],
     "description": "Hard-kill APS on T-14. Intercepts APFSDS and ATGM; unproven in large-scale combat."},
    {"id": "su57_package", "name": "Su-57 Felon Package", "category": "Engine", "tier": 8,
     "reliability_bonus": 12, "fuel_efficiency": 14, "speed_bonus": 38,
     "cost": {"steel": 22, "aluminum": 40, "titanium": 26, "electronics": 35}, "production_time": 165,
     "special_flags": ["russia", "twenty_tens", "stealth", "pak_fa"],
     "description": "Su-57 fifth-generation fighter. Limited production; Syria and Ukraine testing."},
    {"id": "kalibr_cruise_missile", "name": "3M-14 Kalibr", "category": "MainWeapon", "tier": 7,
     "soft_attack": 56, "hard_attack": 60, "piercing": 45, "anti_ship": 90, "air_attack": 8,
     "cost": {"steel": 12, "electronics": 45, "explosives": 38}, "production_time": 95,
     "special_flags": ["russia", "cruise_missile", "twenty_tens", "naval"],
     "description": "Kalibr land-attack cruise missile from ships and submarines. Syria and Ukraine strikes."},
    {"id": "bmpt_terminator", "name": "BMPT Terminator Package", "category": "MainWeapon", "tier": 7,
     "soft_attack": 48, "hard_attack": 38, "piercing": 75, "air_attack": 25,
     "cost": {"steel": 35, "electronics": 22, "explosives": 18}, "production_time": 95,
     "special_flags": ["russia", "twenty_tens", "urban_combat", "support_tank"],
     "description": "Tank support fighting vehicle with dual 30 mm and Ataka missiles. Chechnya and Syria."},

    # ═══════════════════════════════════════════════════════════════════════════
    # CHINA · 2000s–2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "type99a_armor", "name": "Type 99A Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 68, "top_armor_bonus": 42, "reliability_penalty": -5,
     "cost": {"steel": 46, "ceramics": 22, "explosives": 14}, "production_time": 100,
     "special_flags": ["china", "two_thousands", "type99", "era"],
     "description": "Type 99A with FY-4 ERA and improved composite. PLA premier MBT of 2010s."},
    {"id": "zpt98_125mm_gun", "name": "ZPT-98 125 mm", "category": "MainWeapon", "tier": 7,
     "soft_attack": 74, "hard_attack": 72, "piercing": 170, "air_attack": 5,
     "cost": {"steel": 34, "chromium": 8, "tungsten": 7}, "production_time": 105,
     "special_flags": ["china", "two_thousands", "smoothbore", "type99"],
     "description": "Indigenous 125 mm on Type 99 series. Autoloader and improved APFSDS."},
    {"id": "type96b_mbt_package", "name": "Type 96B Package", "category": "Armor", "tier": 6,
     "armor_bonus": 58, "top_armor_bonus": 34, "reliability_penalty": -4,
     "cost": {"steel": 40, "ceramics": 14}, "production_time": 88,
     "special_flags": ["china", "two_thousands", "type96"],
     "description": "Improved Type 96 with better FCS and armor. Mass-production PLA MBT."},
    {"id": "j10c_package", "name": "J-10C Package", "category": "Engine", "tier": 7,
     "reliability_bonus": 12, "fuel_efficiency": 12, "speed_bonus": 34,
     "cost": {"steel": 16, "aluminum": 32, "titanium": 12}, "production_time": 95,
     "special_flags": ["china", "twenty_tens", "j10", "aesa"],
     "description": "J-10C with WS-10B and AESA radar. PLAAF lightweight fighter backbone."},
    {"id": "j20_package", "name": "J-20 Mighty Dragon Package", "category": "Engine", "tier": 8,
     "reliability_bonus": 14, "fuel_efficiency": 14, "speed_bonus": 38,
     "cost": {"steel": 24, "aluminum": 45, "titanium": 28, "electronics": 42}, "production_time": 170,
     "special_flags": ["china", "twenty_tens", "stealth", "fifth_gen"],
     "description": "J-20 fifth-generation fighter entering service 2017. Long-range air superiority."},
    {"id": "pl12_air_missile", "name": "PL-12", "category": "MainWeapon", "tier": 7,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 85, "anti_air": 80,
     "cost": {"steel": 6, "electronics": 38, "explosives": 10}, "production_time": 68,
     "special_flags": ["china", "air_to_air", "two_thousands", "active_radar"],
     "description": "Chinese active-radar BVR missile. Equips J-10, J-11, and J-16."},
    {"id": "pl15_air_missile", "name": "PL-15", "category": "MainWeapon", "tier": 8,
     "soft_attack": 14, "hard_attack": 12, "air_attack": 95, "anti_air": 90,
     "cost": {"steel": 7, "electronics": 48, "explosives": 12}, "production_time": 78,
     "special_flags": ["china", "air_to_air", "twenty_tens", "long_range"],
     "description": "Very-long-range AAM threatening AWACS and tankers. J-20 primary BVR weapon."},
    {"id": "hq9b_sam", "name": "HQ-9B", "category": "AntiAir", "tier": 7,
     "soft_attack": 17, "hard_attack": 15, "air_attack": 92, "anti_air": 90,
     "cost": {"steel": 32, "electronics": 70, "explosives": 24}, "production_time": 125,
     "special_flags": ["china", "sam", "twenty_tens", "strategic"],
     "description": "Improved HQ-9 with better ECCM and range. PLA area air defense."},
    {"id": "df21d_asbm", "name": "DF-21D ASBM", "category": "MainWeapon", "tier": 8,
     "soft_attack": 130, "hard_attack": 80, "piercing": 70, "anti_ship": 120, "air_attack": 10,
     "cost": {"steel": 35, "electronics": 65, "explosives": 60}, "production_time": 140,
     "special_flags": ["china", "twenty_tens", "anti_ship", "ballistic"],
     "description": "Anti-ship ballistic missile. Carrier-killer doctrine centerpiece."},
    {"id": "ws10b_engine", "name": "WS-10B Turbofan", "category": "Engine", "tier": 7,
     "reliability_bonus": 10, "fuel_efficiency": 12, "speed_bonus": 33,
     "cost": {"steel": 18, "aluminum": 34, "titanium": 14}, "production_time": 105,
     "special_flags": ["china", "twenty_tens", "indigenous"],
     "description": "Indigenous fighter engine for J-10C and J-11B. Reduces reliance on Russian AL-31."},

    # ═══════════════════════════════════════════════════════════════════════════
    # FRANCE · 2000s–2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "leclerc_xei_armor", "name": "Leclerc XXI Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 70, "top_armor_bonus": 44, "reliability_penalty": -4,
     "cost": {"steel": 48, "ceramics": 26, "titanium": 12, "kevlar": 10}, "production_time": 115,
     "special_flags": ["france", "two_thousands", "leclerc", "upgrade"],
     "description": "Leclerc Block XXI upgrade with improved armor and battlefield management."},
    {"id": "rafale_package", "name": "Rafale Package", "category": "Engine", "tier": 7,
     "reliability_bonus": 14, "fuel_efficiency": 12, "speed_bonus": 34,
     "cost": {"steel": 18, "aluminum": 36, "titanium": 14}, "production_time": 105,
     "special_flags": ["france", "two_thousands", "rafale", "omnirole"],
     "description": "Rafale multi-role fighter. Libya, Mali, and Syria combat proven."},
    {"id": "mica_ng_missile", "name": "MICA NG", "category": "MainWeapon", "tier": 8,
     "soft_attack": 14, "hard_attack": 12, "air_attack": 90, "anti_air": 86,
     "cost": {"steel": 7, "electronics": 45, "explosives": 10}, "production_time": 75,
     "special_flags": ["france", "twenty_tens", "air_to_air", "dual_mode"],
     "description": "Next-generation MICA with extended range. Rafale standard missile of 2020s development."},
    {"id": "scalp_cruise_missile", "name": "SCALP-EG", "category": "MainWeapon", "tier": 7,
     "soft_attack": 58, "hard_attack": 60, "piercing": 48, "air_attack": 8,
     "cost": {"steel": 10, "electronics": 42, "explosives": 35}, "production_time": 90,
     "special_flags": ["france", "cruise_missile", "two_thousands", "stealth"],
     "description": "Storm Shadow/SCALP cruise missile. Deep strike vs hardened targets (Libya, Syria)."},
    {"id": "vbci_ifv_package", "name": "VBCI Package", "category": "Armor", "tier": 6,
     "armor_bonus": 35, "top_armor_bonus": 20, "reliability_penalty": -3,
     "cost": {"steel": 28, "aluminum": 12, "ceramics": 8}, "production_time": 72,
     "special_flags": ["france", "two_thousands", "ifv", "wheeled"],
     "description": "Wheeled 25 mm IFV for French rapid reaction forces."},
    {"id": "caesar_155mm", "name": "CAESAR 155 mm", "category": "MainWeapon", "tier": 6,
     "soft_attack": 100, "hard_attack": 42, "piercing": 58, "air_attack": 4,
     "cost": {"steel": 22, "electronics": 18, "explosives": 25}, "production_time": 65,
     "special_flags": ["france", "artillery", "two_thousands", "wheeled"],
     "description": "Truck-mounted 155 mm howitzer. Export success; Ukraine 2022+ deliveries."},

    # ═══════════════════════════════════════════════════════════════════════════
    # UNITED KINGDOM · 2000s–2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "challenger2_clip", "name": "Challenger 2 L55 CLIP", "category": "MainWeapon", "tier": 7,
     "soft_attack": 78, "hard_attack": 74, "piercing": 178, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 10, "tungsten": 8}, "production_time": 110,
     "special_flags": ["uk", "twenty_tens", "upgrade", "rifled"],
     "description": "Proposed L55 gun life extension for Challenger 2. Improved APFSDS performance."},
    {"id": "challenger2_dorchester_mk2", "name": "Dorchester Mk 2", "category": "Armor", "tier": 7,
     "armor_bonus": 76, "top_armor_bonus": 54, "reliability_penalty": -6,
     "cost": {"steel": 52, "ceramics": 32, "titanium": 14, "kevlar": 12}, "production_time": 130,
     "special_flags": ["uk", "two_thousands", "challenger2"],
     "description": "Challenger 2 with theatre entry upgrades. Basra and Iraq service record."},
    {"id": "eurofighter_typhoon", "name": "Eurofighter Typhoon Package", "category": "Engine", "tier": 7,
     "reliability_bonus": 15, "fuel_efficiency": 13, "speed_bonus": 37,
     "cost": {"steel": 20, "aluminum": 38, "titanium": 16}, "production_time": 115,
     "special_flags": ["uk", "germany_joint", "two_thousands", "typhoon"],
     "description": "Eurofighter Typhoon with EJ200. Libya and Baltic air policing missions."},
    {"id": "meteor_missile", "name": "Meteor", "category": "MainWeapon", "tier": 8,
     "soft_attack": 15, "hard_attack": 13, "air_attack": 98, "anti_air": 94,
     "cost": {"steel": 7, "electronics": 52, "explosives": 12}, "production_time": 85,
     "special_flags": ["uk", "germany_joint", "twenty_tens", "ramjet", "bvr"],
     "description": "Ramjet BVR missile. Outranges AMRAAM; Typhoon and Rafale integration."},
    {"id": "ajax_recon_package", "name": "Ajax Recon Package", "category": "Sensors", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 18, "electronics": 35, "optics": 20}, "production_time": 80,
     "special_flags": ["uk", "twenty_tens", "recon", "ifv"],
     "description": "Ajax armored reconnaissance vehicle with 40 mm CTA and advanced sensors."},
    {"id": "brimstone_missile", "name": "Brimstone", "category": "MainWeapon", "tier": 7,
     "soft_attack": 48, "hard_attack": 65, "piercing": 100, "air_attack": 8,
     "cost": {"steel": 8, "electronics": 38, "explosives": 16}, "production_time": 75,
     "special_flags": ["uk", "twenty_tens", "fire_and_forget", "anti_armor"],
     "description": "Dual-mode mmW seeker anti-armor missile. Libya and Iraq precision strikes."},
    {"id": "queen_elizabeth_carrier", "name": "Queen Elizabeth Carrier Package", "category": "Cargo", "tier": 7,
     "reliability_bonus": 4,
     "cost": {"steel": 120, "electronics": 45, "aluminum": 30}, "production_time": 200,
     "special_flags": ["uk", "twenty_tens", "carrier", "f35b"],
     "description": "Queen Elizabeth-class carrier for F-35B. Restores UK carrier strike capability."},

    # ═══════════════════════════════════════════════════════════════════════════
    # GERMANY · 2000s–2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "leopard2a6_armor", "name": "Leopard 2A6 Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 72, "top_armor_bonus": 50, "reliability_penalty": -5,
     "cost": {"steel": 50, "ceramics": 26, "titanium": 12}, "production_time": 115,
     "special_flags": ["germany", "two_thousands", "leopard2a6"],
     "description": "Leopard 2A6 with L/55 gun and improved armor. Afghanistan and export standard."},
    {"id": "rh120_l55_gun", "name": "Rh-120 L/55", "category": "MainWeapon", "tier": 7,
     "soft_attack": 76, "hard_attack": 74, "piercing": 178, "air_attack": 5,
     "cost": {"steel": 34, "chromium": 10, "tungsten": 8}, "production_time": 108,
     "special_flags": ["germany", "two_thousands", "smoothbore", "leopard2a6"],
     "description": "Lengthened Rh-120 for Leopard 2A6. Higher velocity DM53/DM63 ammunition."},
    {"id": "dm63_apfsds", "name": "DM63 APFSDS", "category": "Cargo", "tier": 7,
     "soft_attack": 11, "hard_attack": 30, "piercing": 48,
     "cost": {"tungsten": 16, "uranium": 8, "steel": 2}, "production_time": 52,
     "special_flags": ["germany", "ammunition", "apfsds", "two_thousands"],
     "description": "Temperature-independent tungsten penetrator for L/55 guns."},
    {"id": "leopard2a7_package", "name": "Leopard 2A7V Package", "category": "Armor", "tier": 8,
     "armor_bonus": 78, "top_armor_bonus": 55, "reliability_penalty": -5,
     "cost": {"steel": 52, "ceramics": 30, "titanium": 14, "kevlar": 12}, "production_time": 135,
     "special_flags": ["germany", "twenty_tens", "leopard2a7", "urban_kit"],
     "description": "Leopard 2A7+ with mine protection and FLW 200 RCWS. Qatar and Hungary export."},
    {"id": "puma_ifv_package", "name": "Puma IFV Package", "category": "Armor", "tier": 7,
     "armor_bonus": 42, "top_armor_bonus": 28, "reliability_penalty": -6,
     "cost": {"steel": 35, "ceramics": 18, "electronics": 12}, "production_time": 95,
     "special_flags": ["germany", "twenty_tens", "ifv", "puma"],
     "description": "Puma IFV with 30 mm MK30-2 and Spike. Most protected Western IFV."},
    {"id": "spike_lr2_atgm", "name": "Spike-LR2", "category": "MainWeapon", "tier": 7,
     "soft_attack": 40, "hard_attack": 72, "piercing": 150, "air_attack": 4,
     "cost": {"steel": 8, "electronics": 42, "explosives": 16}, "production_time": 72,
     "special_flags": ["germany", "israel_joint", "atgm", "twenty_tens", "fire_and_forget"],
     "description": "Euro-Spike long-range ATGM. Man-in-the-loop and fire-and-forget modes."},
    {"id": "iris_t_slm", "name": "IRIS-T SLM", "category": "AntiAir", "tier": 7,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 85, "anti_air": 82,
     "cost": {"steel": 18, "electronics": 40, "explosives": 12}, "production_time": 88,
     "special_flags": ["germany", "sam", "twenty_tens"],
     "description": "Surface-launched IRIS-T for point and short-range air defense."},

    # ═══════════════════════════════════════════════════════════════════════════
    # ISRAEL · 2000s–2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "merkava_mk4_armor", "name": "Merkava Mk IV Armor", "category": "Armor", "tier": 7,
     "armor_bonus": 72, "top_armor_bonus": 45, "reliability_penalty": -4,
     "cost": {"steel": 48, "ceramics": 24, "kevlar": 14, "electronics": 10}, "production_time": 110,
     "special_flags": ["israel", "two_thousands", "merkava", "front_engine"],
     "description": "Merkava Mk IV with modular armor and improved belly protection. 2006 Lebanon War."},
    {"id": "trophy_aps_israel", "name": "Trophy APS", "category": "Sensors", "tier": 8,
     "reliability_bonus": 8,
     "cost": {"steel": 14, "electronics": 50, "explosives": 10}, "production_time": 95,
     "special_flags": ["israel", "twenty_tens", "active_protection", "merkava"],
     "description": "Combat-proven hard-kill APS. Intercepts RPG-29 and Kornet in Gaza operations."},
    {"id": "merkava_mk4m_120mm", "name": "Merkava Mk IVM 120 mm", "category": "MainWeapon", "tier": 7,
     "soft_attack": 76, "hard_attack": 74, "piercing": 175, "air_attack": 5,
     "cost": {"steel": 32, "chromium": 8, "tungsten": 7}, "production_time": 105,
     "special_flags": ["israel", "two_thousands", "smoothbore", "merkava"],
     "description": "Improved IMI 120 mm with LAHAT capability and better autoloader integration."},
    {"id": "iron_dome_interceptor", "name": "Tamir (Iron Dome)", "category": "AntiAir", "tier": 7,
     "soft_attack": 8, "hard_attack": 6, "air_attack": 88, "anti_air": 85,
     "cost": {"steel": 6, "electronics": 38, "explosives": 8}, "production_time": 70,
     "special_flags": ["israel", "sam", "twenty_tens", "c_ramm"],
     "description": "Iron Dome interceptor for rockets and artillery. High intercept rate vs Hamas rockets."},
    {"id": "spike_nlos", "name": "Spike NLOS", "category": "MainWeapon", "tier": 7,
     "soft_attack": 42, "hard_attack": 70, "piercing": 145, "air_attack": 5,
     "cost": {"steel": 8, "electronics": 45, "explosives": 16}, "production_time": 75,
     "special_flags": ["israel", "atgm", "twenty_tens", "non_line_of_sight"],
     "description": "Networked Spike with 25 km range. Helicopter and vehicle launch from cover."},
    {"id": "f35i_adir_package", "name": "F-35I Adir Package", "category": "Sensors", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 10, "electronics": 65, "aluminum": 20}, "production_time": 150,
     "special_flags": ["israel", "twenty_tens", "f35", "stealth", "usa_joint"],
     "description": "Israeli F-35I with unique electronic warfare and strike packages. Entered service 2017."},
    {"id": "python5_missile", "name": "Python-5", "category": "MainWeapon", "tier": 7,
     "soft_attack": 10, "hard_attack": 8, "air_attack": 80, "anti_air": 76,
     "cost": {"steel": 5, "electronics": 32, "explosives": 7}, "production_time": 62,
     "special_flags": ["israel", "air_to_air", "two_thousands", "imaging_ir"],
     "description": "Imaging infrared dogfight missile. High off-boresight; export worldwide."},
    {"id": "david_sling_interceptor", "name": "Stunner (David's Sling)", "category": "AntiAir", "tier": 7,
     "soft_attack": 12, "hard_attack": 10, "air_attack": 90, "anti_air": 88,
     "cost": {"steel": 8, "electronics": 42, "explosives": 12}, "production_time": 85,
     "special_flags": ["israel", "sam", "twenty_tens", "medium_range"],
     "description": "David's Sling for SRBM and large rocket defense. Layer between Iron Dome and Arrow."},

    # ═══════════════════════════════════════════════════════════════════════════
    # SHARED · 2000s–2010s
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "aesa_radar_gen1", "name": "AESA Radar (Gen 1)", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 8, "electronics": 65, "rare_earths": 18}, "production_time": 120,
     "special_flags": ["nato", "twenty_tens", "aesa", "fighter"],
     "description": "Active electronically scanned array standard on F-22, Rafale, and Typhoon upgrades."},
    {"id": "crows_remote_weapon", "name": "CROWS Remote Weapon Station", "category": "SecondaryWeapon", "tier": 5,
     "soft_attack": 28, "hard_attack": 12, "piercing": 35, "air_attack": 15,
     "cost": {"steel": 8, "electronics": 22, "optics": 10}, "production_time": 48,
     "special_flags": ["usa", "nato", "two_thousands", "rcws"],
     "description": "Stabilized remote machine gun for MRAP and Humvee. Crew protection in COIN."},
    {"id": "network_centric_warfare", "name": "Network-Centric Warfare Suite", "category": "Sensors", "tier": 7,
     "reliability_bonus": 10,
     "cost": {"steel": 5, "electronics": 55}, "production_time": 80,
     "special_flags": ["nato", "two_thousands", "datalink", "blue_force"],
     "description": "Link-16 and battlefield networking. Shared situational awareness across platforms."},
    {"id": "du_apfsds_gen4", "name": "DU APFSDS (Gen 4)", "category": "Cargo", "tier": 8,
     "soft_attack": 14, "hard_attack": 34, "piercing": 55,
     "cost": {"uranium": 26, "tungsten": 6, "steel": 2}, "production_time": 58,
     "special_flags": ["nato", "ammunition", "twenty_tens", "du_penetrator"],
     "description": "Fourth-generation DU rods for L/44 and L/55. Peak Western KE lethality."},
    {"id": "recon_uav_package", "name": "Tactical UAV Package", "category": "DroneAttachment", "tier": 5,
     "reliability_bonus": 4,
     "cost": {"steel": 4, "electronics": 28, "aluminum": 8}, "production_time": 45,
     "special_flags": ["global", "two_thousands", "uav", "isr"],
     "description": "RQ-7 Shadow and similar brigade-level drones. Ubiquitous in Iraq and Afghanistan."},
    {"id": "ceramic_armor_gen3", "name": "Ceramic Armor (Gen 3)", "category": "Armor", "tier": 7,
     "armor_bonus": 20, "top_armor_bonus": 14, "reliability_penalty": -2,
     "cost": {"ceramics": 28, "steel": 12, "kevlar": 8}, "production_time": 55,
     "special_flags": ["nato", "twenty_tens", "add_on_armor"],
     "description": "Third-generation ceramic tile packages for IFV and MBT urban upgrades."},
]
# fmt: on


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in MODULES_DIR.glob("*.json")}
    created = skipped = 0
    for mod in MODULES:
        path = MODULES_DIR / f"{mod['id']}.json"
        if path.name in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(mod, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(MODULES_DIR.glob("*.json")))
    print(f"\n2000s–2010s: {created} created, {skipped} skipped, {total} total modules.")


if __name__ == "__main__":
    main()
