#!/usr/bin/env python3
"""Space unit templates: rockets, satellites, stations, 1940s–2030s."""

from __future__ import annotations

import json
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "data" / "unit_templates"

TEMPLATES: list[dict] = [
    # ─── GERMANY · 1940s ───────────────────────────────────────────────────────
    {
        "id": "a4_v2_rocket",
        "name": "A4/V-2 Rocket",
        "design_family": "german_space_ww2",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 20,
        "max_experience_level": 100,
        "base_production_days": 45,
        "base_stats": {"speed": 55, "reliability": 45, "fuel_consumption": 95, "supply_need": 40,
                      "payload_capacity": 1, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "a4_v2_engine", "Sensors": "v2_guidance_package",
                         "Cargo": "aggregat4_stage"},
        "unlock_tech": ["german_rockets", "ballistic_missiles"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── USA · 1950s–1960s ─────────────────────────────────────────────────────
    {
        "id": "redstone_jupiter",
        "name": "Redstone / Jupiter-C",
        "design_family": "us_space_fifties",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 55,
        "base_stats": {"speed": 62, "reliability": 58, "fuel_consumption": 80, "supply_need": 35,
                      "payload_capacity": 0.5, "hardness": 8},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"Engine": "redstone_engine", "Cargo": "jupiter_irbm_stage",
                         "Sensors": "explorer1_science_payload"},
        "unlock_tech": ["us_space_program", "early_satellites"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "saturn_v_apollo",
        "name": "Saturn V (Apollo)",
        "design_family": "us_space_sixties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "rocket",
        "crew_required": 3,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 180,
        "base_stats": {"speed": 95, "reliability": 82, "fuel_consumption": 120, "supply_need": 90,
                      "payload_capacity": 45, "hardness": 15},
        "slots": {"Engine": {"max": 3}, "Cargo": {"max": 2}, "LifeSupport": {"max": 2}},
        "module_loadout": {"Engine": "f1_saturn_engine", "Cargo": "apollo_lm_lander",
                         "LifeSupport": "apollo_csm_capsule"},
        "unlock_tech": ["apollo_program", "lunar_landing"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "gemini_spacecraft",
        "name": "Gemini",
        "design_family": "us_space_sixties",
        "base_type": "Space",
        "size_category": "Light",
        "visual_archetype": "crew_capsule",
        "crew_required": 2,
        "base_training_level": 35,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 70, "reliability": 75, "fuel_consumption": 50, "supply_need": 30,
                      "payload_capacity": 2, "hardness": 12},
        "slots": {"LifeSupport": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"LifeSupport": "gemini_capsule", "Engine": "j2_upper_stage_engine"},
        "unlock_tech": ["us_crewed_space"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── USSR · 1950s–1980s ────────────────────────────────────────────────────
    {
        "id": "r7_sputnik",
        "name": "R-7 / Sputnik",
        "design_family": "soviet_space_fifties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 70,
        "base_stats": {"speed": 75, "reliability": 70, "fuel_consumption": 85, "supply_need": 40,
                      "payload_capacity": 0.1, "hardness": 8},
        "slots": {"Engine": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"Engine": "r7_soyuz_engine", "Communications": "sputnik1_bus"},
        "unlock_tech": ["soviet_space_program"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "soyuz_spacecraft_tpl",
        "name": "Soyuz",
        "design_family": "soviet_space_sixties",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "crew_capsule",
        "crew_required": 3,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 72, "reliability": 85, "fuel_consumption": 55, "supply_need": 35,
                      "payload_capacity": 3, "hardness": 12},
        "slots": {"Engine": {"max": 1}, "LifeSupport": {"max": 1}},
        "module_loadout": {"Engine": "r7_soyuz_engine", "LifeSupport": "soyuz_spacecraft_bus"},
        "unlock_tech": ["soviet_crewed_space"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "proton_launcher",
        "name": "Proton",
        "design_family": "soviet_space_sixties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 110,
        "base_stats": {"speed": 80, "reliability": 72, "fuel_consumption": 95, "supply_need": 50,
                      "payload_capacity": 22, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "proton_rocket_stage", "Cargo": "proton_m_upgrade"},
        "unlock_tech": ["soviet_heavy_lift"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "mir_space_station",
        "name": "Mir",
        "design_family": "soviet_space_eighties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "space_station",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 200,
        "base_stats": {"speed": 28, "reliability": 78, "fuel_consumption": 40, "supply_need": 60,
                      "payload_capacity": 15, "hardness": 20},
        "slots": {"Cargo": {"max": 2}, "LifeSupport": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"Cargo": "mir_core_module", "LifeSupport": "soyuz_spacecraft_bus",
                         "Communications": "glonass_payload"},
        "unlock_tech": ["space_stations"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "energia_buran",
        "name": "Energia / Buran",
        "design_family": "soviet_space_eighties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "space_shuttle",
        "crew_required": 0,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 220,
        "base_stats": {"speed": 88, "reliability": 65, "fuel_consumption": 110, "supply_need": 85,
                      "payload_capacity": 30, "hardness": 14},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "energia_booster", "Cargo": "buran_orbiter"},
        "unlock_tech": ["soviet_shuttle", "prototype"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── USA · 1970s–2000s ─────────────────────────────────────────────────────
    {
        "id": "space_shuttle",
        "name": "Space Shuttle",
        "design_family": "us_space_seventies",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "space_shuttle",
        "crew_required": 7,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 200,
        "base_stats": {"speed": 78, "reliability": 75, "fuel_consumption": 100, "supply_need": 80,
                      "payload_capacity": 24, "hardness": 16},
        "slots": {"Engine": {"max": 3}, "Cargo": {"max": 1}, "LifeSupport": {"max": 1}},
        "module_loadout": {"Engine": "ssme_shuttle_engine", "Cargo": "shuttle_orbiter_package",
                         "LifeSupport": "shuttle_orbiter_package"},
        "unlock_tech": ["space_shuttle_program"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "hubble_spacecraft",
        "name": "Hubble Space Telescope",
        "design_family": "us_space_eighties",
        "base_type": "Space",
        "size_category": "Light",
        "visual_archetype": "satellite",
        "crew_required": 0,
        "base_training_level": 35,
        "max_experience_level": 100,
        "base_production_days": 150,
        "base_stats": {"speed": 28, "reliability": 88, "fuel_consumption": 15, "supply_need": 20,
                      "payload_capacity": 0, "hardness": 5},
        "slots": {"Sensors": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"Sensors": "hubble_space_telescope", "Communications": "gps_block1_payload"},
        "unlock_tech": ["space_telescopes"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "gps_satellite",
        "name": "GPS Satellite",
        "design_family": "us_space_seventies",
        "base_type": "Space",
        "size_category": "Light",
        "visual_archetype": "satellite",
        "crew_required": 0,
        "base_training_level": 32,
        "max_experience_level": 100,
        "base_production_days": 60,
        "base_stats": {"speed": 28, "reliability": 90, "fuel_consumption": 10, "supply_need": 15,
                      "payload_capacity": 0, "hardness": 5},
        "slots": {"Communications": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"Communications": "gps_block1_payload", "Engine": "vanguard_second_stage"},
        "unlock_tech": ["navigation_satellites"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ESA ───────────────────────────────────────────────────────────────────
    {
        "id": "ariane5_launcher",
        "name": "Ariane 5",
        "design_family": "esa_space_nineties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 120,
        "base_stats": {"speed": 82, "reliability": 88, "fuel_consumption": 90, "supply_need": 45,
                      "payload_capacity": 20, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "ariane1_first_stage", "Cargo": "ariane5_core_stage"},
        "unlock_tech": ["esa_launchers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "ariane6_launcher",
        "name": "Ariane 6",
        "design_family": "esa_space_twenty_twenties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 115,
        "base_stats": {"speed": 84, "reliability": 90, "fuel_consumption": 85, "supply_need": 42,
                      "payload_capacity": 21, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "ariane6_launcher", "Cargo": "ariane5_core_stage"},
        "unlock_tech": ["esa_launchers"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "columbus_iss_module",
        "name": "Columbus (ISS)",
        "design_family": "esa_space_two_thousands",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "space_station",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 160,
        "base_stats": {"speed": 28, "reliability": 90, "fuel_consumption": 25, "supply_need": 40,
                      "payload_capacity": 5, "hardness": 18},
        "slots": {"Cargo": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"Cargo": "columbus_lab_module", "Sensors": "rosetta_comet_probe"},
        "unlock_tech": ["iss_modules"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── CHINA ─────────────────────────────────────────────────────────────────
    {
        "id": "long_march5_launcher",
        "name": "Long March 5",
        "design_family": "chinese_space_twenty_twenties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 125,
        "base_stats": {"speed": 85, "reliability": 82, "fuel_consumption": 92, "supply_need": 48,
                      "payload_capacity": 25, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "long_march2_engine", "Cargo": "long_march5_heavy"},
        "unlock_tech": ["chinese_heavy_lift"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "shenzhou_spacecraft",
        "name": "Shenzhou",
        "design_family": "chinese_space_two_thousands",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "crew_capsule",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 105,
        "base_stats": {"speed": 72, "reliability": 84, "fuel_consumption": 52, "supply_need": 34,
                      "payload_capacity": 3, "hardness": 12},
        "slots": {"Engine": {"max": 1}, "LifeSupport": {"max": 1}},
        "module_loadout": {"Engine": "long_march2_engine", "LifeSupport": "shenzhou_capsule"},
        "unlock_tech": ["chinese_crewed_space"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "tiangong_space_station",
        "name": "Tiangong / CSS",
        "design_family": "chinese_space_twenty_twenties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "space_station",
        "crew_required": 3,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 190,
        "base_stats": {"speed": 28, "reliability": 86, "fuel_consumption": 38, "supply_need": 55,
                      "payload_capacity": 12, "hardness": 20},
        "slots": {"Cargo": {"max": 2}, "LifeSupport": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"Cargo": "tiangong_space_station_core", "LifeSupport": "shenzhou_capsule",
                         "Communications": "beidou_navigation_payload"},
        "unlock_tech": ["chinese_space_station"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "change_lunar_mission",
        "name": "Chang'e Lunar Mission",
        "design_family": "chinese_space_twenty_twenties",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "lunar_lander",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 130,
        "base_stats": {"speed": 65, "reliability": 80, "fuel_consumption": 70, "supply_need": 40,
                      "payload_capacity": 2, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Sensors": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "long_march5_heavy", "Sensors": "change_lunar_lander",
                         "Cargo": "change_lunar_lander"},
        "unlock_tech": ["lunar_exploration"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── SPACEX ────────────────────────────────────────────────────────────────
    {
        "id": "falcon9_rocket",
        "name": "Falcon 9",
        "design_family": "spacex_twenty_twenties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 45,
        "base_stats": {"speed": 82, "reliability": 92, "fuel_consumption": 75, "supply_need": 35,
                      "payload_capacity": 16, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "merlin1d_engine", "Cargo": "falcon9_stage_package"},
        "unlock_tech": ["commercial_space", "reusable_rockets"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "falcon_heavy_rocket",
        "name": "Falcon Heavy",
        "design_family": "spacex_twenty_twenties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 65,
        "base_stats": {"speed": 88, "reliability": 88, "fuel_consumption": 95, "supply_need": 50,
                      "payload_capacity": 26, "hardness": 10},
        "slots": {"Engine": {"max": 3}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "merlin1d_engine", "Cargo": "falcon_heavy_core"},
        "unlock_tech": ["commercial_space"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "crew_dragon",
        "name": "Crew Dragon",
        "design_family": "spacex_twenty_twenties",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "crew_capsule",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 75, "reliability": 90, "fuel_consumption": 45, "supply_need": 30,
                      "payload_capacity": 4, "hardness": 12},
        "slots": {"LifeSupport": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"LifeSupport": "dragon2_capsule", "Engine": "merlin1d_engine"},
        "unlock_tech": ["commercial_crew"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "starship_super_heavy",
        "name": "Starship / Super Heavy",
        "design_family": "spacex_twenty_twenties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 90,
        "base_stats": {"speed": 98, "reliability": 70, "fuel_consumption": 130, "supply_need": 70,
                      "payload_capacity": 100, "hardness": 12},
        "slots": {"Engine": {"max": 6}, "Cargo": {"max": 1}, "LifeSupport": {"max": 1}},
        "module_loadout": {"Engine": "starship_raptor_engine", "Cargo": "starship_vehicle_package",
                         "LifeSupport": "starship_mars_lander_fit"},
        "unlock_tech": ["starship_program", "mars_architecture"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "starlink_satellite",
        "name": "Starlink Satellite",
        "design_family": "spacex_twenty_twenties",
        "base_type": "Space",
        "size_category": "Light",
        "visual_archetype": "satellite",
        "crew_required": 0,
        "base_training_level": 28,
        "max_experience_level": 100,
        "base_production_days": 14,
        "base_stats": {"speed": 28, "reliability": 85, "fuel_consumption": 8, "supply_need": 8,
                      "payload_capacity": 0, "hardness": 3},
        "slots": {"Communications": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"Communications": "starlink_bus", "Engine": "merlin1d_engine"},
        "unlock_tech": ["mega_constellations"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ISS / INTERNATIONAL ───────────────────────────────────────────────────
    {
        "id": "iss_complex",
        "name": "International Space Station",
        "design_family": "international_space_nineties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "space_station",
        "crew_required": 6,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 250,
        "base_stats": {"speed": 28, "reliability": 88, "fuel_consumption": 50, "supply_need": 80,
                      "payload_capacity": 25, "hardness": 22},
        "slots": {"Cargo": {"max": 3}, "LifeSupport": {"max": 2}, "Sensors": {"max": 1},
                  "Communications": {"max": 1}},
        "module_loadout": {"Cargo": "iss_zvezda_module", "LifeSupport": "soyuz_spacecraft_bus",
                         "Sensors": "iss_destiny_lab", "Communications": "gps_block1_payload"},
        "unlock_tech": ["iss", "international_cooperation"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "jwst_observatory",
        "name": "James Webb Space Telescope",
        "design_family": "international_space_twenty_twenties",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "satellite",
        "crew_required": 0,
        "base_training_level": 42,
        "max_experience_level": 100,
        "base_production_days": 280,
        "base_stats": {"speed": 15, "reliability": 92, "fuel_consumption": 12, "supply_need": 35,
                      "payload_capacity": 0, "hardness": 5},
        "slots": {"Sensors": {"max": 1}, "Communications": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": {"Sensors": "jwst_telescope", "Communications": "lasercom_interplanetary",
                         "Engine": "ariane5_core_stage"},
        "unlock_tech": ["deep_space_science"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── ARTEMIS / NASA 2020s–2030s ────────────────────────────────────────────
    {
        "id": "sls_artemis",
        "name": "SLS (Artemis)",
        "design_family": "us_space_twenty_twenties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "rocket",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 200,
        "base_stats": {"speed": 92, "reliability": 78, "fuel_consumption": 115, "supply_need": 88,
                      "payload_capacity": 27, "hardness": 14},
        "slots": {"Engine": {"max": 2}, "LifeSupport": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "sls_block2_booster", "LifeSupport": "orion_spacecraft",
                         "Cargo": "starship_mars_lander_fit"},
        "unlock_tech": ["artemis_program"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "lunar_gateway",
        "name": "Lunar Gateway",
        "design_family": "international_space_twenty_thirties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "space_station",
        "crew_required": 4,
        "base_training_level": 40,
        "max_experience_level": 100,
        "base_production_days": 210,
        "base_stats": {"speed": 25, "reliability": 86, "fuel_consumption": 42, "supply_need": 65,
                      "payload_capacity": 8, "hardness": 20},
        "slots": {"Cargo": {"max": 2}, "LifeSupport": {"max": 1}, "Communications": {"max": 1}},
        "module_loadout": {"Cargo": "gateway_lunar_station", "LifeSupport": "orion_spacecraft",
                         "Communications": "lasercom_interplanetary"},
        "unlock_tech": ["lunar_gateway", "artemis"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "lunar_surface_hab_2030",
        "name": "Lunar Surface Hab (2030)",
        "design_family": "international_space_twenty_thirties",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "lunar_habitat",
        "crew_required": 4,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 180,
        "base_stats": {"speed": 20, "reliability": 82, "fuel_consumption": 35, "supply_need": 50,
                      "payload_capacity": 6, "hardness": 25},
        "slots": {"LifeSupport": {"max": 1}, "Cargo": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"LifeSupport": "lunar_gateway_hab", "Cargo": "on_orbit_refueling_depot",
                         "Sensors": "lasercom_interplanetary"},
        "unlock_tech": ["lunar_base", "planned"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    # ─── OTHER PLAYERS ─────────────────────────────────────────────────────────
    {
        "id": "h2a_launcher",
        "name": "H-IIA",
        "design_family": "jaxa_space",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 80, "reliability": 90, "fuel_consumption": 82, "supply_need": 42,
                      "payload_capacity": 15, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "h2a_launch_vehicle", "Cargo": "hayabusa_probe_bus"},
        "unlock_tech": ["japanese_space"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "pslv_launcher",
        "name": "PSLV",
        "design_family": "isro_space",
        "base_type": "Space",
        "size_category": "Medium",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 34,
        "max_experience_level": 100,
        "base_production_days": 55,
        "base_stats": {"speed": 76, "reliability": 88, "fuel_consumption": 70, "supply_need": 30,
                      "payload_capacity": 4, "hardness": 9},
        "slots": {"Engine": {"max": 1}, "Sensors": {"max": 1}},
        "module_loadout": {"Engine": "pslv_launcher", "Sensors": "chandrayaan_lander"},
        "unlock_tech": ["indian_space"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "new_glenn_rocket",
        "name": "New Glenn",
        "design_family": "blue_origin_twenty_twenties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 100,
        "base_stats": {"speed": 84, "reliability": 85, "fuel_consumption": 88, "supply_need": 45,
                      "payload_capacity": 13, "hardness": 10},
        "slots": {"Engine": {"max": 1}, "Cargo": {"max": 1}},
        "module_loadout": {"Engine": "new_glenn_stage", "Cargo": "blue_moon_lander"},
        "unlock_tech": ["commercial_heavy_lift"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "long_march9_2030",
        "name": "Long March 9 (Planned)",
        "design_family": "chinese_space_twenty_thirties",
        "base_type": "Space",
        "size_category": "SuperHeavy",
        "visual_archetype": "rocket",
        "crew_required": 0,
        "base_training_level": 38,
        "max_experience_level": 100,
        "base_production_days": 220,
        "base_stats": {"speed": 96, "reliability": 75, "fuel_consumption": 125, "supply_need": 75,
                      "payload_capacity": 140, "hardness": 12},
        "slots": {"Engine": {"max": 4}, "Cargo": {"max": 1}, "LifeSupport": {"max": 1}},
        "module_loadout": {"Engine": "long_march2_engine", "Cargo": "long_march9_superheavy",
                         "LifeSupport": "lunar_gateway_hab"},
        "unlock_tech": ["chinese_super_heavy", "planned"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
    {
        "id": "ross_station_2030",
        "name": "ROSS (Planned)",
        "design_family": "russian_space_twenty_thirties",
        "base_type": "Space",
        "size_category": "Heavy",
        "visual_archetype": "space_station",
        "crew_required": 3,
        "base_training_level": 36,
        "max_experience_level": 100,
        "base_production_days": 195,
        "base_stats": {"speed": 28, "reliability": 80, "fuel_consumption": 42, "supply_need": 58,
                      "payload_capacity": 10, "hardness": 20},
        "slots": {"Cargo": {"max": 2}, "LifeSupport": {"max": 1}},
        "module_loadout": {"Cargo": "russian_oren_space_station", "LifeSupport": "soyuz_spacecraft_bus"},
        "unlock_tech": ["russian_space_station", "planned"],
        "can_mount_drones": False,
        "is_vehicle": True,
    },
]


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing = {p.stem for p in TEMPLATES_DIR.glob("*.json")}
    created = skipped = 0
    for tpl in TEMPLATES:
        path = TEMPLATES_DIR / f"{tpl['id']}.json"
        if tpl["id"] in existing:
            skipped += 1
            continue
        with path.open("w", encoding="utf-8") as f:
            json.dump(tpl, f, indent=2, ensure_ascii=False)
            f.write("\n")
        created += 1
        print(f"  + {path.name}")
    total = len(list(TEMPLATES_DIR.glob("*.json")))
    print(f"\nSpace templates: {created} created, {skipped} skipped, {total} total.")


if __name__ == "__main__":
    main()
