#!/usr/bin/env python3
"""Naval helicopter & LHD/LPH/LHA aviation: 1940s–2030s + 2026 scenario nations."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = ROOT / "data" / "modules"
TEMPLATES_DIR = ROOT / "data" / "unit_templates"

T2026 = ["naval_2026", "twenty_twenties_naval"]
U_NAVAL = ["us_naval_aviation", "naval_helicopters"]
UK_NAVAL = ["uk_naval_aviation", "naval_helicopters"]
FR_NAVAL = ["french_naval_aviation", "naval_helicopters"]
RU_NAVAL = ["russian_naval_aviation", "naval_helicopters"]
CN_NAVAL = ["chinese_naval_aviation", "naval_helicopters"]

HELO_STATS = {
    "speed": 58, "reliability": 75, "fuel_consumption": 12,
    "supply_need": 10, "armor": 8, "hardness": 15,
}
HELO_STATS_MODERN = {
    "speed": 68, "reliability": 85, "fuel_consumption": 14,
    "supply_need": 12, "armor": 12, "hardness": 18,
}
HELO_STATS_LEGACY = {
    "speed": 48, "reliability": 65, "fuel_consumption": 10,
    "supply_need": 8, "armor": 5, "hardness": 10,
}

# fmt: off
MODULES: list[dict] = [
    # ═══ Torpedoes / weapons ═══════════════════════════════════════════════════
    {"id": "mk46_lightweight_torpedo", "name": "Mk 46 Lightweight Torpedo", "category": "MainWeapon", "tier": 4,
     "soft_attack": 28, "hard_attack": 42, "piercing": 20, "anti_ship": 72, "air_attack": 3,
     "cost": {"steel": 6, "electronics": 18, "explosives": 14}, "production_time": 48,
     "special_flags": ["usa", "asw", "helicopter", "naval"],
     "description": "Lightweight ASW torpedo for SH-2, SH-60, and allied naval helicopters."},
    {"id": "sea_skua_asm", "name": "Sea Skua ASM", "category": "MainWeapon", "tier": 5,
     "soft_attack": 35, "hard_attack": 48, "piercing": 35, "anti_ship": 78, "air_attack": 5,
     "cost": {"steel": 5, "electronics": 22, "explosives": 12}, "production_time": 52,
     "special_flags": ["uk", "anti_ship", "helicopter", "naval"],
     "description": "Light anti-ship missile for Lynx and Wildcat. Falklands and Gulf War service."},

    # ═══ USA · helicopter suites (by era) ══════════════════════════════════════
    {"id": "ho3s_dragonfly_suite", "name": "HO3S-1 Dragonfly Suite", "category": "Sensors", "tier": 2,
     "reliability_bonus": 2,
     "cost": {"steel": 4, "electronics": 6, "aluminum": 4}, "production_time": 35,
     "special_flags": ["usa", "helicopter", "naval", "forties", "korean_war"],
     "description": "Early U.S. Navy rescue and liaison helicopter. Korean War carrier operations."},
    {"id": "hss1_seabat_asw", "name": "HSS-1 Seabat ASW", "category": "Sensors", "tier": 3,
     "reliability_bonus": 4,
     "cost": {"steel": 6, "electronics": 14, "aluminum": 6}, "production_time": 45,
     "special_flags": ["usa", "asw", "helicopter", "fifties"],
     "description": "First purpose-built U.S. Navy ASW helicopter. Dipping sonar and depth charges."},
    {"id": "h34_choctaw_naval", "name": "H-34 Choctaw Naval", "category": "Engine", "tier": 3,
     "reliability_bonus": 6, "fuel_efficiency": 0, "speed_bonus": 8,
     "cost": {"steel": 8, "aluminum": 10}, "production_time": 42,
     "special_flags": ["usa", "helicopter", "naval", "fifties", "sixties"],
     "description": "Utility and ASW helicopter on Essex-class carriers and early LPH ships."},
    {"id": "sh3_sea_king_asw", "name": "SH-3 Sea King ASW", "category": "Sensors", "tier": 4,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 28, "aluminum": 12}, "production_time": 62,
     "special_flags": ["usa", "asw", "helicopter", "sixties", "vietnam"],
     "description": "Twin-engine ASW helicopter. Apollo recovery and Cold War carrier escort."},
    {"id": "sh2_seasprite_asw", "name": "SH-2 Seasprite ASW", "category": "Sensors", "tier": 4,
     "reliability_bonus": 6,
     "cost": {"steel": 8, "electronics": 24, "aluminum": 10}, "production_time": 55,
     "special_flags": ["usa", "asw", "helicopter", "sixties", "frigate"],
     "description": "Light ASW helicopter for destroyers and frigates. LAMPS Mk I program."},
    {"id": "ch46_sea_knight_assault", "name": "CH-46 Sea Knight Assault", "category": "Cargo", "tier": 4,
     "reliability_bonus": 7,
     "cost": {"steel": 12, "aluminum": 14, "electronics": 8}, "production_time": 58,
     "special_flags": ["usa", "assault", "helicopter", "sixties", "vietnam", "lhd"],
     "description": "Twin-rotor assault helicopter for LPH and early amphibious ships. Vietnam and Gulf War."},
    {"id": "uh1_naval_gunship", "name": "UH-1 Naval Gunship", "category": "MainWeapon", "tier": 4,
     "soft_attack": 42, "hard_attack": 18, "piercing": 22, "air_attack": 25,
     "cost": {"steel": 6, "aluminum": 6, "explosives": 12}, "production_time": 40,
     "special_flags": ["usa", "gunship", "helicopter", "vietnam", "brown_water"],
     "description": "Huey gunship for riverine and amphibious support. U.S. Navy river patrol."},
    {"id": "sh60b_seahawk_asw", "name": "SH-60B Seahawk ASW", "category": "Sensors", "tier": 5,
     "reliability_bonus": 10,
     "cost": {"steel": 9, "electronics": 35, "aluminum": 14}, "production_time": 72,
     "special_flags": ["usa", "asw", "helicopter", "eighties", "lamps_mk3"],
     "description": "LAMPS Mk III Seahawk. Standard U.S. frigate and cruiser ASW helicopter 1980s–2000s."},
    {"id": "mh60s_knighthawk_suite", "name": "MH-60S Knighthawk", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 10, "electronics": 40, "aluminum": 14}, "production_time": 78,
     "special_flags": ["usa", "helicopter", "naval", "two_thousands", "multi_mission"],
     "description": "Multi-mission helicopter for LHD/LHA. Vertrep, CSAR, and light strike."},
    {"id": "ch53e_super_stallion", "name": "CH-53E Super Stallion", "category": "Engine", "tier": 6,
     "reliability_bonus": 8, "fuel_efficiency": -2, "speed_bonus": 12,
     "cost": {"steel": 18, "aluminum": 22, "titanium": 6}, "production_time": 95,
     "special_flags": ["usa", "assault", "helicopter", "eighties", "heavy_lift"],
     "description": "Heavy assault helicopter for USMC from LHA/LHD. Iraq and Afghanistan amphibious ops."},
    {"id": "ch53k_king_stallion", "name": "CH-53K King Stallion", "category": "Engine", "tier": 7,
     "reliability_bonus": 12, "fuel_efficiency": 4, "speed_bonus": 14,
     "cost": {"steel": 20, "aluminum": 28, "titanium": 12, "electronics": 15}, "production_time": 110,
     "special_flags": ["usa", "assault", "helicopter", "twenty_tens", "heavy_lift"],
     "description": "Next-gen heavy lift for USMC amphibious ready groups."},

    # ═══ UK / France / Italy / USSR ════════════════════════════════════════════
    {"id": "westland_wasp_asw", "name": "Westland Wasp ASW", "category": "Sensors", "tier": 3,
     "reliability_bonus": 6,
     "cost": {"steel": 6, "electronics": 16, "aluminum": 8}, "production_time": 48,
     "special_flags": ["uk", "asw", "helicopter", "sixties", "falklands"],
     "description": "Small frigate-based ASW helicopter. Sank Santa Fe submarine in Falklands."},
    {"id": "sea_king_mk1_asw", "name": "Sea King Mk 1 ASW", "category": "Sensors", "tier": 4,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 26, "aluminum": 12}, "production_time": 60,
     "special_flags": ["uk", "asw", "helicopter", "sixties"],
     "description": "British Sea King ASW variant. Invincible-class and destroyer operations."},
    {"id": "lynx_has3_asw", "name": "Lynx HAS.3 ASW", "category": "Sensors", "tier": 5,
     "reliability_bonus": 8,
     "cost": {"steel": 8, "electronics": 30, "aluminum": 10}, "production_time": 65,
     "special_flags": ["uk", "asw", "helicopter", "eighties", "frigate"],
     "description": "Royal Navy Lynx with Sea Skua. Falklands and Gulf War frigate operations."},
    {"id": "aw101_merlin_asw", "name": "AW101 Merlin ASW", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 12, "electronics": 42, "aluminum": 16}, "production_time": 82,
     "special_flags": ["uk", "italy", "asw", "helicopter", "two_thousands"],
     "description": "Merlin HM.1/2 on Type 23 frigates and Queen Elizabeth ASW escort."},
    {"id": "super_frelon_asw", "name": "Super Frelon ASW", "category": "Sensors", "tier": 4,
     "reliability_bonus": 5,
     "cost": {"steel": 10, "electronics": 22, "aluminum": 12}, "production_time": 58,
     "special_flags": ["france", "asw", "helicopter", "sixties", "jeanne_darc"],
     "description": "Large French ASW helicopter on Jeanne d'Arc and destroyers."},
    {"id": "ab212_asw_italy", "name": "AB-212 ASW (Italy)", "category": "Sensors", "tier": 4,
     "reliability_bonus": 6,
     "cost": {"steel": 7, "electronics": 20, "aluminum": 9}, "production_time": 52,
     "special_flags": ["italy", "asw", "helicopter", "cold_war"],
     "description": "Italian naval ASW helicopter on destroyers and Garibaldi."},
    {"id": "ka25_hormone_asw", "name": "Ka-25 Hormone ASW", "category": "Sensors", "tier": 4,
     "reliability_bonus": 5,
     "cost": {"steel": 9, "electronics": 24, "aluminum": 10}, "production_time": 55,
     "special_flags": ["ussr", "asw", "helicopter", "sixties", "moskva"],
     "description": "Soviet ASW helicopter on Moskva/Kiev aviation cruisers."},
    {"id": "ka52k_katran_naval", "name": "Ka-52K Katran", "category": "Sensors", "tier": 7,
     "reliability_bonus": 8,
     "cost": {"steel": 12, "electronics": 45, "aluminum": 18, "explosives": 10}, "production_time": 90,
     "special_flags": ["russia", "attack", "helicopter", "naval", "twenty_tens"],
     "description": "Navalized Ka-52 for Russian LHD programs and carrier escort strike."},
    {"id": "z20f_asw_suite", "name": "Z-20F ASW Suite", "category": "Sensors", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 10, "electronics": 38, "aluminum": 14}, "production_time": 75,
     "special_flags": ["china", "asw", "helicopter", "twenty_tens"],
     "description": "Chinese naval ASW helicopter (Black Hawk derivative). Type 055 and LHD ops."},
    {"id": "harbin_z9c_asw", "name": "Harbin Z-9C ASW", "category": "Sensors", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 8, "electronics": 28, "aluminum": 10}, "production_time": 62,
     "special_flags": ["china", "asw", "helicopter", "nineties"],
     "description": "License Dauphin derivative for PLAN frigate and LHD ASW."},

    # ═══ 2030s prototypes ══════════════════════════════════════════════════════
    {"id": "flraa_maritime_proto", "name": "FLRAA Maritime (Proto)", "category": "Sensors", "tier": 8,
     "reliability_bonus": 10,
     "cost": {"steel": 14, "electronics": 55, "aluminum": 22, "titanium": 10}, "production_time": 120,
     "special_flags": ["usa", "prototype", "twenty_thirties", "tiltrotor", "naval"],
     "description": "Future Long-Range Assault Aircraft for USMC from LHA. Tiltrotor endurance and shipboard ops."},
    {"id": "autonomous_naval_helo_2030", "name": "Autonomous Naval Helo (Proto)", "category": "Sensors", "tier": 7,
     "reliability_bonus": 6,
     "cost": {"steel": 6, "electronics": 62, "aluminum": 12}, "production_time": 100,
     "special_flags": ["usa", "uav", "prototype", "twenty_thirties", "asw"],
     "description": "Unmanned ASW and ISR helicopter for distributed lethality on LHD and frigates."},
    {"id": "aw249_naval_proto", "name": "AW249 Naval (Proto)", "category": "Engine", "tier": 7,
     "reliability_bonus": 8, "fuel_efficiency": 6, "speed_bonus": 16,
     "cost": {"steel": 12, "aluminum": 20, "electronics": 35, "titanium": 8}, "production_time": 105,
     "special_flags": ["italy", "prototype", "twenty_thirties", "attack_helicopter"],
     "description": "Italian next-gen attack helicopter with naval strike variant under study."},

    # ═══ LHD / LPH / amphibious ships (historical hulls) ═══════════════════════
    {"id": "iwo_jima_lph_core", "name": "Iwo Jima-class LPH", "category": "Cargo", "tier": 4,
     "reliability_bonus": 5,
     "cost": {"steel": 70, "electronics": 18, "aluminum": 16}, "production_time": 140,
     "special_flags": ["usa", "lph", "vietnam", "helicopter"],
     "description": "First dedicated amphibious assault ships for Vietnam helicopter operations."},
    {"id": "tarawa_lha_core", "name": "Tarawa-class LHA", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 85, "electronics": 22, "aluminum": 20}, "production_time": 160,
     "special_flags": ["usa", "lha", "cold_war", "helicopter"],
     "description": "Well deck LHA hosting CH-46, CH-53, and Harrier AV-8A in Cold War."},
    {"id": "wasp_lhd_core", "name": "Wasp-class LHD", "category": "Cargo", "tier": 6,
     "reliability_bonus": 8,
     "cost": {"steel": 95, "electronics": 35, "aluminum": 25}, "production_time": 185,
     "special_flags": ["usa", "lhd", "twenty_tens", "stovl"],
     "description": "U.S. LHD with well deck, AV-8B/Harrier and later F-35B alongside Marine helos."},
    {"id": "america_lha_core", "name": "America-class LHA", "category": "Cargo", "tier": 7,
     "reliability_bonus": 9,
     "cost": {"steel": 105, "electronics": 42, "aluminum": 28}, "production_time": 195,
     "special_flags": ["usa", "lha", "twenty_tens", "f35b"],
     "description": "Aviation-focused LHA without well deck. F-35B and MV-22 operations."},
    {"id": "invincible_class_core", "name": "Invincible-class Core", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 80, "electronics": 28, "aluminum": 22}, "production_time": 170,
     "special_flags": ["uk", "carrier", "stovl", "falklands", "harrier"],
     "description": "Through-deck cruiser operating Sea Harrier and Sea King. Falklands War flagship."},
    {"id": "hms_ocean_lph_core", "name": "HMS Ocean LPH", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 75, "electronics": 25, "aluminum": 20}, "production_time": 165,
     "special_flags": ["uk", "lph", "helicopter", "two_thousands"],
     "description": "British helicopter assault ship. Apache and Merlin operations until sold to Brazil."},
    {"id": "jeanne_darc_helo_cruiser", "name": "Jeanne d'Arc Helo Cruiser", "category": "Cargo", "tier": 4,
     "reliability_bonus": 5,
     "cost": {"steel": 72, "electronics": 20, "aluminum": 18}, "production_time": 155,
     "special_flags": ["france", "helicopter_cruiser", "cold_war"],
     "description": "French helicopter cruiser training ship with Super Frelon and later Panther."},
    {"id": "moskva_helo_cruiser_core", "name": "Moskva-class Core", "category": "Cargo", "tier": 5,
     "reliability_bonus": 4,
     "cost": {"steel": 90, "electronics": 24, "aluminum": 20}, "production_time": 175,
     "special_flags": ["ussr", "helicopter_cruiser", "cold_war"],
     "description": "Soviet helicopter cruiser with Ka-25 ASW. Anti-submarine warfare command ship."},
    {"id": "kiev_class_aviation_core", "name": "Kiev-class Aviation Core", "category": "Cargo", "tier": 6,
     "reliability_bonus": 5,
     "cost": {"steel": 100, "electronics": 30, "aluminum": 25}, "production_time": 200,
     "special_flags": ["ussr", "aviation_cruiser", "yak38", "cold_war"],
     "description": "Hybrid cruiser with Yak-38 Forger and Ka-27 helos. Predecessor to Kuznetsov design."},
    {"id": "garibaldi_light_carrier", "name": "Giuseppe Garibaldi Layout", "category": "Cargo", "tier": 5,
     "reliability_bonus": 5,
     "cost": {"steel": 65, "electronics": 22, "aluminum": 18}, "production_time": 150,
     "special_flags": ["italy", "carrier", "stovl", "harrier"],
     "description": "Italian light carrier for AV-8B and EH101. Predecessor to Cavour."},
    {"id": "hyuga_class_ddh", "name": "Hyūga-class DDH", "category": "Cargo", "tier": 6,
     "reliability_bonus": 7,
     "cost": {"steel": 78, "electronics": 32, "aluminum": 22}, "production_time": 168,
     "special_flags": ["japan", "ddh", "helicopter", "two_thousands"],
     "description": "Japanese helicopter destroyer before Izumo STOVL conversion."},
    {"id": "mistral_class_lhd_france", "name": "Mistral-class LHD", "category": "Cargo", "tier": 6,
     "reliability_bonus": 6,
     "cost": {"steel": 72, "electronics": 28, "aluminum": 20}, "production_time": 168,
     "special_flags": ["france", "lhd", "helicopter", "twenty_tens"],
     "description": "French amphibious assault ship. NH90 and Panther; exported to Egypt and Russia (cancelled)."},
    {"id": "albion_class_lpd", "name": "Albion-class LPD", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 68, "electronics": 22, "aluminum": 18}, "production_time": 158,
     "special_flags": ["uk", "lpd", "helicopter", "two_thousands"],
     "description": "Royal Navy landing platform dock with Merlin and Lynx/Wildcat support."},
    {"id": "rotterdam_lpd", "name": "Rotterdam-class LPD", "category": "Cargo", "tier": 5,
     "reliability_bonus": 6,
     "cost": {"steel": 62, "electronics": 20, "aluminum": 16}, "production_time": 150,
     "special_flags": ["netherlands", "lpd", "helicopter", "nineties"],
     "description": "Dutch amphibious transport dock with NH90 NFH."},
    {"id": "san_giorgio_lpd", "name": "San Giorgio-class LPD", "category": "Cargo", "tier": 4,
     "reliability_bonus": 5,
     "cost": {"steel": 58, "electronics": 18, "aluminum": 14}, "production_time": 145,
     "special_flags": ["italy", "lpd", "helicopter", "cold_war"],
     "description": "Italian amphibious warfare ships supporting AB-212 and EH101."},
    {"id": "osprey_mv22_package", "name": "MV-22 Osprey Package", "category": "Engine", "tier": 6,
     "reliability_bonus": 6, "fuel_efficiency": 8, "speed_bonus": 22,
     "cost": {"steel": 16, "aluminum": 28, "electronics": 35, "titanium": 8}, "production_time": 95,
     "special_flags": ["usa", "tiltrotor", "lhd", "twenty_tens", "assault"],
     "description": "Tiltrotor assault aircraft from LHD/LHA. Rapid ship-to-shore mobility."},

    # ═══ 2026 · additional LHD / helo nations ════════════════════════════════
    {"id": "mrh90_taipan_aus", "name": "MRH90 Taipan", "category": "Sensors", "tier": 6,
     "reliability_bonus": 5,
     "cost": {"steel": 9, "electronics": 36, "aluminum": 14}, "production_time": 74,
     "special_flags": ["australia", "helicopter", "naval", "twenty_twenties"],
     "description": "Australian NH90 variant for Canberra LHD and frigates."},
    {"id": "aw101_merlin_uk", "name": "Merlin HM.2", "category": "Sensors", "tier": 6,
     "reliability_bonus": 10,
     "cost": {"steel": 12, "electronics": 42, "aluminum": 16}, "production_time": 80,
     "special_flags": ["uk", "asw", "helicopter", "twenty_twenties"],
     "description": "Royal Navy Merlin on QE carrier ASW escort and Type 23/26 frigates."},
    {"id": "panther_naval_france", "name": "Panther Naval", "category": "Sensors", "tier": 5,
     "reliability_bonus": 7,
     "cost": {"steel": 7, "electronics": 26, "aluminum": 10}, "production_time": 60,
     "special_flags": ["france", "helicopter", "naval", "mistral"],
     "description": "Light naval helicopter on Mistral-class and French frigates."},
    {"id": "sh2g_super_seasprite", "name": "SH-2G Super Seasprite", "category": "Sensors", "tier": 5,
     "reliability_bonus": 7,
     "cost": {"steel": 8, "electronics": 28, "aluminum": 10}, "production_time": 62,
     "special_flags": ["new_zealand", "australia", "poland", "helicopter", "naval"],
     "description": "Upgraded Seasprite for Anzac frigates and NZ naval aviation."},
    {"id": "uh60_blackhawk_naval", "name": "UH-60 Naval Utility", "category": "Sensors", "tier": 5,
     "reliability_bonus": 8,
     "cost": {"steel": 8, "electronics": 24, "aluminum": 10}, "production_time": 58,
     "special_flags": ["usa", "export", "helicopter", "naval"],
     "description": "Naval utility helicopter for export LHD and coast guard operations."},
    {"id": "rolls_royce_gemini", "name": "Rolls-Royce Gem", "category": "Engine", "tier": 4,
     "reliability_bonus": 8, "fuel_efficiency": 2, "speed_bonus": 10,
     "cost": {"steel": 8, "aluminum": 12}, "production_time": 48,
     "special_flags": ["uk", "helicopter", "lynx"],
     "description": "Twin turboshaft for Westland Lynx naval helicopter."},
    {"id": "turbomeca_makila", "name": "Turbomeca Makila", "category": "Engine", "tier": 5,
     "reliability_bonus": 9, "fuel_efficiency": 4, "speed_bonus": 12,
     "cost": {"steel": 9, "aluminum": 14}, "production_time": 55,
     "special_flags": ["france", "helicopter", "super_frelon", "panther"],
     "description": "French turboshaft for Super Frelon, Panther, and Dauphin naval variants."},
]


def helo_tpl(
    id_: str, name: str, family: str, loadout: dict, unlock: list[str],
    stats: dict | None = None, crew: int = 2, days: int = 65, training: int = 32,
    size: str = "Medium",
) -> dict:
    return {
        "id": id_, "name": name, "design_family": family, "base_type": "Air",
        "size_category": size, "visual_archetype": "helicopter",
        "crew_required": crew, "base_training_level": training,
        "max_experience_level": 100, "base_production_days": days,
        "base_stats": stats or HELO_STATS,
        "slots": {"MainWeapon": {"max": 1}, "Sensors": {"max": 1}, "Engine": {"max": 1}},
        "module_loadout": loadout,
        "unlock_tech": unlock, "can_mount_drones": False, "is_vehicle": True,
    }


def naval_tpl(
    id_: str, name: str, family: str, cargo: str, sensors: str, antiair: str,
    unlock: list[str], size: str = "Heavy", days: int = 175, training: int = 32,
    stats: dict | None = None, archetype: str = "carrier",
) -> dict:
    base_stats = stats or {
        "speed": 26, "reliability": 72, "fuel_consumption": 80,
        "supply_need": 95, "armor": 40, "deck_armor": 28, "hardness": 58,
    }
    return {
        "id": id_, "name": name, "design_family": family, "base_type": "Naval",
        "size_category": size, "visual_archetype": archetype,
        "crew_required": 1800, "base_training_level": training,
        "max_experience_level": 100, "base_production_days": days,
        "base_stats": base_stats,
        "slots": {"Cargo": {"max": 1}, "Sensors": {"max": 2}, "AntiAir": {"max": 2}},
        "module_loadout": {"Cargo": cargo, "Sensors": sensors, "AntiAir": antiair},
        "unlock_tech": unlock, "can_mount_drones": False, "is_vehicle": True,
    }


TEMPLATES: list[dict] = [
    # ═══ USA · helicopters 1940s–2030s ═════════════════════════════════════════
    helo_tpl("ho3s_dragonfly", "HO3S-1 Dragonfly", "us_naval_helo_historic",
             {"Sensors": "ho3s_dragonfly_suite", "Engine": "wasp_r1340_carrier_scout"},
             U_NAVAL + ["forties", "korean_war"], stats=HELO_STATS_LEGACY, days=38, crew=2),
    helo_tpl("hss1_seabat", "HSS-1 Seabat", "us_naval_helo_historic",
             {"MainWeapon": "mark44_lightweight_torpedo", "Sensors": "hss1_seabat_asw",
              "Engine": "h34_choctaw_naval"},
             U_NAVAL + ["fifties", "asw_helicopter"], stats=HELO_STATS_LEGACY, days=48),
    helo_tpl("sh3_sea_king", "SH-3 Sea King", "us_naval_helo_cold_war",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "sh3_sea_king_asw",
              "Engine": "pratt_whitney_r2800"},
             U_NAVAL + ["sixties", "vietnam", "asw_helicopter"], days=58, training=34),
    helo_tpl("sh2_seasprite", "SH-2 Seasprite", "us_naval_helo_cold_war",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "sh2_seasprite_asw",
              "Engine": "ge_f110_proto"},
             U_NAVAL + ["sixties", "lamps", "asw_helicopter"], days=52),
    helo_tpl("ch46_sea_knight", "CH-46 Sea Knight", "us_naval_helo_cold_war",
             {"Sensors": "ch46_sea_knight_assault", "Engine": "pratt_whitney_r2800"},
             U_NAVAL + ["sixties", "assault_helicopter", "lhd"], crew=3, days=55),
    helo_tpl("uh1_naval_gunship", "UH-1 Naval Gunship", "us_naval_helo_vietnam",
             {"MainWeapon": "uh1_naval_gunship", "Engine": "allison_v1710_engine"},
             U_NAVAL + ["vietnam", "brown_water"], stats={**HELO_STATS, "speed": 52}, days=42),
    helo_tpl("sh60b_seahawk", "SH-60B Seahawk", "us_naval_helo_modern",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "sh60b_seahawk_asw",
              "Engine": "ge_f404_hornet"},
             U_NAVAL + ["eighties", "asw_helicopter"], stats=HELO_STATS_MODERN, days=72, training=35),
    helo_tpl("mh60r_seahawk", "MH-60R Seahawk", "us_naval_helo_modern",
             {"MainWeapon": "mk48_torpedo", "Sensors": "mh60r_asw_helo_suite", "Engine": "ge_f404_hornet"},
             U_NAVAL + ["two_thousands", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=75),
    helo_tpl("mh60s_knighthawk", "MH-60S Knighthawk", "us_naval_helo_modern",
             {"MainWeapon": "ah64_hellfire", "Sensors": "mh60s_knighthawk_suite", "Engine": "ge_f404_hornet"},
             U_NAVAL + ["two_thousands", "multi_mission"], stats=HELO_STATS_MODERN, crew=3, days=72),
    helo_tpl("ch53e_super_stallion", "CH-53E Super Stallion", "us_naval_helo_modern",
             {"Sensors": "ch53e_super_stallion", "Engine": "ch53e_super_stallion"},
             U_NAVAL + ["assault_helicopter", "usmc"], stats={**HELO_STATS, "speed": 52}, crew=3, days=88, size="Heavy"),
    helo_tpl("ch53k_king_stallion", "CH-53K King Stallion", "us_naval_helo_modern",
             {"Sensors": "ch53k_king_stallion", "Engine": "ch53k_king_stallion"},
             U_NAVAL + ["twenty_tens", "assault_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=95, size="Heavy"),
    helo_tpl("mv22_osprey", "MV-22 Osprey", "us_naval_helo_modern",
             {"Engine": "osprey_mv22_package"},
             U_NAVAL + ["tiltrotor", "lhd"], stats={**HELO_STATS_MODERN, "speed": 85}, crew=3, days=90, size="Heavy"),

    # ═══ UK / France / Italy / USSR-Russia / China ══════════════════════════════
    helo_tpl("westland_wasp", "Westland Wasp", "uk_naval_helo_historic",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "westland_wasp_asw",
              "Engine": "rolls_royce_nene"},
             UK_NAVAL + ["sixties", "falklands", "asw_helicopter"], stats=HELO_STATS_LEGACY, days=45),
    helo_tpl("sea_king_mk1", "Sea King Mk 1", "uk_naval_helo_cold_war",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "sea_king_mk1_asw",
              "Engine": "rolls_royce_nene"},
             UK_NAVAL + ["sixties", "asw_helicopter"], days=56),
    helo_tpl("lynx_has3", "Lynx HAS.3", "uk_naval_helo_cold_war",
             {"MainWeapon": "sea_skua_asm", "Sensors": "lynx_has3_asw", "Engine": "rolls_royce_gemini"},
             UK_NAVAL + ["eighties", "falklands"], days=60),
    helo_tpl("aw101_merlin", "AW101 Merlin", "uk_naval_helo_modern",
             {"MainWeapon": "mk48_torpedo", "Sensors": "aw101_merlin_asw", "Engine": "ge_f110_proto"},
             UK_NAVAL + ["two_thousands", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=78),
    helo_tpl("super_frelon", "Super Frelon", "french_naval_helo_historic",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "super_frelon_asw",
              "Engine": "turbomeca_makila"},
             FR_NAVAL + ["sixties", "asw_helicopter"], days=54),
    helo_tpl("nh90_nfh_france", "NH90 NFH", "french_naval_helo_modern",
             {"MainWeapon": "mk48_torpedo", "Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             FR_NAVAL + ["twenty_tens", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=70),
    helo_tpl("panther_naval", "Panther Naval", "french_naval_helo_modern",
             {"Sensors": "panther_naval_france", "Engine": "turbomeca_makila"},
             FR_NAVAL + ["mistral", "utility_helicopter"], days=58),
    helo_tpl("ab212_asw", "AB-212 ASW", "italian_naval_helo_cold_war",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "ab212_asw_italy",
              "Engine": "pratt_whitney_r2800"},
             ["italian_naval_aviation", "asw_helicopter"], days=50),
    helo_tpl("eh101_italy", "AW101 (Italy)", "italian_naval_helo_modern",
             {"Sensors": "aw101_merlin_asw", "Engine": "ge_f110_proto"},
             ["italian_naval_aviation", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=76),
    helo_tpl("ka25_hormone", "Ka-25 Hormone", "soviet_naval_helo_historic",
             {"MainWeapon": "mark44_lightweight_torpedo", "Sensors": "ka25_hormone_asw",
              "Engine": "klimov_m105_engine"},
             RU_NAVAL + ["sixties", "moskva", "asw_helicopter"], stats=HELO_STATS_LEGACY, days=48),
    helo_tpl("ka27_helix", "Ka-27 Helix", "russian_naval_helo_modern",
             {"MainWeapon": "mk48_torpedo", "Sensors": "ka27_helix_asw_suite", "Engine": "klimov_m105_engine"},
             RU_NAVAL + ["asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=65),
    helo_tpl("ka52k_katran", "Ka-52K Katran", "russian_naval_helo_modern",
             {"MainWeapon": "kh31_asm", "Sensors": "ka52k_katran_naval", "Engine": "al31f_engine"},
             RU_NAVAL + ["twenty_tens", "attack_helicopter"], stats=HELO_STATS_MODERN, crew=2, days=88),
    helo_tpl("z9c_asw", "Z-9C ASW", "chinese_naval_helo_modern",
             {"MainWeapon": "mk46_lightweight_torpedo", "Sensors": "harbin_z9c_asw",
              "Engine": "ws10_proto_turbofan"},
             CN_NAVAL + ["nineties", "asw_helicopter"], days=62),
    helo_tpl("z20f_asw", "Z-20F ASW", "chinese_naval_helo_modern",
             {"MainWeapon": "mk48_torpedo", "Sensors": "z20f_asw_suite", "Engine": "ws10_proto_turbofan"},
             CN_NAVAL + ["twenty_tens", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=70),

    # ═══ 2030s prototypes ══════════════════════════════════════════════════════
    helo_tpl("flraa_maritime_2030", "FLRAA Maritime (Proto)", "us_naval_helo_planned",
             {"Sensors": "flraa_maritime_proto", "Engine": "osprey_mv22_package"},
             U_NAVAL + ["twenty_thirties", "prototype", "tiltrotor"], stats=HELO_STATS_MODERN, crew=2, days=110),
    helo_tpl("autonomous_naval_helo_2030", "MQ-8C / Autonomous (Proto)", "us_naval_helo_planned",
             {"Sensors": "autonomous_naval_helo_2030", "Engine": "ge_f404_hornet"},
             U_NAVAL + ["twenty_thirties", "uav", "asw_helicopter"], stats={**HELO_STATS_MODERN, "speed": 75},
             crew=0, days=85),
    helo_tpl("aw249_naval_2030", "AW249 Naval (Proto)", "italian_naval_helo_planned",
             {"MainWeapon": "scalp_cruise_missile", "Engine": "aw249_naval_proto"},
             ["italian_naval_aviation", "twenty_thirties", "prototype"], days=105),

    # ═══ Historical LHD / LPH / amphibious ═══════════════════════════════════════
    naval_tpl("iwo_jima_lph", "Iwo Jima-class LPH", "us_naval_amphibious_historic", "iwo_jima_lph_core",
              "sh3_sea_king_asw", "aim9_sidewinder", U_NAVAL + ["vietnam", "lph"], size="Medium", days=145),
    naval_tpl("tarawa_lha", "Tarawa-class LHA", "us_naval_amphibious_historic", "tarawa_lha_core",
              "ch46_sea_knight_assault", "aim7_sparrow", U_NAVAL + ["cold_war", "lha"], days=165),
    naval_tpl("wasp_class_lhd", "Wasp-class LHD", "us_naval_amphibious_modern", "wasp_lhd_core",
              "mh60s_knighthawk_suite", "aim120_amraam", U_NAVAL + ["lhd", "twenty_tens"], days=190),
    naval_tpl("america_class_lha", "America-class LHA", "us_naval_amphibious_modern", "america_lha_core",
              "f35b_stovl_package", "aim120d_amraam", U_NAVAL + ["lha", "twenty_tens"], days=200),
    naval_tpl("invincible_class", "HMS Invincible", "uk_naval_amphibious_historic", "invincible_class_core",
              "sea_king_mk1_asw", "sea_dart_sam", UK_NAVAL + ["falklands", "stovl_carrier"], days=175),
    naval_tpl("hms_ocean_lph", "HMS Ocean", "uk_naval_amphibious_modern", "hms_ocean_lph_core",
              "aw101_merlin_asw", "aim9_sidewinder", UK_NAVAL + ["lph", "two_thousands"], size="Medium", days=160),
    naval_tpl("jeanne_darc", "Jeanne d'Arc", "french_naval_amphibious_historic", "jeanne_darc_helo_cruiser",
              "super_frelon_asw", "mica_air_missile", FR_NAVAL + ["cold_war", "helicopter_cruiser"], size="Medium", days=150),
    naval_tpl("moskva_helo_cruiser", "Moskva-class", "soviet_naval_amphibious_historic", "moskva_helo_cruiser_core",
              "ka25_hormone_asw", "hq2_sam", RU_NAVAL + ["cold_war", "helicopter_cruiser"], days=170),
    naval_tpl("kiev_class_carrier", "Kiev-class", "soviet_naval_amphibious_historic", "kiev_class_aviation_core",
              "ka27_helix_asw_suite", "r73_archer_missile", RU_NAVAL + ["cold_war", "yak38"], days=195),
    naval_tpl("garibaldi_carrier", "Giuseppe Garibaldi", "italian_naval_amphibious_historic", "garibaldi_light_carrier",
              "ab212_asw_italy", "aim9_sidewinder", ["italian_naval_aviation", "harrier_carrier"], size="Medium", days=155),
    naval_tpl("hyuga_class_ddh", "Hyūga-class DDH", "japanese_naval_amphibious_modern", "hyuga_class_ddh",
              "sh60b_seahawk_asw", "type055_destroyer_vls", CN_NAVAL + ["ddh", "helicopter"], size="Medium", days=165),
    naval_tpl("mistral_class_france", "Mistral-class", "french_naval_amphibious_modern", "mistral_class_lhd_france",
              "nh90_nato_naval_helo", "mica_air_missile", FR_NAVAL + ["lhd", "twenty_tens"], size="Medium", days=168),
    naval_tpl("albion_class_lpd", "Albion-class LPD", "uk_naval_amphibious_modern", "albion_class_lpd",
              "aw101_merlin_uk", "aim9_sidewinder", UK_NAVAL + ["lpd"], size="Medium", days=155),
    naval_tpl("rotterdam_lpd", "Rotterdam-class LPD", "dutch_naval_amphibious_modern", "rotterdam_lpd",
              "nh90_nato_naval_helo", "aim120_amraam", ["dutch_naval_aviation", "lpd"], size="Medium", days=148),
    naval_tpl("san_giorgio_lpd", "San Giorgio-class", "italian_naval_amphibious_historic", "san_giorgio_lpd",
              "ab212_asw_italy", "aim9_sidewinder", ["italian_naval_aviation", "lpd"], size="Medium", days=142),

    # ═══ 2026 · expanded LHD / helicopter navies ═════════════════════════════════
    naval_tpl("wasp_class_lhd_2026", "Wasp-class LHD (2026)", "us_naval_2026", "wasp_lhd_core",
              "mh60r_asw_helo_suite", "aegis_bmd_package", T2026 + ["us_amphibious_2026"], days=190),
    naval_tpl("america_class_lha_2026", "America-class LHA (2026)", "us_naval_2026", "america_lha_core",
              "f35b_stovl_package", "aim120d_amraam", T2026 + ["us_amphibious_2026"], days=200),
    naval_tpl("mistral_france_2026", "Mistral-class (France)", "french_naval_2026", "mistral_class_lhd_france",
              "panther_naval_france", "aster30_sam", T2026 + ["french_amphibious_2026"], size="Medium", days=168),
    naval_tpl("albion_class_2026", "Albion-class (2026)", "uk_naval_2026", "albion_class_lpd",
              "aw101_merlin_uk", "sea_viper_sam", T2026 + ["uk_amphibious_2026"], size="Medium", days=155),
    naval_tpl("rotterdam_lpd_2026", "Rotterdam (2026)", "dutch_naval_2026", "rotterdam_lpd",
              "nh90_nato_naval_helo", "aim120d_amraam", T2026 + ["dutch_naval_aviation"], size="Medium", days=148),
    naval_tpl("hyuga_class_2026", "Hyūga-class (2026)", "japanese_naval_2026", "hyuga_class_ddh",
              "z20f_asw_suite", "type055_destroyer_vls", T2026 + ["japanese_amphibious_2026"], size="Medium", days=165),
    naval_tpl("garibaldi_2026", "Garibaldi (2026)", "italian_naval_2026", "garibaldi_light_carrier",
              "nh90_nato_naval_helo", "aster30_sam", T2026 + ["italian_amphibious_2026"], size="Medium", days=155),

    helo_tpl("mrh90_australia", "MRH90 Taipan", "australian_naval_helo_2026",
             {"Sensors": "mrh90_taipan_aus", "Engine": "ge_f110_proto"},
             T2026 + ["australian_naval_aviation", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=72),
    helo_tpl("merlin_hm2_uk_2026", "Merlin HM.2 (2026)", "uk_naval_helo_2026",
             {"MainWeapon": "mk48_torpedo", "Sensors": "aw101_merlin_uk", "Engine": "ge_f110_proto"},
             T2026 + ["uk_naval_aviation", "asw_helicopter"], stats=HELO_STATS_MODERN, crew=3, days=78),
    helo_tpl("nh90_france_2026", "NH90 NFH (France 2026)", "french_naval_helo_2026",
             {"MainWeapon": "mk48_torpedo", "Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             T2026 + ["french_naval_aviation", "asw_helicopter"], crew=3, days=70),
    helo_tpl("panther_france_2026", "Panther (France 2026)", "french_naval_helo_2026",
             {"Sensors": "panther_naval_france", "Engine": "turbomeca_makila"},
             T2026 + ["french_naval_aviation"], days=58),
    helo_tpl("sh2g_new_zealand", "SH-2G (RNZN)", "new_zealand_naval_helo_2026",
             {"Sensors": "sh2g_super_seasprite", "Engine": "ge_f404_hornet"},
             T2026 + ["new_zealand_naval_aviation", "asw_helicopter"], days=62),
    helo_tpl("sh2g_poland", "SH-2G (Poland)", "polish_naval_helo_2026",
             {"Sensors": "sh2g_super_seasprite", "Engine": "ge_f404_hornet"},
             T2026 + ["polish_naval_aviation", "asw_helicopter"], days=62),
    helo_tpl("nh90_sweden", "NH90 NFH (Sweden)", "swedish_naval_helo_2026",
             {"Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             T2026 + ["swedish_naval_aviation", "asw_helicopter"], days=68),
    helo_tpl("nh90_finland", "NH90 NFH (Finland)", "finnish_naval_helo_2026",
             {"Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             T2026 + ["finnish_naval_aviation", "asw_helicopter"], days=68),
    helo_tpl("nh90_denmark", "NH90 NFH (Denmark)", "danish_naval_helo_2026",
             {"Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             T2026 + ["danish_naval_aviation", "asw_helicopter"], days=68),
    helo_tpl("aw159_philippines", "AW159 (Philippines)", "philippine_naval_helo_2026",
             {"Sensors": "aw159_wildcat_asw", "Engine": "ge_f404_hornet"},
             T2026 + ["philippine_naval_aviation"], days=60),
    helo_tpl("aw159_malaysia", "AW159 (Malaysia)", "malaysian_naval_helo_2026",
             {"Sensors": "aw159_wildcat_asw", "Engine": "ge_f404_hornet"},
             T2026 + ["malaysian_naval_aviation"], days=60),
    helo_tpl("nh90_indonesia", "NH90 (Indonesia Planned)", "indonesian_naval_helo_2026",
             {"Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             T2026 + ["indonesian_naval_aviation", "planned"], days=70),
    helo_tpl("uh60_mexico_naval", "UH-60 (Mexican Navy)", "mexican_naval_helo_2026",
             {"Sensors": "uh60_blackhawk_naval", "Engine": "ge_f404_hornet"},
             T2026 + ["mexican_naval_aviation"], days=58),
    helo_tpl("uh60_colombia_naval", "UH-60 (Colombian Navy)", "colombian_naval_helo_2026",
             {"Sensors": "uh60_blackhawk_naval", "Engine": "ge_f404_hornet"},
             T2026 + ["colombian_naval_aviation"], days=58),
    helo_tpl("ka32_peru_naval", "Ka-32 (Peru)", "peruvian_naval_helo_2026",
             {"Sensors": "ka27_helix_asw_suite", "Engine": "klimov_m105_engine"},
             T2026 + ["peruvian_naval_aviation"], days=55),
    helo_tpl("dauphin_chile_naval", "AS365 Dauphin (Chile)", "chilean_naval_helo_2026",
             {"Sensors": "harbin_z9c_asw", "Engine": "turbomeca_makila"},
             T2026 + ["chilean_naval_aviation"], days=52),
    helo_tpl("aw159_south_africa", "AW109 (South Africa)", "south_african_naval_helo_2026",
             {"Sensors": "aw159_wildcat_asw", "Engine": "pratt_whitney_r2800"},
             T2026 + ["south_african_naval_aviation"], days=55),
    helo_tpl("ka27_egypt_naval", "Ka-52E / Helix (Egypt)", "egyptian_naval_helo_2026",
             {"Sensors": "ka27_helix_asw_suite", "Engine": "klimov_m105_engine"},
             T2026 + ["egyptian_naval_aviation"], days=65),
    helo_tpl("nh90_norway_2026", "NH90 NFH (Norway 2026)", "norwegian_naval_helo_2026",
             {"MainWeapon": "mk48_torpedo", "Sensors": "nh90_nato_naval_helo", "Engine": "ge_f110_proto"},
             T2026 + ["norwegian_naval_aviation"], crew=3, days=70),
    helo_tpl("mh60r_denmark", "MH-60R (Denmark)", "danish_naval_helo_2026",
             {"MainWeapon": "mk48_torpedo", "Sensors": "mh60r_asw_helo_suite", "Engine": "ge_f404_hornet"},
             T2026 + ["danish_naval_aviation"], crew=3, days=72),
]


def write_json(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def main() -> None:
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    existing_mods = {p.stem for p in MODULES_DIR.glob("*.json")}
    existing_tpls = {p.stem for p in TEMPLATES_DIR.glob("*.json")}

    mc = ms = 0
    for mod in MODULES:
        if mod["id"] in existing_mods:
            ms += 1
            continue
        write_json(MODULES_DIR / f"{mod['id']}.json", mod)
        mc += 1
        print(f"  + module {mod['id']}.json")

    tc = ts = 0
    for tpl in TEMPLATES:
        if tpl["id"] in existing_tpls:
            ts += 1
            continue
        write_json(TEMPLATES_DIR / f"{tpl['id']}.json", tpl)
        tc += 1
        print(f"  + template {tpl['id']}.json")

    mods = {p.stem for p in MODULES_DIR.glob("*.json")}
    errs = []
    for p in TEMPLATES_DIR.glob("*.json"):
        d = json.loads(p.read_text())
        for slot, mid in d.get("module_loadout", {}).items():
            if mid not in mods:
                errs.append(f"{p.name}: {slot} -> {mid}")

    print(f"\nNaval helicopter: modules {mc} created ({ms} skipped), templates {tc} created ({ts} skipped)")
    print(f"Totals: {len(mods)} modules, {len(list(TEMPLATES_DIR.glob('*.json')))} templates")
    print(f"Missing refs: {len(errs)}")
    for e in errs:
        print(f"  ! {e}")


if __name__ == "__main__":
    main()
