


country = {
    tag = LUX


	# Resource Reserves
	energy	=	5000   metal	=	5000	rare_materials =	2000	oil =	2000	supplies =	2000

	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 10
        political_left = 5
        freedom = 9
        free_market = 8
        professional_army = 5
        defense_lobby = 2
        interventionism = 1
    }

		headofstate = { type = 9 id = 66001 }
		headofgovernment = { type = 9 id = 66039 }
  		foreignminister = { type = 9 id = 66046 }
  		armamentminister = { type = 9 id = 66055 }
  		ministerofsecurity = { type = 9 id = 66062 }
  		ministerofintelligence = { type = 9 id = 66072 }
  		chiefofstaff = { type = 9 id = 66082 }
  		chiefofarmy = { type = 9 id = 66090 }
  		chiefofnavy = { type = 9 id = 66009 } 
  		chiefofair = { type = 9 id = 66010 }

	manpower = 4

	capital = 	71

    ownedprovinces =      {
		71
	 }
    controlledprovinces = {
		71
	  }
    nationalprovinces =   {
		71
	}

	# Western Minor Tech '36
	techapps = {
		1010 1190
		2290 2300 2310 2450
		4010
		5010
	}
} 