#	FINNISH VPs (55)
province = { id = 137 points = 5 } # Oulo
province = { id = 138 points = 5 } # Vaasa
province = { id = 141 points = 15 } # Turku
province = { id = 142 points = 20 } # Helsinki
province = { id = 145 points = 10 } # Vipuuri

#	SOVIET VPs (30)
province = { id = 187 points = 10 } # Leningrad
province = { id = 133 points = 7 } # Murmansk
province = { id = 134 points = 2 } # Kola
province = { id = 154 points = 7 } # Arkhangelsk
province = { id = 194 points = 2 } # Tallinn
province = { id = 200 points = 2 } # Pskov